import { applyPortraitSurfaces } from './materials';
import { ViewControl } from '../ui/ViewControl';
import { useEffect,useRef,useState } from 'react';
import * as T from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { characterById } from '../data/characters';
import { createCharacterModel,disposeCharacterModel } from './model';
import type { PortraitPose,Wardrobe } from './appearance';
import './portrait.css';
export default function CharacterViewport({characterId,compact=false,stress=0}:{characterId:string;compact?:boolean;stress?:number}){
 const host=useRef<HTMLDivElement>(null),view=useRef<{move:(n:number)=>void;reset:()=>void;export:()=>Promise<void>}|null>(null);
 const [wardrobe,setWardrobe]=useState<Wardrobe>('default'),[pose,setPose]=useState<PortraitPose|'auto'>('auto'),[error,setError]=useState(''),[retry,setRetry]=useState(0),[exporting,setExporting]=useState(false),[notice,setNotice]=useState('');
 const name=characterById[characterId].name,expression=pose==='auto'?(stress>=80?'stern':'calm'):pose;
 useEffect(()=>{
 const element=host.current!;let renderer:T.WebGLRenderer;
 try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{setError('人物 3D 无法启用。请检查图形加速；人物资料和开局仍可使用。');return;}
 setError('');renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#17231e',1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;element.appendChild(renderer.domElement);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(32,1,.05,30),model=createCharacterModel(characterId,expression,wardrobe);applyPortraitSurfaces(model);scene.add(model);
 scene.add(new T.HemisphereLight('#eee4d5','#242b28',.85));const key=new T.DirectionalLight('#ffe3bd',3);key.position.set(-3,5,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-2,right:2,top:4,bottom:-1,near:.1,far:15});key.shadow.bias=-.0003;key.shadow.normalBias=.018;scene.add(key);const fill=new T.DirectionalLight('#c9d5dc',.65);fill.position.set(3,2,3);scene.add(fill);const rim=new T.DirectionalLight('#c1d5d0',1.4);rim.position.set(3,3,-3);scene.add(rim);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=false;controls.minDistance=2.2;controls.maxDistance=8;controls.minPolarAngle=.7;controls.maxPolarAngle=1.8;controls.target.set(0,1.65,0);
 let disposed=false,lost=false;const render=()=>{if(!disposed&&!lost)renderer.render(scene,camera);};const reset=()=>{controls.target.set(0,2.03,0);camera.position.set(.35,2.13,4.9);controls.update();render();};reset();controls.addEventListener('change',render);
 const resize=new ResizeObserver(()=>{const w=element.clientWidth,h=element.clientHeight;if(w&&h){camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);render();}});resize.observe(element);
 const onLost=(e:Event)=>{e.preventDefault();lost=true;setError('人物视图已中断，可重新加载；游戏数据不受影响。');};renderer.domElement.addEventListener('webglcontextlost',onLost);
 view.current={reset,move:n=>{const offset=camera.position.clone().sub(controls.target);offset.applyAxisAngle(new T.Vector3(0,1,0),n);camera.position.copy(controls.target).add(offset);controls.update();render();},export:async()=>{const {GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js');const data=await new GLTFExporter().parseAsync(model,{binary:true});if(disposed)return;const url=URL.createObjectURL(new Blob([data as ArrayBuffer],{type:'model/gltf-binary'}));const link=document.createElement('a');link.href=url;link.download=characterId+'-'+wardrobe+'.glb';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}};
 return()=>{disposed=true;view.current=null;resize.disconnect();controls.dispose();renderer.domElement.removeEventListener('webglcontextlost',onLost);disposeCharacterModel(model);key.shadow.dispose();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();};
 },[characterId,wardrobe,expression,retry]);
 return <section className={`character-view ${compact?'compact':''}`} aria-label={name+'的三维肖像'}><div className="character-viewport" ref={host} role="img" aria-label={name+'的风格化三维半身肖像，造型为艺术演绎'}/><span className="portrait-badge">{name} · 3D 肖像</span>{error&&<div className="portrait-error" role="alert">{error}<button onClick={()=>setRetry(n=>n+1)}>重新加载</button></div>}<div className="portrait-controls"><ViewControl action="left" label="向左旋转人物" disabled={!!error} onClick={()=>view.current?.move(-.35)}/><ViewControl action="right" label="向右旋转人物" disabled={!!error} onClick={()=>view.current?.move(.35)}/><ViewControl action="reset" disabled={!!error} onClick={()=>view.current?.reset()}/></div><details><summary>人物造型 · 试装与导出</summary><div className="portrait-options"><label>服饰<select value={wardrobe} onChange={e=>setWardrobe(e.target.value as Wardrobe)}><option value="default">人物默认</option><option value="court">文服</option><option value="armor">甲胄</option></select></label><label>神情<select value={pose} onChange={e=>setPose(e.target.value as PortraitPose|'auto')}><option value="auto">随压力变化</option><option value="calm">平静</option><option value="stern">凝重</option><option value="pleased">和缓</option></select></label><button disabled={!!error||exporting} onClick={async()=>{setExporting(true);setNotice('');try{await view.current?.export();setNotice('模型已生成，请查看下载文件。');}catch{setNotice('模型导出失败，请重试。');}finally{setExporting(false);}}}>{exporting?'正在导出…':'导出 GLB 模型'}</button></div><p>拖动旋转，滚轮缩放；按钮也可调整视角。试装不改变身份或存档。压力达到 80 时自动呈凝重神情。</p>{notice&&<p role="status">{notice}</p>}</details><p className="portrait-disclaimer">原创参数化造型 · 非真实容貌复原 · 服饰为时代氛围演绎</p></section>;
}
