import {afterCommand} from './actionFeedback';
import {useState} from 'react';
import {appointmentChange,appointmentFactors,appointmentReason,type AppointmentCommand} from '../core/appointmentCycle';
import {localTitle,localSeatSite} from '../core/localAdministration';
import {officeCandidates,officeName} from '../core/officeEligibility';
import {CharacterPortrait} from './CharacterPortrait';
import {PersonSelectionDialog} from './PersonSelection';
import {HoverHint} from './HoverHint';
import {ConfirmAction} from './ConfirmAction';
import {ArtIcon} from './ArtIcon';
import type {RealmId} from '../core/realm';
import type {World,GameCommand} from '../core/types';
import './appointmentReview.css';
export function AppointmentReview({world:w,realm,pending,send}:{world:World;realm:RealmId;pending:boolean;send:(c:GameCommand)=>Promise<boolean>}){
 const [editing,setEditing]=useState<string|null>(null),[candidate,setCandidate]=useState(''),[approving,setApproving]=useState(false);const q=w.realm?.local?.cycle?.rounds[realm];if(!q||q.status!=='pending')return <p>本轮铨选已结束。</p>;
 const command=(action:'approve'|'reject'|'refresh'):AppointmentCommand=>({type:'appointments',action,realm,year:q.year});const changed=q.rows.filter(row=>row.incumbent!==row.candidate),other=q.rows.find(row=>row.territory!==editing&&row.candidate===candidate);
 return <section className="appointment-review"><p>依现行任官准则，综合对口能力、核验履历、门第声望、举荐信任及当地履职条件。当前拟调整 {changed.length} 职。</p><p>批准后调任职位先交接，由上级代管，文书送达且本人赴任后生效。撤换沿用现有关系与朝野支持代价；破格授官另扣支持 5、治所秩序 3。</p><div className="appointment-list">{q.rows.map(row=><article key={row.territory}><div><strong>{localTitle(row.territory)}</strong><small>{appointmentChange(row)}{row.edited?' · 御改':''}</small>{row.incumbent&&row.incumbent!==row.candidate&&<small>现任 {officeName(row.incumbent,w)}</small>}</div><button className="appointment-candidate" disabled={pending} onClick={()=>{setEditing(row.territory);setCandidate(row.candidate??'');}} aria-label={'修改'+localTitle(row.territory)+'人选'}>{row.candidate?<><CharacterPortrait world={w} characterId={row.candidate} compact/><span>{officeName(row.candidate,w)}</span></>:<><ArtIcon name="person" size={30}/><span>暂缺</span></>}</button><HoverHint label="铨选分数" content={`功绩 ${row.merit}；个人威望 ${row.prestige}；家族威望 ${row.family}。名单编制时的评分。`}><b>{row.score}</b></HoverHint></article>)}</div><div className="appointment-actions">{(['approve','reject','refresh'] as const).map(action=>{const why=appointmentReason(w,command(action));return <HoverHint key={action} label={action} content={why|| (action==='refresh'?'按当前情况重编，已付修改影响力不退还':action==='approve'?'按清单颁下任命，留任不收费':'本轮维持现任官员')}><button disabled={pending||!!why} onClick={()=>{if(action==='approve')setApproving(true);else send(command(action));}}>{action==='approve'?'批准任命':action==='reject'?'维持现任':'重新编制'}</button></HoverHint>;})}</div>{approving&&<ConfirmAction title={'批准 '+changed.length+' 项任命调整？'} detail='调任期间职位由上级代管，撤换与破格代价即时生效；文书送达并赴任后生效。' confirmLabel='批准任命' danger pending={pending||!!appointmentReason(w,command('approve'))} onCancel={()=>setApproving(false)} onConfirm={()=>{if(pending||appointmentReason(w,command('approve')))return;void afterCommand(send(command('approve')),()=>{setApproving(false);});}}/>}{editing&&<PersonSelectionDialog world={w} context={{realm,site:localSeatSite(w,editing,realm)}} title={localTitle(editing)} value={candidate} onSelect={setCandidate} onClose={()=>setEditing(null)} pending={pending} confirmLabel={`修改 · ${other?40:20} 影响力`} description={<p>{other?'此人已拟任'+localTitle(other.territory)+'，将交换两处人选，费用 40 影响力。':'修改此处人选费用 20 影响力。'}审批仍须另行确认；重编或否决不退修改费用。</p>} options={officeCandidates(w,realm).map(p=>{const factors=appointmentFactors(w,p.id,realm,editing);return {id:p.id,score:factors.score,metric:'铨选',detail:`功绩 ${factors.merit} · 个人威望 ${factors.prestige} · 家族威望 ${factors.family} · ${factors.factors.map(f=>f.label+' '+f.value).join(' / ')}`,reason:appointmentReason(w,{type:'appointments',action:'edit',realm,year:q.year,territory:editing,candidate:p.id})};})} onConfirm={()=>{void afterCommand(send({type:'appointments',action:'edit',realm,year:q.year,territory:editing,candidate}),()=>{setEditing(null);});}}/>}</section>;
}
