import {canEnter} from '../core/diplomacy';
import {armyControls,civilWar} from '../core/civilWars';
import {armyDailyFood,armyMonthlyPay,armyFieldStatus,realmReason,type Army} from '../core/realm';
import {armySupplyCapacity,armySupplyTarget,supplyReserve,convoyETA} from '../core/armyLogistics';
import {accountName} from '../core/treasury';
import {siteById} from '../data/scenario';
import {HoverHint} from './HoverHint';
import {ArtIcon,Resource} from './ArtIcon';
import type {World,GameCommand} from '../core/types';
export function ArmySupplyStatus({world:w,army:a,pending,send}:{world:World;army:Army;pending:boolean;send:(c:GameCommand)=>void}){
 const daily=armyDailyFood(w,a),days=Math.floor(a.supply/Math.max(1,daily)),c=a.convoy,city=w.realm!.cities[a.location],reserve=supplyReserve(w,a.location,a.realm),target=armySupplyTarget(w,a);
 const siege=w.realm!.sieges?.find(s=>s.site===a.location),eta=convoyETA(w,a);
 const battle=w.militaryAftermath?.battles.slice().reverse().find(b=>b.a===a.id||b.b===a.id||b.attackers?.includes(a.id!)||b.defenders?.includes(a.id!));
 const blocked=c?.route.slice(c.leg+1).some(id=>!canEnter(w,a.realm,w.realm!.cities[id].controller,undefined,true)||(civilWar(w,a.realm)&&!armyControls(w,a,id)));
 const homes=Object.entries(w.realm!.cities).filter(([,v])=>v.controller===a.realm).map(([id,v])=>({id,free:Math.max(0,v.grain-supplyReserve(w,id,a.realm)),cmd:{type:'realm',action:'march',army:a.id,site:id} as const})).filter(v=>v.free>120&&!realmReason(w,v.cmd)).sort((a,b)=>b.free-a.free).slice(0,3);
 const losses=w.chronicle.filter(e=>e.text.startsWith(`第 ${a.id} 军断粮`)).slice(-3).reverse();
 return <article className="army-supply-status"><header><ArtIcon name="army" size={30}/><strong>{siteById[a.location].name}{a.journey?' → '+siteById[a.journey.route.at(-1)!].name:''}</strong><span className="military-status" data-warning={days<10}>{days<3?'军粮告急':days<10?'补给预警':'补给充足'}</span></header>
 <div className="military-metrics"><Resource name="person" value={a.troops} label="现役兵员"/><Resource name="steadfast" value={a.morale} label="士气"/><HoverHint label="随军粮" content={<><p>随军粮 {a.supply}，每日最多耗粮 {daily}。按当前兵员保守可用 {days} 日，不含在途补给。</p><p>按缺口与持续天数结算：前两日主要影响士气，之后逐步出现减员；完全长期断粮最高每日 2%。恢复足粮后连续缺粮日数归零。</p></>}><Resource name="grain" value={a.supply} label="随军粮" unit={'约 '+days+' 日'}/></HoverHint><HoverHint label="军饷" content={<>{accountName(a.payer??'central:'+a.realm)}供饷，每月 1 日 {armyMonthlyPay(w,a)} 钱。{a.arrears?`欠饷 ${a.arrears}，士气下降、集训延期。`:''}</>}><Resource name="coins" value={armyMonthlyPay(w,a)} label="军饷" unit="/月"/></HoverHint></div>
 <div className="army-logistics-row"><ArtIcon name="grain" size={24}/>{c?<HoverHint label="粮队详情" content={<><p>{siteById[c.from].name} → {siteById[c.to].name} · 军粮 {c.grain} · 装运 {c.loaded??0}/{c.grain}，通行天数另计装运等候；抵达损耗 5%。</p>{blocked&&<p>需恢复军队通行，或撤往己方粮仓。</p>}{c.to!==(a.journey?.route.at(-1)??a.location)&&<p>目的地已改变，粮队不会追随改道。</p>}</>}><span className={blocked?'military-warning':''}>{blocked?'粮道中断':'运往 '+siteById[c.to].name} · {eta===null?'到达时间待通路恢复':`预计 ${eta} 日，含装运等候`} · 实收 {Math.floor(c.grain*.95)} 粮</span></HoverHint>:<HoverHint label="驻地补给" content={`驻地保留民食 ${reserve}；驻军按兵力备粮目标 ${target}，携行容量 ${armySupplyCapacity(a)}。余粮沿可通行道路自动调运；行军部队可向前方安全据点发起运粮，抵达后领取。`}><span>{a.journey?'沿途安全据点备粮，抵达后领取':'驻地可调粮 '+Math.max(0,city.grain-reserve)+' · 目标 '+target}</span></HoverHint>}{!!a.arrears&&<span className="military-warning">欠饷 {a.arrears}</span>}{siege&&<span>{armyFieldStatus(w,a)} · 第 {(siege.round??0)+1} 轮阶段 · 工事 {siege.progress} · 下轮 {Math.max(0,(siege.nextPhase??w.day+14)-w.day)} 日后{a.supply>0?'':' · 待补给'}</span>}</div>
 {days<10&&<div className="army-remedy"><p className="military-warning">持续缺粮将减员 · 可移驻粮仓</p><div className="muster-chips">{homes.map(v=><HoverHint key={v.id} label={'移驻'+siteById[v.id].name} content={`当地可调粮 ${v.free}；沿道路行军，途中继续消耗军粮。`}><button disabled={pending} onClick={()=>send(v.cmd)}><ArtIcon name="world" size={22}/>{siteById[v.id].name}</button></HoverHint>)}</div>{a.logisticsReason&&<small>{a.logisticsReason}</small>}{!homes.length&&<small>暂无可达粮仓，请在迁运页调粮；结清欠饷后可遣散。</small>}</div>}
 {(battle||losses.length>0)&&<div className="army-loss-row"><ArtIcon name="stress" size={22}/>{battle&&<HoverHint label="战斗损失" content={`第 ${battle.last} 日最近交锋累计减员；使用撤军行动脱离交战。`}><span>战损 {battle.losses?.[a.id!]??(battle.a===a.id?battle.lossA:battle.lossB)}</span></HoverHint>}{losses.length>0&&<HoverHint label="断粮减员记录" content={losses.map((e,i)=><p key={i}>第 {e.day} 日 · {e.text}</p>)}><span className="military-warning">断粮减员 · 第 {losses[0].day} 日</span></HoverHint>}</div>}
 </article>;
}
