import {useState} from 'react';
import {troopKinds,armyOrganizationReason,type ArmyCommand,type TroopKind} from '../core/armyOrganization';
import {playerRealm} from '../core/realm';
import {ArtIcon} from './ArtIcon';
import {HoverHint} from './HoverHint';
import {accountName} from '../core/treasury';
import {authorityGrant} from '../core/authority';
import type {World,GameCommand} from '../core/types';

export function ArmyOrganizationPanel({world:w,site,pending,send}:{world:World;site:string;pending:boolean;send:(c:GameCommand)=>void}){
 const [service,setService]=useState<'levy'|'standing'>('levy'),[confirm,setConfirm]=useState<{command:ArmyCommand;label:string;detail:string}|null>(null);
 if(!w.realm)return null;
 const armies=w.realm.armies.filter(a=>a.realm===playerRealm(w)&&a.location===site&&!a.journey),payer=w.characterId?authorityGrant(w,w.characterId,'levy',{realm:playerRealm(w),site}).account:undefined,payerName=payer?accountName(payer):'主管公库';
 const button=(command:ArmyCommand,label:string,detail:string,summary?:string)=>{const reason=armyOrganizationReason(w,command);return <div className="army-organization-choice" key={JSON.stringify(command)}><HoverHint label={label} content={<>{detail}{reason&&<p>{reason}</p>}</>}><button disabled={pending||!!reason} onClick={()=>setConfirm({command,label,detail})}><ArtIcon name="army" size={24}/><span>{label}{summary&&<small>{summary}</small>}</span></button></HoverHint>{reason&&<small className="service-warning">{reason}</small>}</div>;};
 return <section className="army-organization"><nav className="detail-tabs" aria-label="役制">{(['levy','standing'] as const).map(id=><button key={id} aria-pressed={service===id} onClick={()=>{setService(id);setConfirm(null);}}><ArtIcon name={id==='levy'?'person':'army'}/>{id==='levy'?'征发':'常备'}</button>)}</nav><div className="city-policy-grid">{(Object.keys(troopKinds) as TroopKind[]).map(kind=>{const d=troopKinds[kind],cost=d.cost*(service==='standing'?2:1);return button({type:'army',action:'raise',site,kind,service},d.name,`从本城征募 200 名居民；${payerName}支付 ${cost} 钱、本城粮仓支付 60 公粮。集训 ${service==='standing'?60:30} 日，期间照常发饷供粮；${service==='standing'?'常备月饷为同兵种征发的 1.5 倍':'征发军饷按兵种计算'}。攻击 ${d.attack}% / 防护 ${d.defence}%${kind==='siege'?'，围城速度加倍':''}`,`200 人 · ${payerName} ${cost} 钱 · 本城 60 粮`);})}</div>{armies.filter(a=>a.regiments?.length).map(a=><article key={a.id}><h4>第 {a.id} 军 · {a.troops} 人</h4>{(a.trainingUntil??0)>w.day&&<p>集训余 {a.trainingUntil!-w.day} 日</p>}<small>{accountName(a.payer??'central:'+a.realm)}供饷{a.arrears?` · 欠饷 ${a.arrears} 钱`:''}</small><div className="city-policy-grid">{a.regiments!.map(u=><div key={u.id}><strong>{troopKinds[u.kind].name} · {u.troops}</strong><small> {u.service==='standing'?'常备':'征发'}</small>{button({type:'army',action:'split',army:a.id!,regiment:u.id},'分军','兵团独立编军，按人数比例分配随军粮与欠饷。')}</div>)}{armies.filter(b=>b!==a).map(b=>button({type:'army',action:'merge',army:a.id!,target:b.id!},`合并第 ${b.id} 军`,'同城军伍整编，兵员、随军粮和欠饷一并合入所选军队。'))}</div></article>)}{w.realm.armyDebts?.filter(d=>d.realm===playerRealm(w)).map(d=><p key={d.account}>待偿军饷 · {accountName(d.account)} · {d.coins} 钱</p>)}{confirm&&<div className="diplomacy-decision" role="group" aria-label="确认军队编制"><strong>{confirm.label}</strong><p>{confirm.detail}</p><button disabled={pending||!!armyOrganizationReason(w,confirm.command)} onClick={()=>{send(confirm.command);setConfirm(null);}}>确认执行</button><button onClick={()=>setConfirm(null)}>取消</button></div>}</section>;
}
