import {afterCommand} from './actionFeedback';
import {ManpowerPreview} from './ManpowerPreview';
import {RegimentCards} from './RegimentCards';
import {ConfirmAction} from './ConfirmAction';
import {useState} from 'react';
import {troopKinds,armyOrganizationReason,readyTroops,type ArmyCommand,type TroopKind} from '../core/armyOrganization';
import {playerRealm} from '../core/realm';
import {ArtIcon,Resource} from './ArtIcon';
import {DetailTabs} from './DetailTabs';
import {HoverHint} from './HoverHint';
import {ActionDialog} from './ActionDialog';
import {accountName} from '../core/treasury';
import {authorityGrant} from '../core/authority';
import type {World,GameCommand} from '../core/types';
import './warDeclaration.css';
export function ArmyOrganizationPanel({world:w,site,pending,send,view,armyId}:{armyId?:number;view?:'raise'|'organize';world:World;site:string;pending:boolean;send:(c:GameCommand)=>Promise<boolean>}){
 const [reorganize,setReorganize]=useState<{command:ArmyCommand;label:string;detail:string}|null>(null);
 const [tab,setTab]=useState<'raise'|'organize'>('raise'),[target,setTarget]=useState<number|undefined>(),[kind,setKind]=useState<TroopKind>('shield'),[service,setService]=useState<'levy'|'standing'>('levy'),[open,setOpen]=useState(false),[amount,setAmount]=useState(200);
 if(!w.realm)return null;
 const armies=w.realm.armies.filter(a=>a.realm===playerRealm(w)&&a.location===site&&!a.journey),payer=w.characterId?authorityGrant(w,w.characterId,'levy',{realm:playerRealm(w),site}).account:undefined,payerName=payer?accountName(payer):'主管公库';
 const shownArmies=armyId?w.realm.armies.filter(a=>a.id===armyId):armies;
 const chosenTarget=armies.some(a=>a.id===target)?target:undefined;
 const command:ArmyCommand={type:'army',action:'raise',site,kind,service,target:chosenTarget,amount},reason=armyOrganizationReason(w,command),cost=Math.ceil(troopKinds[kind].cost*amount/200*(service==='standing'?2:1));
 const action=(c:ArmyCommand,label:string,detail:string)=>{const why=armyOrganizationReason(w,c);return <HoverHint key={JSON.stringify(c)} label={label} content={why||detail}><button className="muster-small-action" disabled={pending||!!why} onClick={()=>setReorganize({command:c,label,detail})}><ArtIcon name="army" size={22}/>{label}</button></HoverHint>;};
 return <section className="army-organization">{!view&&<DetailTabs label="征募与编制" value={tab} onChange={setTab} items={[{id:'raise',label:'征募',icon:'person'},{id:'organize',label:'编制',icon:'army'}]}/>}
 {(view??tab)==='raise'?<><p className="military-note">选择兵种，查看征募人数、钱粮、服役方式与编入目标。</p><div className="muster-troops">{(Object.keys(troopKinds) as TroopKind[]).map(id=>{const d=troopKinds[id],why=armyOrganizationReason(w,{...command,kind:id});return <HoverHint key={id} label={d.name} content={<><b>{d.name}</b><p>攻击 {d.attack}% · 防护 {d.defence}%{id==='siege'?' · 围城速度加倍':''}</p><p>{service==='standing'?'军饷为同兵种征发的 1.5 倍':'军饷按兵种计算'}</p>{why&&<p>{why}</p>}</>}><button className="muster-troop" data-unavailable={!!why} onClick={()=>{setKind(id);setOpen(true);}}><ArtIcon name="army" size={38}/><strong>{d.name}</strong><Resource name="coins" value={d.cost*(service==='standing'?2:1)} label={payerName}/></button></HoverHint>;})}</div>{open&&<ActionDialog title={'征募 · '+troopKinds[kind].name} onClose={()=>setOpen(false)} actions={<button className="primary" disabled={pending||!!reason} onClick={()=>{if(pending||armyOrganizationReason(w,command))return;void afterCommand(send(command),()=>{setOpen(false);});}}>确认征募 · {service==='standing'?'长期服役':'临时征发'} · {cost} 钱</button>}><p>攻击 {troopKinds[kind].attack}% · 防护 {troopKinds[kind].defence}%{kind==='siege'?' · 围城速度加倍':''}</p><label>征募人数<input type="number" min={1} max={6000} value={Number.isFinite(amount)?amount:''} onChange={event=>setAmount(event.target.valueAsNumber)}/></label><ManpowerPreview world={w} site={site} amount={amount}/><div className="muster-options"><fieldset className="muster-service-choice"><legend>服役方式 · 单选</legend><div className="muster-service-grid">{(['levy','standing'] as const).map(option=><label key={option} className={`muster-service-card ${service===option?'is-selected':''}`}><input type="radio" name={`muster-service-${site}`} value={option} checked={service===option} onChange={()=>setService(option)} disabled={pending}/><span><strong>{option==='standing'?'长期服役':'临时征发'}</strong><small>{option==='standing'?'常备军 · 集训 60 日 · 军饷为征发兵的 1.5 倍':'征发兵 · 集训 30 日 · 通常军饷'}</small></span><span className="muster-service-quote"><b>{Math.ceil(troopKinds[kind].cost*amount/200*(option==='standing'?2:1))} 钱</b><small>初次拨款</small></span></label>)}</div></fieldset>{armies.length>0&&<label className="muster-destination">编入<select value={chosenTarget??''} onChange={e=>setTarget(e.target.value?Number(e.target.value):undefined)}><option value="">另编一军</option>{armies.map(a=><option key={a.id} value={a.id}>第 {a.id} 军 · {a.troops} 人</option>)}</select></label>}</div><div className="military-metrics"><Resource name="person" value={amount} label="从本县人口征募" unit="人"/><Resource name="grain" value={Math.ceil(amount*.3)} label="扣除本城粮仓" unit="粮"/><Resource name="diligent" value={service==='standing'?60:30} label="集训期间照常供粮发饷" unit="日"/></div><p>{payerName}出资 {cost} 钱{chosenTarget!==undefined?' · 新兵集训期间老兵仍可出征':''}。</p>{reason&&<p className="military-warning" role="status">{reason}</p>}</ActionDialog>}</>:
 <div className="muster-roster">{shownArmies.map(a=><article key={a.id}><header><strong>第 {a.id} 军</strong><Resource name="person" value={a.troops} label="现役"/><small>可出征 {readyTroops(a,w.day)} / {a.troops} 人</small></header><RegimentCards army={a} world={w} actions={u=>action({type:'army',action:'split',army:a.id!,regiment:u.id},'分军','按兵员比例划转随军粮与欠饷。')}/><div className="muster-chips">{armies.filter(b=>b.id!==a.id&&(armyId!==undefined||(b.id??0)>(a.id??0))).map(b=>action({type:'army',action:'merge',army:a.id!,target:b.id!},`合入第 ${b.id} 军`,`将第 ${a.id} 军兵员、粮食与欠饷合入第 ${b.id} 军；原军撤销。`))}</div></article>)}{!shownArmies.length&&<p className="military-note">本城暂无停驻军队</p>}{w.realm.armyDebts?.filter(d=>d.realm===playerRealm(w)).map(d=><p key={d.account} className="military-warning">{accountName(d.account)} · 待偿军饷 {d.coins} 钱</p>)}</div>}{reorganize&&<ConfirmAction title={reorganize.label} detail={<><p>{reorganize.detail}</p>{armyOrganizationReason(w,reorganize.command)&&<p role="status">{armyOrganizationReason(w,reorganize.command)}</p>}</>} confirmLabel="确认编制调整" pending={pending||!!armyOrganizationReason(w,reorganize.command)} onCancel={()=>setReorganize(null)} onConfirm={()=>{if(pending||armyOrganizationReason(w,reorganize.command))return;void afterCommand(send(reorganize.command),()=>{setReorganize(null);});}}/>}</section>;
}
