import {CommercePanel} from './CommercePanel';
import {useState} from 'react';
import type {World,GameCommand} from '../core/types';
import {enterpriseReason,type EnterpriseCommand} from '../core/enterprises';
import {campaignReason,type MilitaryCampaignCommand} from '../core/militaryCampaigns';
import {civilReason,revoltSupport,civilWar,playerCommandsArmy} from '../core/civilWars';
import {activeWars} from '../core/wars';
import {playerRealm} from '../core/realm';
import {officeCandidates} from '../core/officeEligibility';
import {attributes} from '../core/social';
import {siteById} from '../data/scenario';
import {ArtIcon,type ArtName} from './ArtIcon';
import {HoverHint} from './HoverHint';
import {PersonChoice} from './PersonSelection';
import {CharacterPortrait} from './CharacterPortrait';
import {politicalName} from '../core/government';
import './careerSystems.css';
type Props={world:World;pending:boolean;send:(c:GameCommand)=>void};
function Action({command,label,reason,detail,icon='influence',...p}:Props&{command:GameCommand;label:string;reason:string;detail:string;icon?:ArtName}){const [confirm,setConfirm]=useState(false);return <div><HoverHint label={label} content={<>{detail}{reason&&<p>{reason}</p>}</>}><button className="diplomacy-action-card" disabled={p.pending||!!reason} onClick={()=>setConfirm(true)}><ArtIcon name={icon} size={28}/>{label}</button></HoverHint>{confirm&&<div className="diplomacy-decision"><p>{detail}</p><button disabled={p.pending||!!reason} onClick={()=>{p.send(command);setConfirm(false);}}>确认</button><button onClick={()=>setConfirm(false)}>取消</button></div>}</div>;}
export function EnterprisePanel(p:Props){const w=p.world;const action=(c:EnterpriseCommand,label:string,detail:string)=><Action key={JSON.stringify(c)} {...p} command={c} label={label} detail={detail} reason={enterpriseReason(w,c)} icon="coins"/>;
 return <section className="career-systems"><h3><ArtIcon name="coins"/>私人事业</h3><div className="city-policy-grid">{action({type:'enterprise',action:'open',kind:'workshop'},'置办作坊','私财 120 钱转入事业资本，承接地方修缮；须赴所在地办理。')}{action({type:'enterprise',action:'open',kind:'agriculture'},'兴办农务','私财 120 钱转入事业资本，承接水利劳务；须赴所在地办理。')}</div>{w.enterprises?.items.filter(e=>e.owner===w.characterId&&!e.closed).map(e=><article key={e.id}><h4><ArtIcon name={e.kind==='workshop'?'city':'grain'}/>{siteById[e.site].name} · {e.kind==='workshop'?'作坊':'农务'}</h4><div className="city-civic-metrics"><span>资本 <b>{e.capital}</b></span><HoverHint label="累计收支" content={`已验收收入 ${e.earned}，已投入劳务成本 ${e.spent}；不包含未验收价款。`}><span>经营盈余 <b>{e.earned-e.spent}</b></span></HoverHint></div><div className="city-policy-grid">{action({type:'enterprise',action:'withdraw',id:e.id},'支取 100','将事业资本 100 钱转入个人现钱；可能影响下一单承接。')}{action({type:'enterprise',action:'invest',id:e.id},'增资 100','从个人现钱投入 100 钱，补充事业资本。')}</div>{e.order?<><progress value={e.order.progress} max={e.order.required}/><p>履约 {e.order.progress}/{e.order.required} 日 · 截止余 {Math.max(0,e.order.deadline-w.day)} 日 · 预付待验款 {e.order.escrow}</p>{action({type:'enterprise',action:'cancel',id:e.id},'撤销合同','未验收价款退回公库，已投入成本不退。')}</>:<div className="city-policy-grid">{action({type:'enterprise',action:'order',id:e.id,method:'careful'},'精工承包','成本 60 钱，驻留办理 30 日，验收收入 100 钱；修缮繁荣 +8 或水利 +1。不得承接自己审批的合同。')}{action({type:'enterprise',action:'order',id:e.id,method:'swift'},'简办承包','成本 30 钱，驻留办理 20 日，验收收入 65 钱；修缮繁荣 +3 或水利 +1。剩余预付款退回公库。')}{action({type:'enterprise',action:'close',id:e.id},'结业取回资本','剩余事业资本转回私财，结业不返还已经消耗的成本。')}</div>}<CommercePanel {...p} enterprise={e.id}/></article>)}</section>;
}
export function MilitaryCampaignPanel(p:Props&{site:string}){const w=p.world,r=playerRealm(w),armies=w.realm!.armies.filter(a=>playerCommandsArmy(w,a)),wars=activeWars(w).filter(v=>!v.civil&&[v.attacker,v.defender].includes(r));
 const [army,setArmy]=useState(0),[war,setWar]=useState(0),[commander,setCommander]=useState(''),[budget,setBudget]=useState(200),[limit,setLimit]=useState(50),[goal,setGoal]=useState<'capture'|'defend'>('capture');
 const a=armies.find(a=>a.id===army)??armies[0],v=wars.find(v=>v.id===war)??wars[0],command:MilitaryCampaignCommand={type:'militaryCampaign',action:'commission',army:a?.id??0,war:v?.id??0,commander,target:p.site,goal,budget,lossLimit:limit};
 const action=(c:MilitaryCampaignCommand,label:string,detail:string)=><Action {...p} command={c} label={label} detail={detail} reason={campaignReason(w,c)} icon="army"/>;
 return <section className="career-systems"><h3><ArtIcon name="army"/>战役委任</h3>{wars.length>0&&<><div className="career-parameters"><label>部队<select value={a?.id??0} onChange={e=>setArmy(+e.target.value)}>{armies.map(a=><option key={a.id} value={a.id}>第 {a.id} 军 · {a.troops} 人</option>)}</select></label><label>战事<select value={v?.id??0} onChange={e=>setWar(+e.target.value)}>{wars.map(v=><option key={v.id} value={v.id}>{siteById[v.target].name}战事</option>)}</select></label><label>专款<input type="number" min={100} max={1000} step={100} value={budget} onChange={e=>setBudget(+e.target.value)}/></label><label>损失上限<select value={limit} onChange={e=>setLimit(+e.target.value)}>{[25,50,75].map(n=><option key={n} value={n}>{n}%</option>)}</select></label></div><nav className="detail-tabs" aria-label="战役职责">{(['capture','defend'] as const).map(g=><button key={g} aria-pressed={goal===g} onClick={()=>setGoal(g)}><ArtIcon name={g==='capture'?'army':'city'}/>{g==='capture'?'攻取此地':'守备此地'}</button>)}</nav><PersonChoice world={w} title="战役统帅" value={commander} onChange={setCommander} pending={p.pending} options={officeCandidates(w,r).map(c=>({id:c.id,score:attributes(w,c.id).martial,metric:'军事',reason:campaignReason(w,{...command,commander:c.id})}))}/>{action(command,'下达委任',`将 ${budget} 公款划为军饷专款；限期 180 日，损失达到 ${limit}% 时结束战役。攻取或守备三十日后按保全部队核记功绩；未用预算退回。`)}</>}{w.militaryCampaigns?.items.filter(q=>q.realm===r&&(q.status==='active'||q.commander===w.characterId)).slice(-8).reverse().map(q=><article key={q.id} className="career-campaign"><div className="career-commander"><CharacterPortrait characterId={q.commander} world={w} compact/><div><strong>{politicalName(q.commander)} · 第 {q.army} 军</strong><small>{siteById[q.target].name} · {q.goal==='capture'?'攻取':'守备'} · {q.status==='active'?`余 ${Math.max(0,q.deadline-w.day)} 日`:q.status==='success'?'完成':q.status==='cancelled'?'撤回':'中止'}</small></div></div><p>预算 {q.budget} · 已付军饷 {q.spent} · 留存 {q.remaining}</p>{q.reason&&<p>{q.reason}</p>}{q.status==='active'&&<div className="city-policy-grid">{action({type:'militaryCampaign',action:'reinforce',id:q.id},'追加军饷','从原账户追加专款 100 钱，不增加军队人数。')}{action({type:'militaryCampaign',action:'cancel',id:q.id},'终止委任','停止自动推进目标，退回未用专款；部队保留当前位置与欠饷。')}</div>}</article>)}</section>;
}
export function CivilWarPanel(p:Props){const w=p.world,r=playerRealm(w),[name,setName]=useState('新朝'),support=revoltSupport(w);if(civilWar(w,r))return null;const c={type:'civilWar',action:'rise',name} as const;
 return <section className="career-systems"><h3><ArtIcon name="influence"/>争夺朝廷</h3><div className="city-civic-metrics"><span>支持县域 <b>{support.cities.length}</b></span><span>响应军队 <b>{support.armies.length}</b></span></div><div className="career-supporters">{support.supporters.filter(id=>id!==w.characterId).map(id=><HoverHint key={id} label={politicalName(id)} content="实任地方官：对你的好感至少 40，且高于对执政者好感 20。"><CharacterPortrait world={w} characterId={id} compact/></HoverHint>)}</div><label>胜后国号<input value={name} maxLength={4} onChange={e=>setName(e.target.value)}/></label><Action {...p} command={c} label="举兵争位" icon="army" reason={civilReason(w,c)} detail="投入私财 100、影响力 60。支持地区截留税款，地方部队与朝廷交战；取得首都且瓦解抵抗后才能要求更换君主。战败失去公职，私产保留。"/></section>;
}
