import {RealmFlag} from './RealmFlag';
import type {Polity} from '../core/types';
import {familyById} from '../data/families';
import {relationshipPersonById} from '../data/relationships';
import {useEffect,useState} from 'react';
import type {FeatureCollection,Geometry,Position} from 'geojson';
import {ageLabel} from '../core/lifeState';
import {regimeName,politicalTitle} from '../core/government';
import type {World} from '../core/types';
import {Resource,ArtIcon} from './ArtIcon';
import {CharacterPortrait} from './CharacterPortrait';
import {getScript} from '../data/scripts';
import {characterById,relationsFor,roleNames,startRules,familyName} from '../data/characters';
import {siteById,polities} from '../data/scenario';
import './characters.css';
const project=([lon,lat]:Position)=>[(lon-100)*25,(42-lat)*30];
function line(points:Position[],closed=false){return points.map((p,i)=>(i?'L':'M')+project(p).join(',')).join(' ')+(closed?'Z':'');}
function path(g:Geometry):string{switch(g.type){case 'Polygon':return g.coordinates.map(p=>line(p,true)).join(' ');case 'MultiPolygon':return g.coordinates.flatMap(p=>p.map(r=>line(r,true))).join(' ');case 'LineString':return line(g.coordinates);case 'MultiLineString':return g.coordinates.map(p=>line(p)).join(' ');case 'GeometryCollection':return g.geometries.map(path).join(' ');default:return '';}}
export function CharacterPicker({selected,onSelect,allowFictional=true,scriptId,sandbox=false,world,pending=false}:{selected:string;onSelect:(id:string)=>void;allowFictional?:boolean;scriptId?:string;sandbox?:boolean;world?:World;pending?:boolean;onPerson?:(id:string)=>void}){
 const script=getScript(scriptId),roster=script.characterIds.map(id=>characterById[id]).filter(Boolean);
 const [realm,setRealm]=useState('all'),[query,setQuery]=useState(''),[view,setView]=useState<'map'|'list'>('map'),[city,setCity]=useState(''),[geography,setGeography]=useState<{land:string;rivers:string}|null>(null),[mapError,setMapError]=useState(false);
 useEffect(()=>{const controller=new AbortController();Promise.all(['land','rivers'].map(async name=>{const response=await fetch(import.meta.env.BASE_URL+'data/'+name+'.geojson',{signal:controller.signal});if(!response.ok)throw new Error('map');const data=await response.json() as FeatureCollection;return data.features.map(f=>path(f.geometry)).join(' ');})).then(([land,rivers])=>setGeography({land,rivers})).catch(()=>{if(!controller.signal.aborted)setMapError(true);});return()=>controller.abort();},[]);
 const c=characterById[selected],rules=c?startRules(c):null,visible=roster.filter(p=>(realm==='all'||p.polity===realm)&&(p.name+p.title+siteById[p.home].name+(familyById[p.family]?.name??familyName(p.family))).includes(query.trim())),cities=Array.from(new Set(visible.map(p=>p.home))),activeCity=cities.includes(city)?city:c&&cities.includes(c.home)?c.home:cities[0],listed=view==='map'?visible.filter(p=>p.home===activeCity):visible;
 const selectedHidden=selected!=='fictional'&&!visible.some(p=>p.id===selected);
 const choose=(id:string)=>{onSelect(id);setCity(characterById[id]?.home??'');};
 return <fieldset className="character-picker" disabled={pending}><div className="roster-heading"><strong>{script.year} · {script.name}</strong><nav aria-label="选人方式">{(['map','list'] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}><ArtIcon name={v==='map'?'world':'person'} size={22}/>{v==='map'?'地图':'名单'}</button>)}</nav><input aria-label="搜索剧本人物" placeholder="搜索姓名、身份、城市" value={query} onChange={e=>{setQuery(e.target.value);if(e.target.value)setView('list');}}/></div><div className="roster-filters">{[['all','全部'],['liang','梁'],['east','东魏'],['west','西魏']].map(([id,label])=><button key={id} aria-pressed={realm===id} onClick={()=>setRealm(id)}>{id!=='all'&&<RealmFlag realm={id as Polity} compact showLabel={false}/>}<span>{label}</span><small>{id==='all'?roster.length:roster.filter(p=>p.polity===id).length}</small></button>)}</div>
 <div className="roster-context"><span>{view==='map'&&activeCity?siteById[activeCity].name+' · 城中人物':'剧本人物'} · {(mapError?visible:listed).length} 人</span>{(query||realm!=='all')&&<button onClick={()=>{setRealm('all');setQuery('');}}>清除筛选</button>}{selectedHidden&&<span role="status">当前所选人物不在筛选结果中</span>}</div><div className="roster-columns"><div className="roster-explorer">{view==='map'&&<div className="roster-map">{mapError?<p role="status">地理底图无法加载，仍可在下方名单选择人物。</p>:<svg viewBox="0 0 600 570" aria-label="选择人物所在城市"><rect width="600" height="570" fill="#9caeaa"/>{geography&&<><path d={geography.land} fill="#d0c19d" stroke="#8b805f" strokeWidth="1"/><path d={geography.rivers} fill="none" stroke="#668d91" strokeWidth="1.3"/></>}{cities.map(id=>{const s=siteById[id],[x,y]=project([s.lon,s.lat]),people=visible.filter(p=>p.home===id);return <g key={id} role="button" tabIndex={pending?-1:0} aria-disabled={pending} aria-label={s.name+'，'+people.map(p=>p.name).join('、')} aria-pressed={activeCity===id} onClick={()=>{if(pending)return;setCity(id);if(people.length===1)choose(people[0].id);}} onKeyDown={e=>{if(!pending&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setCity(id);if(people.length===1)choose(people[0].id);}}}><circle cx={x} cy={y} r={activeCity===id?12:9} fill={polities[s.polity].color} stroke={activeCity===id?'#fff0ad':'#3c4736'} strokeWidth="3"/><text x={x+16} y={y+5}>{s.name} · {people.length}</text></g>;})}</svg>}{!geography&&!mapError&&<span className="roster-map-loading">载入山河…</span>}</div>}<div className="roster-list" aria-label={view==='map'?'城中可选人物':'剧本人物名单'}>{(mapError?visible:listed).map(p=><button key={p.id} aria-pressed={selected===p.id} onClick={()=>choose(p.id)}><CharacterPortrait characterId={p.id} world={world} compact/><span><strong>{p.name}</strong><small>{regimeName(world,p.polity)} · {politicalTitle(world,p.id)}</small></span><small>{siteById[p.home].name}</small></button>)}{!visible.length&&<p>未找到匹配人物。可清除筛选后重新选择。</p>}{allowFictional&&<button aria-pressed={selected==='fictional'} onClick={()=>choose('fictional')}><CharacterPortrait characterId="fictional" compact/><span>沈行舟<small>营建教学</small></span></button>}</div></div>
 <article className="roster-profile" aria-live="polite"><div className="roster-identity"><CharacterPortrait characterId={selected} world={world}/><div><span className="eyebrow">{c?regimeName(world,c.polity)+' · '+roleNames[c.role]:'营建教学'}</span><h2>{c?.name??'沈行舟'}</h2>{relationshipPersonById[selected]?.status==='fictional'&&<small>架空人物</small>}<small>{ageLabel(world,selected)}</small><p className="roster-title">{c?politicalTitle(world,c.id):'江左行旅'}</p>{c&&<span>{familyById[c.family]?.name??familyName(c.family)} · {siteById[c.home].name}</span>}</div></div>{c&&rules?<><div className="roster-resources"><Resource name="coins" value={rules.coins} label="起始盘缠" unit="钱"/><Resource name="grain" value={rules.food} label="起始行粮" unit="日"/></div><p>{c.biography}</p><h3>亲族与同道</h3><div className="roster-kin">{relationsFor(c.id).filter(r=>roster.some(p=>p.id===r.id)).map(r=><button key={r.id} title={r.label+' · '+characterById[r.id].name} onClick={()=>{setRealm('all');setQuery('');choose(r.id);}}><CharacterPortrait characterId={r.id} compact/><small>{r.label}</small><span>{characterById[r.id].name}</span></button>)}</div><p className="entry-note">{sandbox?'经营家族与辖地，争取官职，延续家业。':`120 日内：${siteById[c.home].name}市肆 ${rules.market} 级、${rules.granary?'城仓 '+rules.granary+' 级':'驿舍 1 级'}、田庄 1 级，经营满 30 日。`}</p></>:<p>从建康赴京口领取营建委任，建成市肆与田庄后返回建康。120 日期限，180 钱、90 日行粮。</p>}</article></div></fieldset>;
}
