import {TreasuryPanel} from './TreasuryPanel';
import {localBalance} from '../core/treasury';
import {ArmyCommand,MobilityPanel} from './MobilityPanel';
import {useState} from 'react';
import {ArtIcon,Resource} from './ArtIcon';
import {armyDailyFood,armyMonthlyPay,playerRealm,realmReason,cityYield,type RealmCommand,type Tax} from '../core/realm';
import {governmentOf,regimeName} from '../core/government';
import {siteById} from '../data/scenario';
import type {World,GameCommand} from '../core/types';
import './realm.css';
export function CityManagement({world:w,selected,tab,pending,send,onPerson}:{onPerson?:(id:string)=>void;world:World;selected:string;tab:'governance'|'military';pending:boolean;send:(c:GameCommand)=>void}){
 const [confirm,setConfirm]=useState<string|null>(null),s=w.realm;
 if(!s)return <p>此局尚未开放政务与军务。</p>;
 const r=playerRealm(w),city=s.cities[selected],army=s.armies.find(a=>a.realm===r),war=s.war,y=cityYield(w,selected),t=s.treasuries[r],musterSite=s.cities[w.people[0].home].controller===r?w.people[0].home:Object.keys(s.cities).find(id=>s.cities[id].controller===r);
 const action=(c:RealmCommand,label:string,danger=false)=>{const reason=realmReason(w,c),key=JSON.stringify(c);return <div className="realm-action"><button disabled={pending||!!reason||c.action==='tax'&&c.tax===city.tax} className={danger?'danger':''} onClick={()=>{if(danger&&confirm!==key){setConfirm(key);return;}setConfirm(null);send(c);}}>{confirm===key?'确认：':''}{label}</button>{reason&&<small>{reason}</small>}{confirm===key&&<button onClick={()=>setConfirm(null)}>取消</button>}</div>;};
 return <div className="realm-panel city-management"><div className="city-public-funds"><Resource name="coins" value={localBalance(w,selected)} label="本城公款" caption/><Resource name="grain" value={t.grain} label="中央公粮" caption/><Resource name="influence" value={s.influence} label="影响力" caption/></div>
 {tab==='governance'&&<><MobilityPanel world={w} site={selected} send={send} pending={pending}/><section><h3><ArtIcon name="coins"/>治理城邑</h3><div className="city-civic-metrics"><span>户数 <b>{city.households}</b></span><span>秩序 <b>{city.order}</b></span><span>繁荣 <b>{city.prosperity}</b></span></div><p>本城每期税收 {y.coins} 钱 · 产粮 {y.grain} · 行政支出 {y.expense} 钱</p><div className="realm-actions">{(['light','normal','heavy'] as Tax[]).map(tax=><div key={tax}>{action({type:'realm',action:'tax',site:selected,tax},({light:'轻税 · 70%',normal:'常税 · 100%',heavy:'重税 · 140%'})[tax]+(city.tax===tax?' · 当前':''))}</div>)}</div>{action({type:'realm',action:'relief',site:selected},'赈济本城 · 50 公粮 / 秩序 +15')}<small>轻税每期秩序 +4，常税 +1，重税 −6。</small></section>
 <TreasuryPanel world={w} pending={pending} send={send} site={selected} onPerson={onPerson}/></>}
 {tab==='military'&&<><ArmyCommand onPerson={onPerson} world={w} send={send} pending={pending}/><MobilityPanel world={w} site={selected} send={send} pending={pending}/><section className="realm-war"><h3>{war?`${regimeName(w,war.attacker)}与${regimeName(w,war.defender)}的边境争夺`:'暂无战争'}</h3>{war?<><p>争夺：{siteById[war.target].name} · 攻方战争分数 {war.score} · 历时 {w.day-war.started} 日</p><p>攻方占领目标且战争分数达到 50，议和可割让目标城市；否则恢复战前归属。其他城市占领全部归还。360 日后自动议和，停战期 360 日。</p>{action({type:'realm',action:'peace'},s.cities[war.target].controller===war.attacker&&war.score>=50?'议和 · 目标城割让给攻方':'议和 · 恢复战前归属',true)}</>:<p>军务授权允许消耗 40 影响力，对相邻敌国城市提出边境争夺。</p>}</section><section><h3>{army?'已动员军队':'未动员'}</h3>{army&&<><p>{army.troops} 人 · 士气 {army.morale} · 随军粮 {army.supply}</p><p>位置：{siteById[army.location].name}{army.journey?' → '+siteById[army.journey.route.at(-1)!].name:'（驻扎）'}{army.siege?` · 围城 ${army.siege} 日`:''}</p><p>每日需粮 {armyDailyFood(w,army)}；每 30 日军饷 {armyMonthlyPay(w,army)} 钱。己方控制城市及直接相邻城市可从公库补给，深入敌境会断粮。</p></>}<div className="realm-actions"><p className="realm-note">{governmentOf(w)?.type==='nomadic'?'动员另需畜群 100':governmentOf(w)?.type==='khanate'?'动员另需畜群 50':governmentOf(w)?.type==='tribal'?'动员需支持 50，消耗 10 支持':''}</p>{action({type:'realm',action:'muster'},(musterSite?'在'+siteById[musterSite].name:'无可用驻地')+'动员 600 人 · 120 钱 / 120 粮')}{action({type:'realm',action:'disband'},'遣散军队')}</div></section><p>法理：{regimeName(w,city.owner)} · 军事控制：{regimeName(w,city.controller)}</p><div className="realm-actions">{action({type:'realm',action:'war',site:selected},'发起边境争夺 · 40 影响力',true)}{action({type:'realm',action:'march',site:selected},'向此城行军')}</div><p className="realm-note">行军按道路推进，同城敌军每日交战；守军未被击退不能围城。持续补给下普通城围城约 20 日，都城 40 日，城仓延长守备。议和后军队撤回本方城市，撤军立即完成。</p></>}
 </div>;
}
