import {armyHeraldry} from '../map/ArmyHeraldry';
import {loadCampaignSampleAssets} from '../map/CampaignSampleAssets';
import {campaignCityAppearance} from '../map/campaignScenery';
import {siteById} from '../data/scenario';
import {combatMaterials,combatRoof,combatTent} from './combatScenery';
import {useEffect,useRef,useState} from 'react';
import {ACESFilmicToneMapping,AmbientLight,BoxGeometry,Color,ConeGeometry,DirectionalLight,Float32BufferAttribute,Fog,Group,Mesh,MeshStandardMaterial,PCFSoftShadowMap,PerspectiveCamera,PlaneGeometry,RingGeometry,IcosahedronGeometry,CanvasTexture,MeshBasicMaterial,Raycaster,Scene,Vector2,WebGLRenderer} from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {militaryModelAssets,animateMilitaryModel,type MilitaryModel,type ArmyModelKind} from '../map/MilitaryModels';
import type {World} from '../core/types';
import {regimeName} from '../core/government';
import {formationAction,formationCapacity,formationRepresentatives,type CombatSceneView,type FormationGroup} from '../core/combatPresentation';
import type {Army} from '../core/realm';
const modelKind=(kind:FormationGroup['kind']):ArmyModelKind=>kind==='shield'||kind==='unknown'?'foot':kind;
/** One bounded viewport; owns and disposes every temporary model and GPU resource. */
export function CombatScene({world,view,selected,onSelect,motion}:{world:World;view:CombatSceneView;selected:string;onSelect:(key:string)=>void;motion:boolean}){
 const host=useRef<HTMLDivElement>(null),latest=useRef({view,selected,onSelect,motion});latest.current={view,selected,onSelect,motion};const [error,setError]=useState('');
 const composition=view.groups.map(g=>g.key+':'+(g.troops===0?'empty':'present')).join('|');
 useEffect(()=>{const node=host.current;if(!node)return;let renderer:WebGLRenderer;try{renderer=new WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{setError('战场画面无法载入；军阵数据与战报仍可查看。');return;}
  setError('');const abort=new AbortController(),scene=new Scene(),camera=new PerspectiveCamera(42,1,.1,160);scene.background=new Color('#9c9f9b');scene.fog=new Fog('#9c9f9b',24,64);renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.outputColorSpace='srgb';renderer.toneMapping=ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=PCFSoftShadowMap;node.append(renderer.domElement);renderer.domElement.setAttribute('aria-label',view.kind==='siege'?'围城三维沙盘，可旋转缩放并选择兵团':'战役三维沙盘，可旋转缩放并选择兵团');renderer.domElement.tabIndex=0;
  camera.position.set(view.kind==='siege'?10:1,view.kind==='siege'?6.4:4.3,view.kind==='siege'?18:11.5);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,view.kind==='siege'?2.3:1.4,view.kind==='siege'?-3:0);controls.minDistance=9;controls.maxDistance=42;controls.minPolarAngle=.45;controls.maxPolarAngle=1.4;controls.enablePan=false;controls.enableDamping=false;controls.update();
  const sun=new DirectionalLight('#ffe8c7',2.6);sun.position.set(-18,22,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=sun.shadow.camera.bottom=-25;sun.shadow.camera.right=sun.shadow.camera.top=25;sun.shadow.bias=-.0003;sun.shadow.normalBias=.025;const fill=new DirectionalLight('#d9e3e8',.65);fill.position.set(12,9,14);scene.add(sun,fill,new AmbientLight('#b9c8ce',1.5));
  const resources:{dispose:()=>void}[]=[],surfaces=combatMaterials(abort.signal,()=>{dirty=true;},()=>{if(!disposed)setError('战场材质未能载入，保留军阵与城防画面。');}),{earth,stone,roof,wood,linen}=surfaces;resources.push(surfaces);
  const skyCanvas=document.createElement('canvas');skyCanvas.width=2;skyCanvas.height=128;const skyContext=skyCanvas.getContext('2d')!,skyGradient=skyContext.createLinearGradient(0,0,0,128);skyGradient.addColorStop(0,'#586872');skyGradient.addColorStop(.55,'#9da6a5');skyGradient.addColorStop(1,'#b0b0a3');skyContext.fillStyle=skyGradient;skyContext.fillRect(0,0,2,128);const sky=new CanvasTexture(skyCanvas);sky.colorSpace='srgb';scene.background=sky;resources.push(sky);
  function box(parent:Group|Scene,w:number,h:number,d:number,x:number,y:number,z:number,material=stone){const geometry=new BoxGeometry(w,h,d);resources.push(geometry);const mesh=new Mesh(geometry,material);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
  const groundGeometry=new PlaneGeometry(100,100,30,30);resources.push(groundGeometry);const p=groundGeometry.getAttribute('position');for(let i=0;i<p.count;i++)p.setZ(i,Math.sin(p.getX(i)*.21)*Math.cos(p.getY(i)*.19)*.16);const colors=[];for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getY(i),noise=.88+Math.sin(x*2.7+z*1.2)*.045+Math.cos(z*3.2-x)*.03;colors.push(noise,noise,noise*.94);}groundGeometry.setAttribute('color',new Float32BufferAttribute(colors,3));earth.vertexColors=true;groundGeometry.computeVertexNormals();const ground=new Mesh(groundGeometry,earth);ground.rotation.x=-Math.PI/2;ground.position.y=-.13;ground.receiveShadow=true;scene.add(ground);
  // A schematic local battlefield, separate from the authoritative campaign terrain.
  const trees=new Group();scene.add(trees);const trunkGeometry=new BoxGeometry(.2,1.3,.2),leafGeometry=new ConeGeometry(.95,3.2,7),leaf=new MeshStandardMaterial({color:'#344837',roughness:1});resources.push(trunkGeometry,leafGeometry,leaf);for(let i=0;i<45;i++){const x=Math.sin(i*18.13)*35,z=-13-Math.abs(Math.cos(i*5.81))*25;if(Math.abs(x)<10&&z>-20)continue;const trunk=new Mesh(trunkGeometry,wood),crown=new Mesh(leafGeometry,leaf);trunk.position.set(x,.65,z);crown.position.set(x,2.5,z);trees.add(trunk,crown);}
  const walls=new Group(),gate=new Group(),breaches:Group[]=[],rubble:Group[]=[];scene.add(walls);walls.add(gate);
  function tiledRoof(parent:Group,width:number,depth:number,rise:number,x:number,y:number,z:number){const geometry=combatRoof(width,depth,rise);resources.push(geometry);const mesh=new Mesh(geometry,roof);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
  if(view.kind==='siege'){
   walls.scale.y=.9+view.fort*.12;
   for(let i=0;i<16;i++){const x=(i-7.5)*2.1;if(Math.abs(x)<2.2)continue;const section=new Group();section.position.set(x,0,-6);walls.add(section);box(section,2.08,4.6,1.25,0,2.3,0);box(section,2.08,.22,1.55,0,4.6,0);if(i===5||i===10||i===11)breaches.push(section);for(let j=0;j<3;j++)box(section,.38,.65,1.35,-.7+j*.7,5.04,0);}
   // A readable gate opening; each door pivots about its actual hinge.
   gate.position.set(-1.6,0,-5.3);box(gate,3.2,3.7,.22,1.6,1.85,0,wood);for(let row=0;row<4;row++)box(gate,3.2,.09,.27,1.6,.55+row*.75,0,roof);
   for(const x of [-2.25,2.25])box(walls,1.5,5.1,2.5,x,2.55,-6);
   for(const x of [-13,0,13]){const tower=new Group();tower.position.set(x,0,-6);walls.add(tower);box(tower,x===0?5.8:3.5,.35,3.1,0,5.1,0);for(const px of [-1,1])for(const pz of [-1,1])box(tower,.17,1.8,.17,px*(x===0?2.5:1.3),6.1,pz*1.2,wood);box(tower,x===0?5.2:2.6,1.2,2.4,0,6.1,0,wood);tiledRoof(tower,x===0?7:4.5,4.2,1.2,0,6.85,0);box(tower,x===0?7:4.5,.13,4.1,0,6.87,0,wood);}
   for(let i=0;i<9;i++){const x=(i%3-1)*5,z=-12-Math.floor(i/3)*4;box(walls,3,1.4,2.4,x,.7,z,wood);tiledRoof(walls,3.8,3.1,.8,x,1.4,z);}
   // An exterior encampment and interrupted ditch leave the approach to the gate clear.
   for(const x of [-13,13]){box(scene,3.2,.08,13,x,-.04,3,wood);for(let i=0;i<22;i++){const stake=box(scene,.11,1.1,.11,x+(i%2?1.5:-1.5),.5,-3+Math.floor(i/2)*1.15,wood);stake.rotation.z=i%2?.22:-.22;}}
  }
  const rubbleGeometry=new IcosahedronGeometry(.5,0);resources.push(rubbleGeometry);for(const section of breaches){const debris=new Group();debris.position.set(section.position.x,0,section.position.z+1.2);scene.add(debris);rubble.push(debris);for(let i=0;i<15;i++){const stoneMesh=new Mesh(rubbleGeometry,stone);stoneMesh.position.set(Math.sin(i*9.1)*1.3,.12+Math.abs(Math.cos(i*5.7))*.25,Math.cos(i*7.3)*1.2);stoneMesh.scale.set(.35+(i%4)*.2,.3+(i%3)*.12,.5);stoneMesh.rotation.set(i,.3*i,i*.7);stoneMesh.castShadow=true;stoneMesh.receiveShadow=true;debris.add(stoneMesh);}}
  const tentGeometry=combatTent();resources.push(tentGeometry);for(let i=0;i<(view.kind==='siege'?10:6);i++){const tent=new Mesh(tentGeometry,linen);tent.position.set((i%2?1:-1)*(10+Math.floor(i/2)*2.8),0,view.kind==='siege'?8+Math.floor(i/2)*1.5:-10-Math.floor(i/2)*2);tent.castShadow=true;tent.receiveShadow=true;scene.add(tent);}
  let dirty=true,renderKey='',disposed=false,frame=0,lastFrame=0,elapsed=0,start=performance.now(),event=latest.current.view.eventId;const assets=militaryModelAssets(()=>{dirty=true;},message=>{if(!disposed)setError(message);},abort.signal),units:{model:MilitaryModel;group:string;baseX:number;baseZ:number;index:number}[]=[];
  for(const g of latest.current.view.groups){if(g.troops===0)continue;const count=formationCapacity(g.kind),side=g.side==='attack'?1:-1,cavalry=g.kind==='lightHorse'||g.kind==='heavyHorse',lane=g.kind==='shield'?0:g.kind==='spear'?1:g.kind==='archer'?2:g.kind==='siege'?3:g.kind==='lightHorse'?-2:2;
   for(let i=0;i<count;i++){const a:Pick<Army,'id'|'realm'>={id:units.length+1,realm:g.realm};
    // Concealed forces keep a fixed generic formation, independent of secret strength.
    const model=assets.create(a,modelKind(g.kind),regimeName(world,a.realm),world,g.kind==='unknown');model.root.matrixAutoUpdate=true;model.root.scale.setScalar(g.kind==='siege'?2:1.25);model.root.userData.formation=g.key;model.banner.visible=i===0;model.banner.scale.setScalar(1.35);model.camp.visible=false;
    const guard=view.kind==='siege'&&g.side!==view.besiegingSide,columns=g.kind==='unknown'?4:3;
    const x=view.kind==='siege'?guard?(i%columns-(columns-1)/2)*1.05:(lane-1)*3.2+(i%3-1)*1.1:-side*(.85+Math.floor(i/(cavalry?2:columns))*1.05+(g.kind==='archer'?3.7:g.kind==='siege'?5.7:cavalry?2:0));
    const z=view.kind==='siege'?guard?-8-Math.floor(i/columns)*1.15:1+Math.floor(i/3)*1.05+(g.kind==='archer'?3:0)+(g.kind==='siege'?4:0):cavalry?(g.kind==='lightHorse'?-5:5)+(i%2-.5)*1.2:(i%columns-(columns-1)/2)*1.05+(g.kind==='shield'?-1.65:g.kind==='spear'?1.65:0);model.root.position.set(x,0,z);model.body.rotation.y=view.kind==='siege'?(guard?0:Math.PI):side===1?Math.PI/2:-Math.PI/2;scene.add(model.root);units.push({model,group:g.key,baseX:x,baseZ:z,index:i});
   }
  }
  const ringGeometry=new RingGeometry(.8,.87,40),ringMaterial=new MeshStandardMaterial({color:'#ead08a',emissive:'#ab872f',emissiveIntensity:.8,transparent:true,opacity:.75,depthWrite:false}),selection=new Mesh(ringGeometry,ringMaterial);resources.push(ringGeometry,ringMaterial);selection.rotation.x=-Math.PI/2;selection.position.y=.025;scene.add(selection);
  let scenery:Awaited<ReturnType<typeof loadCampaignSampleAssets>>|undefined;void loadCampaignSampleAssets(abort.signal).then(loaded=>{if(disposed){loaded.dispose();return;}scenery=loaded;trees.clear();const material=new MeshStandardMaterial({vertexColors:true,roughness:1});resources.push(material);for(let i=0;i<40;i++){const mesh=new Mesh(loaded.closeTrees[i%3],material);mesh.position.set(Math.sin(i*18.13)*35,0,-14-Math.abs(Math.cos(i*5.81))*26);mesh.scale.setScalar(1.6+(i%4)*.2);mesh.castShadow=true;trees.add(mesh);}const site=siteById[latest.current.view.site??''];if(site){const controller=latest.current.view.controller??world.realm?.cities[site.id]?.controller;const city=loaded.city({...campaignCityAppearance(world,site),fort:latest.current.view.fort},'close',controller&&controller!=='frontier'?armyHeraldry(controller,regimeName(world,controller),world):undefined,()=>{dirty=true;});city.position.set(-2,0,view.kind==='siege'?-26:-18);city.scale.setScalar(view.kind==='siege'?1.8:1.3);city.traverse(o=>{if(o instanceof Mesh){o.castShadow=true;o.receiveShadow=true;}});scene.add(city);}dirty=true;}).catch(()=>{if(!disposed&&!abort.signal.aborted)setError('城景资源未能载入，保留军阵与城防示意。');});
  const dustCanvas=document.createElement('canvas');dustCanvas.width=dustCanvas.height=64;const dustContext=dustCanvas.getContext('2d')!,gradient=dustContext.createRadialGradient(32,32,0,32,32,32);gradient.addColorStop(0,'rgba(175,167,149,.3)');gradient.addColorStop(.45,'rgba(175,167,149,.15)');gradient.addColorStop(1,'rgba(175,167,149,0)');dustContext.fillStyle=gradient;dustContext.fillRect(0,0,64,64);const dustTexture=new CanvasTexture(dustCanvas),dustGeometry=new PlaneGeometry(1,1),dustMaterial=new MeshBasicMaterial({map:dustTexture,transparent:true,opacity:.45,depthWrite:false}),dust=new Group(),arrows=new Group();resources.push(dustTexture,dustGeometry,dustMaterial);scene.add(dust,arrows);for(let i=0;i<18;i++)dust.add(new Mesh(dustGeometry,dustMaterial));const arrowGeometry=new BoxGeometry(.018,.018,.7),arrowMaterial=new MeshStandardMaterial({color:'#362e25',roughness:1});resources.push(arrowGeometry,arrowMaterial);for(let i=0;i<8;i++)arrows.add(new Mesh(arrowGeometry,arrowMaterial));
  const ray=new Raycaster(),pointer=new Vector2();let down:{x:number;y:number}|undefined;const onDown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY};};const onClick=(e:PointerEvent)=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(units.map(u=>u.model.root),true)[0];if(hit){let o=hit.object;while(o.parent&&!o.userData.formation)o=o.parent;if(o.userData.formation)latest.current.onSelect(o.userData.formation);}};renderer.domElement.addEventListener('pointerdown',onDown);renderer.domElement.addEventListener('pointerup',onClick);controls.addEventListener('change',()=>{dirty=true;});
  const resize=()=>{const width=Math.max(1,node.clientWidth),height=Math.max(1,node.clientHeight);renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();dirty=true;};const observer=new ResizeObserver(resize);observer.observe(node);resize();
  const render=(now:number)=>{if(disposed)return;frame=requestAnimationFrame(render);if(document.hidden){lastFrame=now;return;}const current=latest.current,nextKey=JSON.stringify([current.selected,current.motion,current.view]);if(nextKey!==renderKey){renderKey=nextKey;dirty=true;}if(event!==current.view.eventId){event=current.view.eventId;start=now;elapsed=0;dirty=true;}const moving=current.motion&&(!matchMedia('(prefers-reduced-motion: reduce)').matches)&&(current.view.active||current.view.departing&&elapsed<6||current.view.assault&&elapsed<6);if(!dirty&&!moving)return;if(moving&&now-lastFrame<1000/30)return;lastFrame=now;elapsed=(now-start)/1000;
   for(const u of units){const g=current.view.groups.find(g=>g.key===u.group);if(!g)continue;u.model.root.visible=u.index<formationRepresentatives(g);if(!u.model.root.visible)continue;const action=formationAction(current.view,g,elapsed);const assaultOffset=current.view.assault?-3.5*(elapsed<2?elapsed/2:current.view.gateOpen||elapsed<3.5?1:Math.max(0,1-(elapsed-3.5)/2.5)):0;const withdrawal=action==='retreat'?(g.side==='attack'?1:-1)*(current.view.departing?Math.min(4,elapsed*.8):4):0;u.model.root.position.x=u.baseX+(current.view.kind==='battle'?-withdrawal:0);u.model.root.position.z=u.baseZ+(current.view.kind==='siege'?(current.view.assault?assaultOffset:withdrawal):0);u.model.body.rotation.y=current.view.kind==='siege'?(g.side!==current.view.besiegingSide?0:action==='retreat'?0:Math.PI):g.side==='attack'?(action==='retreat'?-Math.PI/2:Math.PI/2):(action==='retreat'?Math.PI/2:-Math.PI/2);animateMilitaryModel(u.model,action,now/1000,moving);u.model.banner.scale.setScalar(current.selected===g.key?1.6:1.35);}
   dust.visible=moving&&(current.view.assault||current.view.active);dust.children.forEach((o,i)=>{const phase=(elapsed*.8+i*.27)%2;o.position.set(Math.sin(i*4.13)*4,.15+phase*.3,Math.cos(i*3.17)*3+(current.view.kind==='siege'?-4:0));o.scale.setScalar(1+phase*1.4);o.quaternion.copy(camera.quaternion);});arrows.visible=moving&&current.view.kind==='battle'&&current.view.groups.some(g=>g.kind==='archer');arrows.children.forEach((o,i)=>{const ranged=current.view.groups.filter(g=>g.kind==='archer'),sign=ranged[i%Math.max(1,ranged.length)]?.side==='defend'?-1:1,t=(elapsed*.5+i*.13)%1;o.position.set(sign*(-5+t*10),1.7+Math.sin(t*Math.PI)*3.5,-2+i*.6);o.rotation.set(0,Math.PI/2,-sign*Math.atan2(Math.cos(t*Math.PI)*3.5,10));});
   const chosen=units.find(u=>u.group===current.selected);selection.visible=!!chosen;if(chosen)selection.position.set(chosen.model.root.position.x,.025,chosen.model.root.position.z);
   breaches.forEach((wall,i)=>{wall.scale.y=i<current.view.breach?.35:1;wall.position.y=0;rubble[i].visible=i<current.view.breach;});gate.rotation.y=current.view.gateOpen?Math.PI/2:0;try{renderer.render(scene,camera);node.dataset.drawCalls=String(renderer.info.render.calls);node.dataset.triangles=String(renderer.info.render.triangles);}catch{setError('战场渲染中止；请继续查看军阵数据与战报。');cancelAnimationFrame(frame);return;}dirty=false;};frame=requestAnimationFrame(render);
  void assets.ready.then(()=>{if(!disposed){start=performance.now();elapsed=0;dirty=true;}});node.dataset.combatScene='active';document.documentElement.dataset.combatScene='open';return()=>{disposed=true;abort.abort();cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener('pointerdown',onDown);renderer.domElement.removeEventListener('pointerup',onClick);controls.dispose();assets.dispose();scenery?.dispose();resources.forEach(r=>r.dispose());renderer.dispose();renderer.domElement.remove();delete document.documentElement.dataset.combatScene;};
 },[view.kind,view.controller,view.fort,composition,world.scriptId]);
 return <div className="combat-viewport" ref={host}>{error&&<p className="combat-render-error" role="status">{error}</p>}<span className="combat-camera-hint">拖动旋转 · 滚轮缩放 · 点击军阵查看</span></div>;
}
