import {TroopIllustration} from './RegimentCards';
import {useContext,useState} from 'react';
import type {World} from '../core/types';
import type {RealmId} from '../core/realm';
import {activeWars} from '../core/wars';
import {battleSceneView,siegeSceneView,snapshotVisible,combatPhaseNames,type FormationGroup} from '../core/combatPresentation';
import {battleKey,type EngagementRef} from './warPresentation';
import {siteById} from '../data/scenario';
import {politicalName,regimeName} from '../core/government';
import {ActionDialog} from './ActionDialog';
import {RealmBadge,RealmNavigation} from './RealmBadge';
import {CharacterPortrait} from './CharacterPortrait';
import {DetailTabs} from './DetailTabs';
import {CombatScene} from './CombatScene';
import {BattleResult} from './BattleResult';
import {ArtIcon} from './ArtIcon';
import './combatDetails.css';
export function CombatDetails({world:w,selected,onClose,onWar,onRealm,onPerson}:{world:World;selected:EngagementRef;onClose:()=>void;onWar?:(id:number)=>void;onRealm?:(id:RealmId)=>void;onPerson?:(id:string)=>void}){
 const navigation=useContext(RealmNavigation),[tab,setTab]=useState<'formation'|'units'|'records'>('formation'),[groupKey,setGroupKey]=useState(''),[motion,setMotion]=useState(!matchMedia('(prefers-reduced-motion: reduce)').matches),[replay,setReplay]=useState<number|null>(selected.kind==='siege'?selected.event??null:null);
 const battle=selected.kind==='battle'?w.militaryAftermath?.battles.find(b=>battleKey(b)===selected.key):undefined,siege=selected.kind==='siege'?w.realm?.sieges?.find(s=>s.war===selected.war&&s.site===selected.site&&s.side===selected.side):undefined;
 const events=selected.kind==='siege'?(w.militaryAftermath?.siegeEvents??[]).filter(e=>e.after.war===selected.war&&e.after.site===selected.site&&e.after.side===selected.side):[],event=replay?events.find(e=>e.id===replay):events.filter(e=>!siege||e.day===w.day).at(-1),view=battle?battleSceneView(w,battle):siegeSceneView(w,replay?undefined:siege,event),site=battle?.site??siege?.site??(selected.kind==='siege'?selected.site:undefined),warId=battle?.war??(selected.kind==='siege'?selected.war:undefined),war=activeWars(w).find(v=>v.id===warId),rows=battle?.rounds?.at(-1)?.after??event?.after.armies??[],chosen=view.groups.find(g=>g.key===groupKey)??view.groups[0];
 const openRealm=onRealm||navigation?((id:RealmId)=>{onClose();if(onRealm)onRealm(id);else navigation?.open(id);}):undefined;
 const title=(siteById[site??'']?.name??'道路')+(selected.kind==='battle'?'之战':'之围'),sideTitle=(side:'attack'|'defend')=>siege||event?(side===(siege?.side??event?.after.side)?'围城军':view.groups.some(g=>g.side===side)?'驻守军阵':'城防抵抗'):side==='attack'?'进攻方':'防御方';
 const summary=(side:'attack'|'defend')=>{const groups=view.groups.filter(g=>g.side===side),known=groups.length>0&&groups.every(g=>g.troops!==null),leader=rows.find(r=>r.side===side&&r.commander)?.commander??battle?.participants?.find(p=>p.side===side&&p.commander)?.commander,realm=rows.find(r=>r.side===side)?.realm??(war?(side==='attack'?war.attacker:war.defender):undefined),morale=groups.filter(g=>g.morale!==null).map(g=>g.morale!),loss=battle?(side==='attack'?battle.lossA:battle.lossB):undefined;return <aside className={'combat-side '+side} key={side} aria-label={sideTitle(side)}><header>{realm&&<RealmBadge realm={realm} world={w} onOpen={openRealm}/>}<b>{sideTitle(side)}</b></header>{leader&&<><button className="combat-commander" disabled={!onPerson} onClick={()=>{onClose();onPerson?.(leader);}} aria-label={'查看'+politicalName(leader,w)}><CharacterPortrait world={w} characterId={leader}/></button><strong>{politicalName(leader,w)}</strong></>}{!leader&&<small className="combat-no-leader">未记录统帅</small>}<p className="combat-strength">{groups.length?'参战兵力':'城防等级'}<b>{groups.length?(known?groups.reduce((n,g)=>n+g.troops!,0).toLocaleString()+' 人':'未详'):view.kind==='siege'?view.fort+' 级':'未记录'}</b></p>{groups.map(g=><button className="combat-kind" key={g.key} aria-pressed={chosen?.key===g.key} onClick={()=>setGroupKey(g.key)}><ArtIcon name="army" size={18}/><span>{g.name}</span><b>{g.troops===null?'未详':g.troops.toLocaleString()}</b></button>)}{morale.length>0&&<div className="combat-morale"><span>{battle?'轮末士气最低值':'士气最低值'} <b>{Math.min(...morale)}</b></span><meter min={0} max={100} value={Math.min(...morale)} aria-label={sideTitle(side)+'士气最低值'}/></div>}{loss!==undefined&&<p className="combat-loss">累计损失 <b>{known?loss.toLocaleString()+' 人':'未详'}</b></p>}{view.kind==='siege'&&side!==(siege?.side??event?.after.side)&&<>{groups.length>0&&<p>城防等级 <b>{view.fort} 级</b></p>}<p>围城进展 <b>{siege?.progress??event?.after.progress??0}/100</b></p><progress max={100} value={siege?.progress??event?.after.progress??0}/><p>封锁程度 <b>{view.blockade}%</b></p><p>已形成缺口 <b>{view.breach} 处</b></p>{siege?.nextPhase!==undefined&&<p>下次军议 <b>{Math.max(0,siege.nextPhase-w.day)} 日后</b></p>}<small>没有独立守军兵员池；城防与实际驻军分别显示。</small></>}</aside>;};
 const groupDetail=(g:FormationGroup)=> <section className="combat-selected">{g.kind==='unknown'?<ArtIcon name="army" size={34}/>:<TroopIllustration kind={g.kind}/>}<div><h4>{g.name}</h4><p>兵力 {g.troops===null?'未详':g.troops.toLocaleString()+' 人'} · {g.withdrawn?'已退出交战':'当前军阵'}</p><small>{g.loss===null?'损失未详':'本轮损失 '+g.loss+' 人'}{g.experience!==null?' · 训练经验最高 '+g.experience:''}</small><small>所属：{g.armies.map(id=>'第 '+id+' 军').join('、')}</small></div></section>;
 return <ActionDialog className="war-details-dialog engagement-dialog combat-details-dialog" title={view.kind==='battle'?'战役详情':'围城详情'} scene="landscape" onClose={onClose} cancelLabel="返回" actions={war&&onWar?<button onClick={()=>onWar(war.id!)}>查看所属战争</button>:null}>
  {!battle&&!siege&&!event?<p role="status">此战役或围城记录已不在当前存档中。</p>:<>
   <div className="combat-heading"><div><h3>{title}</h3><p>{view.phase} · {battle?'第 '+battle.round+' 轮 · 持续 '+((battle.ended??w.day)-battle.day+1)+' 日':siege?.started!==undefined?'已围城 '+(w.day-siege.started)+' 日':event?'结算第 '+event.day+' 日':'围城日数未记录'}</p></div><button className="combat-motion" aria-pressed={motion} onClick={()=>setMotion(v=>!v)}>{motion?'减少动态':'播放动态'}</button></div>
   <DetailTabs label="交战详情" value={tab} onChange={setTab} items={[{id:'formation',label:'军阵',icon:'army'},{id:'units',label:'部队',icon:'person'},{id:'records',label:'战报',icon:'diligent'}]}/>
   {tab==='formation'&&<><div className="combat-tableau">{summary('attack')}<div className="combat-center"><CombatScene world={w} view={view} selected={chosen?.key??''} onSelect={setGroupKey} motion={motion}/><ol className="combat-stages">{(view.kind==='battle'?Object.values(combatPhaseNames):['扎营封锁','工事推进','破城强攻','议降撤围']).map(label=><li key={label} aria-current={view.phase===label?'step':undefined}>{label}</li>)}</ol></div>{summary('defend')}</div><div className="combat-bottom"><section className="combat-dispatch"><h4>军情战报</h4>{battle?.rounds?.slice(-3).reverse().map(r=>{const known=(side:'attack'|'defend')=>r.after.filter(a=>a.side===side).every(a=>snapshotVisible(w,a));return <p key={r.round}>第 {r.round} 轮 · {combatPhaseNames[r.stage]}<small>攻方损失 {known('attack')?r.lossA+' 人':'未详'} · 守方损失 {known('defend')?r.lossB+' 人':'未详'}</small></p>;})}{view.kind==='siege'&&<><p>{siege?.event??(event?.kind==='assaultWon'?'强攻成功，城池已交割':event?.kind==='assaultLost'?'强攻未克，部队退回围城阵地':event?.kind==='surrender'?'议降交城':'尚无阶段战报')}</p>{event&&<small>本次事件已结算；演出可随时关闭，不改变战果。</small>}</>}{!battle?.rounds?.length&&view.kind==='battle'&&<p>{view.note}</p>}</section>{chosen&&groupDetail(chosen)}</div><p className="combat-note">{view.note}</p></>}
   {tab==='units'&&<div className="combat-unit-ledger">{view.groups.map(g=><button key={g.key} aria-pressed={chosen?.key===g.key} onClick={()=>{setGroupKey(g.key);setTab('formation');}}>{groupDetail(g)}</button>)}{!view.groups.length&&<p>{view.note}</p>}{battle?.participants?.map((p,i)=><p key={p.army+':'+i}>第 {p.army} 军 · {regimeName(w,p.realm)} · 参战时统帅 {p.commander?politicalName(p.commander,w):'未记录'}</p>)}</div>}
   {tab==='records'&&<div className="combat-history">{battle?.ended!==undefined&&<BattleResult world={w} battle={battle}/>} {battle?.rounds?.slice().reverse().map(r=><article key={r.round}><h4>第 {r.round} 轮 · {combatPhaseNames[r.stage]}</h4>{(['attack','defend'] as const).map(side=><p key={side}>{side==='attack'?'攻方':'守方'}损失 {r.after.filter(a=>a.side===side).every(a=>snapshotVisible(w,a))?(side==='attack'?r.lossA:r.lossB)+' 人':'未详'}{r.after.some(a=>a.side===side&&a.withdrawn)?' · 有部队实际退出交战':''}</p>)}</article>)}{events.slice().reverse().map(e=><article key={e.id}><h4>结算第 {e.day} 日 · {{works:'工事推进',breach:'新增缺口',stalled:'围城停滞',hold:'守城待决',assaultWon:'强攻成功',assaultLost:'强攻未克',surrender:'议降交城',withdrawal:'撤围'}[e.kind]}</h4><p>围城进展 {e.before.progress} → {e.after.progress} · 缺口 {e.before.breach} → {e.after.breach}</p>{e.kind.startsWith('assault')&&<button onClick={()=>{setReplay(e.id);setTab('formation');}}>查看本次强攻回放</button>}</article>)}{!battle?.rounds?.length&&!events.length&&<p>该记录不含军阵过程；原有战报继续保留。</p>}{replay&&siege&&<button onClick={()=>{setReplay(null);setTab('formation');}}>返回当前围城</button>}</div>}
  </>}
 </ActionDialog>;
}
