import {armyHeraldry} from '../map/ArmyHeraldry';
import {loadCampaignSampleAssets} from '../map/CampaignSampleAssets';
import {campaignCityAppearance} from '../map/campaignScenery';
import {siteById} from '../data/scenario';
import {landscapeMaterial} from '../map/three/landscapeMaterial';
import {useEffect,useRef,useState} from 'react';
import {ACESFilmicToneMapping,AmbientLight,BoxGeometry,Color,ConeGeometry,DirectionalLight,Float32BufferAttribute,Fog,Group,Mesh,MeshStandardMaterial,PCFSoftShadowMap,PerspectiveCamera,PlaneGeometry,RingGeometry,SphereGeometry,Raycaster,Scene,Vector2,WebGLRenderer} from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {militaryModelAssets,animateMilitaryModel,type MilitaryModel,type ArmyModelKind} from '../map/MilitaryModels';
import type {World} from '../core/types';
import {regimeName} from '../core/government';
import {formationAction,formationRepresentatives,type CombatSceneView,type FormationGroup} from '../core/combatPresentation';
import type {Army} from '../core/realm';
const modelKind=(kind:FormationGroup['kind']):ArmyModelKind=>kind==='shield'||kind==='unknown'?'foot':kind;
/** One bounded viewport; owns and disposes every temporary model and GPU resource. */
export function CombatScene({world,view,selected,onSelect,motion}:{world:World;view:CombatSceneView;selected:string;onSelect:(key:string)=>void;motion:boolean}){
 const host=useRef<HTMLDivElement>(null),latest=useRef({view,selected,onSelect,motion});latest.current={view,selected,onSelect,motion};const [error,setError]=useState('');
 const composition=view.groups.map(g=>g.key+':'+(g.troops===0?'empty':'present')).join('|');
 useEffect(()=>{const node=host.current;if(!node)return;let renderer:WebGLRenderer;try{renderer=new WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{setError('战场画面无法载入；军阵数据与战报仍可查看。');return;}
  setError('');const abort=new AbortController(),scene=new Scene(),camera=new PerspectiveCamera(39,1,.1,160);scene.background=new Color('#a1aaa1');scene.fog=new Fog('#a1aaa1',35,90);renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.outputColorSpace='srgb';renderer.toneMapping=ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;renderer.shadowMap.enabled=true;renderer.shadowMap.type=PCFSoftShadowMap;node.append(renderer.domElement);renderer.domElement.setAttribute('aria-label',view.kind==='siege'?'围城三维沙盘，可旋转缩放并选择兵团':'战役三维沙盘，可旋转缩放并选择兵团');renderer.domElement.tabIndex=0;
  camera.position.set(view.kind==='siege'?16:10,view.kind==='siege'?10:10,view.kind==='siege'?20:17);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1,0);controls.minDistance=12;controls.maxDistance=42;controls.minPolarAngle=.4;controls.maxPolarAngle=1.25;controls.enablePan=false;controls.enableDamping=false;controls.update();
  const sun=new DirectionalLight('#ffe2b1',3.1);sun.position.set(-14,25,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=sun.shadow.camera.bottom=-22;sun.shadow.camera.right=sun.shadow.camera.top=22;sun.shadow.bias=-.0003;scene.add(sun,new AmbientLight('#afc5c0',1.6));
  const resources:{dispose:()=>void}[]=[],earth=landscapeMaterial('Combat earth'),stone=new MeshStandardMaterial({color:'#989785',roughness:.96}),roof=new MeshStandardMaterial({color:'#36453e',roughness:.9}),wood=new MeshStandardMaterial({color:'#544332',roughness:1});earth.vertexColors=false;earth.transparent=false;earth.depthWrite=true;earth.color.set('#6f7660');resources.push(earth,stone,roof,wood);
  function box(parent:Group|Scene,w:number,h:number,d:number,x:number,y:number,z:number,material=stone){const geometry=new BoxGeometry(w,h,d);resources.push(geometry);const mesh=new Mesh(geometry,material);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
  const groundGeometry=new PlaneGeometry(100,100,30,30);resources.push(groundGeometry);const p=groundGeometry.getAttribute('position');for(let i=0;i<p.count;i++)p.setZ(i,Math.sin(p.getX(i)*.21)*Math.cos(p.getY(i)*.19)*.16);const colors=[];for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getY(i),noise=.88+Math.sin(x*2.7+z*1.2)*.045+Math.cos(z*3.2-x)*.03;colors.push(noise,noise,noise*.94);}groundGeometry.setAttribute('color',new Float32BufferAttribute(colors,3));earth.vertexColors=true;groundGeometry.computeVertexNormals();const ground=new Mesh(groundGeometry,earth);ground.rotation.x=-Math.PI/2;ground.position.y=-.13;ground.receiveShadow=true;scene.add(ground);
  // A schematic local battlefield, separate from the authoritative campaign terrain.
  const trees=new Group();scene.add(trees);const trunkGeometry=new BoxGeometry(.2,1.3,.2),leafGeometry=new ConeGeometry(.95,3.2,7),leaf=new MeshStandardMaterial({color:'#344837',roughness:1});resources.push(trunkGeometry,leafGeometry,leaf);for(let i=0;i<45;i++){const x=Math.sin(i*18.13)*35,z=-13-Math.abs(Math.cos(i*5.81))*25;if(Math.abs(x)<10&&z>-20)continue;const trunk=new Mesh(trunkGeometry,wood),crown=new Mesh(leafGeometry,leaf);trunk.position.set(x,.65,z);crown.position.set(x,2.5,z);trees.add(trunk,crown);}
  const walls=new Group(),gate=new Group(),breaches:Group[]=[];scene.add(walls);walls.add(gate);if(view.kind==='siege'){walls.scale.y=.8+view.fort*.2;for(let i=0;i<12;i++){const x=(i-5.5)*2.1;if(Math.abs(x)<2.2)continue;const section=new Group();section.position.set(x,0,-5);walls.add(section);box(section,2.08,3.8,.9,0,1.9,0);if(i===3||i===8||i===9)breaches.push(section);for(let j=0;j<3;j++)box(section,.34,.48,1.05,-.7+j*.7,4.04,0);for(let row=0;row<5;row++)box(section,2.1,.025,.96,0,.4+row*.65,0,wood);}box(gate,3.3,3.4,.65,0,1.7,-5,wood);for(const x of [-2.1,2.1]){box(walls,1.2,4.6,2.2,x,2.3,-5);box(walls,1.8,.3,2.7,x,4.75,-5,roof);}box(walls,4.8,.5,2.8,0,4.3,-5);box(walls,5.4,.35,3.4,0,4.75,-5,roof);const roofGeometry=new ConeGeometry(3.7,1.8,4);resources.push(roofGeometry);const gateRoof=new Mesh(roofGeometry,roof);gateRoof.rotation.y=Math.PI/4;gateRoof.scale.z=.65;gateRoof.position.set(0,5.45,-5);walls.add(gateRoof);for(let i=0;i<9;i++){const x=(i%3-1)*5,z=-11-Math.floor(i/3)*4;box(walls,3,1.4,2.4,x,.7,z,wood);const geo=new ConeGeometry(2.5,1.2,4);resources.push(geo);const top=new Mesh(geo,roof);top.rotation.y=Math.PI/4;top.position.set(x,2,z);top.scale.z=.8;walls.add(top);}}
  let dirty=true,renderKey='',disposed=false,frame=0,lastFrame=0,elapsed=0,start=performance.now(),event=latest.current.view.eventId;const assets=militaryModelAssets(()=>{dirty=true;},message=>{if(!disposed)setError(message);},abort.signal),units:{model:MilitaryModel;group:string;baseX:number;baseZ:number;index:number}[]=[];
  for(const g of latest.current.view.groups){if(g.troops===0)continue;const count=g.kind==='siege'?1:g.kind==='lightHorse'||g.kind==='heavyHorse'?4:6,side=g.side==='attack'?1:-1,cavalry=g.kind==='lightHorse'||g.kind==='heavyHorse',lane=g.kind==='shield'?0:g.kind==='spear'?1:g.kind==='archer'?2:g.kind==='siege'?3:g.kind==='lightHorse'?-2:2;
   for(let i=0;i<count;i++){const a:Pick<Army,'id'|'realm'>={id:units.length+1,realm:g.realm};
    // Unknown formations always use the same generic silhouette and fixed count.
    const model=assets.create(a,modelKind(g.kind),g.kind==='unknown'?'？':regimeName(world,a.realm),world,g.kind==='unknown');model.root.matrixAutoUpdate=true;model.root.scale.setScalar(g.kind==='siege'?1:1.25);model.root.userData.formation=g.key;model.banner.visible=i===0;model.camp.visible=view.kind==='siege'&&i===0;
    const guard=view.kind==='siege'&&g.side!==view.besiegingSide;const x=view.kind==='siege'?guard?(i%3-1)*1.5:(lane-1)*3.6+(i%2)*1.25:cavalry?(g.kind==='lightHorse'?-8:8)+(i%2)*1.2:(i%2-.5)*1.3+(g.kind==='spear'?3.2:0),z=view.kind==='siege'?guard?-7-Math.floor(i/3)*1.2:4+Math.floor(i/2)*1.4+(g.kind==='archer'?3:0)+(g.kind==='siege'?4:0):side*(1.7+Math.floor(i/2)*1.6+(g.kind==='archer'?5:g.kind==='siege'?7:0));model.root.position.set(x,0,z);model.body.rotation.y=view.kind==='siege'?(guard?0:Math.PI):side===1?Math.PI:0;scene.add(model.root);units.push({model,group:g.key,baseX:x,baseZ:z,index:i});
   }
  }
  const ringGeometry=new RingGeometry(1.4,1.5,40),ringMaterial=new MeshStandardMaterial({color:'#ead08a',emissive:'#ab872f',emissiveIntensity:.8,transparent:true,opacity:.75,depthWrite:false}),selection=new Mesh(ringGeometry,ringMaterial);resources.push(ringGeometry,ringMaterial);selection.rotation.x=-Math.PI/2;selection.position.y=.025;scene.add(selection);
  let scenery:Awaited<ReturnType<typeof loadCampaignSampleAssets>>|undefined;void loadCampaignSampleAssets(abort.signal).then(loaded=>{if(disposed){loaded.dispose();return;}scenery=loaded;trees.clear();const material=new MeshStandardMaterial({vertexColors:true,roughness:1});resources.push(material);for(let i=0;i<40;i++){const mesh=new Mesh(loaded.closeTrees[i%3],material);mesh.position.set(Math.sin(i*18.13)*35,0,-14-Math.abs(Math.cos(i*5.81))*26);mesh.scale.setScalar(1.6+(i%4)*.2);mesh.castShadow=true;trees.add(mesh);}const site=siteById[latest.current.view.site??''];if(site){const controller=latest.current.view.controller??world.realm?.cities[site.id]?.controller;const city=loaded.city({...campaignCityAppearance(world,site),fort:latest.current.view.fort},'close',controller&&controller!=='frontier'?armyHeraldry(controller,regimeName(world,controller),world):undefined,()=>{dirty=true;});city.position.set(0,0,view.kind==='siege'?-17:-23);city.scale.setScalar(view.kind==='siege'?1.5:.9);city.traverse(o=>{if(o instanceof Mesh){o.castShadow=true;o.receiveShadow=true;}});scene.add(city);}dirty=true;}).catch(()=>{if(!disposed&&!abort.signal.aborted)setError('城景资源未能载入，保留军阵与城防示意。');});
  const dustGeometry=new SphereGeometry(.14,6,4),dustMaterial=new MeshStandardMaterial({color:'#b9b197',transparent:true,opacity:.38,depthWrite:false}),dust=new Group(),arrows=new Group();resources.push(dustGeometry,dustMaterial);scene.add(dust,arrows);for(let i=0;i<18;i++){const particle=new Mesh(dustGeometry,dustMaterial);dust.add(particle);}const arrowGeometry=new BoxGeometry(.018,.018,.7),arrowMaterial=new MeshStandardMaterial({color:'#362e25',roughness:1});resources.push(arrowGeometry,arrowMaterial);for(let i=0;i<8;i++)arrows.add(new Mesh(arrowGeometry,arrowMaterial));
  const ray=new Raycaster(),pointer=new Vector2();let down:{x:number;y:number}|undefined;const onDown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY};};const onClick=(e:PointerEvent)=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(units.map(u=>u.model.root),true)[0];if(hit){let o=hit.object;while(o.parent&&!o.userData.formation)o=o.parent;if(o.userData.formation)latest.current.onSelect(o.userData.formation);}};renderer.domElement.addEventListener('pointerdown',onDown);renderer.domElement.addEventListener('pointerup',onClick);controls.addEventListener('change',()=>{dirty=true;});
  const resize=()=>{const width=Math.max(1,node.clientWidth),height=Math.max(1,node.clientHeight);renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();dirty=true;};const observer=new ResizeObserver(resize);observer.observe(node);resize();
  const render=(now:number)=>{if(disposed)return;frame=requestAnimationFrame(render);if(document.hidden){lastFrame=now;return;}const current=latest.current,nextKey=JSON.stringify([current.selected,current.motion,current.view]);if(nextKey!==renderKey){renderKey=nextKey;dirty=true;}if(event!==current.view.eventId){event=current.view.eventId;start=now;elapsed=0;dirty=true;}const moving=current.motion&&(!matchMedia('(prefers-reduced-motion: reduce)').matches)&&(current.view.active||current.view.assault&&elapsed<6);if(!dirty&&!moving)return;if(moving&&now-lastFrame<1000/30)return;lastFrame=now;elapsed=(now-start)/1000;
   for(const u of units){const g=current.view.groups.find(g=>g.key===u.group);if(!g)continue;u.model.root.visible=u.index<formationRepresentatives(g);if(!u.model.root.visible)continue;const action=formationAction(current.view,g,elapsed);const assaultOffset=current.view.assault?-3.5*(elapsed<2?elapsed/2:current.view.gateOpen||elapsed<3.5?1:Math.max(0,1-(elapsed-3.5)/2.5)):0;u.model.root.position.z=u.baseZ+(current.view.assault?assaultOffset:action==='retreat'&&moving?(g.side==='attack'?1:-1)*Math.min(4,elapsed*.6):0);u.model.body.rotation.y=current.view.kind==='siege'?(g.side!==current.view.besiegingSide?0:action==='retreat'?0:Math.PI):g.side==='attack'?(action==='retreat'?0:Math.PI):(action==='retreat'?Math.PI:0);animateMilitaryModel(u.model,action,now/1000,moving);u.model.banner.scale.setScalar(current.selected===g.key?1.22:1);}
   dust.visible=moving&&(current.view.assault||current.view.active);dust.children.forEach((o,i)=>{const phase=(elapsed*.8+i*.27)%2;o.position.set(Math.sin(i*4.13)*5,.08+phase*.22,Math.cos(i*3.17)*2+(current.view.kind==='siege'?-4:0));o.scale.setScalar(.3+phase);});arrows.visible=moving&&current.view.kind==='battle'&&current.view.groups.some(g=>g.kind==='archer');arrows.children.forEach((o,i)=>{const ranged=current.view.groups.filter(g=>g.kind==='archer'),sign=ranged[i%Math.max(1,ranged.length)]?.side==='defend'?-1:1,t=(elapsed*.5+i*.13)%1;o.position.set(-2+i*.6,1.7+Math.sin(t*Math.PI)*3.5,sign*(6-t*12));o.rotation.x=-Math.atan2(Math.cos(t*Math.PI)*3.5,12);});
   const chosen=units.find(u=>u.group===current.selected);selection.visible=!!chosen;if(chosen)selection.position.set(chosen.baseX+.7,.025,chosen.model.root.position.z+.7);
   breaches.forEach((wall,i)=>{wall.scale.y=i<current.view.breach?.35:1;wall.position.y=0;});gate.rotation.y=current.view.gateOpen?Math.PI/2:0;try{renderer.render(scene,camera);node.dataset.drawCalls=String(renderer.info.render.calls);node.dataset.triangles=String(renderer.info.render.triangles);}catch{setError('战场渲染中止；请继续查看军阵数据与战报。');cancelAnimationFrame(frame);return;}dirty=false;};frame=requestAnimationFrame(render);
  void assets.ready.then(()=>{if(!disposed){start=performance.now();elapsed=0;dirty=true;}});node.dataset.combatScene='active';document.documentElement.dataset.combatScene='open';return()=>{disposed=true;abort.abort();cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener('pointerdown',onDown);renderer.domElement.removeEventListener('pointerup',onClick);controls.dispose();assets.dispose();scenery?.dispose();resources.forEach(r=>r.dispose());renderer.dispose();renderer.domElement.remove();delete document.documentElement.dataset.combatScene;};
 },[view.kind,view.controller,view.fort,composition,world.scriptId]);
 return <div className="combat-viewport" ref={host}>{error&&<p className="combat-render-error" role="status">{error}</p>}<span className="combat-camera-hint">拖动旋转 · 滚轮缩放 · 点击军阵查看</span></div>;
}
