import {useState} from 'react';
import type {World,GameCommand} from '../core/types';
import {commerceReason,tradeStock,tradePrice,type CommerceCommand} from '../core/commerce';
import {siteById,sites} from '../data/scenario';
import {ArtIcon} from './ArtIcon';
import {HoverHint} from './HoverHint';
export function CommercePanel({world:w,enterprise,pending,send}:{world:World;enterprise:number;pending:boolean;send:(c:GameCommand)=>void}){const [to,setTo]=useState(''),[guard,setGuard]=useState(true),[confirm,setConfirm]=useState<CommerceCommand|null>(null),stock=tradeStock(w,enterprise),target=siteById[to]?to:sites[0].id;
 const action=(c:CommerceCommand,label:string,detail:string)=>{const reason=commerceReason(w,c);return <HoverHint key={c.action+label} label={label} content={<>{detail}{reason&&<p>{reason}</p>}</>}><button disabled={pending||!!reason} onClick={()=>setConfirm(c)}><ArtIcon name={c.action==='produce'?'city':c.action==='deliver'?'world':'grain'} size={24}/>{label}</button></HoverHint>;};
 return <section><h4><ArtIcon name="world" size={24}/>货栈与商旅</h4><div className="city-civic-metrics"><span>粮货 {stock?.grain??0}</span><span>农具 {stock?.tools??0}</span>{stock?.production&&<span>制具 {stock.production.work}/20 日</span>}</div><div className="city-policy-grid">{action({type:'commerce',action:'buy',enterprise},'购粮 50','资本 50 钱向本地公库购买 50 余粮，保留当地两期民食。')}{action({type:'commerce',action:'produce',enterprise},'制作农具','资本 20 钱支付材料与工匠，亲驻作坊生产 20 日，获得 10 农具。')}</div><div className="career-parameters"><label>交货城市<select value={target} onChange={e=>setTo(e.target.value)}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><input type="checkbox" checked={guard} onChange={e=>setGuard(e.target.checked)}/>雇用护运</label></div><p>运费 {guard?20:5} 钱 · 每段损耗 {guard?'1%':'6%'}；逐段取整，不足 1 单位不损耗。</p><div className="city-policy-grid">{(['grain','tools'] as const).map(goods=>action({type:'commerce',action:'deliver',enterprise,to:target,goods,guard},goods==='grain'?'运售粮货':'运售农具',`发运 ${goods==='grain'?50:10} 件，锁定单价 ${tradePrice(w,target,goods)} 钱；买方真实预付，按抵达实收数量结算。道路中断停运，超期或失守撤约。`))}</div>{w.commerce?.contracts.filter(t=>t.enterprise===enterprise&&(t.status==='moving'||t.escrow)).map(t=><article key={t.id}>{siteById[t.location].name} → {siteById[t.to].name}<p>在途 {t.remaining} · 已交 {t.arrived} · 损失 {t.lost} · 未结款 {t.escrow} · 截止余 {Math.max(0,t.deadline-w.day)} 日</p>{action({type:'commerce',action:'cancel',id:t.id},'撤销商约','预付未交货款退回买方；运费不退，在途粮货留给当地，农具弃置。')}</article>)}{confirm&&<div className="diplomacy-decision"><p>{confirm.action==='produce'?'支付资本 20 钱，驻留生产二十日。':confirm.action==='buy'?'支付资本 50 钱购入 50 余粮。':confirm.action==='cancel'?'放弃在途货物并退还未履约价款；运费不退。':`支付运费 ${guard?20:5} 钱，买方按实收货物结算，途中可能延误或损失。`}</p><button disabled={pending||!!commerceReason(w,confirm)} onClick={()=>{send(confirm);setConfirm(null);}}>确认</button><button onClick={()=>setConfirm(null)}>取消</button></div>}</section>;
}
