import {ConfirmAction} from './ConfirmAction';
import {useState} from 'react';
import type {World,GameCommand} from '../core/types';
import {commerceReason,tradeStock,tradePrice,type CommerceCommand} from '../core/commerce';
import {siteById,sites} from '../data/scenario';
import {ArtIcon} from './ArtIcon';
import {HoverHint} from './HoverHint';

export function CommercePanel({world:w,enterprise,pending,send}:{world:World;enterprise:number;pending:boolean;send:(c:GameCommand)=>void}){
 const [to,setTo]=useState(''),[guard,setGuard]=useState(true),[confirm,setConfirm]=useState<CommerceCommand|null>(null);
 const home=w.enterprises?.items.find(e=>e.id===enterprise)?.site,stock=tradeStock(w,enterprise),target=siteById[to]?to:sites.find(s=>s.id!==home)?.id??sites[0].id;
 const action=(c:CommerceCommand,label:string,detail:string,preview?:string)=>{const reason=commerceReason(w,c);return <HoverHint key={c.action+label} label={label} content={<>{detail}{reason&&<p>{reason}</p>}</>}><span className="enterprise-action"><button disabled={pending||!!reason} onClick={()=>setConfirm(c)}><ArtIcon name={c.action==='produce'?'city':c.action==='deliver'?'world':'grain'} size={24}/>{label}</button>{preview&&<small className="enterprise-action-preview">{preview}</small>}{reason&&<small className="enterprise-action-reason">{reason}</small>}</span></HoverHint>;};
 const confirmDetail=()=>{if(!confirm)return '';if(confirm.action==='produce')return '支付事业资本 20 钱，驻留生产 20 日，获得 10 农具。';if(confirm.action==='buy')return '支付事业资本 50 钱，购入本地 50 余粮。';if(confirm.action==='cancel')return '撤销该商约：未交货款退回买方，已付运费不退；在途粮货留给当地，农具弃置。';if(confirm.action!=='deliver')return '';const units=confirm.goods==='grain'?50:10,price=tradePrice(w,confirm.to,confirm.goods),fee=confirm.guard?20:5;return `从本地向${siteById[confirm.to].name}发运 ${units} ${confirm.goods==='grain'?'粮货':'农具'}；事业资本支付运费 ${fee} 钱。买方公库预付 ${units*price} 钱，实收后按 ${price} 钱/件结算，途中可能延误或损失。`;};
 return <section className="enterprise-commerce"><header><h4><ArtIcon name="world" size={24}/>货栈与商旅</h4><p>先备货，再选目的地发运。运费由事业资本支付；买方公库的预付款在到货后按实收结算，收入回到事业资本。</p></header><div className="city-civic-metrics"><span>现有库存</span><span>粮货 {stock?.grain??0}</span><span>农具 {stock?.tools??0}</span>{stock?.production&&<span>制具 {stock.production.work}/20 日</span>}</div><h5>一 · 备货</h5><div className="city-policy-grid">{action({type:'commerce',action:'buy',enterprise},'购粮 50','事业资本支付 50 钱；本地公库收款，购入 50 余粮，并保留当地两期民食。','付资本 50 钱 · 入库 50 粮')}{action({type:'commerce',action:'produce',enterprise},'制作农具','事业资本支付 20 钱给材料与工匠，亲驻作坊生产 20 日，获得 10 农具。','付资本 20 钱 · 20 日后入库 10 件')}</div><h5>二 · 选交货地与护运</h5><div className="career-parameters"><label>交货城市<select value={target} onChange={e=>{setTo(e.target.value);setConfirm(null);}}>{sites.filter(s=>s.id!==home).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><input type="checkbox" checked={guard} onChange={e=>{setGuard(e.target.checked);setConfirm(null);}}/>雇用护运</label></div><p>运费 {guard?20:5} 事业资本 · 每段损耗 {guard?'1%':'6%'}；逐段取整，不足 1 单位不损耗。</p><h5>三 · 发运现有货物</h5><div className="city-policy-grid">{(['grain','tools'] as const).map(goods=>{const units=goods==='grain'?50:10,price=tradePrice(w,target,goods);return action({type:'commerce',action:'deliver',enterprise,to:target,goods,guard},`运售${goods==='grain'?'粮货':'农具'} · ${units} 件`,`买方公库预付 ${units*price} 钱（${price} 钱/件）；抵达后按实际收货结算，损失或未收货部分退回买方。道路中断停运，超期或失守撤约。`,`预付 ${units*price} 钱 · 到货按实收结算`);})}</div>{w.commerce?.contracts.filter(t=>t.enterprise===enterprise&&(t.status==='moving'||t.escrow)).map(t=><article key={t.id}>{siteById[t.location].name} → {siteById[t.to].name}<p>在途 {t.remaining} · 已交 {t.arrived} · 损失 {t.lost} · 未结款 {t.escrow} · 截止余 {Math.max(0,t.deadline-w.day)} 日</p>{action({type:'commerce',action:'cancel',id:t.id},'撤销商约','预付未交货款退回买方；运费不退，在途粮货留给当地，农具弃置。')}</article>)}{confirm&&<ConfirmAction title='确认商旅操作' detail={confirmDetail()} confirmLabel='确认执行' pending={pending||!!commerceReason(w,confirm)} onCancel={()=>setConfirm(null)} onConfirm={()=>{if(pending||commerceReason(w,confirm))return;send(confirm);setConfirm(null);}}/>}</section>;
}
