import {useEffect,useState} from 'react';
import {ActionDialog} from './ActionDialog';
import {ArtIcon,Resource} from './ArtIcon';
import {ConfirmAction} from './ConfirmAction';
import {FiscalPetitionAudience} from './PetitionCases';
import {HoverHint} from './HoverHint';
import {canCommission} from '../core/serviceMandates';
import {countyTerritory,localHasJurisdiction,localTitle} from '../core/localAdministration';
import {accountName,publicFiscalEntries,fiscalPath,localBalance,grantFactors,grantPurposes,fiscalReason,type FiscalCommand,type GrantRequest} from '../core/treasury';
import {executive,playerRealm,cityYield} from '../core/realm';
import {politicalName} from '../core/government';
import {siteById} from '../data/scenario';
import type {GameCommand,World} from '../core/types';
import './courtTreasury.css';

export function CourtTreasuryPanel({world:w,pending,send,onPerson,initialTab='budget',compact=false}:{world:World;pending:boolean;send:(c:GameCommand)=>void;onPerson:(id:string)=>void;initialTab?:'budget'|'requests'|'ledger';compact?:boolean}){
 const [grantOpen,setGrantOpen]=useState(false),[site,setSite]=useState(''),[amount,setAmount]=useState(100),[purpose,setPurpose]=useState<GrantRequest['purpose']>('construction');
 const [ledgerOpen,setLedgerOpen]=useState(initialTab==='ledger'),[historyOpen,setHistoryOpen]=useState(false),[reliefSite,setReliefSite]=useState<string|null>(null);
 const [requestId,setRequestId]=useState<number|null>(null);
 const realm=playerRealm(w),chief=executive(w),fiscal=w.realm!.fiscal;
 const cities=Object.entries(w.realm!.cities).filter(([id,c])=>c.owner===realm&&c.controller===realm&&canCommission(w,w.characterId!,realm,id,'relief'));
 const requests=(fiscal?.requests??[]).filter(q=>q.realm===realm&&(chief||q.actor===w.characterId||q.approver===w.characterId));
 const waiting=requests.filter(q=>q.status==='pending').reverse(),history=requests.filter(q=>q.status!=='pending').reverse();
 const selectedRequest=waiting.find(q=>q.id===requestId&&q.approver===w.characterId);
 useEffect(()=>{if(requestId!==null&&!selectedRequest)setRequestId(null);},[requestId,selectedRequest]);
 const ledger=publicFiscalEntries(w,realm).slice().reverse();
 const target=cities.some(([id])=>id===site)?site:cities[0]?.[0]??'';
 const canAllocate=target&&(chief||localHasJurisdiction(w,w.characterId!,countyTerritory(target),realm));
 const grant: FiscalCommand=canAllocate?{type:'fiscal',action:'allocate',site:target,amount}:{type:'fiscal',action:'request',site:target,amount,purpose};
 const grantReason=target?fiscalReason(w,grant):'暂无可申请的城邑';
 const renderRequest=(q:typeof requests[number])=>!compact&&q.approver===w.characterId&&q.status==='pending'
  ?<FiscalPetitionAudience key={q.id} world={w} request={q} pending={pending} send={send} onPerson={onPerson}/>
  :<article className="court-fiscal-request" key={q.id}><div><strong>{q.territory?localTitle(q.territory):siteById[q.site].name} · {grantPurposes[q.purpose]}</strong><small><button className="court-fiscal-actor" onClick={()=>onPerson(q.actor)}>{politicalName(q.actor,w)}</button> · {q.amount} 钱 · {q.status==='pending'?'候 '+politicalName(q.approver,w)+' 批示':q.reply}</small></div><HoverHint label="审批因素" content={<>{(q.evaluation??grantFactors(w,q)).map(f=><p key={f.label}>{f.label} {f.value>=0?'+':''}{f.value}</p>)}</>}><span tabIndex={0}>评分 {(q.evaluation??grantFactors(w,q)).reduce((n,f)=>n+f.value,0)}</span></HoverHint>{compact&&q.status==='pending'&&q.approver===w.characterId&&<HoverHint label="审阅请款" content="打开请款奏事，比较准拨与暂缓后确认批复。"><button className="court-icon-button" aria-label={'审阅'+politicalName(q.actor,w)+'的请款'} onClick={()=>setRequestId(q.id)}><ArtIcon name="diligent" size={24}/></button></HoverHint>}{q.status==='pending'&&q.actor===w.characterId&&<HoverHint label="撤回请款" content={fiscalReason(w,{type:'fiscal',action:'cancel',id:q.id})||'撤回未批请款，不划转公款。'}><button className={compact?'court-icon-button':undefined} aria-label="撤回请款" disabled={pending||!!fiscalReason(w,{type:'fiscal',action:'cancel',id:q.id})} onClick={()=>{const command={type:'fiscal',action:'cancel',id:q.id} as const;if(pending||fiscalReason(w,command))return;send(command);}}>{compact?<ArtIcon name="wary" size={23}/>:'撤回'}</button></HoverHint>}</article>;
 return <div className={'court-fiscal'+(compact?' court-fiscal--compact':'')}>
  <div className="staff-chamber-heading"><h3>中央账房</h3><small>公库收支与地方拨款</small></div>
  <div className="court-fiscal-toolbar"><div><strong>{waiting.length}</strong><span>件候批文书</span>{!compact&&<small>中央公款 {w.realm!.treasuries[realm].coins} · 公粮 {w.realm!.treasuries[realm].grain}</small>}</div><HoverHint label="发起拨款" content={target?'选择地点、金额与用途，查看实际资金来源后确认。':'暂无有权限发起拨款的城邑'}><button className={compact?'court-icon-button':'primary'} aria-label="发起拨款" disabled={!target} onClick={()=>setGrantOpen(true)}><ArtIcon name="coins" size={25}/>{!compact&&'发起拨款'}</button></HoverHint></div>
  {waiting.length>0&&<section className="court-fiscal-section"><h4>待批与候复</h4><div className="court-fiscal-requests">{waiting.map(renderRequest)}</div></section>}
  <section className="court-fiscal-section"><h4>地方公库 <small>{cities.length} 城</small></h4><div className="court-fiscal-cities">{cities.map(([id])=>{const relief={type:'fiscal',action:'relief',site:id} as const,reason=fiscalReason(w,relief);return <article key={id}><strong>{siteById[id].name}</strong><Resource name="coins" value={localBalance(w,id)} label="公款" caption={!compact}/><HoverHint label="税赋路径" content={fiscalPath(w,id).map(accountName).join(' → ')}><span tabIndex={0}>月税 {cityYield(w,id).coins}</span></HoverHint><HoverHint label="平粜赈济" content={reason||'支出本城公款 20 钱，秩序 +8'}><button className={compact?'court-icon-button':undefined} aria-label={siteById[id].name+'平粜赈济'} disabled={pending||!!reason} onClick={()=>setReliefSite(id)}>{compact?<ArtIcon name="grain" size={23}/>:'平粜'}</button></HoverHint></article>;})}{!cities.length&&<p>暂无可管理的地方公库。</p>}</div></section>
  {history.length>0&&<section className="court-fiscal-section"><div className="court-fiscal-section-heading"><h4>近期批复</h4>{history.length>4&&<HoverHint label="全部拨款批复" content={history.length+' 件已结案文书'}><button className={compact?'court-icon-button':undefined} aria-label="查看全部拨款批复" aria-expanded={historyOpen} onClick={()=>setHistoryOpen(open=>!open)}>{compact?<ArtIcon name="diligent" size={23}/>:historyOpen?'收起':'查看全部'}</button></HoverHint>}</div><div className="court-fiscal-requests">{(!compact&&historyOpen?history:history.slice(0,4)).map(renderRequest)}</div></section>}
  <section className="court-fiscal-section"><div className="court-fiscal-section-heading"><h4>往来账目 <small>{ledger.length} 笔</small></h4><HoverHint label="查看公库账目" content="逐笔查阅钱款的来源、去向和实际结算原因。"><button className={compact?'court-icon-button':undefined} aria-label="查看公库账目" aria-expanded={ledgerOpen} onClick={()=>setLedgerOpen(open=>!open)}>{compact?<ArtIcon name="coins" size={23}/>:ledgerOpen?'收起账目':'查看账目'}</button></HoverHint></div>{ledgerOpen&&!compact&&<div className="court-fiscal-ledger">{ledger.slice(0,60).map(e=><article key={e.id}><span>第 {e.day} 日 · {e.reason}</span><strong>{e.coins} 钱</strong><small>{accountName(e.from)} → {accountName(e.to)}</small></article>)}{!ledger.length&&<p>尚无账目。</p>}</div>}</section>
  {compact&&ledgerOpen&&<ActionDialog title="公库往来账目" onClose={()=>setLedgerOpen(false)} cancelLabel="返回财赋" actions={null}><div className="court-fiscal-ledger">{ledger.slice(0,60).map(e=><article key={e.id}><span>第 {e.day} 日 · {e.reason}</span><strong>{e.coins} 钱</strong><small>{accountName(e.from)} → {accountName(e.to)}</small></article>)}{!ledger.length&&<p>尚无账目。</p>}</div></ActionDialog>}
  {compact&&historyOpen&&<ActionDialog title="拨款批复" onClose={()=>setHistoryOpen(false)} cancelLabel="返回财赋" actions={null}><div className="court-fiscal-requests">{history.map(renderRequest)}</div></ActionDialog>}
  {compact&&selectedRequest&&<ActionDialog title="地方请款奏事" onClose={()=>setRequestId(null)} cancelLabel="返回财赋" actions={null}><FiscalPetitionAudience world={w} request={selectedRequest} pending={pending} send={command=>{send(command);setRequestId(null);}} onPerson={onPerson}/></ActionDialog>}
  {grantOpen&&<ActionDialog title="发起拨款" onClose={()=>setGrantOpen(false)} actions={<button className="primary" disabled={pending||!!grantReason} onClick={()=>{if(pending||fiscalReason(w,grant))return;send(grant);setGrantOpen(false);}}>{canAllocate?'确认拨入地方公库':'确认呈请拨款'} · {amount} 钱</button>}><div className="court-fiscal-grant"><label>目标城邑<select value={target} onChange={e=>setSite(e.target.value)}>{cities.map(([id])=><option key={id} value={id}>{siteById[id].name}</option>)}</select></label><label>公款数额<input type="number" min={20} max={400} step={10} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label>{!canAllocate&&<label>用途<select value={purpose} onChange={e=>setPurpose(e.target.value as GrantRequest['purpose'])}>{Object.entries(grantPurposes).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}<p>资金来源：{canAllocate?'上级公库，立即拨入目标地方公库':'直属上级公库，获批后转入目标地方公库'}。目标：{siteById[target]?.name??'未选'}。</p>{grantReason&&<p role="status" className="court-fiscal-reason">{grantReason}</p>}</div></ActionDialog>}
  {reliefSite&&<ConfirmAction title={'下令 '+siteById[reliefSite].name+' 平粜？'} detail={'从本城地方公库支出 20 钱，秩序 +8；不动用中央公款或私人财产。'} confirmLabel="确认下令" pending={pending||!!fiscalReason(w,{type:'fiscal',action:'relief',site:reliefSite})} onCancel={()=>setReliefSite(null)} onConfirm={()=>{const cmd={type:'fiscal',action:'relief',site:reliefSite} as const;if(pending||fiscalReason(w,cmd))return;send(cmd);setReliefSite(null);}}/>}
 </div>;
}
