import {OfficialActions} from './OfficialActions';
import {PublicSuccessionPanel} from './PublicSuccessionPanel';
import { useState } from 'react';
import { ArtIcon,type ArtName } from './ArtIcon';
import { movements,movementIds,ministries,ministryIds,phases,policies,type MinistryId } from '../data/court';
import { dynastyNames } from '../data/governments';
import { historicalCharacters } from '../data/characters';
import { governmentOf,governingExecutives,currentRealm,regimeName,politicalName,governmentExecutive } from '../core/government';
import { courtOf,courtEnabled,courtReason,courtCatalysts,movementSummary,movementPower,ministryCompetent,foundingPause,courtBonus,courtSalary,type CourtCommand } from '../core/court';
import {PositionSeat,PersonSelectionDialog} from './PersonSelection';
import {isAlive} from '../core/lifeState';
import type { World,GameCommand } from '../core/types';
import './court.css';
const movementArt:Record<string,ArtName>={dynastic:'renown',expansion:'army',reform:'diligent',conservative:'frugal',unaligned:'person'};
export type CourtTab='succession'|'situation'|'movements'|'ministries'|'dynasty';
export function CourtPanel({world:w,pending,send,onPerson,tab,onTab}:{world:World;pending:boolean;send:(c:GameCommand)=>void;onPerson:(id:string)=>void;tab:CourtTab;onTab:(tab:CourtTab)=>void}){
 const [confirmation,setConfirmation]=useState<string|null>(null),[name,setName]=useState(''),[candidate,setCandidate]=useState(w.characterId!),[target,setTarget]=useState(''),[office,setOffice]=useState<MinistryId|null>(null);
 const r=currentRealm(w),g=governmentOf(w)!,c=courtOf(w);if(!c)return <p>重新读取存档后可启用朝廷系统。</p>;
 const group=c.members[w.characterId!],bonus=courtBonus(w,r),eligible=historicalCharacters.filter(p=>p.polity===r&&isAlive(w,p.id)),enabled=courtEnabled(w,r);
 const person=(id:string)=><button className="court-person" onClick={()=>onPerson(id)}>{politicalName(id)} ↗</button>;
 const action=(command:CourtCommand,label:string,consequence?:string)=>{const reason=courtReason(w,command),key=JSON.stringify(command);return <div className="court-action"><button disabled={pending||!!reason} onClick={()=>{if(consequence&&confirmation!==key){setConfirmation(key);return;}setConfirmation(null);send(command);}}>{confirmation===key?'确认：':''}{label}</button>{reason&&<small>{reason}</small>}{confirmation===key&&<aside role="status"><p>{consequence}</p><button onClick={()=>setConfirmation(null)}>取消</button></aside>}</div>;};
 return <div className="court-panel">{tab==='situation'&&<><header className="court-banner"><ArtIcon name="renown" size={52}/><div><span className="eyebrow">{g.type==='celestial'?'天朝秩序':'朝廷政治'}</span><h3>{regimeName(w,r)} · {phases[c.phase].name}</h3><p>{policies[c.policy].name}国策 · {phases[c.phase].effect}</p></div></header>
 <div className="court-meters"><label>天命／合法性 <b>{g.legitimacy}</b><progress max={100} value={g.legitimacy}/></label><label>朝局紧张 <b>{c.tension}</b><progress max={100} value={c.tension}/></label><label>官场积弊 <b>{c.corruption}</b><progress max={100} value={c.corruption}/></label></div></>}
 {!enabled&&<p className="government-warning">此政体暂停朝廷集团、中央履职与局势推进；历史记录保留。可在制度页改为官僚类政体。</p>}
 {tab!=='situation'&&<nav className="realm-subnav detail-tabs" aria-label="朝廷事务">{([['ministries','朝廷','influence'],['succession','继承','renown']] as const).map(([key,label,icon])=><button key={key} aria-pressed={key==='ministries'?tab==='ministries'||tab==='movements':tab===key} onClick={()=>{onTab(key);setConfirmation(null);}}><ArtIcon name={icon}/><span>{label}</span></button>)}</nav>}
 {tab==='movements'&&<button onClick={()=>onTab('ministries')}>← 朝廷概览</button>}
 {tab==='succession'&&<PublicSuccessionPanel world={w} pending={pending} send={send} onPerson={onPerson}/>}
 {tab==='situation'&&<>
 <section className="court-card"><h4>下期局势催化 · {30-w.day%30} 日后</h4>{courtCatalysts(w,r).map(v=><div className="court-catalyst" key={v.label}><span>{v.label}</span><b>{v.value>0?'+':''}{v.value}</b></div>)}<p>紧张 40 转入动荡，80 转入危局；合法性低于 15 也会进入危局。改善条件可恢复安定，局势每 30 日结算。</p><p>朝廷增益：税收 {bonus.tax}% · 军饷 {bonus.pay}% · 攻击 {bonus.attack}%（另叠加政体与改革）。</p>{action({type:'court',action:'audit'},'整饬吏治 · 60 公款 / 15 影响力')}<small>积弊 −20、紧张 −10、朝野支持 −3；冷却 90 日。监察和国策另有月度效果。</small></section>
 {c.petition&&<section className="court-card"><h4>{movements[c.petition.group].name}奏议</h4><p>发起人 {person(c.petition.sponsor)} · 余 {c.petition.due-w.day} 日</p><p>{movements[c.petition.group].goal}</p>{action({type:'court',action:'resolve',accept:true},'批准 · 80 公款 / 20 影响力')}{action({type:'court',action:'resolve',accept:false},'否决 · 支持 −5 / 紧张 +8')}<small>批准：支持 +5、紧张 −8，调整国策或增加合法性；玩家执政逾期视为否决。非玩家执政时，集团势力 ≥30% 且资源足够则获准。</small></section>}
 {c.founding&&<section className="court-card"><h4>「{c.founding.name}」承统议程</h4><p>{person(c.founding.sponsor)} · {c.founding.progress} / 120 日</p><p>{foundingPause(w,r)||'正在推进'}</p>{action({type:'court',action:'cancel'},'撤回议程','撤回后不返还已付成本。')}</section>}
 <details><summary>最近朝廷纪事</summary>{c.history.slice().reverse().map((h,i)=><p key={i}>第 {h.day} 日 · {h.text}</p>)}{!c.history.length&&<p>尚无记录。</p>}</details></>}
 {tab==='movements'&&<><p>你的立场：<b>{movements[group].name}</b> · 当前势力 {movementPower(w,r,w.characterId!)}。</p>{movementIds.map(k=>{const m=movementSummary(w,r,k);return <section className={'court-card '+(k===group?'court-selected':'')} key={k}><header><ArtIcon name={movementArt[k]} size={36}/><h4>{movements[k].name}</h4><b>{m.share}%</b></header><progress max={100} value={m.share}/><p>{movements[k].goal}</p><small>势力 {m.power} · {c.favored===k?'朝廷眷顾':'未获眷顾'}</small><p>领袖 {m.leader?person(m.leader):'无'}</p><div className="court-members">{m.members.map(id=><span key={id}>{person(id)}<small>{movementPower(w,r,id)}</small></span>)}</div>{action({type:'court',action:'join',group:k},'加入 · 10 影响力')}{k!=='unaligned'&&action({type:'court',action:'favor',group:k},'朝廷眷顾 · 20 影响力')}</section>;})}
 <section className="court-card"><h4>经营政治同道</h4><p>势力来自功绩、中央任职、合法辖城、家族声望、匹配特质及清议。势力最高者领衔。</p>{action({type:'court',action:'debate'},'主持清议 · 30 个人钱')}<small>个人势力 +25，持续／冷却 180 日。</small><label>游说对象<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">选择本国人物</option>{eligible.filter(p=>p.id!==w.characterId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{action({type:'court',action:'convince',target},'游说加入 · 30 个人钱 / 10 影响力')}{action({type:'court',action:'petition'},'领衔集团奏议 · 15 影响力')}<small>换党冷却 90 日、游说冷却 30 日、奏议冷却 90 日。未结党不产生领袖。</small></section></>}
 {tab==='ministries'&&<><div className="realm-section-title"><h3>利益集团</h3><button onClick={()=>onTab('movements')}>交涉 ›</button></div><div className="court-factions">{movementIds.map(id=>{const m=movementSummary(w,r,id);return <button key={id} onClick={()=>onTab('movements')} title={movements[id].goal}><ArtIcon name={movementArt[id]}/><span>{movements[id].name}<strong>{m.share}%</strong><small>{m.leader?politicalName(m.leader):'无领袖'}{group===id?' · 所属':''}{c.favored===id?' · 眷顾':''}</small></span><progress max={100} value={m.share}/></button>;})}</div>
 <div className="realm-section-title"><h3>中央官职</h3><small>俸给 {courtSalary(w,r)} 钱／月</small></div><div className="court-office-grid">
 {[{id:g.ruler,title:'君主'},...governingExecutives(w,r).filter(id=>id!==g.ruler).map(id=>({id,title:'执政'}))].map(({id,title})=><PositionSeat key={title+id} world={w} holder={id} title={title} onPerson={onPerson}/>)}
 {ministryIds.map(id=><PositionSeat key={id} world={w} holder={c.ministries[id]} title={ministries[id].name} icon={id==='military'?'army':id==='finance'?'coins':'influence'} onPerson={onPerson} onManage={()=>{setOffice(id);setCandidate(governmentExecutive(w)?c.ministries[id]??w.characterId!:w.characterId!);setConfirmation(null);}} status={c.ministries[id]?(ministryCompetent(w,r,id)?'称职':'履职不足'):undefined}>{c.ministries[id]&&<OfficialActions world={w} person={c.ministries[id]!} pending={pending} send={send}/>}</PositionSeat>)}</div>
 {office&&<PersonSelectionDialog world={w} title={ministries[office].name} value={candidate} onSelect={setCandidate} onClose={()=>setOffice(null)} pending={pending} description={<>{ministries[office].duty} · {ministries[office].effect}。功绩达到 40 时称职。{c.ministries[office]&&<p>现任 {politicalName(c.ministries[office]!)}；新任命将撤换此人。</p>}</>} options={(governmentExecutive(w)?eligible:eligible.filter(p=>p.id===w.characterId)).map(p=>({id:p.id,score:g.merit[p.id]??0,metric:'功绩',reason:courtReason(w,governmentExecutive(w)?{type:'court',action:'appoint',ministry:office,candidate:p.id}:{type:'court',action:'seek-office',ministry:office})}))} confirmLabel={governmentExecutive(w)?'任命 · 15 影响力':'申请任职 · 25 影响力'} onConfirm={()=>{send(governmentExecutive(w)?{type:'court',action:'appoint',ministry:office,candidate}:{type:'court',action:'seek-office',ministry:office});setOffice(null);}}>{governmentExecutive(w)&&c.ministries[office]&&action({type:'court',action:'appoint',ministry:office,candidate:null},'免职 · 15 影响力','撤销此人的中央官职与履职增益。')}</PersonSelectionDialog>}

 </>}
 {tab==='dynasty'&&<><section className="court-card"><h4>新朝国号</h4><label>国号<input value={name} maxLength={6} placeholder="填写 1—6 个汉字" onChange={e=>{setName(e.target.value);setConfirmation(null);}}/></label><p>当前君主 {person(g.ruler)} · 实际执政 {governingExecutives(w,r).map(id=><span key={id}>{person(id)}</span>)}</p>{action({type:'court',action:'found',mode:'usurp',name},'拥立新朝 · 300 公款 / 80 影响力','这是本局架空改朝换代。需推进 120 个有效日；完成后你成为君主与执政，旧官撤任，公库损失 15%、军队士气 −20、所属城市秩序 −10。家业、人物与既有疆界保留。')}{action({type:'court',action:'found',mode:'unify',name},'重建天朝 · 300 公款 / 80 影响力','需实控 75% 非边疆城市、天命 80、支持 70、功绩 60、实际执政。120 个有效日后建立所选国号与天朝制；旧官撤任、公库损失 15%、士气 −20、秩序 −10。未控制政权不会被自动吞并。')}<small>拥立需地方或中央权力基础、领衔势力 ≥50% 的集团、支持 70、功绩 60；原君主合法性 ≤40 或朝局危局。君位继承可在朝廷的“继承”中查看。</small></section>
 {c.founding&&<section className="court-card"><h4>「{c.founding.name}」建朝议程</h4><p>拥立 {person(c.founding.sponsor)} · {c.founding.progress} / 120 日</p><progress max={120} value={c.founding.progress}/><p>{foundingPause(w,r)||'条件满足，正在推进'}</p>{action({type:'court',action:'cancel'},'撤回 · 成本不退','撤回当前建朝议程，不返还已付成本。')}</section>}
 <h4>历朝国号</h4><ol className="court-dynasties">{w.realm!.governments!.regimes.filter(v=>v.realm===r).map(v=><li key={v.id}><strong>{v.name??dynastyNames[v.dynasty]}</strong><small>{v.kind==='sandbox'?'本局推演':'历史路线／剧本'} · 第 {v.from} 日至{v.until===null?'今':v.until+' 日'}</small><p>建朝／建档君主 {person(v.ruler)} · 承接 {v.cities.length} 个城市</p></li>)}</ol></>}

 </div>;
}
