import {WarDeclaration} from './WarDeclaration';
import {PersonChoice} from './PersonSelection';
import {envoyCandidates,envoyEstimate} from '../core/envoyTravel';
import {activeWars} from '../core/wars';
import {RealmBadge} from './RealmBadge';
import {ClanRanking} from './ClanRanking';
import {useState,useEffect,useRef} from 'react';
import {OfficeHierarchy} from './OfficeHierarchy';
import {CharacterPortrait} from './CharacterPortrait';
import {ArtIcon,type ArtName} from './ArtIcon';
import {DetailTabs} from './DetailTabs';
import {HoverHint} from './HoverHint';
import {playerRealm,type RealmId} from '../core/realm';
import {governingExecutives,governmentOf,politicalName} from '../core/government';
import {diplomacyActions,diplomaticQuote,diplomaticPair,diplomaticScore,diplomaticOpinionBreakdown,warState,attitude,type DiplomacyAction,type TreatyKind} from '../core/diplomacy';
import {relationshipPersonById} from '../data/relationships';
import type {World,GameCommand} from '../core/types';
import './diplomacy.css';
const treatyNames:Record<TreatyKind,string>={transit:'民事通行',safe:'安全通行',military:'军队借道',pact:'互不侵犯',alliance:'同盟'};
const groups:{name:string;icon:ArtName;actions:DiplomacyAction[]}[]=[{name:'邦交与礼仪',icon:'influence',actions:['improve','recognize','meeting','insult','revoke']},{name:'通行往来',icon:'world',actions:['transit','safe']},{name:'军事合作',icon:'army',actions:['military','pact','alliance','aid']},{name:'朝贡与宗属',icon:'coins',actions:['submit','independence']}];
const effects:Record<DiplomacyAction,string>={improve:'获接纳后，两国关系 +25。',safe:'批准后本人获得 240 日安全通行；交战时失效。',meeting:'批准后本人获得安全通行，须亲赴对方都城完成会盟，完成后关系再 +15。',transit:'普通人物可通行 720 日；君主、执政和统帅仍需安全通行。',military:'己方军队可借道 720 日，不授予占领权。',aid:'盟国答应后拨付 120 钱与 120 粮。',submit:'成为对方臣属，每月朝贡 20 钱，失去独立宣战及军政缔约权。',independence:'解除臣属，关系 −50、信用 −20。',revoke:'终止双方全部条约，关系 −30、信用 −20。',insult:'立即使两国关系 −25。',recognize:'相互承认国号，双方合法性 +5。',pact:'720 日互不侵犯；宣战前须先终止条约。',alliance:'720 日军事同盟，参战时可请求盟约军援。'};
const instant=(a:DiplomacyAction)=>['insult','revoke','independence'].includes(a);
const signed=(n:number)=>(n>0?'+':'')+n;
export function DiplomacyPanel({world:w,selected:target,onSelect,onPerson,pending,send}:{world:World;selected:RealmId;onSelect:(r:RealmId)=>void;onPerson:(id:string)=>void;pending:boolean;send:(c:GameCommand)=>void}){
 const [tab,setTab]=useState<'relations'|'officers'|'history'|'clans'>('relations'),[action,setAction]=useState<DiplomacyAction|null>(null),[warConfirm,setWarConfirm]=useState<'war'|'peace'|null>(null);
 const [envoy,setEnvoy]=useState<string|undefined>();
 useEffect(()=>{setEnvoy(undefined);setAction(null);},[target]);
 const decision=useRef<HTMLElement>(null);useEffect(()=>{if(action)decision.current?.scrollIntoView({block:'nearest'});},[action]);
 const s=w.diplomacy;if(!s||!w.realm)return <p>此局没有国家外交事务。</p>;
 const r=playerRealm(w),g=governmentOf(w,target)!,p=target===r?null:diplomaticPair(w,r,target),exec=governingExecutives(w,target),lord=s.subjects[target],isSubject=s.subjects[r]===target,isOverlord=s.subjects[target]===r,status=warState(w,r,target),active=p?.treaties.filter(t=>t.until>w.day)??[];
 const person=(id:string)=><button className="diplomacy-person-link" onClick={()=>onPerson(id)}>{politicalName(id)} ›</button>;
 const leaders=[{id:g.ruler,title:exec.includes(g.ruler)?'君主 · 执政':'君主'},...exec.filter(id=>id!==g.ruler).map(id=>({id,title:'执政'}))];
 const bilateral=(a:RealmId,b:RealmId)=>target===r?a===r||b===r:[a,b].includes(r)&&[a,b].includes(target);
 const missions=s.missions.filter(m=>bilateral(m.from,m.to)),history=s.history.filter(h=>bilateral(h.from,h.to));
 const marriages=w.relationships?.marriages.filter(m=>m.until===null&&p&&bilateral(relationshipPersonById[m.a]?.realm,relationshipPersonById[m.b]?.realm))??[];
 const relevantWar=activeWars(w).find(v=>bilateral(v.attacker,v.defender));
 const q=action?diplomaticQuote(w,{type:'diplomacy',action,target,envoy}):null;
 const treaties=(kinds:TreatyKind[])=>active.filter(t=>kinds.includes(t.kind)).map(t=><div className="diplomacy-treaty-row" key={t.kind+t.from}><strong>{treatyNames[t.kind]}</strong><small><RealmBadge realm={t.from} world={w}/> → <RealmBadge realm={t.to} world={w}/> · 余 {t.until-w.day} 日</small>{t.actor&&<small>{person(t.actor)}{t.meeting==='invited'?' · 待赴会盟':t.meeting==='held'?' · 会盟已成':''}</small>}</div>);
 return <div className="diplomacy-panel"><header className="diplomacy-banner"><RealmBadge realm={target} world={w}/><div><small>{target===r?'本国':'政权档案'}</small><span>{lord?<>宗主：<RealmBadge realm={lord} world={w} onOpen={onSelect}/></>:'独立政权'}</span><small>国家信用 {s.credit[target]} / 100</small></div></header>
 <div className="diplomacy-leaders">{leaders.map(({id,title})=><button key={id} onClick={()=>onPerson(id)}><CharacterPortrait characterId={id} world={w}/><span><strong>{politicalName(id)}</strong><small>{title}</small></span></button>)}</div>
 <DetailTabs label="国家详情" value={tab} onChange={setTab} items={[{id:'relations',label:'外交',icon:'world'},{id:'officers',label:'官员',icon:'influence'},{id:'clans',label:'世族',icon:'renown'},{id:'history',label:'往事',icon:'diligent'}]}/>
 {tab==='clans'&&<ClanRanking world={w} realm={target} onPerson={onPerson}/>}
 {tab==='officers'&&<OfficeHierarchy world={w} realm={target} onPerson={onPerson} expanded/>}
 {tab==='history'&&<section className="diplomacy-history"><h3><ArtIcon name="diligent"/>外交往事</h3>{history.slice(-20).reverse().map((h,i)=><article key={i}><small>第 {h.day} 日</small><p>{h.text}</p></article>)}{!history.length&&<p className="diplomacy-empty">尚无外交记录。</p>}</section>}
 {tab==='relations'&&<>{p?<><section><h3>与<RealmBadge realm={r} world={w}/>的关系</h3><div className="diplomacy-status"><span className={status==='交战'?'is-war':''}><ArtIcon name={status==='交战'?'army':status==='停战期'?'steadfast':'frugal'}/><b>{status}</b></span><span><ArtIcon name={p.opinion>=40?'gregarious':p.opinion>=0?'person':p.opinion>-40?'wary':'stress'}/><b>{attitude(p.opinion)}</b></span>{(isSubject||isOverlord)&&<span><ArtIcon name="coins"/><b>{isSubject?'向其朝贡':'向我朝贡'}</b></span>}{active.some(t=>t.kind==='alliance')&&<span><ArtIcon name="steadfast"/><b>盟国</b></span>}
 <HoverHint label={'关系分数 '+p.opinion+'，查看影响因子'} content={<><strong>国家关系 · {signed(p.opinion)}</strong>{diplomaticOpinionBreakdown(p).map(v=><p key={v.label}>{v.label}<b>{signed(v.value)}</b></p>)}<small>范围 −100 至 +100；列示实际计入的变化。</small></>}><span className="diplomacy-score">{signed(p.opinion)}<small>关系</small></span></HoverHint></div><p className="diplomacy-meta">{p.recognized?'相互承认国号':r!=='liang'&&target!=='liang'?'竞争正统':'未相互承认国号'}{status==='停战期'?' · 停战余 '+(w.realm.truces[[r,target].sort().join('|')]-w.day)+' 日':''}</p></section>
 <section><h3><ArtIcon name="influence"/>现行约定</h3>{!active.length&&!isSubject&&!isOverlord&&!marriages.length?<p className="diplomacy-empty">双方尚无条约或姻亲关系。</p>:<div className="diplomacy-treaties">{(isSubject||isOverlord)&&<article><h4><ArtIcon name="coins"/>经济</h4><p><RealmBadge realm={isSubject?r:target} world={w}/>每月向<RealmBadge realm={isSubject?target:r} world={w}/>朝贡 20 钱</p></article>}{active.some(t=>['military','pact','alliance'].includes(t.kind))&&<article><h4><ArtIcon name="army"/>军事</h4>{treaties(['military','pact','alliance'])}</article>}{active.some(t=>['transit','safe'].includes(t.kind))&&<article><h4><ArtIcon name="world"/>通行</h4>{treaties(['transit','safe'])}</article>}{marriages.length>0&&<article><h4><ArtIcon name="renown"/>姻亲</h4>{marriages.map(m=><p key={m.a+m.b}>{person(m.a)} × {person(m.b)}</p>)}<p className="diplomacy-empty">人物婚姻不附带国家盟约。</p></article>}</div>}</section>
 <section><h3><ArtIcon name="gregarious"/>国家交涉</h3>{groups.map(group=><div className="diplomacy-action-group" key={group.name}><h4><ArtIcon name={group.icon} size={23}/>{group.name}</h4><div className="diplomacy-action-grid">{group.actions.map(id=>{const quote=diplomaticQuote(w,{type:'diplomacy',action:id,target}),reason=pending?'正在处理上一项命令':quote.reason;return <HoverHint key={id} label={diplomacyActions[id]+(reason?'：'+reason:'')} content={<><strong>{diplomacyActions[id]}</strong><p>{effects[id]}</p><p>{quote.coins} 公款 · {quote.influence} 影响力</p>{reason&&<p className="hint-requirement">{reason}</p>}{!instant(id)&&<><p>接受度 {quote.score} / 所需 {quote.threshold}</p>{diplomaticScore(w,r,target).map(v=><p key={v.label}>{v.label}<b>{signed(v.value)}</b></p>)}<small>派遣前可选使者，成功率与办理时间随人选和局势变化。</small></>}</>}><button className="diplomacy-action-card" disabled={!!reason} aria-pressed={action===id} onClick={()=>{setAction(id);setWarConfirm(null);}}><ArtIcon name={group.icon} size={28}/><span>{diplomacyActions[id]}</span></button></HoverHint>;})}</div></div>)}
 {action&&q&&<article ref={decision} className="diplomacy-decision" aria-live="polite"><h4>{diplomacyActions[action]}</h4><p>{effects[action]}</p>{!instant(action)&&<><PersonChoice world={w} title="使者" value={q.envoy??''} onChange={setEnvoy} pending={pending} onPerson={onPerson} options={envoyCandidates(w,r,target).map(p=>({...p,metric:'外交',detail:(()=>{const e=envoyEstimate(w,p.id,r,target,action,q.threshold);return `赴都 ${e.travel} 日 · 交涉 ${e.negotiation} 日 · 成功率 ${e.chance}%`;})()}))}/>{q.estimate&&<p>赴都 {q.estimate.travel} 日 · 交涉 {q.estimate.negotiation} 日 · 成功率 {q.estimate.chance}%<br/><small>按抵达时两国关系与使者能力结算；出使期间不能兼办差事，交涉后沿可通行道路返程。行程费用包含在使团公款内。</small></p>}</>}<p>{q.coins} 公款 · {q.influence} 影响力{!instant(action)?' · 使团费用不退还':''}</p>{q.reason&&<p>{q.reason}</p>}<button className="primary" disabled={pending||!!q.reason} onClick={()=>{send({type:'diplomacy',action,target,envoy:q.envoy});setAction(null);}}>{instant(action)?'确认执行':'派遣使团'}</button><button onClick={()=>setAction(null)}>取消</button></article>}</section>
</>:<p className="diplomacy-meta">本国朝廷 · 点击地图上的政权、人物所属政权或城市国名，查看对应国家关系。</p>}
 <section className="diplomacy-war-entry"><button className="diplomacy-action-card" onClick={()=>{setAction(null);setWarConfirm('war');}}><ArtIcon name="army"/>{relevantWar||target===r?'战事':'宣战'}</button>{warConfirm&&<WarDeclaration key={target} world={w} target={target} pending={pending} send={send} onPerson={onPerson} onClose={()=>setWarConfirm(null)}/>}</section>
 {(w.realm.reparations??[]).filter(d=>bilateral(d.from,d.to)).map(d=><div className="diplomacy-treaty-row" key={d.war}><ArtIcon name="coins"/><RealmBadge world={w} realm={d.from}/> → <RealmBadge world={w} realm={d.to}/><span>赔款待偿 {d.remaining} · 每期 {d.instalment} · {Math.max(0,d.next-w.day)} 日后偿付</span></div>)}<section><h3><ArtIcon name="world"/>往来使团</h3>{missions.map(m=><article key={m.id}><strong><RealmBadge realm={m.from} world={w}/> → <RealmBadge realm={m.to} world={w}/></strong><p>{m.envoy&&<button className="envoy-person" onClick={()=>onPerson(m.envoy!)}><CharacterPortrait characterId={m.envoy} world={w} compact/>{politicalName(m.envoy)}</button>}{diplomacyActions[m.action]} · {m.status==='returning'?'返程 · 余 '+Math.max(0,m.due-w.day)+' 日':m.status==='traveling'?(m.arrived===undefined?'出使与交涉':'驻都交涉')+' · 余 '+Math.max(0,m.due-w.day)+' 日':'等待答复，余 '+(m.expires-w.day)+' 日'}</p>{m.status==='audience'&&m.to===r&&(['accept','reject'] as const).map(a=>{const cmd={type:'diplomacy',action:a,mission:m.id} as const,reason=diplomaticQuote(w,cmd).reason;return <HoverHint key={a} label={a==='accept'?'接纳议案':'拒绝议案'} content={reason||'确认后答复使团。'}><button disabled={pending||!!reason} onClick={()=>send(cmd)}>{a==='accept'?'接纳议案':'拒绝议案'}</button></HoverHint>;})}</article>)}{!missions.length&&<p className="diplomacy-empty">暂无使团</p>}</section></>}
 </div>;
}
