import {useEffect,useRef,useState} from 'react';
import {EstatePainting} from './EstatePainting';
import {MobilityPanel} from './MobilityPanel';
import {ArtIcon,Resource} from './ArtIcon';
import {ActionDialog} from './ActionDialog';
import {CommandButton} from './CommandButton';
import {SingleChoiceCards} from './SingleChoiceCards';
import {buildQuote,estateBuildings,estateName,type EstateBuilding} from '../core/construction';
import {allEstates,estateById,estateCapacity,estateGrainCapacity,estateForecast,estateQuote,estateRents,estatePolicies,actualEstatePolicy,estateAccessReason,ordinaryPopulation,ownedEstates,type EstateRent,type EstateCommand} from '../core/estates';
import {manpower,sourceOccupied} from '../core/manpower';
import {getPerson} from '../core/personRegistry';
import {siteById} from '../data/scenario';
import type {World,GameCommand} from '../core/types';
import './estateManagement.css';
export function EstateWorkshop({world:w,send,pending=false,estateId,onEstate,onPerson,onMilitary}:{world:World;pending?:boolean;estateId?:string;onEstate?:(id:string)=>void;onPerson?:(id:string)=>void;onMilitary?:()=>void;send:(c:GameCommand)=>void}){
 const [selected,setSelected]=useState<EstateBuilding|null>(null),[family,setFamily]=useState(false),[draft,setDraft]=useState<EstateCommand|null>(null),close=useRef<HTMLButtonElement>(null);
 const e=estateId?estateById(w,estateId)??w.holdings.estate:ownedEstates(w)[0]??w.holdings.estate;
 useEffect(()=>{setSelected(null);setFamily(false);setDraft(null);},[e.id,w.characterId]);
 useEffect(()=>{if(!selected)return;const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;close.current?.focus();return()=>{if(previous?.isConnected)previous.focus();};},[selected]);
 const d=selected?estateBuildings[selected]:null,cmd=selected?{type:'build',scope:'estate',site:e.location,estate:e.id,building:selected} as const:null,q=cmd?buildQuote(w,cmd):null,level=selected?e.levels[selected]:0,forecast=estateForecast(w,e),own=e.owner===(w.characterId??'fictional'),policy=estatePolicies[actualEstatePolicy(w,e.location)],army=w.realm?manpower(w,e.location,e.owner):null,blocked=w.realm?estateAccessReason(w,e,w.characterId):'';
 return <div className="estate-workshop estate-canvas-workshop">
  <div className="estate-workshop-heading"><span>{siteById[e.location].name}</span><button className="estate-owner" onClick={()=>onPerson?.(e.owner)}>{getPerson(w,e.owner)?.name??'庄主'}</button>{own&&<Resource name="coins" value={w.people[0].coins} label="个人钱"/>}<small>建筑位 {Object.entries(e.levels).filter(([id,n])=>id!=='hall'&&n>0).length}/{e.levels.hall}</small>{own&&<button aria-pressed={family} onClick={()=>{setFamily(!family);setSelected(null);}}><ArtIcon name="person" size={22}/>家事</button>}</div>
  {w.realm&&<div className="estate-management-summary" aria-label="庄园经营摘要"><span><ArtIcon name="person" size={22}/><b>{e.population.toLocaleString()}</b><small>庄户 / 承载 {estateCapacity(e).toLocaleString()}</small></span><span><ArtIcon name="coins" size={22}/><b>+{forecast.coins}</b><small>庄主月净收入</small></span><span><ArtIcon name="grain" size={22}/><b>{e.grain}</b><small>庄粮 / 容量 {estateGrainCapacity(e)}</small></span><span><ArtIcon name="army" size={22}/><b>{army?.privateAvailable??0}</b><small>庄主本县私人兵额</small></span><span><ArtIcon name="influence" size={22}/><b>{policy.name}</b><small>农业税 {Math.round(policy.tax*100)}% / 公兵额 {Math.round(policy.publicShare*100)}%</small></span></div>}
  <EstatePainting estate={e} day={w.day} selected={selected} onSelect={id=>{setSelected(id);setFamily(false);}}>
   {selected&&d&&q&&cmd&&<section className={'estate-plot-popover at-'+selected} aria-label={d.name+'营建'} onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();setSelected(null);}}}><header><h3>{d.name} <small>{level}/3 级</small></h3><button ref={close} aria-label="关闭营建详情" onClick={()=>setSelected(null)}>×</button></header><p>{w.realm?d.effect:selected==='fields'?'教学局每级每月行粮 +6':selected==='workshop'?'教学局每级每月收入 +6 钱':selected==='storehouse'?'教学局每级每月行粮 +3':d.effect}</p>{e.project?.building===selected&&<div><progress max={e.project.due-e.project.started} value={w.day-e.project.started}/><small>营建中 · 余 {Math.max(0,e.project.due-w.day)} 日</small></div>}{level<3&&<div className="estate-plot-cost"><ArtIcon name="coins" size={22}/><b>{q.cost}</b><span>{q.days} 日</span></div>}<button className="primary" disabled={pending||!!q.reason||!own} onClick={()=>{if(pending||buildQuote(w,cmd).reason||!own)return;send(cmd);setSelected(null);}}>{level>=3?'已满级':level?'扩建至 '+q.level+' 级':'兴建'}</button>{(q.reason||!own)&&<small className="estate-requirement">{q.reason||'仅庄主可动用私财营建'}</small>}</section>}
   {family&&<section className="estate-family-overlay"><header><strong>家事</strong><button aria-label="关闭家事" onClick={()=>setFamily(false)}>×</button></header><MobilityPanel world={w} site={e.location} estate send={send}/></section>}
  </EstatePainting>
  {w.realm&&<div className="estate-management-footer"><nav aria-label="本人家产">{allEstates(w).filter(a=>a.disposed===undefined&&(a.owner===w.characterId||a.id===e.id)).map(a=><button key={a.id} aria-pressed={e.id===a.id} onClick={()=>onEstate?.(a.id)}><ArtIcon name="estate" size={22}/>{siteById[a.location].name}</button>)}</nav><div className="estate-management-actions">
   {own&&(['tenants','rent','relief','withdraw'] as const).map(action=><CommandButton key={action} label={{tenants:'招佃',rent:'调租',relief:'赈粮',withdraw:'行粮'}[action]} icon={action==='tenants'?'person':action==='rent'?'coins':'grain'} pending={pending} reason={blocked} hint={{tenants:'本县编户入庄，人口总量不变；先看安置成本和公私兵源变化',rent:'三档租额，每次调整间隔 90 日',relief:'庄粮转入本县公仓供民食',withdraw:'本人抵达后提取庄粮作为行粮'}[action]} onClick={()=>setDraft(action==='rent'?{type:'estate',action,estate:e.id,rent:e.rent}:{type:'estate',action,estate:e.id,amount:action==='tenants'?100:10})}/>)}
   {onMilitary&&<CommandButton label="军队" icon="army" hint="进入军事页征募；公私来源共用同一动员比例" onClick={onMilitary}/>}{own&&<CommandButton label="置业" icon="estate" pending={pending} hint="在本国实控县开办空庄，支出私财 120，田庄需十日竣工" onClick={()=>setDraft({type:'estate',action:'found',site:w.people[0].location})}/>}
  </div>{blocked&&<p role="status">{blocked}</p>}<small>开局庄产规模为剧本设定，非精确历史庄产。</small></div>}
  {draft&&<EstateOrder world={w} estate={e.id} draft={draft} onDraft={setDraft} pending={pending} send={send} onClose={()=>setDraft(null)}/>}
 </div>;
}
function EstateOrder({world:w,estate,draft,onDraft,pending,send,onClose}:{world:World;estate:string;draft:EstateCommand;onDraft:(c:EstateCommand)=>void;pending:boolean;send:(c:GameCommand)=>void;onClose:()=>void}){
 const e=estateById(w,estate)!,quote=estateQuote(w,draft),tenants=draft.action==='tenants',forecast=estateForecast(w,e),before=manpower(w,e.location,e.owner);
 const after=tenants&&Number.isSafeInteger(draft.amount)&&!quote.reason?(()=>{const next=structuredClone(w);estateById(next,e.id)!.population+=draft.amount;return {army:manpower(next,e.location,e.owner),income:estateForecast(next,estateById(next,e.id)!)};})():null;
 return <ActionDialog title={{found:'开办庄园',tenants:'招佃安置',rent:'调整租额',relief:'庄粮赈济',withdraw:'提取行粮'}[draft.action]} scene="landscape" className="estate-management-dialog" onClose={onClose} actions={<button className="primary" disabled={pending||!!quote.reason} onClick={()=>{if(pending||estateQuote(w,draft).reason)return;send(draft);onClose();}}>确认{draft.action==='rent'?'调租':draft.action==='found'?'置业':draft.action==='tenants'?'安置 '+draft.amount+' 人':'支粮'} · {quote.coins} 钱 / {quote.grain} 粮</button>}>
  <p>{getPerson(w,w.characterId??'fictional')?.name} · {draft.action==='found'?siteById[draft.site]?.name:estateName(e.family)+'，'+siteById[e.location].name} · 使用本人私财与庄粮。</p>
  {draft.action==='found'?<label>置业县域<select value={draft.site} onChange={event=>onDraft({...draft,site:event.target.value})}>{Object.keys(w.realm!.cities).map(site=><option key={site} value={site}>{siteById[site].name}</option>)}</select></label>:draft.action==='rent'?<SingleChoiceCards label="租额 · 单选" value={draft.rent} onChange={rent=>onDraft({...draft,rent:rent as EstateRent})} options={Object.entries(estateRents).map(([id,r])=>{const next=structuredClone(w),proposed=estateById(next,e.id)!;proposed.rent=id as EstateRent;const income=estateForecast(next,proposed);return {id,title:r.name,description:r.description,detail:`月租钱 ${income.coins}、粮租 ${income.grain}；份额 ${Math.round(r.share*100)}%，90 日冷却`};})}/>:<label>{tenants?'安置人口':'庄粮数量'}<input type="number" min={1} max={2000} step={1} value={Number.isFinite(draft.amount)?draft.amount:''} onChange={event=>onDraft({...draft,amount:event.target.valueAsNumber})}/></label>}
  {tenants&&<><p>本县普通编户 {ordinaryPopulation(w,e.location).toLocaleString()} 人；空余安置规模 {Math.max(0,estateCapacity(e)-e.population-sourceOccupied(w,e.location,e.id).total)} 人。同源现役与返乡在途仍占规模。</p><p>县域民用人口保持 {w.realm!.cities[e.location].population.toLocaleString()} 人；月租钱 {forecast.coins} → {after?.income.coins??forecast.coins}，公共兵额 {before.publicAvailable} → {after?.army.publicAvailable??before.publicAvailable}，本人私人兵额 {before.privateAvailable} → {after?.army.privateAvailable??before.privateAvailable}。普通农业税源减少，商业税不变。</p></>}
  {draft.action==='found'&&<p>民间置业 80 钱、田庄施工 40 钱；十日竣工后承载 2000 人，招佃须另付安置钱粮。建造期间预留县域经营容量。</p>}{draft.action==='relief'&&<p>庄粮减少 {draft.amount}，本县民食公仓增加同额；不发钱、不制造人口。</p>}{draft.action==='withdraw'&&<p>庄粮减少 {draft.amount}，本人随身行粮增加同额；远方收成不会自动送进旅囊。</p>}{quote.reason&&<p role="status">{quote.reason}</p>}
 </ActionDialog>;
}
