import {ActionDialog} from './ActionDialog';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {GameSound} from './soundEngine';
import {useSound,useSoundError,changeSound} from './audioSettings';
import {subscribeFeedback,getFeedback} from './actionFeedback';
let currentSound:GameSound|null=null;
export function useGameAudio(page:'menu'|'play',eventId?:string){
 const preferences=useSound(),engine=useRef<GameSound|null>(null),lastEvent=useRef<string|undefined>(undefined);
 useEffect(()=>{const audio=new GameSound();engine.current=audio;currentSound=audio;const unlock=()=>void audio.unlock();const click=(event:MouseEvent)=>{const button=event.target instanceof Element?event.target.closest('button'):null;if(!button||button.disabled)return;const label=button.getAttribute('aria-label')||button.textContent||'';audio.cue(/取消|关闭|返回/.test(label)?'cancel':button.classList.contains('primary')?'confirm':'select');};
  const choice=(event:Event)=>{if(event.target instanceof Element&&event.target.matches('select,input[type=radio],input[type=checkbox]'))audio.cue('select');};
  const visibility=()=>audio.update();document.addEventListener('pointerdown',unlock,{once:true});document.addEventListener('keydown',unlock,{once:true});document.addEventListener('click',click);document.addEventListener('change',choice);document.addEventListener('visibilitychange',visibility);
  const unsubscribe=subscribeFeedback(()=>{const f=getFeedback();if(f?.state==='success')audio.cue('complete');else if(f?.state==='error')audio.cue('blocked');});
  return()=>{unsubscribe();document.removeEventListener('pointerdown',unlock);document.removeEventListener('keydown',unlock);document.removeEventListener('click',click);document.removeEventListener('change',choice);document.removeEventListener('visibilitychange',visibility);audio.dispose();engine.current=null;currentSound=null;};},[]);
 useEffect(()=>{engine.current?.setPage(page);engine.current?.update();},[page,preferences]);
 useEffect(()=>{if(eventId&&eventId!==lastEvent.current)engine.current?.cue(eventId.includes('arrival')?'arrival':'event');lastEvent.current=eventId;},[eventId]);
}
export function SoundGlyph({muted=false}:{muted?:boolean}){return <svg viewBox="0 0 40 40" aria-hidden="true"><path d="M7 11Q20 4 33 11L30 31Q20 36 10 31Z"/><path d="M12 11v18m4-20v22m4-22v23m4-23v22m4-20v18"/>{muted&&<path className="sound-glyph-slash" d="m5 5 30 30"/>}</svg>;}
function SoundConsole(){const settings=useSound(),error=useSoundError();return <section className="sound-console" aria-label="声音设置"><header><SoundGlyph muted={settings.muted}/><div><h3>山河之声</h3><small>{settings.muted?'万籁俱静':'弦音入画，风过山河'}</small></div><button type="button" className="sound-silence" aria-label={settings.muted?'恢复全部声音':'静音全部声音'} aria-pressed={settings.muted} onClick={()=>changeSound({muted:!settings.muted})}>{settings.muted?'启声':'静音'}</button></header><div className="sound-strings">{([['music','配乐'],['effects','操作'],['ambience','山河']] as const).map(([key,label])=><label key={key}><span>{label}</span><input type="range" min="0" max="100" value={Math.round(settings[key]*100)} style={{'--sound-level':settings[key]*100+'%'} as CSSProperties} aria-label={{music:'配乐',effects:'操作音',ambience:'环境声'}[key]+'音量'} aria-valuetext={Math.round(settings[key]*100)+'%'} onChange={e=>changeSound({[key]:Number(e.target.value)/100})}/><output>{Math.round(settings[key]*100)}</output></label>)}</div><footer><button type="button" className="manuscript-link" onClick={()=>currentSound?.retry()}>{error?'重试声音':'试听'}</button><a href={import.meta.env.BASE_URL+'audio/CREDITS.md'} target="_blank" rel="noreferrer">配乐题记</a></footer>{error&&<p className="sound-error" role="status">{error}</p>}</section>;}
export function SoundSettings({compact=false}:{compact?:boolean}){const settings=useSound(),[open,setOpen]=useState(false);if(!compact)return <SoundConsole/>;return <><button type="button" className="entry-sound-medallion" aria-label="声音设置" title="声音设置" aria-haspopup="dialog" onClick={()=>setOpen(true)}><SoundGlyph muted={settings.muted}/></button>{open&&<ActionDialog title="山河之声" className="sound-dialog" onClose={()=>setOpen(false)} cancelLabel="收起" actions={null}><SoundConsole/></ActionDialog>}</>;}
