import {realmAtWar} from '../core/wars';
import {plannedReinvestment} from '../core/treasury';
import {lifeOf,ageLabel} from '../core/lifeState';
import { regimeName } from '../core/government';
import { Resource } from './ArtIcon';
import { playerRealm,realmForecast } from '../core/realm';
import { DEFAULT_SCRIPT,gameScripts,getScript,scriptLabel } from '../data/scripts';
import { CharacterPicker } from './CharacterPicker';
import { characterById } from '../data/characters';
import { useRef,useState } from 'react';
import { campaignGoals,campaignTitle } from '../core/campaign';
import { dateLabel } from '../core/world';
import type { Request,SaveInfo,World } from '../core/types';
import './gameEntry.css';
const accountSaves=import.meta.env.BASE_URL.startsWith('/games/fengyun-nanbeichao/');
export const saveLabel=(id:string)=>id==='manual'?'手动存档':id==='previous-run'?'上一局备份':'自动存档 '+id.slice(-1);
interface EntryProps {world:World|null;slots:SaveInfo[];pending:boolean;notice:{text:string;error?:boolean}|null;send:(request:Request)=>void;notify:(text:string,error?:boolean)=>void}
export function GameEntry({world,slots,pending,notice,send,notify}:EntryProps){
  const [playMode,setPlayMode]=useState<'sandbox'|'tutorial'>('sandbox');
  const [selectedScript,setSelectedScript]=useState(DEFAULT_SCRIPT);
  const script=getScript(selectedScript);
  const [selectedCharacter,setSelectedCharacter]=useState(script.defaultCharacter);
  const [tab,setTab]=useState<'home'|'scripts'|'new'|'load'>('home');const upload=useRef<HTMLInputElement>(null);
  return <main className={`game-entry ${tab==='new'?'is-selecting':''}`}><div className="entry-backdrop"/><section className="entry-content"><span className="eyebrow">山河流转 · 家业长存</span><h1>风云南北朝</h1><p className="entry-lead">择一段时代，续一族风云。</p>
    {!world?<div className="entry-loading" role="status"><span/>{notice?.error?'存档暂时无法读取':'正在准备世界与'+(accountSaves?'账号':'本地')+'存档…'}<small>首次进入需要加载游戏资源。</small>{notice?.error&&<button onClick={()=>send({type:'init'})}>重试读取存档</button>}</div>:<>
    {tab==='home'?<div className="entry-actions"><button className="primary" disabled={pending||!slots.length} onClick={()=>send({type:'resume'})}>继续游戏</button><button disabled={pending} onClick={()=>setTab('scripts')}>开始新游戏</button><button disabled={pending} onClick={()=>setTab('load')}>读取／导入存档</button><p>长期历史沙盒 · 可随时保存离开</p></div>:<><button className="entry-back" onClick={()=>setTab(tab==='new'?'scripts':'home')} disabled={pending}>{tab==='new'?'← 返回剧本选择':'← 返回主菜单'}</button>
    {tab==='scripts'?<div className="script-selection"><h2>选择剧本</h2><div className="script-list">{gameScripts.map(s=><button key={s.id} className="script-card" aria-pressed={selectedScript===s.id} disabled={pending} onClick={()=>{setSelectedScript(s.id);setSelectedCharacter(s.defaultCharacter);}}><span className="script-year">{s.year}<small>公元</small></span><span><strong>{s.name}</strong><span>{s.description}</span><small>{s.characterIds.length} 位剧本人物 · {selectedScript===s.id?'已选择':'选择剧本'}</small></span></button>)}</div><button className="primary" disabled={pending} onClick={()=>setTab('new')}>选择人物 → {scriptLabel(selectedScript)}</button></div>:tab==='new'?<div className="entry-new-game"><div className="mode-picker"><button aria-pressed={playMode==='sandbox'} onClick={()=>{setPlayMode('sandbox');if(selectedCharacter==='fictional')setSelectedCharacter(script.defaultCharacter);}}>历史沙盒<small>持续经营 · 政治、财政与军事 · 无 120 日强制结局</small></button><button aria-pressed={playMode==='tutorial'} onClick={()=>setPlayMode('tutorial')}>营建教学局<small>120 日目标 · 熟悉旅行、建设与家族</small></button></div><CharacterPicker sandbox={playMode==='sandbox'} key={selectedScript} scriptId={selectedScript} allowFictional={playMode==='tutorial'&&script.allowFictional} selected={selectedCharacter} onSelect={setSelectedCharacter}/><div className="entry-launch">{slots.length>0&&<p className="entry-note">新局将替换手动存档，当前进度保留为“上一局备份”；再次开新局会更新该备份。</p>}<button className="primary" disabled={pending} onClick={()=>send({type:'new',mode:playMode,scriptId:selectedScript,characterId:selectedCharacter==='fictional'?undefined:selectedCharacter})}>{pending?'正在准备…':'以'+(characterById[selectedCharacter]?.name??'沈行舟')+'开始这一局'}</button></div></div>:<div className="entry-saves"><button disabled={pending} onClick={()=>upload.current?.click()}>导入存档文件</button>{!slots.length&&<p>{accountSaves?'此账号暂无存档。可导入备份，或返回开始新游戏。':'暂无本地存档。可导入备份，或返回开始新游戏。'}</p>}{slots.map(slot=><article key={slot.id}><div><strong>{saveLabel(slot.id)}{slot.characterName?' · '+slot.characterName:''}</strong><small>{slot.mode==='sandbox'?'历史沙盒':'原有玩法'} · {scriptLabel(slot.scriptId)} · {dateLabel(slot.day,slot.scriptId)} · {new Date(slot.savedAt).toLocaleString('zh-CN')}</small></div><div className="save-row-actions"><button disabled={pending} onClick={()=>send({type:'load',slot:slot.id})}>读取</button><button disabled={pending} className="danger" onClick={()=>{if(window.confirm('删除「'+saveLabel(slot.id)+'」？此操作无法撤销，当前游玩进度不会被删除。'))send({type:'delete-save',slot:slot.id});}}>删除</button></div></article>)}</div>}</>}
    <input ref={upload} hidden type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>2_000_000){notify('存档超过 2 MB。',true);return;}try{send({type:'import',text:await file.text()});}catch{notify('无法读取文件。',true);}}}/>
    </>}{notice&&<p className={`entry-notice ${notice.error?'is-error':''}`} role={notice.error?'alert':'status'}>{notice.text}</p>}<footer>单人策略 · {accountSaves?'账号存档':'本地存档'}</footer></section></main>;
}
export function RunOutcome({world,pending,notice,send}:Pick<EntryProps,'pending'|'notice'|'send'>&{world:World}){
  const won=world.campaign?.status==='won',death=lifeOf(world,world.characterId??'fictional')?.death;return <main className="game-entry"><div className="entry-backdrop"/><section className="entry-content"><span className="eyebrow">{campaignTitle(world)} · 本局结算</span><h1>{death?'一生落幕':won?'一方家业':'未竟之志'}</h1><p className="entry-lead">{death?world.people[0].name+'已逝，享年 '+ageLabel(world,world.characterId??'fictional')+'。没有在世且合格的家业继任者，本局结束。':won?(world.characterId?world.people[0].name+'完成本局营建目标，城邑与家业渐兴。':'市肆渐兴，田庄初成。你带着一份新的家业返回建康。'):'期限已至，本局目标尚未完成。重新筹划行程与营建，再试一次。'}</p><div className="outcome-stats"><span>历时 <strong>{world.day} 日</strong></span><span>余钱 <strong>{world.people[0].coins} 钱</strong></span></div><ul className="outcome-goals">{campaignGoals(world).map(g=><li key={g.title}><span>{g.done?'已完成':'未完成'}</span>{g.title}</li>)}</ul><div className="entry-actions"><button className="primary" disabled={pending} onClick={()=>send({type:'menu'})}>保存结局并返回主菜单</button><button disabled={pending} onClick={()=>send({type:'export'})}>导出本局存档</button></div>{notice&&<p role={notice.error?'alert':'status'}>{notice.text}</p>}</section></main>;
}
export function CampaignTracker({world,onCity,onEstate,onRealm,send}:{world:World;onRealm?:()=>void;onCity:(id:string)=>void;onEstate:()=>void;send:EntryProps['send']}){
  if(world.realm){const r=playerRealm(world),t=world.realm.treasuries[r],f=realmForecast(world,r);return <section className="campaign-tracker sandbox-tracker" aria-label="沙盒局势"><header><strong>{regimeName(world,r)} · 家国经营</strong><span>第 {world.day} 日</span></header><p><Resource name="coins" value={t.coins} label="公款"/> <Resource name="grain" value={t.grain} label="公粮"/><br/>月度财政预算 {f.income-f.expense-plannedReinvestment(world,r)>=0?'+':''}{f.income-f.expense-plannedReinvestment(world,r)} 钱<br/>亲自治理 {world.holdings.governedCities.length} 城 · {realmAtWar(world,r)?'战争中':'和平'}</p><button className={world.realm.event?'realm-alert':'primary'} onClick={onRealm}>{world.realm.event?'待决事务 · 打开政务':'政务 · 财政 / 任职 / 军事'}</button>{t.grain<100&&<p>公粮不足，动员可能导致断粮。</p>}<section className="detail-record-group"><h4>经营指引</h4><p>先检查收支与税制，再安排城市建设。通过交往取得任职与军务授权；动员前储备军粮。家族庄园使用私产，交接家业不等于继承公职。</p></section></section>;}
  const goals=campaignGoals(world),first=goals.findIndex(g=>!g.done),p=world.people[0];
  const canClaim=world.campaign?.id==='jiangzuo'&&!world.campaign?.appointed&&!p.journey&&p.location==='jingkou';
  return <section className="campaign-tracker" aria-label="本局目标"><header><strong>{campaignTitle(world)}</strong><span>余 {120-world.day} 日</span></header><div className="campaign-goals"><p>{goals.filter(g=>g.done).length} / 4 已完成</p><ol>{goals.map(g=><li key={g.title} className={g.done?'done':''}>{g.done?'✓ ':''}{g.title}</li>)}</ol><p>{goals[first]?.hint}</p></div><button className="primary" onClick={()=>canClaim?send({type:'command',command:{type:'commission'}}):first===2?onEstate():onCity(world.characterId?characterById[world.social?.founder??world.characterId].home:first===3?'jiankang':'jingkou')}>{canClaim?'领取委任 · +180 钱':first===2?'前往庄园':world.characterId?'查看辖城':first===3?'规划归程':'前往京口'}</button></section>;
}
