import {CharacterPortrait} from './CharacterPortrait';
import {DetailTabs} from './DetailTabs';
import { useState } from 'react';
import { ArtIcon,Resource } from './ArtIcon';
import { governmentDefinitions,governmentTypes,reformDefinitions,reformIds } from '../data/governments';
import { governmentOf,governingExecutives,governmentReason,governmentYear,governmentBonus,governmentTaskPause,politicalName,taskName,currentRealm,type GovernmentCommand,type Contract } from '../core/government';
import { historicalCharacters } from '../data/characters';
import { siteById } from '../data/scenario';
import type { World } from '../core/types';
import './government.css';
export function GovernmentPanel({world:w,pending,send,onPerson}:{onPerson:(id:string)=>void;world:World;pending:boolean;send:(c:GovernmentCommand)=>void}){
 const [tab,setTab]=useState<'constitution'|'reforms'|'merit'|'camp'|'history'>('constitution'),[confirmation,setConfirmation]=useState<string|null>(null),[selected,setSelected]=useState(w.people[0].home);
 const g=governmentOf(w);if(!g)return <p>读取存档后可使用政体制度。</p>;
 const r=currentRealm(w),definition=governmentDefinitions[g.type],bonus=governmentBonus(w,r),cities=Object.entries(w.realm!.cities).filter(([,c])=>c.owner===r&&c.controller===r),task=g.task;
 const action=(c:GovernmentCommand,label:string,consequence?:string)=>{const reason=governmentReason(w,c),key=JSON.stringify(c);return <div className="government-action"><button className={consequence?'primary':''} disabled={pending||!!reason} onClick={()=>{if(consequence&&confirmation!==key){setConfirmation(key);return;}setConfirmation(null);send(c);}}>{confirmation===key?'确认：':''}{label}</button>{reason&&<small>{reason}</small>}{confirmation===key&&<div className="government-confirm"><p>{consequence}</p><button onClick={()=>setConfirmation(null)}>暂不执行</button></div>}</div>;};
 return <div className="government-panel"><div className="government-banner"><ArtIcon name="influence" size={48}/><div><span className="eyebrow">{governmentYear(w)} 年</span><h3>{definition.name}</h3><p>{definition.subtitle}</p></div></div>
 <div className="government-rulers"><button className="government-person" onClick={()=>onPerson(g.ruler)}><CharacterPortrait characterId={g.ruler} world={w} compact/><span><small>君主</small>{politicalName(g.ruler)}</span></button>{governingExecutives(w,r).filter(id=>id!==g.ruler).map(id=><button className="government-person" key={id} onClick={()=>onPerson(id)}><CharacterPortrait characterId={id} world={w} compact/><span><small>实际执政</small>{politicalName(id)}</span></button>)}</div>
 <div className="government-meters"><label>{g.type==='celestial'?'天命':'合法性'} <b>{g.legitimacy}</b><progress max={100} value={g.legitimacy}/></label><label>{g.type==='tribal'?'部众支持':'朝野支持'} <b>{g.support}</b><progress max={100} value={g.support}/></label></div>
 {task&&<article className="government-progress" aria-live="polite"><small>正在推进 · 发起人 {politicalName(task.sponsor)}</small><h3>{taskName(task)}</h3><progress max={task.required} value={task.progress}/><p>{task.progress} / {task.required} 有效实施日 · {governmentTaskPause(w,r)||'正在实施'}</p>{action({type:'government',action:'cancel'},'撤回议程','已付成本不退，已经产生的支持变化保留。')}</article>}
 <DetailTabs label="制度分类" value={tab} onChange={key=>{setTab(key);setConfirmation(null);}} items={[{id:'constitution',label:'政体',icon:'influence'},{id:'reforms',label:'改革',icon:'diligent'},{id:'merit',label:'考课',icon:'person'},{id:'camp',label:'宫帐',icon:'estate'},{id:'history',label:'纪事',icon:'world'}]}/>
 {tab==='constitution'&&<><article><p>{definition.description}</p><div className="government-effects"><span>税收 {bonus.tax>=0?'+':''}{bonus.tax}%</span><span>军饷 {bonus.pay>=0?'+':''}{bonus.pay}%</span><span>攻击 {bonus.attack>=0?'+':''}{bonus.attack}%</span></div><small>实际叠加已行改革；封建契约税率另按城市计算。合法性随都城、秩序与公库变化，支持随平均秩序变化。</small></article>
 <div className="government-actions">{action({type:'government',action:'council'},g.type==='tribal'?'召集部众 · 15 影响力 / 40 公款':'议政协商 · 15 影响力 / 40 公款')}</div><p className="small-note">议政：支持 +12、合法性 +5，冷却 30 日。功绩由实际治理与差事成果积累，上限 100。</p>

 {(g.type==='feudal')&&<article><h3>逐城领有契约</h3><label>城市 <select value={selected} onChange={e=>setSelected(e.target.value)}>{cities.map(([id])=><option key={id} value={id}>{siteById[id].name}</option>)}</select></label><p>当前：{({balanced:'均衡',tax:'税赋',levy:'军役'})[g.contracts[selected]??'balanced']}</p>{(['balanced','tax','levy'] as Contract[]).map(contract=><div key={contract}>{action({type:'government',action:'contract',site:selected,contract},({balanced:'均衡：无额外修正',tax:'税赋：本城税收 +20%',levy:'军役：本城税收 −15%，国家攻击 +5%'})[contract])}</div>)}<small>每次消耗影响力 10、支持 −3；同城冷却 90 日；军役攻击总计最多 +20%。领有由合格家业继任者承接。</small></article>}

 <h3>改革政体</h3><p className="small-note">改制需 160 公款、40 影响力、180 个有效实施日，启动支持 −12。战争、失都或秩序／支持不足将暂停。</p><div className="government-cards">{governmentTypes.map(type=><article key={type} className={type===g.type?'current':''}><h4><ArtIcon name={type==='nomadic'||type==='khanate'?'grain':type==='feudal'?'estate':type==='tribal'?'person':'influence'} size={27}/>{governmentDefinitions[type].name}{type===g.type?' · 当前':''}</h4><p>{governmentDefinitions[type].description}</p>{type!==g.type&&action({type:'government',action:'adopt',government:type},'拟定改制方案','将支出 160 公款、40 影响力，支持 −12；完成后全政权经济、军务及任职规则随之改变。')}</article>)}</div></>}
 {tab==='reforms'&&<>{reformIds.filter(id=>reformDefinitions[id].realm===r).map(id=>{const d=reformDefinitions[id],done=g.laws.includes(id);return <article key={id} className={done?'government-complete':''}><span className="eyebrow">{done?'已施行':d.year+' 年起'}{d.initial?' · 开局制度':''}</span><h3>{d.name}</h3><p>{d.effect}</p><small>{d.history}</small><p><a href={d.source.url} target="_blank" rel="noreferrer">{d.source.title} ↗</a></p>{!done&&action({type:'government',action:'law',law:id},`推行 · ${d.cost} 公款 / 40 影响力 / ${d.days} 日`,`支出 ${d.cost} 公款、40 影响力，支持 −12；经 ${d.days} 个有效实施日生效。`)}</article>;})}{r==='liang'&&<p>可在“政体”页推行改革，或在“朝廷 → 继承”议定君位与执政的传承。</p>}</>}
 {tab==='merit'&&<> <section><h3>功绩与任职资格 · 你的功绩 {g.merit[w.characterId!]??0}</h3><div className="government-merit">{historicalCharacters.filter(c=>c.polity===r).map(c=><button className="government-person" key={c.id} onClick={()=>onPerson(c.id)}><CharacterPortrait characterId={c.id} world={w} compact/><span>{c.name}</span><b>{g.merit[c.id]??0}</b></button>)}</div><p>官僚类任命需功绩 20；功绩 20 可请任，40 可请军务，均仍须影响力。在任且所治城市秩序达到 60，每月功绩 +2（多人多城不重复叠加）。人物好感仍是另一条请任路径。</p></section></>}
 {tab==='camp'&&<> <section><h3>畜群与宫帐准备</h3><p><Resource name="grain" value={g.herd} label="畜群"/> · 驻牧地 {siteById[g.camp].name}</p><label>迁往 <select value={selected} onChange={e=>setSelected(e.target.value)}>{cities.map(([id])=><option key={id} value={id}>{siteById[id].name}{siteById[id].lat>=38?' · 可驻牧':''}</option>)}</select></label>{action({type:'government',action:'camp',site:selected},'迁设驻牧地 · 50 公款 / 60 公粮')}{action({type:'government',action:'herd'},'购入畜群 +100 · 60 公款')}<p className="small-note">游牧／宫帐制中，冬季每月 −20 畜群，其余月份 +15；失去驻牧地每月 −40，少于 50 时支持每月额外 −4。迁营冷却 90 日，不移动城市或私产庄园。可在北纬 38° 以北的己方城市驻牧。</p></section></>}
 {tab==='history'&&<> <section><h3>近期制度记录</h3>{w.realm!.governments!.history.filter(e=>e.realm===r).slice(-12).reverse().map((e,i)=><p key={i}>第 {e.day} 日 · {e.text}</p>)}</section></>}
 </div>;
}
