import {governmentPreview} from './governmentPreview';
import {DecisionMetrics} from './DecisionPresentation';
import type {GovernmentType,ReformId} from '../data/governments';
import {afterCommand} from './actionFeedback';
import {CommandButton} from './CommandButton';
import {ConfirmAction} from './ConfirmAction';
import {useEffect,useState} from 'react';
import {ArtIcon,Resource} from './ArtIcon';
import {ActionDialog} from './ActionDialog';
import {HoverHint} from './HoverHint';
import {governmentDefinitions,governmentTypes,reformDefinitions,reformIds} from '../data/governments';
import {governmentOf,governmentReason,governmentBonus,governmentTaskPause,politicalName,taskName,currentRealm,type GovernmentCommand,type Contract} from '../core/government';
import {siteById} from '../data/scenario';
import type {RealmId} from '../core/realm';
import type {World} from '../core/types';
import './government.css';
export function GovernmentPanel({world:w,realm,compact=false,pending,send}:{world:World;realm?:RealmId;compact?:boolean;pending:boolean;send:(c:GovernmentCommand)=>Promise<boolean>}){
 const [candidate,setCandidate]=useState<GovernmentType|null>(null),[lawDraft,setLawDraft]=useState<ReformId|null>(null);
 const [confirmation,setConfirmation]=useState<string|null>(null),[selected,setSelected]=useState(w.people[0].home),[detailsOpen,setDetailsOpen]=useState(false);
 const r=realm??currentRealm(w),own=r===currentRealm(w),g=governmentOf(w,r);useEffect(()=>{setCandidate(null);setLawDraft(null);setConfirmation(null);},[r]);if(!g)return <p>读取存档后可使用政体制度。</p>;
 const definition=governmentDefinitions[g.type],bonus=governmentBonus(w,r),cities=Object.entries(w.realm!.cities).filter(([,c])=>c.owner===r&&c.controller===r),site=cities.some(([id])=>id===selected)?selected:cities[0]?.[0]??'',task=g.task,laws=reformIds.filter(id=>reformDefinitions[id].realm===r),records=w.realm!.governments!.history.filter(e=>e.realm===r).slice(-4).reverse();
 const action=(c:GovernmentCommand,label:string,consequence?:string)=>{const reason=own?governmentReason(w,c):'他国制度仅供查阅',key=JSON.stringify(c);return <div className="government-action"><CommandButton label={label} icon="influence" hint={consequence||label} pending={pending} reason={reason} onClick={()=>{setConfirmation(key);}}/>{confirmation===key&&<ConfirmAction title={label} detail={consequence??label} confirmLabel="确认执行" danger pending={pending||!!reason} onCancel={()=>setConfirmation(null)} onConfirm={()=>{if(pending||governmentReason(w,c))return;void afterCommand(send(c),()=>{setConfirmation(null);});}}/>}</div>;};
 if(compact){
  const council={type:'government',action:'council'} as const,councilReason=own?governmentReason(w,council):'他国事务仅供查阅',cancel={type:'government',action:'cancel'} as const,cancelReason=own?governmentReason(w,cancel):'他国事务仅供查阅';
  return <section className="court-government-state">
   <header className="detail-landscape detail-landscape--court"><ArtIcon name="influence" size={30}/><h3>{definition.name}</h3><HoverHint label="政体与法令" content="查阅现行政体、改革条件、契约与驻牧规则；涉及更改时单独确认。"><button className="court-icon-button" aria-label="打开政体与法令" onClick={()=>setDetailsOpen(true)}><ArtIcon name="estate" size={24}/></button></HoverHint></header>
   <HoverHint label="政体规则" content={definition.description}><div className="court-government-effects" tabIndex={0}><span>税收 {bonus.tax>=0?'+':''}{bonus.tax}%</span><span>军饷 {bonus.pay>=0?'+':''}{bonus.pay}%</span><span>攻击 {bonus.attack>=0?'+':''}{bonus.attack}%</span></div></HoverHint>
   <section className="court-current-laws"><h4>现行法令</h4>{g.laws.map(id=><HoverHint key={id} label={reformDefinitions[id].name} content={reformDefinitions[id].effect}><span tabIndex={0}>{reformDefinitions[id].name}</span></HoverHint>)}{!g.laws.length&&<p>尚无已录法令</p>}</section>
   {task&&<section className="court-policy-agenda"><h4>{taskName(task)}</h4><progress max={task.required} value={task.progress}/><small>{task.progress}/{task.required} 有效日</small><p>{governmentTaskPause(w,r)||'正在实施'}</p>{own&&<HoverHint label="撤回议程" content={cancelReason||'已付成本不退，已产生的支持变化保留。'}><button className="court-icon-button" aria-label="撤回当前议程" disabled={pending||!!cancelReason} onClick={()=>setConfirmation('compact-cancel')}><ArtIcon name="wary" size={23}/></button></HoverHint>}{confirmation==='compact-cancel'&&<ConfirmAction title="撤回议程" detail="已付成本不退，已产生的支持变化保留。" confirmLabel="确认撤回" danger pending={pending||!!cancelReason} onCancel={()=>setConfirmation(null)} onConfirm={()=>{if(pending||governmentReason(w,cancel))return;void afterCommand(send(cancel),()=>{setConfirmation(null);});}}/>}</section>}
   {own&&<div className="court-government-actions"><HoverHint label="议政协商" content={<>{councilReason||'支出 40 中央公款、15 影响力；支持 +12、合法性 +5，冷却 30 日。'}</>}><button className="court-icon-button" aria-label="议政协商" disabled={pending||!!councilReason} onClick={()=>{setConfirmation('compact-council');}}><ArtIcon name="gregarious" size={25}/></button></HoverHint></div>}
   {confirmation==='compact-council'&&<ConfirmAction title="议政协商" detail="支出 40 中央公款、15 影响力；支持 +12、合法性 +5，冷却 30 日。" confirmLabel="确认议政" pending={pending||!!councilReason} onCancel={()=>setConfirmation(null)} onConfirm={()=>{if(pending||governmentReason(w,council))return;void afterCommand(send(council),()=>setConfirmation(null));}}/>}{detailsOpen&&<ActionDialog title="政体与法令" onClose={()=>setDetailsOpen(false)} cancelLabel="返回国策" actions={null}><GovernmentPanel world={w} realm={r} pending={pending} send={send}/></ActionDialog>}
  </section>;
 }
 return <div className="government-panel">
  <section className="government-status"><header className="detail-landscape detail-landscape--court"><ArtIcon name="influence" size={32}/><div><small>现行政体</small><h3>{definition.name}</h3></div></header><p>{definition.description}</p><div className="government-effects"><span>税收 {bonus.tax>=0?'+':''}{bonus.tax}%</span><span>军饷 {bonus.pay>=0?'+':''}{bonus.pay}%</span><span>攻击 {bonus.attack>=0?'+':''}{bonus.attack}%</span></div><div className="government-meters"><label>{g.type==='celestial'?'天命':'合法性'} <b>{g.legitimacy}</b><progress max={100} value={g.legitimacy}/></label><label>{g.type==='tribal'?'部众支持':'朝野支持'} <b>{g.support}</b><progress max={100} value={g.support}/></label></div>{g.laws.length>0&&<small>已施行：{g.laws.map(id=>reformDefinitions[id].name).join('、')}</small>}</section>
  {task&&<section className="government-progress" aria-live="polite"><small>正在推进 · 发起人 {politicalName(task.sponsor,w)}</small><h3>{taskName(task)}</h3><progress max={task.required} value={task.progress}/><p>{task.progress} / {task.required} 有效实施日 · {governmentTaskPause(w,r)||'正在实施'}</p>{action({type:'government',action:'cancel'},'撤回议程','已付成本不退，已经产生的支持变化保留。')}</section>}
  <section className="government-section"><h3>朝议</h3><p>支持 +12、合法性 +5；议政冷却 30 日，消耗 15 影响力与 40 中央公款。</p>{action({type:'government',action:'council'},g.type==='tribal'?'召集部众':'议政协商','支出 40 中央公款、15 本人影响力；支持 +12、合法性 +5，冷却 30 日。')}</section>
  {laws.some(id=>!g.laws.includes(id))&&<section className="government-section"><h3>法令议案</h3><div className="government-choice-grid">{laws.filter(id=>!g.laws.includes(id)).map(id=><button key={id} aria-pressed={lawDraft===id} onClick={()=>setLawDraft(id)}><ArtIcon name="diligent" size={38}/><strong>{reformDefinitions[id].name}</strong><small>{reformDefinitions[id].year} 年起</small></button>)}</div>{lawDraft&&laws.includes(lawDraft)&&!g.laws.includes(lawDraft)&&(()=>{const d=reformDefinitions[lawDraft],next=governmentPreview(w,r,{law:lawDraft})!;return <section className="government-comparison"><header><ArtIcon name="diligent" size={40}/><h4>{d.name}</h4></header><p>{d.effect}</p><table><caption>按当前条件比较法令效果（未计启动支持 −12）</caption><thead><tr><th>修正</th><th>当前</th><th>施行后</th></tr></thead><tbody>{(['tax','pay','attack'] as const).map(key=><tr key={key}><th>{{tax:'税收',pay:'军饷',attack:'攻击'}[key]}</th><td>{bonus[key]}%</td><td>{next[key]}%</td></tr>)}</tbody></table><DecisionMetrics items={[{label:'中央公款',value:d.cost,icon:'coins'},{label:'本人影响力',value:40,icon:'influence'},{label:'有效实施日',value:d.days,icon:'world'},{label:'启动支持',value:'−12',icon:'person'}]}/>{action({type:'government',action:'law',law:lawDraft},'呈请施行',`支出 ${d.cost} 公款、40 影响力，支持 −12；经 ${d.days} 个有效实施日生效。${d.effect}`)}</section>;})()}</section>}
  <section className="government-section"><h3>改定政体</h3><div className="government-choice-grid">{governmentTypes.filter(type=>type!==g.type).map(type=><button key={type} aria-pressed={candidate===type} onClick={()=>setCandidate(type)}><ArtIcon name={type==='nomadic'||type==='khanate'?'grain':type==='feudal'?'estate':type==='tribal'?'person':'influence'} size={38}/><strong>{governmentDefinitions[type].name}</strong><small>{governmentDefinitions[type].subtitle}</small></button>)}</div>{candidate&&candidate!==g.type&&(()=>{const next=governmentPreview(w,r,{government:candidate})!;return <section className="government-comparison"><header><ArtIcon name="influence" size={40}/><h4>{definition.name} → {governmentDefinitions[candidate].name}</h4></header><p>{governmentDefinitions[candidate].description}</p><table><caption>保留当前朝局、支持与法令的效果对照</caption><thead><tr><th>修正</th><th>当前</th><th>拟议</th></tr></thead><tbody>{(['tax','pay','attack'] as const).map(key=><tr key={key}><th>{{tax:'税收',pay:'军饷',attack:'攻击'}[key]}</th><td>{bonus[key]}%</td><td>{next[key]}%</td></tr>)}</tbody></table><DecisionMetrics items={[{label:'中央公款',value:160,icon:'coins'},{label:'本人影响力',value:40,icon:'influence'},{label:'有效实施日',value:180,icon:'world'},{label:'启动支持',value:'−12',icon:'person'}]}/><small>表中未计入启动支持 −12、改制完成合法性 −5；未来朝局与地方契约变化会继续修正结果；有效日不含受阻等待。</small>{action({type:'government',action:'adopt',government:candidate},'呈请改制','将支出 160 公款、40 影响力，支持 −12；完成后全政权经济、军务及任职规则随之改变。'+governmentDefinitions[candidate].description)}</section>;})()}</section>
  {g.type==='feudal'&&site&&<section className="government-section"><h3>领有契约</h3><label>城邑 <select value={site} onChange={e=>setSelected(e.target.value)}>{cities.map(([id])=><option key={id} value={id}>{siteById[id].name}</option>)}</select></label><p>当前：{({balanced:'均衡',tax:'税赋',levy:'军役'})[g.contracts[site]??'balanced']}</p><div className="government-contracts">{(['balanced','tax','levy'] as Contract[]).map(contract=><div key={contract}>{action({type:'government',action:'contract',site,contract},({balanced:'均衡 · 无额外修正',tax:'税赋 · 本城税收 +20%',levy:'军役 · 本城税收 −15%，国家攻击 +5%'})[contract],`${siteById[site].name}调整领有契约，消耗本人影响力 10、朝野支持 −3；同城冷却 90 日。`)}</div>)}</div><small>每次调整消耗影响力 10、支持 −3；同城冷却 90 日。</small></section>}
  {(g.type==='nomadic'||g.type==='khanate'||cities.some(([id])=>siteById[id].lat>=38))&&<section className="government-section"><h3>驻牧与畜群</h3><p><Resource name="grain" value={g.herd} label="畜群"/> · 驻牧地 {siteById[g.camp].name}</p><label>迁往 <select value={site} onChange={e=>setSelected(e.target.value)}>{cities.map(([id])=><option key={id} value={id}>{siteById[id].name}{siteById[id].lat>=38?' · 可驻牧':''}</option>)}</select></label><div className="government-contracts">{action({type:'government',action:'camp',site},'迁设驻牧地 · 50 公款 / 60 公粮',`驻牧地迁至${siteById[site].name}，支出中央公款 50、公粮 60；此后畜群损益按新驻牧地计算。`)}{action({type:'government',action:'herd'},'购入畜群 +100 · 60 公款')}</div><small>冬季每月 −20 畜群，其余月份 +15；失去驻牧地每月 −40。</small></section>}
  {records.length>0&&<section className="government-records"><h3>近期制度纪事</h3>{records.map((e,i)=><p key={i}>第 {e.day} 日 · {e.text}</p>)}</section>}
 </div>;
}
