import {ConfirmAction} from './ConfirmAction';
import {useState} from 'react';
import {ArtIcon,Resource} from './ArtIcon';
import {governmentDefinitions,governmentTypes,reformDefinitions,reformIds} from '../data/governments';
import {governmentOf,governmentReason,governmentBonus,governmentTaskPause,politicalName,taskName,currentRealm,type GovernmentCommand,type Contract} from '../core/government';
import {siteById} from '../data/scenario';
import type {World} from '../core/types';
import './government.css';
export function GovernmentPanel({world:w,pending,send}:{world:World;pending:boolean;send:(c:GovernmentCommand)=>void}){
 const [confirmation,setConfirmation]=useState<string|null>(null),[selected,setSelected]=useState(w.people[0].home);
 const g=governmentOf(w);if(!g)return <p>读取存档后可使用政体制度。</p>;
 const r=currentRealm(w),definition=governmentDefinitions[g.type],bonus=governmentBonus(w,r),cities=Object.entries(w.realm!.cities).filter(([,c])=>c.owner===r&&c.controller===r),site=cities.some(([id])=>id===selected)?selected:cities[0]?.[0]??'',task=g.task,laws=reformIds.filter(id=>reformDefinitions[id].realm===r),records=w.realm!.governments!.history.filter(e=>e.realm===r).slice(-4).reverse();
 const action=(c:GovernmentCommand,label:string,consequence?:string)=>{const reason=governmentReason(w,c),key=JSON.stringify(c);return <div className="government-action"><button className={consequence?'primary':''} disabled={pending||!!reason} onClick={()=>{if(consequence)setConfirmation(key);else send(c);}}>{label}</button>{reason&&<small>{reason}</small>}{confirmation===key&&consequence&&<ConfirmAction title={label} detail={consequence} confirmLabel="确认执行" danger pending={pending||!!reason} onCancel={()=>setConfirmation(null)} onConfirm={()=>{if(pending||governmentReason(w,c))return;send(c);setConfirmation(null);}}/>}</div>;};
 return <div className="government-panel">
  <section className="government-status"><header><ArtIcon name="influence" size={32}/><div><small>现行政体</small><h3>{definition.name}</h3></div></header><p>{definition.description}</p><div className="government-effects"><span>税收 {bonus.tax>=0?'+':''}{bonus.tax}%</span><span>军饷 {bonus.pay>=0?'+':''}{bonus.pay}%</span><span>攻击 {bonus.attack>=0?'+':''}{bonus.attack}%</span></div><div className="government-meters"><label>{g.type==='celestial'?'天命':'合法性'} <b>{g.legitimacy}</b><progress max={100} value={g.legitimacy}/></label><label>{g.type==='tribal'?'部众支持':'朝野支持'} <b>{g.support}</b><progress max={100} value={g.support}/></label></div>{g.laws.length>0&&<small>已施行：{g.laws.map(id=>reformDefinitions[id].name).join('、')}</small>}</section>
  {task&&<section className="government-progress" aria-live="polite"><small>正在推进 · 发起人 {politicalName(task.sponsor)}</small><h3>{taskName(task)}</h3><progress max={task.required} value={task.progress}/><p>{task.progress} / {task.required} 有效实施日 · {governmentTaskPause(w,r)||'正在实施'}</p>{action({type:'government',action:'cancel'},'撤回议程','已付成本不退，已经产生的支持变化保留。')}</section>}
  <section className="government-section"><h3>朝议</h3><p>支持 +12、合法性 +5；议政冷却 30 日，消耗 15 影响力与 40 中央公款。</p>{action({type:'government',action:'council'},g.type==='tribal'?'召集部众':'议政协商')}</section>
  {laws.some(id=>!g.laws.includes(id))&&<section className="government-section"><h3>可推行法令</h3><div className="government-cards">{laws.filter(id=>!g.laws.includes(id)).map(id=>{const d=reformDefinitions[id];return <article key={id}><small>{d.year} 年起</small><h4><ArtIcon name="diligent" size={25}/>{d.name}</h4><p>{d.effect}</p>{action({type:'government',action:'law',law:id},`推行 · ${d.cost} 公款 / 40 影响力 / ${d.days} 日`,`支出 ${d.cost} 公款、40 影响力，支持 −12；经 ${d.days} 个有效实施日生效。`)}</article>;})}</div></section>}
  <section className="government-section"><h3>改定政体</h3><p>需 160 中央公款、40 影响力、180 个有效实施日；启动时支持 −12。</p><div className="government-cards">{governmentTypes.filter(type=>type!==g.type).map(type=><article key={type}><h4><ArtIcon name={type==='nomadic'||type==='khanate'?'grain':type==='feudal'?'estate':type==='tribal'?'person':'influence'} size={25}/>{governmentDefinitions[type].name}</h4><p>{governmentDefinitions[type].description}</p>{action({type:'government',action:'adopt',government:type},'拟定改制方案','将支出 160 公款、40 影响力，支持 −12；完成后全政权经济、军务及任职规则随之改变。')}</article>)}</div></section>
  {g.type==='feudal'&&site&&<section className="government-section"><h3>领有契约</h3><label>城邑 <select value={site} onChange={e=>setSelected(e.target.value)}>{cities.map(([id])=><option key={id} value={id}>{siteById[id].name}</option>)}</select></label><p>当前：{({balanced:'均衡',tax:'税赋',levy:'军役'})[g.contracts[site]??'balanced']}</p><div className="government-contracts">{(['balanced','tax','levy'] as Contract[]).map(contract=><div key={contract}>{action({type:'government',action:'contract',site,contract},({balanced:'均衡 · 无额外修正',tax:'税赋 · 本城税收 +20%',levy:'军役 · 本城税收 −15%，国家攻击 +5%'})[contract])}</div>)}</div><small>每次调整消耗影响力 10、支持 −3；同城冷却 90 日。</small></section>}
  {(g.type==='nomadic'||g.type==='khanate'||cities.some(([id])=>siteById[id].lat>=38))&&<section className="government-section"><h3>驻牧与畜群</h3><p><Resource name="grain" value={g.herd} label="畜群"/> · 驻牧地 {siteById[g.camp].name}</p><label>迁往 <select value={site} onChange={e=>setSelected(e.target.value)}>{cities.map(([id])=><option key={id} value={id}>{siteById[id].name}{siteById[id].lat>=38?' · 可驻牧':''}</option>)}</select></label><div className="government-contracts">{action({type:'government',action:'camp',site},'迁设驻牧地 · 50 公款 / 60 公粮')}{action({type:'government',action:'herd'},'购入畜群 +100 · 60 公款')}</div><small>冬季每月 −20 畜群，其余月份 +15；失去驻牧地每月 −40。</small></section>}
  {records.length>0&&<section className="government-records"><h3>近期制度纪事</h3>{records.map((e,i)=><p key={i}>第 {e.day} 日 · {e.text}</p>)}</section>}
 </div>;
}
