import {cloneElement,isValidElement,useEffect,useId,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
function hasVisibleText(node:ReactNode):boolean{if(typeof node==='string'||typeof node==='number')return String(node).trim().length>0;if(Array.isArray(node))return node.some(hasVisibleText);return isValidElement<{children?:ReactNode}>(node)&&hasVisibleText(node.props.children);}
export function HoverHint({children,content,label}:{children:ReactNode;content:ReactNode;label:string}){
 const id=useId(),anchor=useRef<HTMLSpanElement>(null),tip=useRef<HTMLDivElement>(null),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),[open,setOpen]=useState(false),[pinned,setPinned]=useState(false),[position,setPosition]=useState({left:12,top:12,width:320,maxHeight:320});
 const keep=()=>{clearTimeout(timer.current);setOpen(true);},leave=()=>{clearTimeout(timer.current);if(!pinned)timer.current=setTimeout(()=>setOpen(false),180);},close=()=>{clearTimeout(timer.current);if(tip.current?.contains(document.activeElement)){const target=anchor.current?.querySelector<HTMLElement>('button:not(:disabled),a,input,select,[tabindex="0"]')??anchor.current;target?.focus({preventScroll:true});}setPinned(false);setOpen(false);};
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 useLayoutEffect(()=>{if(!open||!anchor.current||!tip.current)return;const b=anchor.current.getBoundingClientRect(),width=Math.min(340,window.innerWidth-24),height=Math.min(tip.current.scrollHeight,window.innerHeight-24),right=window.innerWidth-b.right-12,left=b.left-12,below=window.innerHeight-b.bottom-12,above=b.top-12;let x=b.left,y=b.bottom+8,maxHeight=height;if(right>=width+8){x=b.right+8;y=b.top;}else if(left>=width+8){x=b.left-width-8;y=b.top;}else if(below>=height+8){y=b.bottom+8;}else if(above>=height+8){y=b.top-height-8;}else if(below>=above){y=b.bottom+8;maxHeight=Math.max(60,below-8);}else{maxHeight=Math.max(60,above-8);y=12;}setPosition({width,left:Math.max(12,Math.min(x,window.innerWidth-width-12)),top:Math.max(12,Math.min(y,window.innerHeight-maxHeight-12)),maxHeight});},[open,content,pinned]);
 useEffect(()=>{if(!open)return;const scroll=(e:Event)=>{if(!pinned&&!tip.current?.contains(e.target as Node))close();},outside=(e:Event)=>{if(!anchor.current?.contains(e.target as Node)&&!tip.current?.contains(e.target as Node))close();},escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();}};window.addEventListener('scroll',scroll,true);window.addEventListener('resize',close);window.addEventListener('pointerdown',outside,true);window.addEventListener('keydown',escape,true);return()=>{window.removeEventListener('scroll',scroll,true);window.removeEventListener('resize',close);window.removeEventListener('pointerdown',outside,true);window.removeEventListener('keydown',escape,true);};},[open,pinned]);
 const child=isValidElement<{children?:ReactNode;'aria-label'?:string;'aria-describedby'?:string;disabled?:boolean}>(children)?children:null,interactive=!!child&&typeof child.type==='string'&&['button','a','input','select','textarea','summary'].includes(child.type),focusable=interactive&&!child?.props.disabled,describedBy=[child?.props['aria-describedby'],open?id:null].filter(Boolean).join(' ')||undefined;
 const trigger=interactive&&child?cloneElement(child,{'aria-label':child.props['aria-label']??(hasVisibleText(child.props.children)?undefined:label),'aria-describedby':describedBy}):children;
 return <span ref={anchor} className="hover-hint" tabIndex={focusable?undefined:0} aria-label={focusable?undefined:label} aria-disabled={interactive&&child?.props.disabled||undefined} aria-describedby={!focusable&&open?id:undefined} onMouseEnter={keep} onMouseLeave={leave} onFocus={keep} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null)&&!tip.current?.contains(e.relatedTarget as Node|null))leave();}} onKeyDown={e=>{if(e.key==='F2'){e.preventDefault();setPinned(true);setOpen(true);requestAnimationFrame(()=>tip.current?.focus());}}}>{trigger}{open&&createPortal(<div ref={tip} id={id} role={pinned?'region':'tooltip'} aria-label={pinned?label+'说明':undefined} tabIndex={pinned?0:undefined} className={'diplomacy-tooltip game-hint'+(pinned?' is-pinned':'')} style={{...position,pointerEvents:'auto',overflowY:'auto'}} onMouseEnter={keep} onMouseLeave={leave} onFocus={keep} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))leave();}}><div className="hint-copy">{content}</div><button type="button" className="hint-pin-button" aria-label={pinned?'关闭固定说明':'固定说明'} aria-keyshortcuts="F2" title={pinned?'关闭说明 · Escape':'固定说明 · F2'} aria-pressed={pinned} onClick={()=>{if(pinned)close();else{setPinned(true);requestAnimationFrame(()=>tip.current?.focus());}}}><svg viewBox="0 0 24 24" aria-hidden="true">{pinned?<path d="m6 6 12 12M6 18 18 6"/>:<path d="m9 3 6 0-1 6 4 4H6l4-4ZM12 13v8"/>}</svg></button></div>,anchor.current?.closest('dialog')??document.body)}</span>;
}
