import type {ReactNode} from 'react';
import {LifestyleGlyph} from './LifestyleGlyph';
import {branchPerks,branchFocuses,lifestylePerks,lifestyleFocuses,type LifestyleBranch} from '../data/lifestyles';
import {lifestyleReason,lifestyleBeneficiaries,lifestyleQueue,lifestyleProgress} from '../core/lifestyle';
import type {World} from '../core/types';
export function LifestyleTree({world,branch,owned,pending,selection,onSelect,auto,onAuto,onPrioritize,priorityDraft,focusChoices,focusDraft}:{world:World;branch:LifestyleBranch;owned:string[];pending:boolean;selection:string;onSelect:(id:string)=>void;auto:boolean;onAuto:(value:boolean)=>void;onPrioritize:(id:string)=>void;priorityDraft?:string;focusChoices:ReactNode;focusDraft?:string|null}){
 const perks=branchPerks(branch),selected=perks.find(([id])=>id===selection)??perks[0],id=selected[0],perk=selected[1],reason=lifestyleReason(world,{type:'lifestyle',action:'unlock',perk:id}),beneficiaries=lifestyleBeneficiaries(world,id),p=lifestyleProgress(world),queue=lifestyleQueue(world,branch,undefined,priorityDraft,focusDraft?lifestyleFocuses[focusDraft].scope:undefined),remaining=360-(p?.xp[branch]??0)%360;
 const indexes={common:0,public:0,private:0},nodes=perks.map(([key,entry])=>{const n=indexes[entry.scope]++;return {id:key,perk:entry,x:entry.scope==='common'?41.5+n*17.5:(entry.scope==='public'?12:59)+n%3*14.5,y:entry.scope==='common'?7:43+Math.floor(n/3)*21};}),byId=new Map(nodes.map(n=>[n.id,n]));
 const condition=perk.scope==='common'?'本人承担对应事务':branch==='stewardship'?perk.scope==='public'?'实际承担地方治理或公务':'本人所有且可经营的庄园':branch==='diplomacy'?perk.scope==='public'?'实际奉使，具备国家授权':'本人交往与家族事务':branch==='martial'?perk.scope==='public'?'实际统率对应公军':'自有私军、实际统率或私人供养':perk.scope==='public'?'实际辅政职责与有效保护':'本人发起或本人自保';
 return <section className="lifestyle-arbor"><div className="lifestyle-study-field">{focusChoices}<div className="lifestyle-arbor-scene" aria-label="公私修习图，连线表示实际前置">
 <svg className="lifestyle-connections" viewBox="0 0 1000 460" preserveAspectRatio="none" aria-hidden="true">{nodes.flatMap(n=>n.perk.requires.map(req=>{const parent=byId.get(req);if(!parent)return null;const x=parent.x*10,y=parent.y*4.6+34,x2=n.x*10,y2=n.y*4.6-34;return <path key={req+':'+n.id} className={owned.includes(req)?'is-owned':''} d={`M ${x} ${y} V ${(y+y2)/2} H ${x2} V ${y2}`}/>;}))}</svg>
 {branchFocuses(branch).map(([key,f])=><span key={key} className={'lifestyle-path-label '+f.scope}>{f.name}</span>)}
 {nodes.map(n=>{const why=lifestyleReason(world,{type:'lifestyle',action:'unlock',perk:n.id}),learned=owned.includes(n.id);return <button key={n.id} type="button" className={'lifestyle-tree-node '+(learned?'is-owned':!why?'is-ready':'is-locked')} style={{left:n.x+'%',top:n.y+'%'}} aria-pressed={id===n.id} aria-label={n.perk.name+'，'+(learned?'已掌握':why||'可学习，消耗 1 点')} title={n.perk.effect+'；'+(learned?'已掌握':why||'可学习')} onClick={()=>onSelect(n.id)}><span className="lifestyle-node-seal"><LifestyleGlyph perk={n.id} size={52}/>{learned&&<i aria-hidden="true">✓</i>}</span><strong>{n.perk.name}</strong></button>;})}
 </div></div><aside className={'lifestyle-node-detail'+(perk.effect.length>=18?' has-long-effect':'')} aria-live="polite"><header><span className="lifestyle-detail-seal"><LifestyleGlyph perk={id} size={64}/></span><div><h4>{perk.name}</h4><small tabIndex={0} title={perk.requires.length?'前置：'+perk.requires.map(key=>lifestylePerks[key].name).join('、'):'无前置，可直接学习'}>{perk.scope==='common'?'通用':perk.scope==='public'?'公向':'私向'} · {perk.mastery?'专长':perk.tier===0?'入门':perk.tier===1?'熟练':'精通'}</small><p className="lifestyle-availability">{owned.includes(id)?'已掌握':reason||'可修习，消耗本类 1 点'}</p></div></header><p className="lifestyle-selected-effect">{perk.effect.split(/([+-]\d+%?)/g).map((part,index)=>/^[+-]\d/.test(part)?<b key={index} className="lifestyle-effect-value">{part}</b>:part)}</p><dl className="lifestyle-effect-target"><dt>作用对象</dt><dd>{beneficiaries.length?beneficiaries.join('、'):'目前暂无适用对象'}</dd><dt>生效条件</dt><dd>{condition}</dd></dl>
 <section className="lifestyle-plan"><h5>学习安排</h5><label><input type="checkbox" checked={auto} disabled={pending||!p?.focus} onChange={e=>onAuto(e.target.checked)}/>有技能点时自动学习</label><dl className="lifestyle-plan-facts" tabIndex={0} title={`${p?.xp[branch]??0} 累计经验 · ${Math.floor((p?.xp[branch]??0)/360)-owned.filter(key=>lifestylePerks[key].branch===branch).length} 点可用；持续投入本类的预估。`}><dt>下一技能</dt><dd>{queue.length?lifestylePerks[queue[0]].name:'本类已学完'}</dd><dt>下一点预计</dt><dd>{(p?.xp[branch]??0)>=7200?'经验已满':queue.length?`${Math.ceil(remaining/22)}–${Math.ceil(remaining/18)} 个月`:'已完成'}</dd></dl><p className="lifestyle-queue-title">学习队列</p><ol>{queue.slice(0,3).map(key=><li key={key}>{lifestylePerks[key].name}</li>)}</ol><button type="button" title={owned.includes(id)?'已经掌握此项':!p?.focus?'先确认生活重心':'设置优先目标，自动补齐前置；底部确认后生效'} disabled={pending||owned.includes(id)||!p?.focus} onClick={()=>onPrioritize(id)}>优先学习此项</button></section>
 </aside><span className="lifestyle-margin-motto" aria-hidden="true">江山犹在　百姓为本</span></section>;
}
