import {ActionDialog} from './ActionDialog';
import {LifestyleTree} from './LifestyleTree';
import {HoverHint} from './HoverHint';
import {useState} from 'react';
import {ArtIcon} from './ArtIcon';
import {LifestyleGlyph} from './LifestyleGlyph';
import {lifestyleBranches,lifestyleFocuses,lifestylePerks,branchPerks,branchFocuses,LIFESTYLE_SWITCH_DAYS,type LifestyleBranch} from '../data/lifestyles';
import {lifestyleProgress,lifestyleLearning,lifestylePoints,lifestyleReason,lifestyleMasteries,lifestylePerson,freshLifestyle,type LifestyleCommand} from '../core/lifestyle';
import type {World} from '../core/types';
import './lifestyle.css';
export function LifestyleMasteryBadges({world,id}:{world:World;id?:string}){
 const masteries=lifestyleMasteries(world,id);return masteries.length?<div className="lifestyle-masteries" aria-label="后天生活专长">{masteries.map(p=><HoverHint key={p.name} label={p.name} content={<><strong>{p.name}</strong><p>{p.effect}</p></>}><span className="trait-badge trait-icon-only"><ArtIcon name={lifestyleBranches[p.branch].icon} size={30}/></span></HoverHint>)}</div>:null;
}
export function LifestylePanel({world:w,pending,send}:{world:World;pending:boolean;send:(c:LifestyleCommand)=>void}){
 const progress=lifestyleProgress(w)??freshLifestyle(w.day),current=progress.focus?lifestyleFocuses[progress.focus]:null,[expanded,setExpanded]=useState(false);
 return <div className="lifestyle-panel"><section className="lifestyle-current"><ArtIcon name={current?lifestyleBranches[current.branch].icon:'person'} size={42}/><div><small>{w.people[0].name} · 当前生活重心</small><h3>{current?`${lifestyleBranches[current.branch].name} · ${current.name}`:'选择此生所长'}</h3><p>{current?current.effect:'初次选择获得本类 1 点入门技能点'}</p></div></section><LifestyleMasteryBadges world={w}/><button className="lifestyle-scene-entry" onClick={()=>setExpanded(true)}><span><strong>生活重心</strong><small>{current?'公私兼修 · 查看成长与学习安排':'选择公私方向 · 预览后确认'}</small></span><ArtIcon name="diligent" size={34}/></button>{expanded&&<LifestyleDialog key={lifestylePerson(w)} world={w} pending={pending} send={send} onClose={()=>setExpanded(false)} cancelLabel="返回人物"/>}</div>;
}
export function LifestyleDialog({world:w,pending,send,onClose,initialBranch,cancelLabel='返回地图'}:{world:World;pending:boolean;send:(c:LifestyleCommand)=>void;onClose:()=>void;initialBranch?:LifestyleBranch;cancelLabel?:string}){
 const progress=lifestyleProgress(w)??freshLifestyle(w.day),current=progress.focus?lifestyleFocuses[progress.focus]:null;
 const [branch,setBranch]=useState<LifestyleBranch>(initialBranch??current?.branch??'stewardship'),[focusDraft,setFocusDraft]=useState<string|null>(current?null:branchFocuses(initialBranch??'stewardship')[0][0]),[selection,setSelection]=useState(''),[planDraft,setPlanDraft]=useState<{auto?:boolean;perk?:string}|null>(null);
 const info=lifestyleBranches[branch],learning=lifestyleLearning(w),selected=branchPerks(branch).find(([id])=>id===selection)??branchPerks(branch).find(([,p])=>p.scope==='public'&&!p.requires.length)??branchPerks(branch)[0],learned=progress.perks.filter(key=>lifestylePerks[key].branch===branch).length;
 const command:LifestyleCommand=focusDraft?{type:'lifestyle',action:'focus',focus:focusDraft}:planDraft?{type:'lifestyle',action:'plan',...planDraft}:{type:'lifestyle',action:'unlock',perk:selected[0]},reason=lifestyleReason(w,command);
 const action=focusDraft?'确认重心':planDraft?'确认学习安排':progress.perks.includes(selected[0])?'已掌握':'确认修习';
 const preview=focusDraft?`已学技能保留 · 更换重心冷却 ${LIFESTYLE_SWITCH_DAYS} 日`:planDraft?planDraft.perk?`优先学习「${lifestylePerks[planDraft.perk].name}」，先补前置`:`${planDraft.auto?'启用':'暂停'}自动学习，已学技能保留`:`已学技能保留 · ${current&&!progress.reselect&&Math.max(0,progress.changed+LIFESTYLE_SWITCH_DAYS-w.day)?'更换冷却 '+Math.max(0,progress.changed+LIFESTYLE_SWITCH_DAYS-w.day)+' 日':'可更换重心'}`;
 return <ActionDialog title={w.people[0].name+' · 生活重心'} className="lifestyle-tree-dialog" scene="landscape" cancelLabel={cancelLabel} onClose={onClose} actions={<><span className="lifestyle-confirm-preview" role="status" title={reason||'确认后按真实人物状态结算'}>{preview}{reason&&(!focusDraft||focusDraft!==progress.focus)?' · '+reason:''}</span><button className="primary" title={reason||'按当前状态复核并确认'} disabled={pending||!!reason} onClick={()=>{if(pending||lifestyleReason(w,command))return;send(command);setFocusDraft(null);setPlanDraft(null);}}>{action}</button></>}>
 <div className="lifestyle-scene-toolbar"><nav className="lifestyle-branches" aria-label="生活分类">{(Object.entries(lifestyleBranches) as [LifestyleBranch,typeof info][]).map(([key,b])=><button key={key} type="button" aria-pressed={branch===key} title={`${b.name} · ${lifestylePoints(progress,key)} 点可用`} onClick={()=>{setBranch(key);setSelection('');setFocusDraft(current?null:branchFocuses(key)[0][0]);setPlanDraft(null);}}><LifestyleGlyph branch={key} size={40}/><span>{b.name}</span></button>)}</nav><HoverHint label="月度经验来源" content={`基础每月 18；性格、勤勉与指导合计最多 +2，真实实践最多 +2。当前月速 ${learning.total}，实践 ${learning.practice}；按实际投入天数结算。${current?'当前重心「'+current.name+'」。':'尚未选择重心，底部确认后生效。'}`}><div className="lifestyle-scene-summary" tabIndex={0}><strong>{info.name}修习 {learned} / 20</strong><span>月经验 18–22</span></div></HoverHint></div>
 <LifestyleTree key={branch} world={w} branch={branch} owned={progress.perks} pending={pending} selection={selected[0]} onSelect={id=>setSelection(id)} auto={planDraft?.auto??progress.auto!==false} onAuto={auto=>{setFocusDraft(null);setPlanDraft({auto});}} onPrioritize={perk=>{setFocusDraft(null);setPlanDraft({perk});}} priorityDraft={planDraft?.perk} focusDraft={focusDraft} focusChoices={<fieldset className="lifestyle-focus-choice"><legend className="sr-only">选择重心，在底部确认</legend>{branchFocuses(branch).map(([id,f])=><label className={f.scope} key={id}><input type="radio" name="lifestyle-focus" checked={(focusDraft??progress.focus)===id} disabled={pending} onChange={()=>{setFocusDraft(id);setPlanDraft(null);setSelection(branchPerks(branch).find(([,p])=>p.scope===f.scope&&!p.requires.length)![0]);}}/><span><strong><em>{f.scope==='public'?'公':'私'}</em>{f.name}</strong><small className="lifestyle-focus-intent">{f.scope==='public'?'立朝行道，经世安民。':'桑梓可耕，家业长固。'}</small><small className="lifestyle-focus-benefit">{f.effect}</small></span></label>)}</fieldset>}/>
 </ActionDialog>;
}
