import {ActionDialog} from './ActionDialog';
import {LifestyleTree} from './LifestyleTree';
import {HoverHint} from './HoverHint';
import {useState} from 'react';
import {ArtIcon} from './ArtIcon';
import {lifestyleBranches,lifestyleFocuses,branchPerks,LIFESTYLE_XP_PER_POINT,LIFESTYLE_SWITCH_DAYS,type LifestyleBranch} from '../data/lifestyles';
import {lifestyleProgress,lifestyleLearning,lifestyleStudyXP,lifestylePoints,lifestyleReason,lifestyleMasteries,freshLifestyle,type LifestyleCommand} from '../core/lifestyle';
import type {World} from '../core/types';
import './lifestyle.css';
export function LifestyleMasteryBadges({world,id}:{world:World;id?:string}){
 const masteries=lifestyleMasteries(world,id);return masteries.length?<div className="lifestyle-masteries" aria-label="后天生活专长">{masteries.map(p=><HoverHint key={p.name} label={p.name} content={<><strong>{p.name}</strong><p>{p.effect}</p></>}><span className="trait-badge trait-icon-only"><ArtIcon name={lifestyleBranches[p.branch].icon} size={30}/></span></HoverHint>)}</div>:null;
}
export function LifestylePanel({world:w,pending,send}:{world:World;pending:boolean;send:(c:LifestyleCommand)=>void}){
 const progress=lifestyleProgress(w)??freshLifestyle(w.day),current=progress.focus?lifestyleFocuses[progress.focus]:null;
 const [branch,setBranch]=useState<LifestyleBranch>(current?.branch??'stewardship'),[expanded,setExpanded]=useState(false),[focusDraft,setFocusDraft]=useState<string|null>(null);
 const info=lifestyleBranches[branch],learning=lifestyleLearning(w),points=lifestylePoints(progress,branch),cap=branchPerks(branch).length*LIFESTYLE_XP_PER_POINT,ready=progress.study;
 const focusCommand:LifestyleCommand={type:'lifestyle',action:'focus',focus:focusDraft??''},focusReason=focusDraft?lifestyleReason(w,focusCommand):'请选择重心';
 return <div className="lifestyle-panel"><section className="lifestyle-current"><ArtIcon name={current?lifestyleBranches[current.branch].icon:'person'} size={42}/><div><small>{w.people[0].name} · 当前生活重心</small><h3>{current?`${lifestyleBranches[current.branch].name} · ${current.name}`:'选择此生所长'}</h3><p>{current?current.effect:'初次选择获得该路线 1 点入门技能点'}</p></div></section><LifestyleMasteryBadges world={w}/><button className="lifestyle-scene-entry" onClick={()=>setExpanded(true)}><span><strong>生活重心</strong><small>{ready?'有待处理的研习抉择':'查看修习图 · 调整重心'}</small></span><ArtIcon name="diligent" size={34}/></button>
 {expanded&&<ActionDialog title="生活重心" className="lifestyle-tree-dialog" cancelLabel="返回人物" onClose={()=>{setFocusDraft(null);setExpanded(false);}} actions={<button onClick={()=>setFocusDraft(progress.focus??Object.keys(lifestyleFocuses).find(id=>lifestyleFocuses[id].branch===branch)!)}>调整重心</button>}>
 <div className="lifestyle-scene-toolbar"><nav className="lifestyle-branches detail-tabs" aria-label="生活路线">{(Object.entries(lifestyleBranches) as [LifestyleBranch,typeof info][]).map(([key,b])=><button key={key} aria-pressed={branch===key} onClick={()=>setBranch(key)}><ArtIcon name={b.icon} size={25}/><span>{b.name}</span><small>{lifestylePoints(progress,key)} 点</small></button>)}</nav><div className="lifestyle-scene-summary"><strong>{points} 可用技能点</strong><span>{progress.xp[branch]} / {cap} 经验</span><small>每 {LIFESTYLE_XP_PER_POINT} 经验获得 1 点</small></div></div>
 <div className="lifestyle-scene-status"><span>当前：{current?current.name:'尚未选择重心'}</span>{current&&<HoverHint label="每日经验来源" content={`基础 3${learning.affinity?' · 性格契合 +1':''}${learning.diligent?' · 勤勉 +1':''}${learning.stress?' · 高压力 -1':''}；经验按当前路线随游戏日推进。`}><span tabIndex={0}>{progress.xp[current.branch]>=branchPerks(current.branch).length*LIFESTYLE_XP_PER_POINT?'当前路线经验已满':`每日 +${learning.total} 经验`}</span></HoverHint>}<span>{current&&Math.max(0,progress.changed+LIFESTYLE_SWITCH_DAYS-w.day)?`更换冷却 ${progress.changed+LIFESTYLE_SWITCH_DAYS-w.day} 日`:'可调整重心'}</span></div>
 {ready&&<section className="lifestyle-study"><strong>研习抉择 · {lifestyleBranches[ready.branch].name}</strong>{(['practice','rest'] as const).map(choice=>{const c:LifestyleCommand={type:'lifestyle',action:'study',choice},reason=lifestyleReason(w,c);return <HoverHint key={choice} label={choice==='practice'?'潜心研习':'休整'} content={reason||'按当前状态结算，不消耗技能点。'}><button disabled={pending||!!reason} onClick={()=>{if(pending||lifestyleReason(w,c))return;send(c);}}>{choice==='practice'?`研习 · 经验 +${lifestyleStudyXP(w)}${w.social?' / 压力 +8':''}`:w.social?'休整 · 压力 -8':'暂歇'}</button></HoverHint>;})}</section>}
 <LifestyleTree key={branch} world={w} branch={branch} owned={progress.perks} pending={pending} send={send}/>
 <p className="lifestyle-boundary">已学技能更换重心后保留；继任者使用自己的成长记录。军事及公款／公粮效果需历史沙盒，军务加成需授权，税粮加成仅作用于亲治城市；新工程加成不追改在建工程。</p>
 </ActionDialog>}
 {focusDraft!==null&&<ActionDialog title="调整生活重心" onClose={()=>setFocusDraft(null)} actions={<button className="primary" disabled={pending||!!focusReason} onClick={()=>{if(pending||lifestyleReason(w,focusCommand))return;send(focusCommand);setFocusDraft(null);}}>确认重心</button>}><p>选择只作预览；确认后开始积累对应路线经验。已学技能保留，更换后冷却 {LIFESTYLE_SWITCH_DAYS} 日。</p><div className="lifestyle-focus-choice">{Object.entries(lifestyleBranches).map(([key,b])=><fieldset key={key}><legend>{b.name}</legend>{Object.entries(lifestyleFocuses).filter(([,f])=>f.branch===key).map(([id,f])=><label key={id}><input type="radio" name="lifestyle-focus" checked={focusDraft===id} disabled={pending} onChange={()=>setFocusDraft(id)}/><span><strong>{f.name}</strong><small>{f.effect}</small></span></label>)}</fieldset>)}</div><p role="status">{focusReason||'可确认 · '+lifestyleFocuses[focusDraft].effect}</p></ActionDialog>}
 </div>;
}
