import {ActionDialog} from './ActionDialog';
import {LifestyleTree} from './LifestyleTree';
import {HoverHint} from './HoverHint';
import {useState} from 'react';
import {ArtIcon} from './ArtIcon';
import {lifestyleBranches,lifestyleFocuses,lifestylePerks,branchPerks,branchFocuses,LIFESTYLE_XP_PER_POINT,LIFESTYLE_SWITCH_DAYS,type LifestyleBranch} from '../data/lifestyles';
import {lifestyleProgress,lifestyleLearning,lifestylePoints,lifestyleReason,lifestyleMasteries,lifestylePerson,freshLifestyle,lifestyleQueue,type LifestyleCommand} from '../core/lifestyle';
import type {World} from '../core/types';
import './lifestyle.css';
export function LifestyleMasteryBadges({world,id}:{world:World;id?:string}){
 const masteries=lifestyleMasteries(world,id);return masteries.length?<div className="lifestyle-masteries" aria-label="后天生活专长">{masteries.map(p=><HoverHint key={p.name} label={p.name} content={<><strong>{p.name}</strong><p>{p.effect}</p></>}><span className="trait-badge trait-icon-only"><ArtIcon name={lifestyleBranches[p.branch].icon} size={30}/></span></HoverHint>)}</div>:null;
}
export function LifestylePanel({world:w,pending,send}:{world:World;pending:boolean;send:(c:LifestyleCommand)=>void}){
 const progress=lifestyleProgress(w)??freshLifestyle(w.day),current=progress.focus?lifestyleFocuses[progress.focus]:null,[expanded,setExpanded]=useState(false);
 return <div className="lifestyle-panel"><section className="lifestyle-current"><ArtIcon name={current?lifestyleBranches[current.branch].icon:'person'} size={42}/><div><small>{w.people[0].name} · 当前生活重心</small><h3>{current?`${lifestyleBranches[current.branch].name} · ${current.name}`:'选择此生所长'}</h3><p>{current?current.effect:'初次选择获得本类 1 点入门技能点'}</p></div></section><LifestyleMasteryBadges world={w}/><button className="lifestyle-scene-entry" onClick={()=>setExpanded(true)}><span><strong>生活重心</strong><small>{current?'公私兼修 · 查看成长与学习安排':'选择公私方向 · 预览后确认'}</small></span><ArtIcon name="diligent" size={34}/></button>{expanded&&<LifestyleDialog key={lifestylePerson(w)} world={w} pending={pending} send={send} onClose={()=>setExpanded(false)} cancelLabel="返回人物"/>}</div>;
}
export function LifestyleDialog({world:w,pending,send,onClose,initialBranch,cancelLabel='返回地图'}:{world:World;pending:boolean;send:(c:LifestyleCommand)=>void;onClose:()=>void;initialBranch?:LifestyleBranch;cancelLabel?:string}){
 const progress=lifestyleProgress(w)??freshLifestyle(w.day),current=progress.focus?lifestyleFocuses[progress.focus]:null;
 const [branch,setBranch]=useState<LifestyleBranch>(initialBranch??current?.branch??'stewardship'),[focusDraft,setFocusDraft]=useState<string|null>(null),[selection,setSelection]=useState(''),[planDraft,setPlanDraft]=useState<{auto?:boolean;perk?:string}|null>(null);
 const info=lifestyleBranches[branch],learning=lifestyleLearning(w),points=lifestylePoints(progress,branch),selected=branchPerks(branch).find(([id])=>id===selection)??branchPerks(branch)[0],learned=progress.perks.filter(key=>lifestylePerks[key].branch===branch).length,queue=lifestyleQueue(w,branch);
 const command:LifestyleCommand=focusDraft?{type:'lifestyle',action:'focus',focus:focusDraft}:planDraft?{type:'lifestyle',action:'plan',...planDraft}:{type:'lifestyle',action:'unlock',perk:selected[0]},reason=lifestyleReason(w,command);
 const action=focusDraft?'确认重心':planDraft?'确认学习安排':progress.perks.includes(selected[0])?'已掌握':'确认修习';
 const preview=focusDraft?`选择「${lifestyleFocuses[focusDraft].name}」 · ${lifestyleFocuses[focusDraft].effect}`:planDraft?planDraft.perk?`优先学习「${lifestylePerks[planDraft.perk].name}」，先补前置`:`${planDraft.auto?'启用':'暂停'}自动学习，已学技能保留`:`${selected[1].name} · ${reason||'消耗本类 1 点技能点'}`;
 return <ActionDialog title={w.people[0].name+' · 生活重心'} className="lifestyle-tree-dialog" scene="landscape" cancelLabel={cancelLabel} onClose={onClose} actions={<><span className="lifestyle-confirm-preview" role="status">{preview}{focusDraft&&reason?' · '+reason:''}</span><button className="primary" title={reason||'按当前状态复核并确认'} disabled={pending||!!reason} onClick={()=>{if(pending||lifestyleReason(w,command))return;send(command);setFocusDraft(null);setPlanDraft(null);}}>{action}</button></>}>
 <div className="lifestyle-scene-toolbar"><nav className="lifestyle-branches detail-tabs" aria-label="生活分类">{(Object.entries(lifestyleBranches) as [LifestyleBranch,typeof info][]).map(([key,b])=><button key={key} type="button" aria-pressed={branch===key} onClick={()=>{setBranch(key);setSelection('');setFocusDraft(null);setPlanDraft(null);}}><ArtIcon name={b.icon} size={25}/><span>{b.name}</span><small>{lifestylePoints(progress,key)} 点</small></button>)}</nav><div className="lifestyle-scene-summary"><strong>{info.name}修习 {learned} / 20 · {points} 点可用</strong><span>{progress.xp[branch]>=20*LIFESTYLE_XP_PER_POINT?'本类经验已满':`距下一点 ${progress.xp[branch]%LIFESTYLE_XP_PER_POINT} / ${LIFESTYLE_XP_PER_POINT} 经验`}</span><progress max={LIFESTYLE_XP_PER_POINT} value={progress.xp[branch]>=20*LIFESTYLE_XP_PER_POINT?LIFESTYLE_XP_PER_POINT:progress.xp[branch]%LIFESTYLE_XP_PER_POINT} aria-label="距下一个技能点的经验"/></div></div>
 <div className="lifestyle-scene-status"><span>当前：{current?.name??'尚未选择'}{progress.reselect?' · 旧档可重选一次':''}</span><HoverHint label="月度经验来源" content={`基础每月 18；性格、勤勉与指导合计最多 +2；完成相关实践最多 +2；全部来源合计最多 22。按实际投入天数积累，在下月结算；高压力暂停额外研习。`}><span tabIndex={0}>{current?`月度成长 ${learning.total} + 实践 ${learning.practice} / 上限 22`:'每类共享经验，公私可兼修'}</span></HoverHint><span>{current&&!progress.reselect&&Math.max(0,progress.changed+LIFESTYLE_SWITCH_DAYS-w.day)?`更换冷却 ${progress.changed+LIFESTYLE_SWITCH_DAYS-w.day} 日`:'可选择重心'} · 已学技能保留</span></div>
 <fieldset className="lifestyle-focus-choice"><legend className="sr-only">选择重心，在底部确认</legend>{branchFocuses(branch).map(([id,f])=><label className={f.scope} key={id}><input type="radio" name="lifestyle-focus" checked={(focusDraft??progress.focus)===id} disabled={pending} onChange={()=>{setFocusDraft(id);setPlanDraft(null);}}/><span><strong><em>{f.scope==='public'?'公':'私'}</em>{f.name}{progress.focus===id?' ✓':''}</strong><small>{f.effect}</small></span></label>)}</fieldset>
 <LifestyleTree key={branch} world={w} branch={branch} owned={progress.perks} pending={pending} selection={selected[0]} onSelect={id=>setSelection(id)} auto={planDraft?.auto??progress.auto!==false} onAuto={auto=>{setFocusDraft(null);setPlanDraft({auto});}} onPrioritize={perk=>{setFocusDraft(null);setPlanDraft({perk});}} priorityDraft={planDraft?.perk}/>
 <p className="lifestyle-boundary">{progress.auto!==false&&queue.length?`自动学习按所选方向安排，下一项「${lifestylePerks[queue[0]].name}」。`:'可手动选择并学习技能。'}公向需实际职责，私向使用自己的资产；选择重心不授予官职、土地或兵源。</p>
 </ActionDialog>;
}
