import {ArtIcon,type ArtName} from './ArtIcon';
import {branchPerks,branchFocuses,lifestylePerks,type LifestyleBranch} from '../data/lifestyles';
import {lifestyleReason,lifestyleBeneficiaries,lifestyleQueue,lifestyleProgress} from '../core/lifestyle';
import type {World} from '../core/types';
const perkIcon=(p:typeof lifestylePerks[string]):ArtName=>p.branch==='intrigue'?'wary':p.bonus.grain||p.bonus.supply||p.bonus.estateLoss?'grain':p.bonus.buildCost||p.bonus.tax||p.bonus.armyExpense||p.bonus.giftCost||p.bonus.estateBuildCost||p.bonus.estateSettleCost||p.bonus.estateWorkshop?'coins':p.bonus.buildTime||p.bonus.estateBuildTime?'diligent':p.bonus.siege?'city':p.bonus.attack||p.bonus.privateAttack?'army':p.bonus.calm||p.bonus.personalDefense?'steadfast':'gregarious';
export function LifestyleTree({world,branch,owned,pending,selection,onSelect,auto,onAuto,onPrioritize,priorityDraft}:{world:World;branch:LifestyleBranch;owned:string[];pending:boolean;selection:string;onSelect:(id:string)=>void;auto:boolean;onAuto:(value:boolean)=>void;onPrioritize:(id:string)=>void;priorityDraft?:string}){
 const perks=branchPerks(branch),selected=perks.find(([id])=>id===selection)??perks[0],id=selected[0],perk=selected[1],reason=lifestyleReason(world,{type:'lifestyle',action:'unlock',perk:id}),beneficiaries=lifestyleBeneficiaries(world,id),p=lifestyleProgress(world),queue=lifestyleQueue(world,branch,undefined,priorityDraft),remaining=360-(p?.xp[branch]??0)%360;
 const indexes={common:0,public:0,private:0},nodes=perks.map(([key,entry])=>{const n=indexes[entry.scope]++;return {id:key,perk:entry,x:entry.scope==='common'?43+n*14:(entry.scope==='public'?12:60)+n%3*14,y:entry.scope==='common'?12:38+Math.floor(n/3)*23};}),byId=new Map(nodes.map(n=>[n.id,n]));
 return <section className="lifestyle-arbor"><div className="lifestyle-arbor-scene" aria-label="公私修习图，连线表示实际前置">
 <svg className="lifestyle-connections" viewBox="0 0 1000 460" preserveAspectRatio="none" aria-hidden="true">{nodes.flatMap(n=>n.perk.requires.map(req=>{const parent=byId.get(req);if(!parent)return null;const x=parent.x*10,y=parent.y*4.6+22,x2=n.x*10,y2=n.y*4.6-24;return <path key={req+':'+n.id} className={owned.includes(req)?'is-owned':''} d={`M ${x} ${y} V ${(y+y2)/2} H ${x2} V ${y2}`}/>;}))}</svg>
 <span className="lifestyle-common-label">通用修习 · 可按需兼修</span>{branchFocuses(branch).map(([key,f])=><span key={key} className={'lifestyle-path-label '+f.scope}>{f.name}</span>)}
 {nodes.map(n=>{const why=lifestyleReason(world,{type:'lifestyle',action:'unlock',perk:n.id}),learned=owned.includes(n.id);return <button key={n.id} type="button" className={'lifestyle-tree-node '+(learned?'is-owned':!why?'is-ready':'is-locked')} style={{left:n.x+'%',top:n.y+'%'}} aria-pressed={id===n.id} aria-label={n.perk.name+'，'+(learned?'已掌握':why||'可学习，消耗 1 点')} title={n.perk.effect+'；'+(learned?'已掌握':why||'可学习')} onClick={()=>onSelect(n.id)}><span className="lifestyle-node-seal"><ArtIcon name={perkIcon(n.perk)} size={27}/>{learned&&<i>✓</i>}</span><strong>{n.perk.name}</strong></button>;})}
 <div className="lifestyle-tree-legend"><span>✓ 已掌握</span><span>金环 可学习</span><span>淡墨 待前置或技能点</span></div>
 </div><aside className="lifestyle-node-detail" aria-live="polite"><header><ArtIcon name={perkIcon(perk)} size={34}/><div><small>{perk.scope==='common'?'通用':perk.scope==='public'?'公向':'私向'} · {perk.mastery?'专长':perk.tier===0?'入门':perk.tier===1?'熟练':'精通'}</small><h4>{perk.name}</h4></div></header><p>{perk.effect}</p><dl className="lifestyle-effect-target"><dt>适用对象</dt><dd>{beneficiaries.length?beneficiaries.join('、'):'目前没有适用对象，能力可先学会'}</dd><dt>当前状态</dt><dd>{owned.includes(id)?beneficiaries.length?'已掌握，符合条件时生效':'已掌握，暂无适用对象':reason||'可学习，消耗本类 1 点'}</dd></dl><small>{perk.requires.length?'前置：'+perk.requires.map(key=>lifestylePerks[key].name).join('、'):'无前置，可直接学习'}{perk.mastery?' · 获得后天专长':''}</small>
 <section className="lifestyle-plan"><h5>学习安排</h5><label><input type="checkbox" checked={auto} disabled={pending||!p?.focus} onChange={e=>onAuto(e.target.checked)}/>有技能点时自动学习</label><p>下一技能：{queue.length?lifestylePerks[queue[0]].name:'本类已学完'}</p><small>{(p?.xp[branch]??0)>=7200?'经验已满，使用现有技能点':queue.length?`下一点约 ${Math.ceil(remaining/22)}–${Math.ceil(remaining/18)} 个月（持续投入本类）`:'可在同一入口选择另一分类'}{p?.focus&&branch!==p.focus.split('_').slice(1).join('_')?' · 当前未投入本类':''}</small><ol>{queue.slice(0,3).map(key=><li key={key}>{lifestylePerks[key].name}</li>)}</ol><button type="button" disabled={pending||owned.includes(id)||!p?.focus} onClick={()=>onPrioritize(id)}>优先学习此项</button><small>前置将先行学习；在底部确认安排。</small></section>
 </aside></section>;
}
