import type {MapMode} from '../map/WorldMap';
import type {CameraAction} from '../map/atlasPresentation';

type Props={mode:MapMode;onMode:(mode:MapMode)=>void;hasRealm:boolean;options:boolean;onOptions:()=>void;travelers:boolean;onTravelers:()=>void;tilted:boolean;onTilted:()=>void;models:boolean;onModels:()=>void;motion:boolean;onMotion:()=>void;sceneryDetail:boolean;onSceneryDetail:()=>void};
type Glyph='in'|'out'|'location'|'camera'|'layers'|'settings'|'left'|'right'|'north'|'player'|'selected'|'home'|'political'|'domains'|'diplomacy'|'terrain'|'roads';
const paths:Record<Glyph,string>={in:'M5 12h14M12 5v14',out:'M5 12h14',location:'M12 3a6 6 0 0 0-6 6c0 5 6 12 6 12s6-7 6-12a6 6 0 0 0-6-6ZM10 9h4',camera:'M3 8l9-5 9 5v9l-9 4-9-4ZM3 8l9 5 9-5M12 13v8',layers:'M3 7l9-4 9 4-9 4ZM3 12l9 4 9-4M3 17l9 4 9-4',settings:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6',left:'M4 10a8 8 0 1 1 2 9M4 4v6h6',right:'M20 10a8 8 0 1 0-2 9M20 4v6h-6',north:'M12 3l7 17-7-4-7 4ZM12 3v13',player:'M8 7a4 4 0 1 0 8 0 4 4 0 1 0-8 0M4 21v-3a8 8 0 0 1 16 0v3',selected:'M4 21V9h16v12M3 9l9-6 9 6M8 21v-7h8v7',home:'M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2ZM9 3v16M15 5v16',political:'M5 21V3h14l-3 5 3 5H5',domains:'M3 3h18v18H3ZM3 12h18M12 3v18',diplomacy:'M12 3v18M5 21h14M3 7h18M6 7l-3 7h6ZM18 7l-3 7h6Z',terrain:'M2 20l7-14 5 9 3-6 5 11ZM7 10l2 2 2-2',roads:'M7 3c12 7-12 11 0 18M15 3c12 7-12 11 0 18'};
function MapGlyph({name}:{name:Glyph}){return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>;}
export function MapCameraControls({focus}:{focus:(action:CameraAction)=>void}){
 return <div className="zoom-tools compact-map-tools" role="group" aria-label="地图视角">
 {(['in','out'] as const).map(action=><button key={action} className="art-map-button" title={action==='in'?'放大地图':'缩小地图'} aria-label={action==='in'?'放大地图':'缩小地图'} onClick={()=>focus(action)}><MapGlyph name={action}/></button>)}
 {([{icon:'location',label:'定位',items:[['player','此身'],['selected','所选城邑'],['home','天下舆图']]},{icon:'camera',label:'视角',items:[['left','向左旋转'],['north','北向回正'],['right','向右旋转']]}] as const).map(group=><details name="atlas-tools" className="map-tool-group" key={group.icon} onKeyDown={e=>{if(e.key==='Escape'){e.currentTarget.open=false;e.currentTarget.querySelector('summary')?.focus();}}}><summary title={group.label}><MapGlyph name={group.icon}/><small>{group.label}</small></summary><div className="map-tool-popover">{group.items.map(([action,label])=><button key={action} onClick={e=>{focus(action);const details=e.currentTarget.closest('details');if(details){details.open=false;details.querySelector('summary')?.focus();}}}><MapGlyph name={action}/>{label}</button>)}</div></details>)}
 </div>;
}
export function MapDisplayControls(p:Props){
 return <><div className="map-toolbox compact-map-tools"><details name="atlas-tools" className="map-tool-group" onKeyDown={e=>{if(e.key==='Escape'){e.currentTarget.open=false;e.currentTarget.querySelector('summary')?.focus();}}}><summary title="地图图层"><MapGlyph name="layers"/><small>{{political:'势力',domains:'郡县',diplomacy:'外交',terrain:'山川',roads:'道路'}[p.mode]}</small></summary><div className="map-tool-popover" role="group" aria-label="地图模式">{([['political','势力'],['domains','郡县'],['diplomacy','外交'],['terrain','山川'],['roads','道路']] as const).filter(([id])=>id!=='diplomacy'||p.hasRealm).map(([id,label])=><button key={id} aria-pressed={p.mode===id} onClick={e=>{p.onMode(id);const details=e.currentTarget.closest('details');if(details){details.open=false;details.querySelector('summary')?.focus();}}}><MapGlyph name={id}/>{label}</button>)}</div></details><button id="atlas-display-toggle" className="map-options-toggle" aria-expanded={p.options} aria-controls="atlas-display-options" onClick={p.onOptions} aria-label="地图显示设置"><MapGlyph name="settings"/><span>显示</span></button></div>
 {p.options&&<section id="atlas-display-options" className="map-options" aria-label="地图显示设置"><header><strong>舆图显示</strong><button aria-label="关闭地图显示设置" onClick={p.onOptions}><span aria-hidden="true">×</span></button></header>{([
 ['在途人物',p.travelers,p.onTravelers,'天下视野保留玩家行旅，拉近后显示其他在途人物'],
 ['立体山河',p.tilted,p.onTilted,'近景使用真实高程，远景自动铺平为纸质舆图'],
 ['近景细节',p.sceneryDetail,p.onSceneryDetail,'开启细密建筑、林地树木与象征农田；关闭以减少图形负担，城池与操作仍保留'],
 ['军队兵模',p.models,p.onModels,'拉近时显示兵模；关闭后使用军旗'],
 ['军队动画',p.motion,p.onMotion,'关闭以减少动态；位置与军情照常更新'],
 ] as const).map(([label,value,onClick,hint])=><div key={label} className="map-option"><button aria-describedby={"map-option-"+label} aria-pressed={value} onClick={onClick}><span>{label}</span><b aria-hidden="true">{value?'开':'关'}</b></button><small id={"map-option-"+label}>{hint}</small></div>)}</section>}
 </>;
}
