import {ArmyDeploymentDialog} from './ArmyDeploymentDialog';
import {useState} from 'react';
import type {World,GameCommand} from '../core/types';
import {armyDailyFood,playerRealm,realms,type RealmId} from '../core/realm';
import {militaryDefectionQuote} from '../core/militaryDefection';
import {nominationReason} from '../core/militaryNominations';
import {authorityGrant} from '../core/authority';
import {activeWars,warRealmSide} from '../core/wars';
import {warScoreBreakdown,warWillToContinue} from '../core/warScoring';
import {armyCommander} from '../core/mobility';
import {militaryCareerReason,commanderCompliance} from '../core/militaryCareer';
import {defectionReason} from '../core/defections';
import {separatePeaceReason} from '../core/separatePeace';
import {siegeDecisionReason,siegePhaseQuote} from '../core/siegePhases';
import {armySupplyTarget,convoyETA} from '../core/armyLogistics';
import {governingExecutives,politicalName,regimeName} from '../core/government';
import {allegianceRealm} from '../core/officeEligibility';
import {attributes} from '../core/social';
import {isAlive} from '../core/lifeState';
import {relationshipPeople} from '../data/relationships';
import {siteById} from '../data/scenario';
import {troopKinds,type TroopKind} from '../core/armyOrganization';
import {DetailTabs} from './DetailTabs';
import {ArtIcon,Resource} from './ArtIcon';
import {CommandButton} from './CommandButton';
import {ActionDialog} from './ActionDialog';
import {SingleChoiceCards} from './SingleChoiceCards';
import {RealmBadge} from './RealmBadge';
import {MilitaryChoiceDialog,type MilitaryChoice} from './MilitaryChoiceDialog';
import {CharacterPortrait} from './CharacterPortrait';
import {ConfirmAction} from './ConfirmAction';
import {WarSettlement} from './WarSettlement';
import {RecruitmentPlanDialog} from './RecruitmentPlanDialog';
import './militaryHub.css';
type Tab='overview'|'armies'|'wars'|'generals'|'supply'|'history';
const tabs=[{id:'overview',label:'军情',icon:'stress'},{id:'armies',label:'军队',icon:'army'},{id:'wars',label:'战争',icon:'influence'},{id:'generals',label:'将领',icon:'person'},{id:'supply',label:'粮运',icon:'grain'},{id:'history',label:'战史',icon:'renown'}] as const;
export function MilitaryHub({world:w,pending,send,onArmy,onCity,onPerson,onDiplomacy}:{world:World;pending:boolean;send:(c:GameCommand)=>void;onArmy:(id:number)=>void;onCity:(id:string)=>void;onPerson:(id:string)=>void;onDiplomacy:(r:RealmId)=>void}){
 const [tab,setTab]=useState<Tab>('overview'),[choice,setChoice]=useState<MilitaryChoice|null>(null),[recruit,setRecruit]=useState(false),[deploy,setDeploy]=useState(false),[privateDialog,setPrivateDialog]=useState(false),[privateKind,setPrivateKind]=useState<TroopKind>('shield'),[confirm,setConfirm]=useState<{command:GameCommand;title:string;detail:string}|null>(null),r=playerRealm(w),id=w.characterId!,central=governingExecutives(w,r).includes(id);
 const armies=w.realm!.armies.filter(a=>authorityGrant(w,id,'command',{realm:a.realm,site:a.location,army:a}).allowed),wars=activeWars(w).filter(v=>!!warRealmSide(v,r)),recruitSites=Object.keys(w.realm!.cities).filter(site=>authorityGrant(w,id,'levy',{realm:r,site}).allowed),site=w.people[0].location;
 const alerts=armies.filter(a=>a.supply<armyDailyFood(w,a)*10||a.refusal||a.logisticsReason&&a.supply<armySupplyTarget(w,a));
 const order=(command:GameCommand,title:string,detail:string)=>setConfirm({command,title,detail});
 const askArmy=(army:number)=>onArmy(army);
 const battleHistory=(w.militaryAftermath?.battles??[]).filter(b=>central?b.participants?.some(p=>p.realm===r):b.participants?.some(p=>p.commander===id)).slice().reverse();
 return <div className="military-hub"><div className="military-hub-identity"><ArtIcon name="army" size={30}/><strong>{central?regimeName(w,r)+'军务':politicalName(id)+'军务'}</strong><span className="military-identity-summary">{armies.length} 支可指挥军队 · {wars.length} 场相关战争</span></div><DetailTabs label="军事事务" value={tab} items={tabs} onChange={setTab}/>
 {(tab==='overview'||tab==='armies')&&<div className="military-hub-actions" role="group" aria-label="军队行动">
  <CommandButton label="征募计划" icon="army" pending={pending} reason={!recruitSites.length?'当前无合法征募辖区':''} hint="预览兵种、人数、出资、地方负担与集结安排。" onClick={()=>setRecruit(true)}/>
  <CommandButton label="联合军令" icon="world" pending={pending} reason={!armies.some(a=>!a.journey)?'当前无可部署的驻留军队':''} hint="选择军队和目的地，预览整组行程后下令。" onClick={()=>setDeploy(true)}/>
  <CommandButton label="私募部曲" icon="person" pending={pending} hint="使用个人财产征募部曲；预览兵种、费用与条件。" onClick={()=>{setPrivateKind('shield');setPrivateDialog(true);}}/>
 </div>}
 {tab==='overview'&&<><div className="military-alerts">{alerts.map(a=><button key={a.id} onClick={()=>askArmy(a.id!)}><strong>第 {a.id} 军 · {siteById[a.location].name}</strong><span>{a.refusal?.reason??a.logisticsReason??'军粮不足十日'} · 携粮约 {Math.floor(a.supply/Math.max(1,armyDailyFood(w,a)))} 日</span></button>)}{!alerts.length&&<p>暂无本军缺粮、拒命或补给受阻急报。</p>}</div>{w.militaryNominations?.items.filter(q=>q.status==='pending'&&(central&&q.realm===r||q.person===id)).map(q=><article className="military-record" key={'nomination-'+q.id}><strong>{politicalName(q.person)}自荐接掌第 {q.army} 军</strong><span>{q.reason} · 最早第 {q.due} 日答复</span>{central&&<div className="military-record-actions">{(['approve','reject'] as const).map(action=>{const command={type:'militaryNomination',action,id:q.id} as const;return <CommandButton key={action} label={action==='approve'?'任命':'拒绝'} icon="person" pending={pending} reason={nominationReason(w,command)} hint="按当前席位与人物状态复核，接掌仅限该军。" onClick={()=>order(command,action==='approve'?'接受军职自荐':'拒绝自荐','确认前按当前席位与人物状态复核，接掌仅限该军。')}/>;})}</div>}</article>)}{w.defections?.items.filter(q=>q.status==='pending'&&(q.from===r||q.to===r)).map(q=><article className="military-record" key={q.id}><strong>{siteById[q.site].name}请求归附{regimeName(w,q.to)}</strong><span>{q.reason} · 原属国有七日处置时间</span><div>{(q.from===r?['relieve']:['accept','reject']).map(action=>{const c={type:'defection',action,id:q.id} as GameCommand,why=defectionReason(w,c as Parameters<typeof defectionReason>[1]);return <CommandButton key={action} label={action==='accept'?'接纳':action==='reject'?'拒绝':'赈济'} icon="influence" hint="查看归附处置的费用与外交后果。" reason={why} pending={pending} onClick={()=>order(c,action==='accept'?'接纳归附并开战':action==='reject'?'拒绝归附':'赈济挽留',action==='accept'?'中央支出 100 钱保护预算，与原属国进入战争，可能破坏盟约和停战；该城法理归属保留。':action==='relieve'?'本城公粮支出 50，秩序 +20，归附请求撤回。':'拒绝本次请求，不改变城市控制。')}/>;})}</div></article>)}{w.realm!.sieges?.filter(s=>s.playerDecision&&w.realm!.cities[s.site].governor===id).map(s=><article className="military-record" key={s.site}><strong>{siteById[s.site].name}守城裁定</strong><span>议降可结束抵抗并转移实控；坚守会使地方秩序 −5。</span><div className="military-record-actions">{(['hold','surrender'] as const).map(choice=>{const command={type:'siegeDecision',war:s.war,site:s.site,choice} as const;return <CommandButton key={choice} label={choice==='hold'?'坚守':'议降'} icon="army" danger={choice==='surrender'} pending={pending} reason={siegeDecisionReason(w,command)} hint={choice==='hold'?'地方秩序 −5，进入下一轮围城。':'实控权转给围城方，法理归属保留。'} onClick={()=>order(command,choice==='hold'?'继续坚守':'接受围城议降',choice==='hold'?'地方秩序 −5，进入下一轮围城。':'实控权转给围城方，法理归属保留。')}/>;})}</div></article>)}</>}
 {tab==='armies'&&<div className="military-army-list">{armies.map(a=>{const q=commanderCompliance(w,a,'replace'),leader=armyCommander(w,a);return <article className="military-record" key={a.id}><button className="military-record-main" onClick={()=>askArmy(a.id!)}><strong>第 {a.id} 军 · {a.owner?'私人部曲':'公军'} · {siteById[a.location].name}</strong><span>{a.troops} 人 · 士气 {a.morale} · {leader?politicalName(leader):'统帅空缺'} · {authorityGrant(w,id,'command',{realm:r,site:a.location,army:a}).source}</span></button><span>制度信任 {q.institution} · 原将忠诚 {q.personal}{q.refuses?' · 交接可能拒命':''}</span><CommandButton label={'指挥 · '+((a.automation??'direct')==='direct'?'亲自下令':'自主行军')} icon="army" pending={pending} hint="调整本军指挥方式，确认后生效。" onClick={()=>setChoice({kind:'automation',army:a.id!})}/>{a.refusal&&<p className="service-warning">{a.refusal.reason}</p>}<div>{(['pacify','integrate'] as const).filter(action=>action==='pacify'||a.owner).map(action=>{const c={type:'militaryCareer',action,army:a.id!} as const,why=militaryCareerReason(w,c);return <CommandButton key={action} label={action==='pacify'?'安抚':'改编'} icon="steadfast" hint="预览出资与军队交接后果。" reason={why} pending={pending} onClick={()=>order(c,action==='pacify'?'清偿与安抚':'正式改编',action==='pacify'?`原供饷账户支出 ${Math.ceil(a.troops/20)+(a.arrears??0)} 钱，含欠饷与老兵安置；制度信任 +30。`:'经主人同意转入中央供饷，兵团原籍和私人忠诚保留。')}/>;})}<CommandButton label="驻地" icon="city" hint="查看军队当前驻地。" onClick={()=>onCity(a.location)}/>{realms.filter(to=>to!==r&&w.realm!.cities[a.location].controller===to).map(to=>{const c={type:'militaryDefection',army:a.id!,realm:to} as const,q=militaryDefectionQuote(w,c);return <CommandButton key={to} label={'投降给'+regimeName(w,to)} icon="army" danger hint="本人投降，按兵团忠诚分裂；预览后确认。" reason={q.reason} pending={pending} onClick={()=>order(c,'本人投降并转移效忠',`将有 ${q.troops} 人追随，${q.remaining} 人留在原阵营；旧国职权交接，旧国欠饷保留，当前部队转入对方军籍。`)} />;})}</div></article>})}{!armies.length&&<p>尚无当前职掌允许指挥的军队。可研习兵法、私募部曲，或申请地方公职与军事委任。</p>}</div>}
 {tab==='wars'&&wars.map(war=>{const score=war.civil?null:warScoreBreakdown(w,war),enemy=warRealmSide(war,r)==='attack'?war.defender:war.attacker,will=warWillToContinue(w,war,enemy);return <article className="military-record" key={war.id}><header className="military-war-heading"><RealmBadge realm={enemy} world={w} onOpen={onDiplomacy}/><strong>{siteById[war.target].name}之战</strong><CommandButton label="外交" icon="world" hint="查看战争对象与外交关系。" onClick={()=>onDiplomacy(enemy)}/></header>{score&&<p>{score.parts.map(p=>p.label+' '+p.value).join(' · ')} · 总分 {score.total}</p>}{central&&!war.civil&&<p title={will.parts.map(p=>p.label+' '+p.value).join('；')}>对方续战意愿 {will.total}（正值表示仍愿继续）</p>}<WarSettlement world={w} war={war} pending={pending} send={send} onPerson={onPerson}/>{r!==war.attacker&&r!==war.defender&&[0,100,300].map(coins=>{const c={type:'separatePeace',war:war.id!,coins} as const,why=separatePeaceReason(w,c);return <CommandButton key={coins} label={'单独退出'+(coins?' · '+coins+' 钱':'')} icon="world" hint="预览退出战争的赔款与义务。" reason={why} pending={pending} onClick={()=>order(c,'单独退出战争',`本国退出${coins?'并支付 '+coins+' 钱':''}；仅处理本国占领与义务，其他参战方继续交战。`)}/>;})}</article>})}
 {tab==='wars'&&!wars.length&&<p className="military-empty">当前没有本国参与的战争。</p>}
 {tab==='supply'&&!armies.length&&<p className="military-empty">当前没有可指挥军队的粮运记录。</p>}
 {tab==='generals'&&<><div className="military-hub-actions">{(()=>{const c={type:'militaryCareer',action:'study'} as const,why=militaryCareerReason(w,c);return <CommandButton label="研习兵法" icon="diligent" hint="私财 10 钱，三十个有效驻留日；行旅与公务期间暂停。" reason={why} pending={pending} onClick={()=>order(c,'研习兵法','支出私财 10 钱，研习三十个有效驻留日，行旅与公务期间暂停，完成后计入能力来源；收益递减。')}/>;})()}<Resource caption name="army" label="本人军事" value={attributes(w,id).martial}/><Resource caption name="renown" label="本人历练" value={w.militaryCareer?.xp[id]??0}/>{w.militaryCareer?.studies[id]&&<small>兵法研习 · 第 {w.militaryCareer.studies[id].due} 日最早完成</small>}</div><div className="military-generals">{relationshipPeople.filter(p=>isAlive(w,p.id)&&allegianceRealm(w,p.id)===r&&(central||p.id===id||armies.some(a=>armyCommander(w,a)===p.id))).map(p=><button key={p.id} onClick={()=>onPerson(p.id)}><span className="military-general-portrait"><CharacterPortrait world={w} characterId={p.id} compact/></span><span>{p.name}<small>军事 {attributes(w,p.id).martial} · 历练 {w.militaryCareer?.xp[p.id]??0}</small></span></button>)}</div><div className="military-hub-actions">{w.realm!.armies.filter(a=>a.realm===r&&!armyCommander(w,a)&&a.location===site&&!a.owner).map(a=>{const c={type:'militaryNomination',action:'apply',army:a.id!} as const,why=nominationReason(w,c);return <CommandButton key={a.id} label={'自荐第 '+a.id+' 军'} icon="person" hint="向实际执政者提出自荐，约七日后答复。" reason={why} pending={pending} onClick={()=>order(c,'自荐接掌军队','向实际执政者提出自荐；按现行用人政策、军事能力、功绩、门第和信任裁定，约七日后答复。')}/>;})}</div><p>在军队详情统帅席位中任命；御驾亲征使用本人赴营并随该军行动，委任战役使用既有统帅、目标与专款。</p></>}
 {tab==='supply'&&<>{central&&<CommandButton label={'征粮 · '+({civilian:'保民优先',normal:'常规军需',emergency:'紧急征发'}[w.realm!.supplyPolicies?.[r]??'normal'])} icon="grain" pending={pending} hint="比较各方案保留的民食与征发代价；确认后生效。" onClick={()=>setChoice({kind:'supplyPolicy'})}/>}{armies.map(a=><article className="military-record" key={a.id}><button onClick={()=>askArmy(a.id!)}><strong>第 {a.id} 军</strong> · 每日 {armyDailyFood(w,a)} 粮 · 可用 {Math.floor(a.supply/Math.max(1,armyDailyFood(w,a)))} 日</button><span>{a.convoy?`在途 ${a.convoy.grain} 粮 · ${convoyETA(w,a)===null?'粮道受阻':convoyETA(w,a)+' 日后最早抵达（道路占用另计）'}`:a.logisticsReason||'暂无粮队'} · 累计运输损失 {a.supplyLost??0}</span><CommandButton label={'粮运 · '+(['后备','常规','前线'][a.supplyPriority??1])} icon="grain" pending={pending} hint="调整本军粮源分配顺序，确认后生效。" onClick={()=>setChoice({kind:'priority',army:a.id!})}/></article>)}{w.realm!.sieges?.filter(s=>wars.some(v=>v.id===s.war)).map(s=>{const a=w.realm!.armies.filter(a=>a.location===s.site&&!a.journey),q=siegePhaseQuote(w,s,a);return <article key={s.site} className="military-record"><button onClick={()=>onCity(s.site)}>{siteById[s.site].name}围城 · 包围 {q.blockade}%</button><span>下一轮第 {s.nextPhase??w.day+14} 日 · 本轮迫降概率 {q.chance}%{q.reinforcements?' · 援军正在接近':''} · 缺口 {s.breach??0} · {s.event??'工事初筑'}</span></article>})}</>}
 {tab==='history'&&<div className="military-history">{battleHistory.map(b=><article className="military-record" key={b.id??b.key}><strong>战斗 {b.id??'旧档'} · {b.site?siteById[b.site].name:'旧档未记录地点'}</strong><span>第 {b.day}–{b.ended??b.last} 日 · {b.winner?b.winner==='draw'?'双方撤离':b.winner==='attack'?'攻方获胜':'守方获胜':'未有最终胜负'} · 减员 {b.lossA}/{b.lossB} · 战争分数 {b.scoreDelta??0}</span><div>{b.participants?.map(p=><span key={p.army}>第 {p.army} 军 {p.troops} 人 · {p.commander?<button onClick={()=>onPerson(p.commander!)}>{politicalName(p.commander)}</button>:'未任统帅'}</span>)}</div></article>)}{!battleHistory.length&&<p>尚无当前身份可查的参战快照；旧档缺失的参与信息不事后推定。</p>}</div>}
 {recruit&&<RecruitmentPlanDialog world={w} pending={pending} send={send} onClose={()=>setRecruit(false)}/>}
 {deploy&&<ArmyDeploymentDialog world={w} pending={pending} send={send} onClose={()=>setDeploy(false)}/>}
 {privateDialog&&<ActionDialog title="私募部曲" onClose={()=>setPrivateDialog(false)} actions={<button className="primary" disabled={pending||!!militaryCareerReason(w,{type:'militaryCareer',action:'privateRaise',site,kind:privateKind})} onClick={()=>{const c={type:'militaryCareer',action:'privateRaise',site,kind:privateKind} as const;if(pending||militaryCareerReason(w,c))return;send(c);setPrivateDialog(false);}}>确认私募 · {troopKinds[privateKind].cost+60} 钱</button>}>
  <p>驻地{siteById[site].name}，200 人来自当地人口，购买 60 粮，训练三十日；后续私财支付薪饷和军粮。平时上限 600 人，战时 1800 人。</p>
  <SingleChoiceCards label="兵种与私财支出" value={privateKind} onChange={setPrivateKind} disabled={pending} options={(Object.keys(troopKinds) as TroopKind[]).map(kind=>({id:kind,title:troopKinds[kind].name,description:`私财 ${troopKinds[kind].cost+60} 钱 · 200 人 · 30 日训练`,detail:`攻击 ${troopKinds[kind].attack}% · 防护 ${troopKinds[kind].defence}%`,reason:militaryCareerReason(w,{type:'militaryCareer',action:'privateRaise',site,kind})}))}/>
  <div className="military-metrics"><Resource caption name="coins" label="个人现钱" value={w.people[0].coins}/><Resource caption name="coins" label="本次私财支出" value={troopKinds[privateKind].cost+60}/></div>
  {militaryCareerReason(w,{type:'militaryCareer',action:'privateRaise',site,kind:privateKind})&&<p role="status" className="military-warning">{militaryCareerReason(w,{type:'militaryCareer',action:'privateRaise',site,kind:privateKind})}</p>}
 </ActionDialog>}
 {choice&&<MilitaryChoiceDialog world={w} choice={choice} pending={pending} send={send} onClose={()=>setChoice(null)}/>}
 {confirm&&(()=>{const c=confirm.command,why=c.type==='militaryDefection'?militaryDefectionQuote(w,c).reason:c.type==='militaryNomination'?nominationReason(w,c):c.type==='militaryCareer'?militaryCareerReason(w,c):c.type==='defection'?defectionReason(w,c):c.type==='siegeDecision'?siegeDecisionReason(w,c):c.type==='separatePeace'?separatePeaceReason(w,c):'';return <ConfirmAction title={confirm.title} detail={<><p>{confirm.detail}</p>{why&&<p className="service-warning">{why}</p>}</>} confirmLabel={'确认 · '+confirm.title} danger={c.type==='militaryDefection'||c.type==='siegeDecision'&&c.choice==='surrender'||c.type==='separatePeace'} pending={pending||!!why} onCancel={()=>setConfirm(null)} onConfirm={()=>{if(pending||why)return;send(c);setConfirm(null);}}/>;})()}
 </div>;
}
