import {ArmyDeploymentDialog} from './ArmyDeploymentDialog';
import {useState} from 'react';
import type {World,GameCommand} from '../core/types';
import {armyDailyFood,playerRealm,realms,type RealmId} from '../core/realm';
import {militaryDefectionQuote} from '../core/militaryDefection';
import {nominationReason} from '../core/militaryNominations';
import {authorityGrant} from '../core/authority';
import {activeWars,warRealmSide} from '../core/wars';
import {warScoreBreakdown,warWillToContinue} from '../core/warScoring';
import {armyCommander} from '../core/mobility';
import {militaryCareerReason,commanderCompliance} from '../core/militaryCareer';
import {defectionReason} from '../core/defections';
import {separatePeaceReason} from '../core/separatePeace';
import {siegeDecisionReason,siegePhaseQuote} from '../core/siegePhases';
import {armySupplyTarget,convoyETA} from '../core/armyLogistics';
import {governingExecutives,politicalName,regimeName} from '../core/government';
import {allegianceRealm} from '../core/officeEligibility';
import {attributes} from '../core/social';
import {isAlive} from '../core/lifeState';
import {relationshipPeople} from '../data/relationships';
import {siteById} from '../data/scenario';
import {troopKinds,type TroopKind} from '../core/armyOrganization';
import {DetailTabs} from './DetailTabs';
import {ArtIcon} from './ArtIcon';
import {CharacterPortrait} from './CharacterPortrait';
import {ConfirmAction} from './ConfirmAction';
import {WarSettlement} from './WarSettlement';
import {RecruitmentPlanDialog} from './RecruitmentPlanDialog';
import './militaryHub.css';
type Tab='overview'|'armies'|'wars'|'generals'|'supply'|'history';
const tabs=[{id:'overview',label:'军情',icon:'stress'},{id:'armies',label:'军队',icon:'army'},{id:'wars',label:'战争',icon:'influence'},{id:'generals',label:'将领',icon:'person'},{id:'supply',label:'粮运',icon:'grain'},{id:'history',label:'战史',icon:'renown'}] as const;
export function MilitaryHub({world:w,pending,send,onArmy,onCity,onPerson,onDiplomacy}:{world:World;pending:boolean;send:(c:GameCommand)=>void;onArmy:(id:number)=>void;onCity:(id:string)=>void;onPerson:(id:string)=>void;onDiplomacy:(r:RealmId)=>void}){
 const [tab,setTab]=useState<Tab>('overview'),[recruit,setRecruit]=useState(false),[deploy,setDeploy]=useState(false),[privateDialog,setPrivateDialog]=useState(false),[privateKind,setPrivateKind]=useState<TroopKind>('shield'),[confirm,setConfirm]=useState<{command:GameCommand;title:string;detail:string}|null>(null),r=playerRealm(w),id=w.characterId!,central=governingExecutives(w,r).includes(id);
 const armies=w.realm!.armies.filter(a=>authorityGrant(w,id,'command',{realm:a.realm,site:a.location,army:a}).allowed),wars=activeWars(w).filter(v=>!!warRealmSide(v,r)),recruitSites=Object.keys(w.realm!.cities).filter(site=>authorityGrant(w,id,'levy',{realm:r,site}).allowed),site=w.people[0].location;
 const order=(command:GameCommand,title:string,detail:string)=>setConfirm({command,title,detail});
 const askArmy=(army:number)=>onArmy(army);
 const battleHistory=(w.militaryAftermath?.battles??[]).filter(b=>central?b.participants?.some(p=>p.realm===r):b.participants?.some(p=>p.commander===id)).slice().reverse();
 return <div className="military-hub"><div className="military-hub-identity"><ArtIcon name="army" size={30}/><strong>{central?regimeName(w,r)+'军务':politicalName(id)+'军务'}</strong><span>{armies.length} 支可指挥军队 · {wars.length} 场相关战争</span></div><DetailTabs label="军事事务" value={tab} items={tabs} onChange={setTab}/>
 {(tab==='overview'||tab==='armies')&&<div className="military-hub-actions"><button disabled={pending||!recruitSites.length} title={!recruitSites.length?'当前无合法征募辖区':'预览征募、出资、地方负担和集结'} onClick={()=>setRecruit(true)}><ArtIcon name="army"/>征募计划</button><button disabled={pending||!armies.length} onClick={()=>setDeploy(true)}><ArtIcon name="army"/>联合军令</button><button disabled={pending} onClick={()=>setPrivateDialog(true)}><ArtIcon name="person"/>私募部曲</button></div>}
 {tab==='overview'&&<><div className="military-alerts">{armies.filter(a=>a.supply<armyDailyFood(w,a)*10||a.refusal||a.logisticsReason&&a.supply<armySupplyTarget(w,a)).map(a=><button key={a.id} onClick={()=>askArmy(a.id!)}><strong>第 {a.id} 军 · {siteById[a.location].name}</strong><span>{a.refusal?.reason??a.logisticsReason??'军粮不足十日'} · 携粮约 {Math.floor(a.supply/Math.max(1,armyDailyFood(w,a)))} 日</span></button>)}{!armies.some(a=>a.supply<armyDailyFood(w,a)*10||a.refusal)&&<p>暂无本军断粮或拒命急报。</p>}</div>{w.militaryNominations?.items.filter(q=>q.status==='pending'&&(central&&q.realm===r||q.person===id)).map(q=><article className="military-record" key={'nomination-'+q.id}><strong>{politicalName(q.person)}自荐接掌第 {q.army} 军</strong><span>{q.reason} · 最早第 {q.due} 日答复</span>{central&&(['approve','reject'] as const).map(action=><button key={action} disabled={pending} onClick={()=>order({type:'militaryNomination',action,id:q.id},action==='approve'?'接受军职自荐':'拒绝自荐','确认前按当前席位与人物状态复核，接掌仅限该军。')}>{action==='approve'?'任命':'拒绝'}</button>)}</article>)}{w.defections?.items.filter(q=>q.status==='pending'&&(q.from===r||q.to===r)).map(q=><article className="military-record" key={q.id}><strong>{siteById[q.site].name}请求归附{regimeName(w,q.to)}</strong><span>{q.reason} · 原属国有七日处置时间</span><div>{(q.from===r?['relieve']:['accept','reject']).map(action=>{const c={type:'defection',action,id:q.id} as GameCommand,why=defectionReason(w,c as Parameters<typeof defectionReason>[1]);return <button key={action} title={why} disabled={pending||!!why} onClick={()=>order(c,action==='accept'?'接纳归附并开战':action==='reject'?'拒绝归附':'赈济挽留',action==='accept'?'中央支出 100 钱保护预算，与原属国进入战争，可能破坏盟约和停战；该城法理归属保留。':action==='relieve'?'本城公粮支出 50，秩序 +20，归附请求撤回。':'拒绝本次请求，不改变城市控制。')}>{action==='accept'?'接纳':action==='reject'?'拒绝':'赈济'}</button>;})}</div></article>)}{w.realm!.sieges?.filter(s=>s.playerDecision&&w.realm!.cities[s.site].governor===id).map(s=><article className="military-record" key={s.site}><strong>{siteById[s.site].name}守城裁定</strong><span>议降可结束抵抗并转移实控；坚守会使地方秩序 −5。</span>{(['hold','surrender'] as const).map(choice=><button key={choice} disabled={pending} onClick={()=>order({type:'siegeDecision',war:s.war,site:s.site,choice},choice==='hold'?'继续坚守':'接受围城议降',choice==='hold'?'地方秩序 −5，进入下一轮围城。':'实控权转给围城方，法理归属保留。')}>{choice==='hold'?'坚守':'议降'}</button>)}</article>)}</>}
 {tab==='armies'&&<div className="military-army-list">{armies.map(a=>{const q=commanderCompliance(w,a,'replace'),leader=armyCommander(w,a);return <article className="military-record" key={a.id}><button className="military-record-main" onClick={()=>askArmy(a.id!)}><strong>第 {a.id} 军 · {a.owner?'私人部曲':'公军'} · {siteById[a.location].name}</strong><span>{a.troops} 人 · 士气 {a.morale} · {leader?politicalName(leader):'统帅空缺'} · {authorityGrant(w,id,'command',{realm:r,site:a.location,army:a}).source}</span></button><span>制度信任 {q.institution} · 原将忠诚 {q.personal}{q.refuses?' · 交接可能拒命':''}</span><fieldset className="military-choice-group"><legend>日常军令</legend>{(['direct','delegated'] as const).map(control=><label className="military-choice" key={control}><input type="radio" name={'army-control-'+a.id} checked={(a.automation??'direct')===control} disabled={pending} onChange={()=>order({type:'militaryCareer',action:'automation',army:a.id!,control},control==='direct'?'接管军令':'授权自主行军',control==='direct'?'本军保留当前行程，抵达后等待你的军令。':'按本国实际战事与补给选择集结、救援或撤退；保留将领、编制与账户，不自动追加征募或预算。')}/><span>{control==='direct'?'亲自下令':'自主行军'}<small>{control==='direct'?'抵达后等待军令':'将领按战事与补给行动'}</small></span></label>)}</fieldset>{a.refusal&&<p className="service-warning">{a.refusal.reason}</p>}<div>{(['pacify','integrate'] as const).filter(action=>action==='pacify'||a.owner).map(action=>{const c={type:'militaryCareer',action,army:a.id!} as const,why=militaryCareerReason(w,c);return <button key={action} disabled={pending||!!why} title={why} onClick={()=>order(c,action==='pacify'?'清偿与安抚':'正式改编',action==='pacify'?`原供饷账户支出 ${Math.ceil(a.troops/20)+(a.arrears??0)} 钱，含欠饷与老兵安置；制度信任 +30。`:'经主人同意转入中央供饷，兵团原籍和私人忠诚保留。')}>{action==='pacify'?'安抚':'改编'}</button>;})}<button onClick={()=>onCity(a.location)}>查看驻地</button>{realms.filter(to=>to!==r&&w.realm!.cities[a.location].controller===to).map(to=>{const c={type:'militaryDefection',army:a.id!,realm:to} as const,q=militaryDefectionQuote(w,c);return <button key={to} disabled={pending||!!q.reason} title={q.reason||'本人投降，按兵团分裂'} onClick={()=>order(c,'本人投降并转移效忠',`将有 ${q.troops} 人追随，${q.remaining} 人留在原阵营；旧国职权交接，旧国欠饷保留，当前部队转入对方军籍。`)}><ArtIcon name="army"/>投降给{regimeName(w,to)}</button>;})}</div></article>})}{!armies.length&&<p>尚无当前职掌允许指挥的军队。可研习兵法、私募部曲，或申请地方公职与军事委任。</p>}</div>}
 {tab==='wars'&&wars.map(war=>{const score=war.civil?null:warScoreBreakdown(w,war),enemy=warRealmSide(war,r)==='attack'?war.defender:war.attacker,will=warWillToContinue(w,war,enemy);return <article className="military-record" key={war.id}><button onClick={()=>onDiplomacy(enemy)}>外交详情</button>{score&&<p>{score.parts.map(p=>p.label+' '+p.value).join(' · ')} · 总分 {score.total}</p>}{central&&!war.civil&&<p title={will.parts.map(p=>p.label+' '+p.value).join('；')}>对方续战意愿 {will.total}（正值表示仍愿继续）</p>}<WarSettlement world={w} war={war} pending={pending} send={send} onPerson={onPerson}/>{r!==war.attacker&&r!==war.defender&&[0,100,300].map(coins=>{const c={type:'separatePeace',war:war.id!,coins} as const,why=separatePeaceReason(w,c);return <button key={coins} disabled={pending||!!why} title={why} onClick={()=>order(c,'单独退出战争',`本国退出${coins?'并支付 '+coins+' 钱':''}；仅处理本国占领与义务，其他参战方继续交战。`)}>单独退出{coins?' · '+coins+' 钱':''}</button>;})}</article>})}
 {tab==='generals'&&<><div className="military-hub-actions">{(()=>{const c={type:'militaryCareer',action:'study'} as const,why=militaryCareerReason(w,c);return <button disabled={pending||!!why} title={why} onClick={()=>order(c,'研习兵法','支出私财 10 钱，研习三十个有效驻留日，行旅与公务期间暂停，完成后计入能力来源；收益递减。')}>研习兵法{w.militaryCareer?.studies[id]?' · 第 '+w.militaryCareer.studies[id].due+' 日最早完成':''}</button>;})()}<span>当前军事 {attributes(w,id).martial} · 历练 {w.militaryCareer?.xp[id]??0}</span></div><div className="military-generals">{relationshipPeople.filter(p=>isAlive(w,p.id)&&allegianceRealm(w,p.id)===r&&(central||p.id===id||armies.some(a=>armyCommander(w,a)===p.id))).map(p=><button key={p.id} onClick={()=>onPerson(p.id)}><CharacterPortrait world={w} characterId={p.id} compact/><span>{p.name}<small>军事 {attributes(w,p.id).martial} · 历练 {w.militaryCareer?.xp[p.id]??0}</small></span></button>)}</div><div className="military-hub-actions">{w.realm!.armies.filter(a=>a.realm===r&&!armyCommander(w,a)&&a.location===site&&!a.owner).map(a=>{const c={type:'militaryNomination',action:'apply',army:a.id!} as const,why=nominationReason(w,c);return <button key={a.id} disabled={pending||!!why} title={why} onClick={()=>order(c,'自荐接掌军队','向实际执政者提出自荐；按现行用人政策、军事能力、功绩、门第和信任裁定，约七日后答复。')}>自荐第 {a.id} 军</button>;})}</div><p>在军队详情统帅席位中任命；御驾亲征使用本人赴营并随该军行动，委任战役使用既有统帅、目标与专款。</p></>}
 {tab==='supply'&&<>{central&&<fieldset className="military-choice-group"><legend>国家征粮政策</legend>{(['civilian','normal','emergency'] as const).map(policy=><label className="military-choice" key={policy}><input type="radio" name="military-supply-policy" checked={(w.realm!.supplyPolicies?.[r]??'normal')===policy} disabled={pending} onChange={()=>order({type:'militaryCareer',action:'supplyPolicy',policy},'调整征粮政策',policy==='emergency'?'安全储备降为一月民食，突破常规两月安全线的征粮降低地方秩序；每日军粮不变。':`保留 ${policy==='civilian'?3:2} 月民食，安全线以内粮源沿真实道路调运。`)}/><span>{policy==='civilian'?'保民优先':policy==='normal'?'常规军需':'紧急征发'}<small>保留 {policy==='civilian'?3:policy==='normal'?2:1} 月民食{policy==='emergency'?' · 征发伤秩序':''}</small></span></label>)}</fieldset>}{armies.map(a=><article className="military-record" key={a.id}><button onClick={()=>askArmy(a.id!)}><strong>第 {a.id} 军</strong> · 每日 {armyDailyFood(w,a)} 粮 · 可用 {Math.floor(a.supply/Math.max(1,armyDailyFood(w,a)))} 日</button><span>{a.convoy?`在途 ${a.convoy.grain} 粮 · ${convoyETA(w,a)===null?'粮道受阻':convoyETA(w,a)+' 日后最早抵达（道路占用另计）'}`:a.logisticsReason||'暂无粮队'} · 累计运输损失 {a.supplyLost??0}</span><fieldset className="military-choice-group"><legend>调度优先级</legend>{[0,1,2].map(priority=><label className="military-choice" key={priority}><input type="radio" name={'army-priority-'+a.id} checked={(a.supplyPriority??1)===priority} disabled={pending} onChange={()=>send({type:'militaryCareer',action:'priority',army:a.id!,priority})}/><span>{['后备','常规','前线'][priority]}<small>{['剩余粮源','默认调度','优先供粮'][priority]}</small></span></label>)}</fieldset></article>)}{w.realm!.sieges?.filter(s=>wars.some(v=>v.id===s.war)).map(s=>{const a=w.realm!.armies.filter(a=>a.location===s.site&&!a.journey),q=siegePhaseQuote(w,s,a);return <article key={s.site} className="military-record"><button onClick={()=>onCity(s.site)}>{siteById[s.site].name}围城 · 包围 {q.blockade}%</button><span>下一轮第 {s.nextPhase??w.day+14} 日 · 本轮迫降概率 {q.chance}%{q.reinforcements?' · 援军正在接近':''} · 缺口 {s.breach??0} · {s.event??'工事初筑'}</span></article>})}</>}
 {tab==='history'&&<div className="military-history">{battleHistory.map(b=><article className="military-record" key={b.id??b.key}><strong>战斗 {b.id??'旧档'} · {b.site?siteById[b.site].name:'旧档未记录地点'}</strong><span>第 {b.day}–{b.ended??b.last} 日 · {b.winner?b.winner==='draw'?'双方撤离':b.winner==='attack'?'攻方获胜':'守方获胜':'未有最终胜负'} · 减员 {b.lossA}/{b.lossB} · 战争分数 {b.scoreDelta??0}</span><div>{b.participants?.map(p=><span key={p.army}>第 {p.army} 军 {p.troops} 人 · {p.commander?<button onClick={()=>onPerson(p.commander!)}>{politicalName(p.commander)}</button>:'未任统帅'}</span>)}</div></article>)}{!battleHistory.length&&<p>尚无当前身份可查的参战快照；旧档缺失的参与信息不事后推定。</p>}</div>}
 {recruit&&<RecruitmentPlanDialog world={w} pending={pending} send={send} onClose={()=>setRecruit(false)}/>}
 {deploy&&<ArmyDeploymentDialog world={w} pending={pending} send={send} onClose={()=>setDeploy(false)}/>}
 {privateDialog&&<ConfirmAction title="私募部曲" detail={<div className="military-private-detail"><p>驻地{siteById[site].name}，200 人来自当地人口，购买 60 粮，训练三十日；后续私财支付薪饷和军粮。平时上限 600 人，战时 1800 人。</p><label>兵种<select value={privateKind} onChange={e=>setPrivateKind(e.target.value as TroopKind)}>{Object.entries(troopKinds).map(([k,v])=><option key={k} value={k}>{v.name} · 总价 {v.cost+60} 钱</option>)}</select></label><p className="service-warning">{militaryCareerReason(w,{type:'militaryCareer',action:'privateRaise',site,kind:privateKind})}</p></div>} confirmLabel="私财征募" pending={pending||!!militaryCareerReason(w,{type:'militaryCareer',action:'privateRaise',site,kind:privateKind})} onCancel={()=>setPrivateDialog(false)} onConfirm={()=>{const c={type:'militaryCareer',action:'privateRaise',site,kind:privateKind} as const;if(militaryCareerReason(w,c))return;send(c);setPrivateDialog(false);}}/>}
 {confirm&&(()=>{const c=confirm.command,why=c.type==='militaryDefection'?militaryDefectionQuote(w,c).reason:c.type==='militaryNomination'?nominationReason(w,c):c.type==='militaryCareer'?militaryCareerReason(w,c):c.type==='defection'?defectionReason(w,c):c.type==='siegeDecision'?siegeDecisionReason(w,c):c.type==='separatePeace'?separatePeaceReason(w,c):'';return <ConfirmAction title={confirm.title} detail={<><p>{confirm.detail}</p>{why&&<p className="service-warning">{why}</p>}</>} confirmLabel="确认执行" pending={pending||!!why} onCancel={()=>setConfirm(null)} onConfirm={()=>{if(why)return;send(c);setConfirm(null);}}/>;})()}
 </div>;
}
