import {PersonChoice} from './PersonSelection';
import {useState} from 'react';
import {activities,activityResultPreview,activityQuote,mobilityReason,departureReason,departureImpact} from '../core/mobility';
import {personResidence} from '../core/residence';
import {relationshipPeople} from '../data/relationships';
import {siteById} from '../data/scenario';
import {capital,playerRealm} from '../core/realm';
import {governingExecutives,politicalName} from '../core/government';
import {isAlive} from '../core/lifeState';
import {allegianceRealm} from '../core/officeEligibility';
import {attributes} from '../core/social';
import type {GameCommand,World} from '../core/types';
import type {ActivityKind,MobilityCommand} from '../core/mobilityState';
import {ArtIcon} from './ArtIcon';
import {HoverHint} from './HoverHint';
import {CharacterPortrait} from './CharacterPortrait';
import './mobility.css';
type Props={world:World;send:(c:GameCommand)=>void;pending?:boolean};
export function ActivityProgress({world:w,send,pending=false,id,site,target,estate=false}:{id?:number;site?:string;target?:string;estate?:boolean}&Props){
 const list=w.mobility?.activities.filter(a=>id!==undefined?a.id===id:!['done','cancelled'].includes(a.phase)&&(!site||a.site===site)&&(!target||a.target===target)&&(!estate||['family','succession'].includes(a.kind)))??[];
 const button=(c:MobilityCommand,label:string)=>{const reason=mobilityReason(w,c);return <HoverHint label={label} content={reason||(c.action==='resolve'?activityResultPreview(w,c.id,c.choice!):label)}><button disabled={pending||!!reason} onClick={()=>send(c)}>{label}</button></HoverHint>;};
 return <div className="journey-agenda">{!site&&!target&&!estate&&w.mobility?.captivity&&<article><h4>身陷囹圄 · {siteById[w.mobility.captivity.site].name}</h4>{button({type:'mobility',action:'ransom'},'筹赎返 · 80 钱')}</article>}{list.map(a=><article key={a.id} className="journey-activity"><header><ArtIcon name={activities[a.kind].icon} size={30}/><div><h4>{activities[a.kind].name} · {siteById[a.site].name}</h4><small>{a.delegate?'承办：'+politicalName(a.delegate):'亲自参加'}{a.target?' · '+politicalName(a.target):''}</small></div></header><p>{({travel:'赴约途中',ready:'人员已到齐',working:`驻留中 · 还需 ${Math.max(0,(a.due??w.day)-w.day)} 日`,decision:'待你定夺',done:'已完成',cancelled:'已中止'})[a.phase]}{!['done','cancelled'].includes(a.phase)&&` · 约定余 ${Math.max(0,a.deadline-w.day)} 日`}</p>{a.phase==='working'&&<progress aria-label="事务进度" value={w.day-a.started!} max={a.due!-a.started!}/>}{a.result&&<p>{a.result}</p>}<div className="journey-actions">{a.phase==='ready'&&!a.delegate&&button({type:'mobility',action:'begin',id:a.id},'开始办理')}{a.phase==='decision'&&!a.delegate&&<>{button({type:'mobility',action:'resolve',id:a.id,choice:'measured'},'从容安排 · 减压')}{button({type:'mobility',action:'resolve',id:a.id,choice:'decisive'},'积极争取 · 增压')}</>}{!['done','cancelled'].includes(a.phase)&&button({type:'mobility',action:'cancel',id:a.id},'取消安排')}</div></article>)}</div>;
}
export function MobilityPanel({world:w,send,pending=false,site,target,estate=false,embedded=false}:{site?:string;target?:string;estate?:boolean;embedded?:boolean}&Props){
 const [selected,setSelected]=useState<string|null>(null),[delegate,setDelegate]=useState('');
 if(!w.mobility||!w.characterId)return null;
 const r=playerRealm(w),at=site??(target?personResidence(w,target).site:w.people[0].location),candidates:{kind:ActivityKind;target?:string;site:string}[]=[];
 if(target){for(const kind of ['visit','banquet','mentor'] as const)candidates.push({kind,target,site:at});if(governingExecutives(w,r).includes(target))candidates.push({kind:'audience',target,site:capital(r)});}
 else if(estate){for(const p of relationshipPeople.filter(p=>p.id!==w.characterId&&p.family===w.holdings.estate.family&&isAlive(w,p.id))){candidates.push({kind:'family',target:p.id,site:at});if(w.social?.heir===p.id)candidates.push({kind:'succession',target:p.id,site:at});}}
 else {if(w.realm?.cities[at]?.controller===r){candidates.push({kind:'tour',site:at});if(w.realm.armies.some(a=>a.realm===r&&a.location===at&&!a.journey))candidates.push({kind:'training',site:at});}if(at===capital(r))for(const person of governingExecutives(w,r).filter(id=>id!==w.characterId))candidates.push({kind:'audience',target:person,site:at});}
 const options=candidates.map(c=>({...c,key:c.kind+'|'+(c.target??c.site)})),chosen=options.find(c=>c.key===selected);
 const cmd=chosen?{type:'mobility' as const,action:'plan' as const,kind:chosen.kind,site:chosen.site,...(chosen.target?{target:chosen.target}:{}),...delegate&&['tour','training'].includes(chosen.kind)?{delegate}:{}}:null,q=cmd?activityQuote(w,cmd):null;
 return <section className="mobility-panel"><ActivityProgress world={w} send={send} pending={pending} site={site??(estate?at:undefined)} target={target} estate={estate}/>{options.length>0&&<>{!embedded&&<h3><ArtIcon name="world" size={28}/> {target?'约见与研习':estate?'家族相聚':'当地事务'}</h3>}<div className="journey-options">{options.map(c=>{const d=activities[c.kind],reason=activityQuote(w,{type:'mobility',action:'plan',kind:c.kind,site:c.site,target:c.target}).reason;return <HoverHint key={c.key} label={d.name} content={<><p>{d.effect}</p>{reason&&<p>{reason}</p>}</>}><button data-unavailable={!!reason} aria-pressed={selected===c.key} onClick={()=>{setSelected(c.key);setDelegate('');}}>{c.target&&estate?<CharacterPortrait characterId={c.target} world={w} compact/>:<ArtIcon name={d.icon} size={32}/>}<span>{d.name}{c.target&&<small>{politicalName(c.target)}</small>}</span></button></HoverHint>;})}</div></>}{chosen&&cmd&&q&&<article className="journey-preview"><h4>{activities[chosen.kind].name} · {siteById[chosen.site].name}</h4><p>{activities[chosen.kind].effect}</p>{['tour','training'].includes(chosen.kind)&&governingExecutives(w,r).includes(w.characterId)&&<><PersonChoice world={w} title="承办人" value={delegate||w.characterId} onChange={id=>setDelegate(id===w.characterId?'':id)} pending={pending} options={relationshipPeople.filter(p=>allegianceRealm(w,p.id)===r&&isAlive(w,p.id)).map(p=>({id:p.id,score:attributes(w,p.id)[chosen.kind==='training'?'martial':'stewardship'],metric:chosen.kind==='training'?'军事':'管理',reason:activityQuote(w,{...cmd,delegate:p.id===w.characterId?undefined:p.id}).reason}))}/></>}<div className="journey-cost"><span><ArtIcon name="coins" size={24}/>{q.cost}</span><span><ArtIcon name="grain" size={24}/>{delegate?'公差自备':q.food}</span><span>路程 {q.days} 日 · 驻留 {q.duration} 日</span></div>{!delegate&&departureImpact(w).map(text=><p key={text}>{text}</p>)}<HoverHint label="筹办要求" content={q.reason||'确认后支付筹办费用，出发并约定会面期限。'}><button className="primary" disabled={pending||!!q.reason} onClick={()=>send(cmd)}>{delegate?'派员办理':q.days?'约定并出发':'约定当地事务'}</button></HoverHint></article>}</section>;
}
export function TravelStatus({world:w}:Pick<Props,'world'>){const reason=departureReason(w),impact=departureImpact(w);return <>{reason&&<p role="status">{reason}</p>}{impact.map(text=><p key={text}>{text}</p>)}</>;}
