import {useEffect,useId,useRef,useState,type ReactNode} from 'react';
import {CharacterPortrait} from './CharacterPortrait';
import {ArtIcon,type ArtName} from './ArtIcon';
import {politicalName} from '../core/government';
import type {World} from '../core/types';
import './personSelection.css';
export type PersonOption={id:string;score?:number;metric?:string;detail?:string;reason?:string|null};
export function PositionSeat({world,holder,title,icon='influence',status,onPerson,onManage,children,compact=false}:{world:World;holder?:string|null;title:string;icon?:ArtName;status?:ReactNode;onPerson?:(id:string)=>void;onManage?:()=>void;children?:ReactNode;compact?:boolean}){
 return <article className={'position-seat'+(compact?' position-seat--compact':'')}><button type="button" className="position-image" disabled={holder?!onPerson:!onManage} onClick={()=>holder?onPerson?.(holder):onManage?.()} aria-label={holder?politicalName(holder)+' · 查看人物':(compact?'选择':'任命')+title}>{holder?<CharacterPortrait characterId={holder} world={world}/>:<span className="position-vacant"><ArtIcon name={icon} size={40}/><span>虚位以待</span>{onManage&&<b>＋</b>}</span>}</button><strong className="position-name">{holder?politicalName(holder):'空缺'}</strong><button className="position-title" disabled={!onManage} onClick={onManage}><ArtIcon name={icon} size={22}/>{title}{onManage&&' ›'}</button>{status&&<small className="position-status">{status}</small>}{children}</article>;
}
export function PersonSelectionDialog({world,title,options,value,onSelect,onClose,onConfirm,confirmLabel='确定人选',pending=false,children,description}:{world:World;title:string;options:PersonOption[];value:string;onSelect:(id:string)=>void;onClose:()=>void;onConfirm:()=>void;confirmLabel?:string;pending?:boolean;children?:ReactNode;description?:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null),id=useId(),[query,setQuery]=useState(''),[sort,setSort]=useState<'score'|'name'>('score');
 useEffect(()=>{const dialog=ref.current!,previous=document.activeElement as HTMLElement|null;dialog.showModal();return()=>{dialog.close();if(previous?.isConnected)previous.focus();};},[]);
 const selected=options.find(p=>p.id===value),visible=options.filter(p=>(politicalName(p.id)+' '+(p.detail??'')).includes(query.trim())).sort((a,b)=>sort==='score'?(b.score??0)-(a.score??0)||politicalName(a.id).localeCompare(politicalName(b.id),'zh'):politicalName(a.id).localeCompare(politicalName(b.id),'zh'));
 return <dialog ref={ref} className="person-selection-dialog paper-dialog" aria-labelledby={id} onCancel={e=>{e.preventDefault();onClose();}} onKeyDown={e=>e.stopPropagation()}><header><h3 id={id}><ArtIcon name="person"/>{title}</h3><button aria-label="关闭选人" onClick={onClose}>×</button></header>{description&&<div className="person-selection-description">{description}</div>}<div className="person-selection-tools"><input autoFocus aria-label="搜索候选人" placeholder="搜索姓名、身份" value={query} onChange={e=>setQuery(e.target.value)}/><button aria-pressed={sort==='score'} onClick={()=>setSort('score')}>适任优先</button><button aria-pressed={sort==='name'} onClick={()=>setSort('name')}>姓名</button></div><div className="person-selection-grid">{visible.map(p=><button key={p.id} className="person-option" aria-pressed={value===p.id} data-unavailable={!!p.reason} onClick={()=>onSelect(p.id)} title={p.reason??p.detail}><CharacterPortrait characterId={p.id} world={world}/><strong>{politicalName(p.id)}</strong>{p.score!==undefined&&<b>{p.metric??'适任'} {p.score}</b>}{p.detail&&<small>{p.detail}</small>}{p.reason&&<small className="person-option-reason">{p.reason}</small>}</button>)}{!visible.length&&<p>{options.length?'没有匹配的人物。':'暂无候选人。'}</p>}</div><footer>{children}<div className="person-selection-decision"><button onClick={onClose}>取消</button><span>{selected?politicalName(selected.id):'请选择人物'}{selected?.reason&&<small role="status">{selected.reason}</small>}</span><button className="primary" disabled={pending||!selected||!!selected.reason} onClick={onConfirm}>{confirmLabel}</button></div></footer></dialog>;
}
/** Choice-only control for an action with additional parameters. No command is sent until its parent confirms. */
export function PersonChoice({world,title,value,onChange,options,pending=false,onPerson}:{world:World;title:string;value:string;onChange:(id:string)=>void;options:PersonOption[];pending?:boolean;onPerson?:(id:string)=>void}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(value);
 const selected=options.find(option=>option.id===value);
 return <><PositionSeat compact world={world} holder={value||null} title={title} status={selected?.score!==undefined?`${selected.metric??'能力'} ${selected.score}`:undefined} onPerson={onPerson} onManage={()=>{setDraft(value);setOpen(true);}}/>{open&&<PersonSelectionDialog world={world} title={title} value={draft} options={options} onSelect={setDraft} onClose={()=>setOpen(false)} pending={pending} onConfirm={()=>{onChange(draft);setOpen(false);}}/>}</>;
}
