import {useState} from 'react';
import {claimReason,rulerEligibility,claimantProvenance,type ClaimsCommand} from '../core/claims';
import {nobleRanks,nobleTitle,nobilityReason,type NobleRank,type NobilityCommand} from '../core/nobility';
import {historyOfRealm,historyOfTerritory,honorOfPerson,honorRecommendations,honorReason,type HonorCommand} from '../core/rulerHistory';
import {allPeople} from '../core/personRegistry';
import {isAlive,isDeceased} from '../core/lifeState';
import {allegianceRealm} from '../core/officeEligibility';
import {governmentOf,politicalName,currentRealm} from '../core/government';
import {personInfluence} from '../core/personalInfluence';
import {dynastyNameOptions} from '../core/dynastyNaming';
import {dateLabel} from '../core/world';
import type {RealmId} from '../core/realm';
import type {World,GameCommand} from '../core/types';
import {CharacterPortrait} from './CharacterPortrait';
import {ArtIcon} from './ArtIcon';
import {PersonChoice} from './PersonSelection';
import {RealmBadge} from './RealmBadge';
import {CommandButton} from './CommandButton';
import {ActionDialog} from './ActionDialog';
import {ConfirmAction} from './ConfirmAction';
import './politicalIdentity.css';

type Props={world:World;pending:boolean;send:(c:GameCommand)=>void;onPerson:(id:string)=>void};

export function ClaimPanel({world:w,realm:r,pending,send,onPerson,onPolitics}:{realm:RealmId;onPolitics?:()=>void}&Props){
 const [command,setCommand]=useState<ClaimsCommand|null>(null),[query,setQuery]=useState(''),[limit,setLimit]=useState(24),actor=w.characterId!,g=governmentOf(w,r);
 const candidates=allPeople(w).filter(p=>!rulerEligibility(w,r,p.id,{allowForeign:true})&&p.id!==g?.ruler&&(p.name.includes(query)||p.family?.includes(query)));
 const records=(w.claims?.records??[]).filter(c=>c.realm===r&&c.until===null&&isAlive(w,c.person));
 return <section className="political-identity"><h3><ArtIcon name="renown"/>君位宣称 <RealmBadge world={w} realm={r}/></h3><p className="political-note">宗室名分源于已录亲缘。支持拥立才成为活跃宣称；有名分仍须争取人心和兵力。</p><input type="search" aria-label="查找宣称候选人" placeholder="查找姓名或家族" value={query} onChange={e=>{setQuery(e.target.value);setLimit(24);}}/><div className="political-person-list">{candidates.slice(0,limit).map(p=>{const provenance=claimantProvenance(w,r,p.id),pledge=records.find(c=>c.person===p.id&&c.patron===actor),c:ClaimsCommand={type:'claim',action:pledge?'renounce':'support',realm:r,person:p.id};return <article key={p.id}><button className="political-person" onClick={()=>onPerson(p.id)}><CharacterPortrait world={w} characterId={p.id} compact/><span><strong>{politicalName(p.id,w)}</strong><small>{allegianceRealm(w,p.id)===r?'本国宗室':'异国／流亡人物'} · {pledge?'本人已支持':records.some(c=>c.person===p.id)?'已有拥立者':'潜在资格'}</small><small>{provenance?'亲缘来源：'+politicalName(provenance.person,w):'承统记录'}</small></span></button><CommandButton label={pledge?'撤回支持':'支持拥立'} icon="renown" pending={pending} reason={claimReason(w,c)} hint="明确支持此人的君位名分；不会立即换君、自动起兵或转移领土。" onClick={()=>setCommand(c)}/></article>;})}</div>{candidates.length>limit&&<button onClick={()=>setLimit(n=>n+24)}>继续查看宗室</button>}{!candidates.length&&<p className="political-note">尚无符合已录亲缘和承统条件的候选人。</p>}{onPolitics&&<CommandButton label="筹议拥立" icon="influence" hint="把名分与实际支持接入权力议案；受益君主、发起者和执政者分别选择。" onClick={onPolitics}/>}
 {command&&<ConfirmAction title={command.action==='support'?'支持君位宣称':'撤回拥立支持'} detail={`${politicalName(command.person,w)} · ${command.action==='support'?'为此人的承统名分留下公开支持，后续须另行发起议案或扶立战争。':'撤回本人支持；他人的拥立和已经发生的战争分别保留。'}`} confirmLabel="确认安排" pending={pending||!!claimReason(w,command)} onCancel={()=>setCommand(null)} onConfirm={()=>{if(pending||claimReason(w,command))return;send(command);setCommand(null);}}/>}
 </section>;
}

export function NobilityPanel({world:w,realm,person,pending,send,onPerson}:Props&{realm?:RealmId;person?:string}){
 const r=realm??currentRealm(w),g=governmentOf(w,r),[open,setOpen]=useState(false),[target,setTarget]=useState(person??''),[rank,setRank]=useState<NobleRank>('countyMarquis'),[name,setName]=useState(''),[rites,setRites]=useState(false),[revoke,setRevoke]=useState<NobilityCommand|null>(null);
 if(!g)return null;const grant:NobilityCommand={type:'nobility',action:'grant',person:target,rank,name,rites},reason=nobilityReason(w,grant),titles=(w.nobility?.titles??[]).filter(t=>t.realm===r&&t.until===null&&(!person||t.person===person));
 const options=allPeople(w).filter(p=>p.id!==g.ruler&&isAlive(w,p.id)&&allegianceRealm(w,p.id)===r).map(p=>({id:p.id,score:g.merit[p.id]??0,metric:'功绩',detail:'本人影响力 '+personInfluence(w,p.id)}));
 const current=target?nobleTitle(w,target):undefined;
 return <section className="political-identity"><h3><ArtIcon name="renown"/>爵位与殊礼</h3><div className="political-person-list">{titles.map(t=><article key={t.id}><button className="political-person" onClick={()=>onPerson(t.person)}><CharacterPortrait world={w} characterId={t.person} compact/><span><strong>{politicalName(t.person,w)}</strong><small>{t.name}{nobleRanks[t.rank].name}{t.rites?' · 加殊礼':''}</small></span></button>{w.characterId===g.ruler&&<CommandButton label="夺爵" icon="renown" danger pending={pending} reason={nobilityReason(w,{type:'nobility',action:'revoke',id:t.id})} hint="撤销爵位；影响持爵者好感和政治地位，官职与土地分别保留。" onClick={()=>setRevoke({type:'nobility',action:'revoke',id:t.id})}/>}</article>)}</div>{!titles.length&&<p className="political-note">{person?'尚无本朝所授爵位。':'本局尚无册封记录。'}</p>}{w.characterId===g.ruler&&<CommandButton label="册封晋爵" icon="renown" pending={pending} hint="选人、比较爵等、封号与礼仪成本；确认后由中央公库支付。" onClick={()=>{setTarget(person??'');setOpen(true);}}/>}
 {open&&<ActionDialog title="册封与晋爵" onClose={()=>setOpen(false)} actions={<><small className="political-confirm" role="status">{reason||`中央礼仪支出 ${nobleRanks[rank].cost+(rites?160:0)} 钱，君主影响力 20。`}</small><button className="primary" disabled={pending||!!reason} onClick={()=>{if(pending||nobilityReason(w,grant))return;send(grant);setOpen(false);}}>确认册封</button></>}><div className="political-grant-layout"><PersonChoice world={w} title="受封者" value={target} options={options} onChange={id=>{setTarget(id);setName(nobleTitle(w,id)?.name??'');}} pending={pending} onPerson={onPerson}/><div><fieldset className="political-options"><legend>爵等</legend>{(Object.keys(nobleRanks) as NobleRank[]).map(key=><label key={key}><input type="radio" name="noble-rank" checked={rank===key} onChange={()=>setRank(key)}/><span><strong>{nobleRanks[key].name}</strong><small>中央 {nobleRanks[key].cost} 钱 · 功绩 {nobleRanks[key].merit} · 影响力 {nobleRanks[key].influence}</small></span></label>)}</fieldset><label className="political-input">封号<input value={name} maxLength={4} onChange={e=>setName(e.target.value)}/></label><div className="political-suggestions">{target&&dynastyNameOptions(w,r,target).slice(0,3).map(o=><button key={o.name} aria-pressed={name===o.name} title={o.reason} onClick={()=>setName(o.name)}>{o.name}</button>)}</div><label className="political-check"><input type="checkbox" checked={rites} onChange={e=>setRites(e.target.checked)}/>加殊礼 · 另支中央 160 钱；须国公或王，功绩与影响力各 80</label></div></div>{current&&<p>现为 {current.name}{nobleRanks[current.rank].name}；晋爵或加殊礼承接现有身份。</p>}<p className="political-note">爵位提高个人政治权重和家族声望，好感变化联动集团满意度；它不授予行政辖地、官职或军队。</p></ActionDialog>}
 {revoke&&<ConfirmAction title="撤销爵位" detail="持爵者好感降低，爵位带来的政治权重和家族声望不再生效；官职、军队和土地保留。" confirmLabel="确认夺爵" danger pending={pending||!!nobilityReason(w,revoke)} onCancel={()=>setRevoke(null)} onConfirm={()=>{if(pending||nobilityReason(w,revoke))return;send(revoke);setRevoke(null);}}/>}
 </section>;
}

export function RulerHistoryPanel({world:w,realm,territory,onPerson,pending=false,send}:{world:World;realm?:RealmId;territory?:string;onPerson:(id:string)=>void;pending?:boolean;send?:(c:GameCommand)=>void}){
 const [honorTenure,setHonorTenure]=useState<number|null>(null);
 const records=territory?historyOfTerritory(w,territory):historyOfRealm(w,realm??currentRealm(w));
 return <section className="political-identity"><h3><ArtIcon name="renown"/>{territory?'历任地方主官':'历任君主与执政'}</h3><div className="political-history">{records.slice().reverse().map((t,i)=>{const honor='id'in t?honorOfPerson(w,t.realm,t.person):undefined;return <article key={i}><button className="political-person" onClick={()=>onPerson(t.person)}><CharacterPortrait world={w} characterId={t.person} compact/><span><strong>{politicalName(t.person,w)}{honor?' · '+honor.posthumous+(honor.temple?'／'+honor.temple:''):''}</strong><small>{'office'in t?t.office==='ruler'?'君主':'实际执政':'地方主官'} · {dateLabel(t.from,w.scriptId)} — {t.until===null?'今':dateLabel(t.until,w.scriptId)}</small><small>{'basis'in t?({initial:'开局任职',migration:'恢复存档时确认',succession:'依序承继',designation:'指定承继',power:'政治交接',founding:'建立国统',appointment:'任命'}[t.basis]):'本局任职记录'}</small></span></button>{send&&'office'in t&&t.office==='ruler'&&t.until!==null&&isDeceased(w,t.person)&&!honor&&t.realm===currentRealm(w)&&<CommandButton label="议谥" icon="renown" reason={honorReason(w,{type:'honor',action:'confer',tenure:t.id,posthumous:'简'})} pending={pending} hint="为已故前任议定谥号与庙号；亡国与复位任期也按本局记录处理。" onClick={()=>setHonorTenure(t.id)}/>}</article>;})}</div>{honorTenure!==null&&send&&<ActionDialog title="为前任议谥" onClose={()=>setHonorTenure(null)} cancelLabel="返回往事" actions={null}><HonorChoice world={w} tenure={honorTenure} pending={pending} send={send} onPerson={onPerson}/></ActionDialog>}{!records.length&&<p className="political-note">尚无本局任职记录。</p>}<p className="political-note">任期只记录本局实际交接；旧档从恢复时起记，不补造历史任期。</p></section>;
}

export function HonorChoice({world:w,tenure,pending,send,onPerson}:Props&{tenure:number}){
 const t=w.rulerHistory?.tenures.find(t=>t.id===tenure),recommended=honorRecommendations(w,tenure),[posthumous,setPosthumous]=useState(recommended.posthumous),[temple,setTemple]=useState(recommended.temple);
 if(!t)return <p>这份继位文书已不再有效。</p>;if(honorOfPerson(w,t.realm,t.person)||w.rulerHistory?.notifications.find(n=>n.tenure===tenure)?.acknowledged&&!!honorReason(w,{type:'honor',action:'confer',tenure,posthumous:'简'}))return <p className="political-note">继位文书已经处理，可在国家往事中查看本次交接与称号。</p>;const c:HonorCommand={type:'honor',action:'confer',tenure,posthumous,temple},reason=honorReason(w,c),canConfer=!honorReason(w,{...c,posthumous:recommended.posthumous,temple:''}),current=governmentOf(w,t.realm);
 return <section className="political-identity"><div className="political-succession-chain"><button className="political-person" onClick={()=>onPerson(t.person)}><CharacterPortrait world={w} characterId={t.person} compact/><span><strong>{politicalName(t.person,w)}</strong><small>{isDeceased(w,t.person)?'大行君主':'前任君主'} · 在位 {Math.max(0,(t.until??w.day)-t.from)} 日</small></span></button>{current&&<button className="political-person" onClick={()=>onPerson(current.ruler)}><CharacterPortrait world={w} characterId={current.ruler} compact/><span><strong>{politicalName(current.ruler,w)}</strong><small>新君践祚</small></span></button>}</div>{canConfer&&<><p>{recommended.reason}</p><div className="political-suggestions">{recommended.choices.map((choice,i)=><button key={i} aria-pressed={posthumous===choice.posthumous&&temple===choice.temple} title={choice.reason} onClick={()=>{setPosthumous(choice.posthumous);setTemple(choice.temple);}}>{choice.posthumous}{choice.temple?'／'+choice.temple:''}</button>)}</div><label className="political-input">谥号<input maxLength={8} value={posthumous} onChange={e=>setPosthumous(e.target.value)}/></label><label className="political-input">庙号<input maxLength={4} value={temple} placeholder="可留空" onChange={e=>setTemple(e.target.value)}/></label><p className="political-note">称号记录对前任的评价，不追改生前功绩与数值。</p><p role="status">{reason}</p><button className="primary" disabled={pending||!!reason} onClick={()=>{if(!pending&&!honorReason(w,c))send(c);}}>确认议谥与继位文书</button></>}{!canConfer&&<><p className="political-note">{isDeceased(w,t.person)?reason:'前任仍在世；此时只能确认君位交接，不能授予身后称号。'}</p><button className="primary" disabled={pending||!!honorReason(w,{type:'honor',action:'acknowledge',tenure})} onClick={()=>send({type:'honor',action:'acknowledge',tenure})}>知道了</button></>}</section>;
}
