import {loadingDays} from '../core/roadCapacity';
import {useState} from 'react';
import {populationQuote,populationReason,type PopulationCommand} from '../core/population';
import {playerRealm} from '../core/realm';
import {siteById} from '../data/scenario';
import {ArtIcon} from './ArtIcon';
import {HoverHint} from './HoverHint';
import {ConfirmAction} from './ConfirmAction';
import type {World,GameCommand} from '../core/types';
export function PopulationPanel({world:w,site,send,pending}:{world:World;site:string;send:(c:GameCommand)=>void;pending:boolean}){
 const [to,setTo]=useState(''),[amount,setAmount]=useState(100),[kind,setKind]=useState<'assisted'|'forced'|'raid'|'grain'>('assisted'),[confirm,setConfirm]=useState(false);
 if(!w.realm)return null;const r=playerRealm(w),cmd:Extract<PopulationCommand,{action:'transfer'}>={type:'population',action:'transfer',from:site,to,amount,kind},reason=populationReason(w,cmd),q=to&&siteById[to]&&Number.isSafeInteger(amount)&&amount>0?populationQuote(w,cmd):null;
 const transfers=w.realm.population?.transfers.filter(t=>t.from===site||t.to===site).slice(-10)??[];
 return <section className="city-population"><h3><ArtIcon name="person" size={24}/>迁民与转运</h3><div className="city-policy-grid">{([['assisted','招徕安置','person'],['forced','强制迁徙','influence'],['raid','掠夺人口','army'],['grain','运送公粮','grain']] as const).map(([id,label,icon])=><button key={id} aria-pressed={kind===id} onClick={()=>{setKind(id);setConfirm(false);}}><ArtIcon name={icon} size={28}/><span><strong>{label}</strong></span></button>)}</div><div className="city-civic-metrics"><label>目的地 <select value={to} onChange={e=>{setTo(e.target.value);setConfirm(false);}}><option value="">选择城市</option>{Object.entries(w.realm.cities).filter(([id,c])=>id!==site&&c.owner===r&&c.controller===r).map(([id])=><option value={id} key={id}>{siteById[id].name}</option>)}</select></label><label>{kind==='grain'?'公粮':'人口'} <input type="number" min={1} max={1000000} value={amount} onChange={e=>{setAmount(Number(e.target.value));setConfirm(false);}}/></label></div>{q&&<p>预计至少 {q.days} 日（道路排队另计） · 预计抵达 {q.arrived} · 损耗 {q.lossRate}% · 中央公款 {q.coins} / 公粮 {q.grain}</p>}<div className="city-command-row"><HoverHint label="组织队伍" content={reason||'出发即扣除原地人口或粮食；途中受道路控制影响。已用经费不退。都城调粮可动用中央粮储。'}><button disabled={pending||!!reason} onClick={()=>setConfirm(true)}><ArtIcon name={kind==='grain'?'grain':'world'} size={24}/>组织队伍</button></HoverHint></div>{confirm&&<ConfirmAction title='确认组织队伍？' detail={<><p>{siteById[site].name} → {siteById[to]?.name} · {amount} {kind==='grain'?'粮':'人'}；预计至少 {q?.days??'—'} 日，抵达 {q?.arrived??'—'}，损耗 {q?.lossRate??'—'}%。</p><p>出发即扣除原地人口或公粮；中央公款 {q?.coins??'—'}、公粮 {q?.grain??'—'}，已用经费不退。</p></>} confirmLabel='确认出发' danger pending={pending||!!reason} onCancel={()=>setConfirm(false)} onConfirm={()=>{if(pending||reason)return;send(cmd);setConfirm(false);}}/>}{transfers.map(t=><div key={t.id}><strong>{siteById[t.from].name} → {siteById[t.to].name}</strong><small> · {t.sent} {t.kind==='grain'?'粮':'人'} · {t.status==='traveling'?(w.realm!.cities[t.route[t.leg+1]].controller!==t.realm?'道路受阻':`预计余 ${t.durations.slice(t.leg).reduce((n,d,i)=>n+d+loadingDays(t.route[t.leg+i],t.route[t.leg+i+1],t.sent-(i===0?(t.loaded??0):0)),0)-t.elapsed} 日${t.elapsed===0?' · 等候装运':''}`):`已接收 ${t.arrived} / 损耗 ${t.lost}`}</small>{t.status==='traveling'&&!t.returning&&<HoverHint label="撤回队伍" content={populationReason(w,{type:'population',action:'return',id:t.id})||'原路返还，损耗增加 5%，已用经费不退'}><button disabled={pending||!!populationReason(w,{type:'population',action:'return',id:t.id})} onClick={()=>send({type:'population',action:'return',id:t.id})}>撤回</button></HoverHint>}</div>)}</section>;
}
