import {afterCommand} from './actionFeedback';
import {CommandButton} from './CommandButton';
import {loadingDays} from '../core/roadCapacity';
import {useState} from 'react';
import {populationQuote,populationReason,type PopulationCommand} from '../core/population';
import {playerRealm} from '../core/realm';
import {siteById} from '../data/scenario';
import {ArtIcon} from './ArtIcon';
import {HoverHint} from './HoverHint';
import {ActionDialog} from './ActionDialog';
import type {World,GameCommand} from '../core/types';
export function PopulationPanel({world:w,site,send,pending}:{world:World;site:string;send:(c:GameCommand)=>Promise<boolean>;pending:boolean}){
 const [to,setTo]=useState(''),[amount,setAmount]=useState(100),[kind,setKind]=useState<'assisted'|'forced'|'raid'|'grain'>('assisted'),[open,setOpen]=useState(false);
 if(!w.realm)return null;const r=playerRealm(w),cmd:Extract<PopulationCommand,{action:'transfer'}>={type:'population',action:'transfer',from:site,to,amount,kind},reason=populationReason(w,cmd),q=to&&siteById[to]&&Number.isSafeInteger(amount)&&amount>0?populationQuote(w,cmd):null;
 const transfers=w.realm.population?.transfers.filter(t=>t.from===site||t.to===site).slice(-10)??[];
 return <section className="city-population"><h3><ArtIcon name="person" size={24}/>迁民与转运</h3><div className="city-policy-grid">{([['assisted','招徕安置','person'],['forced','强制迁徙','influence'],['raid','掠夺人口','army'],['grain','运送公粮','grain']] as const).map(([id,label,icon])=><CommandButton key={id} label={label} icon={icon} pending={pending} selected={open&&kind===id} hint={{assisted:'预览安置人数、目的地、中央钱粮与沿途损耗。',forced:'预览强制迁徙的人数、费用、地方后果与沿途损耗。',raid:'预览掠夺来源、执行条件、费用与沿途损耗。',grain:'预览公粮来源、目的地、运输费用与沿途损耗。'}[id]} onClick={()=>{setKind(id);setOpen(true);}}/>)}</div>{open&&<ActionDialog title={{assisted:'招徕安置',forced:'强制迁徙',raid:'掠夺人口',grain:'运送公粮'}[kind]} onClose={()=>setOpen(false)} actions={<button className="primary" disabled={pending||!!reason} onClick={()=>{if(pending||populationReason(w,cmd))return;void afterCommand(send(cmd),()=>{setOpen(false);});}}>确认出发</button>}><div className="city-civic-metrics"><label>目的地 <select value={to} onChange={e=>setTo(e.target.value)}><option value="">选择城市</option>{Object.entries(w.realm.cities).filter(([id,c])=>id!==site&&c.owner===r&&c.controller===r).map(([id])=><option value={id} key={id}>{siteById[id].name}</option>)}</select></label><label>{kind==='grain'?'公粮':'人口'} <input type="number" min={1} max={1000000} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label></div><p>{siteById[site].name} → {siteById[to]?.name??'待选目的地'} · {amount} {kind==='grain'?'粮':'人'}。预计至少 {q?.days??'—'} 日（道路排队另计），抵达 {q?.arrived??'—'}，损耗 {q?.lossRate??'—'}%。</p><p>出发即扣除原地人口或公粮；中央公款 {q?.coins??'—'}、公粮 {q?.grain??'—'}，已用经费不退。途中受道路控制影响；都城调粮可动用中央粮储。</p>{reason&&<p className="service-warning" role="status">{reason}</p>}</ActionDialog>}{transfers.map(t=><div key={t.id}><strong>{siteById[t.from].name} → {siteById[t.to].name}</strong><small> · {t.sent} {t.kind==='grain'?'粮':'人'} · {t.status==='traveling'?(w.realm!.cities[t.route[t.leg+1]].controller!==t.realm?'道路受阻':`预计余 ${t.durations.slice(t.leg).reduce((n,d,i)=>n+d+loadingDays(t.route[t.leg+i],t.route[t.leg+i+1],t.sent-(i===0?(t.loaded??0):0)),0)-t.elapsed} 日${t.elapsed===0?' · 等候装运':''}`):`已接收 ${t.arrived} / 损耗 ${t.lost}`}</small>{t.status==='traveling'&&!t.returning&&<HoverHint label="撤回队伍" content={populationReason(w,{type:'population',action:'return',id:t.id})||'原路返还，损耗增加 5%，已用经费不退'}><button disabled={pending||!!populationReason(w,{type:'population',action:'return',id:t.id})} onClick={()=>send({type:'population',action:'return',id:t.id})}>撤回</button></HoverHint>}</div>)}</section>;
}
