import {RealmBadge} from './RealmBadge';
import './publicSuccession.css';
import {useState} from 'react';
import {PositionSeat,PersonSelectionDialog} from './PersonSelection';
import {ArtIcon} from './ArtIcon';
import {HoverHint} from './HoverHint';
import {governmentOf,currentRealm,governmentReason,politicalName,governingExecutives,type GovernmentCommand} from '../core/government';
import {publicFamily,publicSuccessor,successionCandidates,type PublicOffice} from '../core/publicSuccession';
import {isAlive} from '../core/lifeState';
import type {RealmId} from '../core/realm';
import type {World} from '../core/types';
export function PublicSuccessionPanel({world:w,realm,compact=false,pending,send,onPerson}:{world:World;realm?:RealmId;compact?:boolean;pending:boolean;send:(c:GovernmentCommand)=>void;onPerson:(id:string)=>void}){
 const r=realm??currentRealm(w),g=governmentOf(w,r)!,own=r===currentRealm(w),executive=own&&governingExecutives(w,r).includes(w.characterId!),[office,setOffice]=useState<PublicOffice|null>(null),[candidate,setCandidate]=useState(''),[name,setName]=useState('');
 const successions=w.life?.successions.filter(e=>e.realm===r)??[],regimes=w.realm!.governments!.regimes.filter(v=>v.realm===r);
 const person=(id:string|null,label:string)=><PositionSeat world={w} holder={id} title={label} onPerson={onPerson} status={id&&!isAlive(w,id)?'已故 · 位虚':undefined}/>;
 const choices=office?successionCandidates(w,r).filter(id=>id!==(office==='ruler'?g.ruler:g.executives[0])):[],chosen=choices.includes(candidate)?candidate:choices[0]??'',newHouse=office==='ruler'&&publicFamily(chosen)!==publicFamily(g.ruler),command={type:'government',action:'nominate',office:office??'ruler',candidate:chosen,...(newHouse?{name}:{})} as const;
 return <section className={'public-succession'+(compact?' public-succession--court':'')}>{compact?<><HoverHint label="继承安排" content="君位与执政分别交接；未指定时依成年子嗣和同族长幼承继，官职不随家产继承。"><h3>继统</h3></HoverHint><div className="court-successor-seats">{(['ruler','executive'] as const).map(key=>{const next=publicSuccessor(w,r,key),mayManage=executive||own&&key==='ruler'&&w.characterId===g.ruler;return <PositionSeat key={key} world={w} holder={next} title={key==='ruler'?'君位继承':'执政继任'} icon={key==='ruler'?'renown':'influence'} status={next?(g.heirs?.[key]===next?'已指定':'依序承继'):'暂无合资格者'} onPerson={onPerson} onManage={mayManage?()=>{setOffice(key);setCandidate(g.heirs?.[key]??'');setName(key==='ruler'?g.heirs?.dynasty??'':'');}:undefined}/>;})}</div>{g.heirs?.dynasty&&<small>承统国号：{g.heirs.dynasty}</small>}</>:<><p>君位与执政分别议定；指定者优先，未指定时依成年子嗣、同族长幼承继。</p>{(['ruler','executive'] as const).map(key=>{const holder=key==='ruler'?g.ruler:g.executives[0]??null,next=publicSuccessor(w,r,key);return <article key={key}><h3><ArtIcon name={key==='ruler'?'renown':'influence'}/>{key==='ruler'?'君位传承':'执政交接'}</h3><div className="succession-chain">{person(holder,key==='ruler'?'在位君主':'当前执政')}<span aria-hidden="true">→</span>{person(next,g.heirs?.[key]===next&&next?'已指定':'依序继承')}</div>{key==='ruler'&&g.heirs?.dynasty&&<p>异姓承统后国号：<RealmBadge realm={r} world={w} name={g.heirs.dynasty}/></p>}<button aria-expanded={office===key} onClick={()=>{setOffice(office===key?null:key);setCandidate(g.heirs?.[key]??'');setName(key==='ruler'?g.heirs?.dynasty??'':'');}}>议定继承 ›</button></article>;})}
</>} {own&&office&&<PersonSelectionDialog world={w} title={office==='ruler'?'议定君位继承':'议定执政继任'} value={chosen} onSelect={id=>{setCandidate(id);setName('');}} onClose={()=>setOffice(null)} pending={pending} description={newHouse?'异姓继承人在君主身后建立新朝，承接本国实际控制的辖地。':'在位者去世后交接，不会立即撤换现任人物。'} options={choices.map(id=>({id,score:g.merit[id]??0,metric:'功绩',reason:governmentReason(w,{...command,candidate:id,...(office==='ruler'&&publicFamily(id)!==publicFamily(g.ruler)?{name}:{name:undefined})})}))} confirmLabel="指定继承人 · 20 影响力" onConfirm={()=>{if(pending||governmentReason(w,command))return;send(command);setOffice(null);}}>{newHouse&&<label>承统国号 <input value={name} maxLength={6} placeholder="新国号" onChange={e=>setName(e.target.value)}/></label>}{g.heirs?.[office]&&<button disabled={pending||!!governmentReason(w,{type:'government',action:'nominate',office,candidate:null})} onClick={()=>{send({type:'government',action:'nominate',office,candidate:null});setOffice(null);}}>撤销指定</button>}</PersonSelectionDialog>}

 {!compact&&(successions.length>0||regimes.length>1)&&<section className="detail-record-group"><h4>传承纪事</h4>{successions.slice(-4).map((e,i)=><p key={i}>第 {e.day} 日 · {politicalName(e.deceased)}身后，{politicalName(e.ruler)}居君位；{e.executives.map(politicalName).join('、')||'无人'}执政。</p>)}{regimes.slice(-4).map(v=><p key={v.id}><RealmBadge realm={r} world={w} name={v.name??({liang:'梁',east:'东魏',west:'西魏',qi:'北齐',zhou:'北周',chen:'陈'} as Record<string,string>)[v.dynasty]}/> · 第 {v.from} 日 — {v.until??'今'}</p>)}</section>}
 </section>;
}
