import {useEffect,useRef,useState,useMemo} from 'react';
import {createPortal} from 'react-dom';
import type {World,GameCommand} from '../core/types';
import {authorityGrant} from '../core/authority';
import {playerRealm} from '../core/realm';
import {troopKinds,type TroopKind,type Regiment} from '../core/armyOrganization';
import {recruitmentPlanQuote,type RecruitmentPlanCommand} from '../core/recruitmentPlans';
import {act} from '../core/world';
import {siteById} from '../data/scenario';
export function RecruitmentPlanDialog({world:w,pending,send,onClose}:{world:World;pending:boolean;send:(c:GameCommand)=>void;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),r=playerRealm(w),[counts,setCounts]=useState<Record<string,number>>({}),[kind,setKind]=useState<TroopKind>('shield'),[service,setService]=useState<Regiment['service']>('levy'),[rally,setRally]=useState('');
 useEffect(()=>{const prev=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>{ref.current?.close();prev?.focus();};},[]);
 const sites=Object.keys(w.realm!.cities).filter(site=>authorityGrant(w,w.characterId!,'levy',{realm:r,site}).allowed),command:RecruitmentPlanCommand=useMemo(()=>({type:'recruitmentPlan',entries:Object.entries(counts).filter(([,n])=>n>0).map(([site,count])=>({site,count,kind,service})),rally:rally||undefined}),[counts,kind,service,rally]),quote=useMemo(()=>recruitmentPlanQuote(w,command,act),[w,command]);
 const totals=quote.rows.reduce((v,row)=>({troops:v.troops+row.troops,coins:v.coins+row.coins,grain:v.grain+row.grain,pay:v.pay+row.pay,food:v.food+row.food}),{troops:0,coins:0,grain:0,pay:0,food:0});
 return createPortal(<dialog ref={ref} className="military-plan-dialog" aria-labelledby="recruitment-plan-title" onCancel={e=>{e.preventDefault();onClose();}} onKeyDown={e=>e.stopPropagation()}><h2 id="recruitment-plan-title">征募与集结</h2><div className="military-plan-body"><div className="military-plan-parameters"><label>兵种<select value={kind} onChange={e=>setKind(e.target.value as TroopKind)}>{Object.entries(troopKinds).map(([id,v])=><option key={id} value={id}>{v.name}</option>)}</select></label><label>兵役<select value={service} onChange={e=>setService(e.target.value as Regiment['service'])}><option value="levy">征发兵 · 训练 30 日</option><option value="standing">常备兵 · 训练 60 日</option></select></label><label>集结地<select value={rally} onChange={e=>setRally(e.target.value)}><option value="">训练后原地驻留</option>{Object.keys(w.realm!.cities).filter(id=>w.realm!.cities[id].controller===r).map(id=><option key={id} value={id}>{siteById[id].name}</option>)}</select></label></div><p>每个兵团 200 人、携粮 60；每处组成一军，最多 6000 人。下单整份校验，训练、停滞与集结按实际状态推进。</p><div className="military-recruit-sites">{sites.map(site=><label key={site}><input type="checkbox" checked={!!counts[site]} onChange={e=>setCounts(v=>({...v,[site]:e.target.checked?1:0}))}/><span>{siteById[site].name}</span><input aria-label={siteById[site].name+'兵团数'} type="number" min={1} max={30} value={counts[site]||1} disabled={!counts[site]||pending} onChange={e=>setCounts(v=>({...v,[site]:Number(e.target.value)}))}/><small>人口 {w.realm!.cities[site].population} · 粮 {w.realm!.cities[site].grain}</small></label>)}</div>{quote.rows.length>0&&<><p>合计 {totals.troops} 人 · 一次支出 {totals.coins} 钱、{totals.grain} 粮 · 后续军饷 {totals.pay}/月、军粮 {totals.food}/日。</p><div className="military-preview-rows">{quote.rows.map(row=><article key={row.site}><strong>{siteById[row.site].name} · {row.troops} 人</strong><span>出资：{authorityGrant(w,w.characterId!,'levy',{realm:r,site:row.site}).source} · {row.coins} 钱</span><span>最早训练完：第 {row.ready} 日 · 集结另需 {row.travel} 行军日</span><span>剩余人口 {row.population} · 常规民食安全余量 {row.foodReserve}{row.foodReserve<0?'，下次民食结算存在缺口':''}</span></article>)}</div><small>最早日期未包含欠饷、缺粮、失守、通路中断与装运等待造成的延误。</small></>}{quote.reason&&<p role="status" className="service-warning">{quote.reason}</p>}</div><footer><button autoFocus onClick={onClose}>取消</button><button className="primary" disabled={pending||!!quote.reason} onClick={()=>{if(recruitmentPlanQuote(w,command,act).reason)return;send(command);onClose();}}>确认征募计划</button></footer></dialog>,document.body);
}
