import {RealmBadge} from './RealmBadge';
import {PersonChoice,PositionSeat} from './PersonSelection';
import {attributes} from '../core/social';
import {useState} from 'react';
import {assignmentTemplates,assignmentPhases,servicePriorities,type AssignmentKind,type ServicePriority} from '../data/assignments';
import {serviceChief,serviceCandidates,serviceRealm,serviceReason,assignmentOptions,careerStanding,recommendedPriority,type ServiceCommand} from '../core/assignments';
import {governmentOf,politicalName,regimeName} from '../core/government';
import {realms,capital,type RealmId} from '../core/realm';
import {siteById} from '../data/scenario';
import {AssignmentPanel,type ServiceProps} from './AssignmentPanel';
import {ArtIcon,type ArtName} from './ArtIcon';
import './service.css';
export function CouncilPanel({world:w,pending,send,onPerson}:ServiceProps){
 const r=serviceRealm(w.characterId!)!,c=w.service?.councils[r],chief=serviceChief(w,r);if(!c)return null;
 const action=(command:ServiceCommand,label:string)=>{const reason=serviceReason(w,command);return <div className="realm-action"><button disabled={pending||!!reason} onClick={()=>send(command)}>{label}</button>{reason&&<small>{reason}</small>}</div>;};
 return <section className="service-council"><small>本季评议 · 余 {90-w.day%90} 日</small><h3>{servicePriorities[c.priority]}</h3><div className="assignment-officers"><PositionSeat world={w} holder={chief} title="执政" onPerson={onPerson}/><p>已办结 {c.completed} / 2 项</p></div><p>季末办结两项，朝野支持 +3；不足两项 −2。符合本季重心的差事主办考绩总额为 24，其余为 20，按贡献分配。</p><p>当前建议：{servicePriorities[recommendedPriority(w,r)]}</p>{c.lastResult&&<p>{c.lastResult}</p>}{c.reply&&<p>第 {c.reply.day} 日 · {c.reply.text}</p>}
 {c.proposal?<><p>{politicalName(c.proposal.actor)}上书，请以「{servicePriorities[c.proposal.priority]}」为重心。</p>{chief===w.characterId?<div className="realm-actions">{action({type:'service',action:'council-accept'},'采纳上书')}{action({type:'service',action:'council-decline'},'维持原议')}</div>:<p>等待执政者裁决，请继续时间。</p>}</>:(!c.decided||chief!==w.characterId&&!c.petitioned.includes(w.characterId!))&&<div className="realm-actions">{(Object.keys(servicePriorities) as ServicePriority[]).map(priority=><div key={priority}>{action({type:'service',action:'priority',priority},(chief===w.characterId?'议定：':'上书：')+servicePriorities[priority])}</div>)}</div>}</section>;
}
export function ServiceProfile({world:w,person,onOpen}:Pick<ServiceProps,'world'>&{person:string;onOpen:()=>void}){if(!w.service?.enabled)return <button onClick={onOpen}>差事与生涯 →</button>;const tasks=w.service.tasks.filter(t=>t.phase!=='closed'&&(t.officer===person||t.helper===person||t.invitation?.person===person)),r=serviceRealm(person);if(!r)return null;return <section className="service-profile"><h3>任职履历</h3><p>官僚功绩 {governmentOf(w,r)?.merit[person]??0} · 可用于请任与军务授权</p>{(Object.keys(servicePriorities) as ServicePriority[]).map(category=>{const p=careerStanding(w,person,category);return <p key={category}>{p.name} · 完成 {p.count} 项 · 对应差事效率 +{p.bonus}</p>;})}{tasks.map(t=><p key={t.id}>{siteById[t.site].name}{assignmentTemplates[t.kind].name} · {assignmentPhases[t.phase]}{t.invitation?.person===person?' · 邀请待答':''}</p>)}<button onClick={onOpen}>查看差事簿 →</button></section>;}
export function ServicePanel(props:ServiceProps&{initialTaskId?:number;initialTab?:'active'|'council'}){
 const {world:w,pending,send,onPerson}=props,r=serviceRealm(w.characterId!)!,s=w.service;
 const [tab,setTab]=useState<'council'|'offers'|'active'|'archive'|'career'>(props.initialTab??'active'),[selected,setSelected]=useState<number|null>(props.initialTaskId??null),[kind,setKind]=useState<AssignmentKind>('relief'),[city,setCity]=useState(''),[officer,setOfficer]=useState(''),[target,setTarget]=useState<RealmId>(r==='west'?'east':'west');
 if(!s?.enabled)return <section className="service-welcome"><ArtIcon name="influence" size={56}/><h3>赴任议事</h3><p>从一城一事做起，与同僚共理国事。执政者议定目标、任命与考课；官员和宗室请命办理，积累功绩与声望。</p><p>每九十日评议，官员会主动呈请差事。进入后，梁、东魏、西魏均开始依照局势议事办差。</p><button className="primary" disabled={pending} onClick={()=>send({type:'service',action:'begin'})}>赴任议事</button></section>;
 const chief=serviceChief(w,r)===w.characterId,candidates=serviceCandidates(w,r),cities=Object.keys(w.realm!.cities).filter(id=>w.realm!.cities[id].owner===r&&w.realm!.cities[id].controller===r),site=cities.includes(city)?city:cities.includes(capital(r))?capital(r):cities[0]??'',candidate=chief?(candidates.some(c=>c.id===officer)?officer:candidates[0]?.id??''):w.characterId!,command={type:'service',action:'open',kind,site,officer:candidate,...(kind==='envoy'?{target}: {})} as const,reason=serviceReason(w,command),task=selected?s.tasks.find(t=>t.id===selected):undefined;
 const relevant=s.tasks.filter(t=>t.realm===r),active=relevant.filter(t=>t.phase!=='closed'),archive=relevant.filter(t=>t.phase==='closed').slice().reverse();
 return <div className="service-panel"><nav className="service-icon-nav detail-tabs" aria-label="差事章节">{([['active',`在办 ${active.length}`],['offers',chief?'委任':'请办'],['council','议事'],['archive','文书'],['career','履历']] as const).map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setSelected(null);}} title={label}><ArtIcon name={({active:'influence',offers:'city',council:'renown',archive:'world',career:'person'} as Record<string,ArtName>)[id]}/><span>{label}</span></button>)}</nav>
 {task?<><button onClick={()=>setSelected(null)}>← 返回差事簿</button><AssignmentPanel {...props} task={task}/></>:<>
 {tab==='council'&&<CouncilPanel {...props}/>}
 {tab==='career'&&<ServiceProfile world={w} person={w.characterId!} onOpen={()=>setTab('active')}/>}
 {(tab==='active'||tab==='archive')&&<>{(tab==='active'?active:archive).map(t=><button className="assignment-card" key={t.id} onClick={()=>setSelected(t.id)}><ArtIcon name={assignmentTemplates[t.kind].icon} size={42}/><span><strong>{siteById[t.site].name} · {assignmentTemplates[t.kind].name}</strong><small>{politicalName(t.officer)} · {assignmentPhases[t.phase]}{t.phase!=='closed'?` · 限期余 ${Math.max(0,t.deadline-w.day)} 日`:''}</small></span><span>→</span></button>)}{!(tab==='active'?active:archive).length&&<p>暂无{tab==='active'?'在办差事。':'结案文书。'}</p>}{tab==='active'&&<button onClick={()=>setTab('offers')}>{chief?'委任新差事':'请领新差事'} →</button>}</>}
 {tab==='offers'&&<><p>本国同时最多三案，每人限一项主办或协办。你可{chief?'委任可用人物':'自荐承办，由执政者批复'}。</p><div className="service-offers">{(Object.keys(assignmentTemplates) as AssignmentKind[]).map(id=><button key={id} aria-pressed={kind===id} onClick={()=>setKind(id)}><ArtIcon name={assignmentTemplates[id].icon}/>{assignmentTemplates[id].name}</button>)}</div><h3>{assignmentTemplates[kind].name}</h3><p>{assignmentTemplates[kind].description}</p><p>{assignmentTemplates[kind].effect}</p><label>办理城邑 <select value={site} onChange={e=>setCity(e.target.value)}>{cities.map(id=><option key={id} value={id}>{siteById[id].name}</option>)}</select></label>{chief&&<PersonChoice world={w} title="承办人" value={candidate} onChange={setOfficer} pending={pending} onPerson={onPerson} options={candidates.map(c=>({id:c.id,score:attributes(w,c.id)[assignmentTemplates[kind].skill],metric:"职务能力",reason:serviceReason(w,{...command,officer:c.id})}))}/>}{kind==='envoy'&&<div className="realm-choice-row" role="group" aria-label="出使政权">{realms.filter(x=>x!==r).map(x=><span key={x} data-selected={target===x}><RealmBadge realm={x} world={w}/><button aria-label={"选择出使"+regimeName(w,x)} aria-pressed={target===x} onClick={()=>setTarget(x)}>{target===x?"已选":"选择"}</button></span>)}</div>}
 <button className="primary" disabled={pending||!!reason} onClick={()=>{send(command);setTab('active');}}>{chief?'下达委任':'上书请命'}</button>{reason&&<p>{reason}</p>}<details><summary>本季推荐</summary>{assignmentOptions(w,r).slice(0,6).map((o,i)=><button key={i} onClick={()=>{setKind(o.kind);setCity(o.site);if(o.target)setTarget(o.target);}}>{siteById[o.site].name} · {assignmentTemplates[o.kind].name}</button>)}</details>{candidate&&<button onClick={()=>onPerson(candidate)}>查看承办人 →</button>}</>}
 </>}</div>;
}
