import {CourtIcon} from './CourtIcon';
import {useEffect,useId,useState,type CSSProperties,type ReactNode} from 'react';
import {phases,phaseIds,type CourtPhase} from '../data/court';
export function SituationWheel({phase,tension,realm,interactive=true}:{phase:CourtPhase;tension:number;realm:ReactNode;interactive?:boolean}){
 const [view,setView]=useState(phase),id=useId().replace(/:/g,'');
 useEffect(()=>setView(phase),[phase]);
 const displayed=interactive?view:phase,index=phaseIds.indexOf(displayed),preview=interactive&&view!==phase;
 return <div className="dynasty-dial" data-phase={displayed}><div className="dynasty-dial-window"><svg className="dynasty-disc" viewBox="0 0 360 360" style={{'--dial-angle':`${-index*120}deg`} as CSSProperties} role="img" aria-label={phases[displayed].name+'局势画像'}><defs>{phaseIds.map((p,i)=><pattern key={p} id={id+p} width="360" height="360" patternUnits="userSpaceOnUse"><image href={import.meta.env.BASE_URL+'art/court/dynasty-phases.png'} x={-i*360} y="0" width="1080" height="360" preserveAspectRatio="none"/></pattern>)}</defs>{phaseIds.map((p,i)=><path key={p} d="M180 180L24.1 90A180 180 0 0 1 335.9 90Z" transform={`rotate(${i*120} 180 180)`} fill={`url(#${id+p})`} stroke="#c2a36a" strokeWidth="3"/>)}<circle cx="180" cy="180" r="174" fill="none" stroke="#705130" strokeWidth="10"/><circle cx="180" cy="180" r="168" fill="none" stroke="#d1b47a" strokeWidth="1" strokeDasharray="2 5"/><circle cx="180" cy="180" r="21" fill="#223d30" stroke="#d1b47a" strokeWidth="3"/><path d="M170 180h20M180 170v20" stroke="#d1b47a" strokeWidth="2"/></svg><span className="dynasty-pointer" aria-hidden="true">◆</span>{interactive&&<div className="dynasty-phase-controls">{phaseIds.map(p=><button key={p} aria-pressed={p===view} aria-label={'查看'+phases[p].name+'局势'} title={phases[p].name+(p===phase?' · 当前':' · 预览')} onClick={()=>setView(p)}><span className="phase-art-medallion" data-phase={p}><CourtIcon name={p} size={36}/></span><small>{phases[p].name}</small></button>)}</div>}</div><div className="dynasty-dial-caption"><div><small>{realm}{preview?' · 局势预览':''}</small><CourtIcon name={displayed} size={30}/><strong>{phases[displayed].name}</strong></div>{preview?<button onClick={()=>setView(phase)}>返回当前</button>:<span>紧张 <b>{tension}</b></span>}<p>{phases[displayed].effect}</p></div></div>;
}
