import {politicalAction,type PolicyDomain} from '../core/politicalActions';
import {RealmBadge} from './RealmBadge';
import {CivilWarPanel} from './CareerSystems';
import {SituationWheel} from './SituationWheel';
import {useState} from 'react';
import {courtOf,courtEnabled,courtCatalysts,courtBonus,movementMood,movementPower,movementPowerParts,courtReason,foundingPause,type CourtCommand} from '../core/court';
import {currentRealm,governmentOf,politicalName} from '../core/government';
import {movements,movementIds,policies,type MovementId} from '../data/court';
import {ArtIcon,type ArtName} from './ArtIcon';
import {HoverHint} from './HoverHint';
import {CharacterPortrait} from './CharacterPortrait';
import {PersonSelectionDialog} from './PersonSelection';
import type {World,GameCommand} from '../core/types';
import './situation.css';
const icons:Record<MovementId,ArtName>={dynastic:'renown',expansion:'army',reform:'diligent',conservative:'frugal',unaligned:'person'};
export function SituationPanel({world:w,pending,send,onPerson}:{world:World;pending:boolean;send:(c:GameCommand)=>void;onPerson:(id:string)=>void}){
 const [tab,setTab]=useState<'overview'|'groups'|'history'>('overview'),[selected,setSelected]=useState<MovementId>('dynastic'),[cancel,setCancel]=useState(false),[recruit,setRecruit]=useState(false),[candidate,setCandidate]=useState('');
 const r=currentRealm(w),c=courtOf(w,r),g=governmentOf(w,r)!;if(!c)return null;
 const own=c.members[w.characterId!]??'unaligned',m=movementMood(w,r,selected),bonus=courtBonus(w,r),catalysts=courtCatalysts(w,r),delta=catalysts.reduce((n,v)=>n+v.value,0),enabled=courtEnabled(w,r);
 const action=(cmd:CourtCommand,label:string,icon:ArtName,detail:string)=>{const reason=courtReason(w,cmd);return <HoverHint label={label} content={<>{detail}{reason&&<p>{reason}</p>}</>}><button className="situation-action" disabled={pending||!!reason} onClick={()=>send(cmd)}><ArtIcon name={icon} size={24}/><span>{label}</span></button></HoverHint>;};
 const portrait=(id:string)=><button className="faction-person" key={id} onClick={()=>onPerson(id)} aria-label={'查看'+politicalName(id)}><CharacterPortrait characterId={id} world={w} compact/><span>{politicalName(id)}</span></button>;
 return <div className="situation-panel"><div className="situation-summary"><HoverHint label="局势阈值" content="每 30 日结算；紧张 40 转入动荡，80 转入危局，合法性低于 15 也会进入危局。改善条件可恢复安定。"><strong>{policies[c.policy].name}国策</strong></HoverHint><div className="situation-stat-row"><span>天命 <b>{g.legitimacy}</b></span><span>积弊 <b>{c.corruption}</b></span><span>支持 <b>{g.support}</b></span><span>紧张 <b>{c.tension}</b></span></div><p>税收 {bonus.tax}% · 军饷 {bonus.pay}% · 攻击 {bonus.attack}%</p></div><nav className="detail-tabs" aria-label="局势页面">{([['overview','王朝兴衰','renown'],['groups','利益集团','person'],['history','纪事','diligent']] as const).map(([id,label,icon])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}><ArtIcon name={icon} size={24}/>{label}</button>)}</nav>
 {!enabled&&<p>当前政体暂停集团与局势结算。</p>}
 {tab==='overview'&&<><SituationWheel phase={c.phase} tension={c.tension} realm={<RealmBadge realm={r} world={w}/>}/><section><h3>局势推力 <small>{enabled?30-w.day%30+' 日后 · '+(delta>=0?'+':'')+delta:'暂停结算'}</small></h3>{catalysts.map(v=><div className="court-catalyst" key={v.label}><span>{v.label}</span><b>{v.value>0?'+':''}{v.value}</b></div>)}{action({type:'court',action:'audit'},'整饬吏治','diligent','60 公款、15 影响力；积弊 −20、紧张 −10、支持 −3，冷却 90 日。')}</section><div className="situation-group-strip">{movementIds.filter(id=>id!=='unaligned').map(id=>{const a=movementMood(w,r,id);return <HoverHint key={id} label={movements[id].name} content={`${movements[id].name} · 势力 ${a.share}% · 满意 ${a.satisfaction} · 每期紧张 ${a.tension} / 支持 ${a.support}`}><button onClick={()=>{setSelected(id);setTab('groups');}}><ArtIcon name={icons[id]}/><span>{a.share}%</span></button></HoverHint>;})}</div></>}
 {tab==='groups'&&<><div className="situation-group-strip">{movementIds.map(id=><button key={id} aria-pressed={selected===id} onClick={()=>setSelected(id)} title={movements[id].name}><ArtIcon name={icons[id]}/><span>{movements[id].name}</span></button>)}</div><section className="faction-detail"><header><ArtIcon name={icons[selected]} size={38}/><div><h3>{movements[selected].name}</h3><small>{own===selected&&g.ruler!==w.characterId?'你的集团 · ':''}{c.favored===selected?'朝廷眷顾':''}</small></div><b>{m.share}%</b></header><p>{movements[selected].goal}</p><div className="situation-stat-row">{([['appointment','任官'],['reform','改革'],['tax','征税'],['military','军务'],['migration','迁民'],['welfare','赈济'],['commerce','商贸']] as [PolicyDomain,string][]).map(([domain,label])=>{const p=politicalAction(w,r,domain).parts.find(p=>p.id===selected);return p&&p.value?<HoverHint key={domain} label={label+'立场'} content={`本集团影响 ${p.value}；汇合其他集团后影响朝野支持、局势紧张及相关差事办理效率。`}><span>{label} <b>{p.value>0?'支持':'反对'}</b></span></HoverHint>:null;})}</div><div className="situation-stat-row"><HoverHint label="集团势力" content={<>{m.members.map(id=><div key={id}><strong>{politicalName(id)}</strong>{movementPowerParts(w,r,id).filter(p=>p.value).map(p=><p key={p.label}>{p.label} +{p.value}</p>)}</div>)}</>}><span>势力 <b>{m.power}</b></span></HoverHint><HoverHint label="满意度来源" content={<>{m.factors.map(f=><p key={f.label}>{f.label} {f.value>0?'+':''}{f.value}</p>)}{!m.factors.length&&'未结党或无成员不施加集团影响。'}</>}><span>满意 <b>{m.satisfaction}</b></span></HoverHint><span>每期紧张 <b>{m.tension>0?'+':''}{m.tension}</b></span><span>每期支持 <b>{m.support>0?'+':''}{m.support}</b></span></div>{m.leader&&<div className="faction-leader">{portrait(m.leader)}<span>集团领袖<br/><small>{m.members.length} 位成员</small></span></div>}<div className="faction-members">{m.members.filter(id=>id!==m.leader).map(portrait)}</div><div className="situation-actions">{g.ruler!==w.characterId&&action({type:'court',action:'join',group:selected},'加入','person','10 影响力，换党冷却 90 日。')}{selected!=='unaligned'&&action({type:'court',action:'favor',group:selected},'眷顾','renown','20 影响力，冷却 90 日；本派满意 +20，他派 −10。')}{own===selected&&g.ruler!==w.characterId&&<>{action({type:'court',action:'debate'},'主持清议','diligent','30 私人钱；个人势力 +25，持续及冷却 180 日。')}{action({type:'court',action:'petition'},'集团奏议','influence','领袖消耗 15 影响力；15 日待决，冷却 90 日。')}<button onClick={()=>setRecruit(true)}><ArtIcon name="gregarious" size={24}/>游说同道</button></>}</div></section>{g.ruler!==w.characterId&&<CivilWarPanel world={w} pending={pending} send={send} onPerson={onPerson}/>}</>}
 {tab==='history'&&<div className="situation-history">{c.history.length?c.history.slice().reverse().map((h,i)=><p key={i}><small>第 {h.day} 日</small>{h.text}</p>):<p>尚无朝局纪事。</p>}</div>}
 {c.petition&&tab!=='history'&&<section className="situation-petition"><h3>{movements[c.petition.group].name}奏议 <small>余 {Math.max(0,c.petition.due-w.day)} 日</small></h3>{portrait(c.petition.sponsor)}<p>{movements[c.petition.group].goal}</p><div className="situation-actions">{action({type:'court',action:'resolve',accept:true},'批准','steadfast','80 公款、20 影响力；支持 +5、紧张 −8，眷顾集团并调整国策或合法性。')}{action({type:'court',action:'resolve',accept:false},'否决','wary','支持 −5、紧张 +8。玩家执政逾期视为否决。')}</div></section>}
 {c.founding&&tab==='overview'&&<section><h3>{c.founding.name} · 承统议程</h3><progress max={120} value={c.founding.progress}/><p>{foundingPause(w,r)||`${c.founding.progress} / 120 日`}</p>{cancel?<><p>撤回后已付成本不退。</p>{action({type:'court',action:'cancel'},'确认撤回','wary','撤回后成本不退。')}<button onClick={()=>setCancel(false)}>保留议程</button></>:<button onClick={()=>setCancel(true)}>撤回议程</button>}</section>}
 {recruit&&<PersonSelectionDialog world={w} title="游说同道" value={candidate} onSelect={setCandidate} onClose={()=>setRecruit(false)} pending={pending} description="个人钱 30、影响力 10；接受度须达到 50。成功后加入你的集团，冷却 30 日。" options={Object.keys(c.members).filter(id=>id!==w.characterId).map(id=>({id,score:movementPower(w,r,id),metric:'个人势力',reason:courtReason(w,{type:'court',action:'convince',target:id})}))} confirmLabel="游说加入" onConfirm={()=>{send({type:'court',action:'convince',target:candidate});setRecruit(false);}}/>}
 </div>;
}
