import {canonicalTerritory,countyTerritory,localHasJurisdiction,localTitle} from '../core/localAdministration';
import {canCommission} from '../core/serviceMandates';
import {ConfirmAction} from './ConfirmAction';
import {useState} from 'react';
import {ArtIcon,Resource} from './ArtIcon';
import {DetailTabs} from './DetailTabs';
import {HoverHint} from './HoverHint';
import {CharacterPortrait} from './CharacterPortrait';
import {territoryAccount,accountName,fiscalPath,localBalance,grantFactors,grantPurposes,fiscalReason,superiorForCity,type FiscalCommand,type GrantRequest} from '../core/treasury';
import {playerRealm,executive,cityYield} from '../core/realm';
import {politicalName} from '../core/government';
import {siteById} from '../data/scenario';
import type {World,GameCommand} from '../core/types';
import './treasury.css';
export function TreasuryPanel({world:w,pending,send,site,onPerson,flat=false}:{world:World;pending:boolean;send:(c:GameCommand)=>void;site?:string;onPerson?:(id:string)=>void;flat?:boolean}){
 const [tab,setTab]=useState<'budget'|'requests'|'ledger'>('budget'),[amount,setAmount]=useState(100),[purpose,setPurpose]=useState<GrantRequest['purpose']>('construction'),[selectedSite,setSelectedSite]=useState(''),[confirmRelief,setConfirmRelief]=useState<string|null>(null);
 const r=playerRealm(w),s=w.realm!.fiscal,treasury=w.realm!.treasuries[r],chief=executive(w),cities=Object.entries(w.realm!.cities).filter(([id,c])=>(!site||site===id)&&c.owner===r&&c.controller===r&&canCommission(w,w.characterId!,r,id,'relief')),requests=s?.requests.filter(q=>q.realm===r&&(!site||q.site===site)&&(chief||q.actor===w.characterId||q.approver===w.characterId))??[],targetSite=cities.some(([id])=>id===selectedSite)?selectedSite:cities[0]?.[0]??'';
 const canAllocate=(id:string)=>chief||localHasJurisdiction(w,w.characterId!,countyTerritory(id),r);
 const ledger=(s?.entries??[]).filter(e=>e.realm===r&&(!site||e.from===fiscalPath(w,site)[0]||e.to===fiscalPath(w,site)[0])).slice(-60).reverse();
 if(site&&(w.realm!.cities[site].owner!==r||w.realm!.cities[site].controller!==r))return null;
 const action=(cmd:FiscalCommand,label:string)=>{const reason=fiscalReason(w,cmd);return <HoverHint label={label} content={reason||label}><button disabled={pending||!!reason} onClick={()=>cmd.action==='relief'?setConfirmRelief(cmd.site):send(cmd)}>{label}</button></HoverHint>;};
 return <section className={flat?'treasury-panel treasury-panel-flat':'treasury-panel'}>{!flat&&<h3><ArtIcon name="coins" size={26}/>公库</h3>}{!site&&<div className="treasury-central-summary"><Resource name="coins" value={treasury.coins} label="中央公款" caption/><Resource name="grain" value={treasury.grain} label="中央公粮" caption/></div>}{!flat&&<DetailTabs label="公库事务" value={tab} onChange={setTab} items={[{id:'budget',label:'预算',icon:'coins'},{id:'requests',label:'拨款'+(requests.some(q=>q.status==='pending')?' · '+requests.filter(q=>q.status==='pending').length:''),icon:'influence'},{id:'ledger',label:'账目',icon:'diligent'}]}/>}
 {(flat||tab==='requests')&&<>{flat&&(cities.length>0||requests.length>0)&&<h4>拨款与批示</h4>}{cities.length>0&&<><div className="treasury-form"><label>拨款钱数<input type="number" min={20} max={400} step={10} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label>{!canAllocate(targetSite)&&<label>用途<select value={purpose} onChange={e=>setPurpose(e.target.value as GrantRequest['purpose'])}>{Object.entries(grantPurposes).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label>}</div>{flat?targetSite&&<div className="treasury-request-city"><label>城邑 <select value={targetSite} onChange={e=>setSelectedSite(e.target.value)}>{cities.map(([id])=><option key={id} value={id}>{siteById[id].name}</option>)}</select></label>{action(canAllocate(targetSite)?{type:'fiscal',action:'allocate',site:targetSite,amount}:{type:'fiscal',action:'request',site:targetSite,amount,purpose},canAllocate(targetSite)?'拨入地方公库':'呈请'+politicalName(superiorForCity(w,targetSite)!))}</div>:cities.map(([id])=><div className="treasury-request-city" key={id}><strong>{siteById[id].name}</strong>{action(canAllocate(id)?{type:'fiscal',action:'allocate',site:id,amount}:{type:'fiscal',action:'request',site:id,amount,purpose},canAllocate(id)?'拨入地方公库':'呈请'+politicalName(superiorForCity(w,id)!))}</div>)}</>}
 {requests.length>0&&<div className="treasury-requests">{requests.slice().reverse().sort((a,b)=>Number(b.status==='pending')-Number(a.status==='pending')).map(q=><article className="treasury-request" key={q.id}><button className="treasury-applicant" onClick={()=>onPerson?.(q.actor)} aria-label={politicalName(q.actor)}><CharacterPortrait world={w} characterId={q.actor} compact/></button><div><strong>{q.territory?localTitle(q.territory):siteById[q.site].name} · {grantPurposes[q.purpose]} · {q.amount} 钱</strong><p>{q.status==='pending'?'候批 · '+politicalName(q.approver):q.reply}</p><HoverHint label="审批因素" content={<>{(q.evaluation??grantFactors(w,q)).map(p=><p key={p.label}>{p.label} {p.value>=0?'+':''}{p.value}</p>)}<p>非玩家上级在 3 日后审议，评分至少 50 且上级公库足额时批准。</p></>}><span>审批评分 {(q.evaluation??grantFactors(w,q)).reduce((n,p)=>n+p.value,0)} ⓘ</span></HoverHint>{q.status==='pending'&&<div className="realm-actions">{q.approver===w.characterId?<>{action({type:'fiscal',action:'approve',id:q.id},'批准')}{action({type:'fiscal',action:'reject',id:q.id},'驳回')}</>:q.actor===w.characterId&&action({type:'fiscal',action:'cancel',id:q.id},'撤回')}</div>}</div></article>)}</div>}</>}
 {(flat||tab==='budget')&&<>{flat&&cities.length>0&&<h4>地方公库 <HoverHint label="税收与审批规则" content="每 30 日征收：县留用 35%，郡、州各留用所收上缴额的 10%，余款入中央。申请由直属上级以其公库审批，余额不足可再向上申请。"><span className="treasury-help">ⓘ</span></HoverHint></h4>}{!flat&&<p>每 30 日征收：县留用 35%，郡、州各留用所收上缴额的 10%，余款入中央。申请由直属上级以其公库审批，余额不足可再向上申请。</p>}{cities.length>0&&<div className="treasury-cities">{cities.map(([id])=><article key={id}><strong>{siteById[id].name}</strong>{!site&&<Resource name="coins" value={localBalance(w,id)} label="地方余额" caption/>}<HoverHint label="税赋与拨付路径" content={fiscalPath(w,id).map(accountName).join(' → ')}><small>税收 {cityYield(w,id).coins} · 本县留用 {Math.floor(cityYield(w,id).coins*.35)} ⓘ</small></HoverHint>{action({type:'fiscal',action:'relief',site:id},w.realm!.cities[id].governor===w.characterId?'平粜赈济 · 20 钱 / 秩序 +8':'下令平粜 · 20 钱 / 秩序 +8')}</article>)}</div>}{!flat&&!cities.length&&<p>尚无归你管理的地方公库。</p>}</>}
 {(flat||tab==='ledger')&&(ledger.length>0||!flat)&&<><h4>最近账目</h4><div className="treasury-ledger">{ledger.map(e=><article key={e.id}><span>第 {e.day} 日 · {e.reason}</span><strong>{e.coins} 钱</strong><small>{accountName(e.from)} → {accountName(e.to)}</small></article>)}{!ledger.length&&<p>本期尚无入账。</p>}</div></>}
 {confirmRelief&&<ConfirmAction title="确认下令平粜？" detail={`下令人：${politicalName(w.characterId!)}；由本城官署执行，不单列人物功绩。立即从 ${siteById[confirmRelief].name} 公库支出 20 钱，秩序 +8；不动用中央公款或私人财产。`} confirmLabel="确认下令" pending={pending||!!fiscalReason(w,{type:'fiscal',action:'relief',site:confirmRelief})} onCancel={()=>setConfirmRelief(null)} onConfirm={()=>{const cmd={type:'fiscal',action:'relief',site:confirmRelief} as const;if(fiscalReason(w,cmd))return;send(cmd);setConfirmRelief(null);}}/>}
 </section>;
}

/** The upper-tier treasury owns its own applications and ledger, not its seat county's. */
export function TerritoryFiscalActivity({world:w,territory,realm,send,pending}:{world:World;territory:string;realm:import('../core/realm').RealmId;send:(c:GameCommand)=>void;pending:boolean}){
 const key=territoryAccount(w,realm,territory),entries=(w.realm?.fiscal?.entries??[]).filter(e=>e.from===key||e.to===key).slice(-6).reverse(),requests=(w.realm?.fiscal?.requests??[]).filter(q=>q.actor===w.characterId&&canonicalTerritory(q.territory??'city:'+q.site)===canonicalTerritory(territory)).slice(-4).reverse();
 return <div className="treasury-panel">{requests.map(q=><article className="treasury-request" key={q.id}><div><strong><ArtIcon name="influence" size={22}/>{q.amount} 钱 · {q.status==='pending'?'候批':q.status==='approved'?'获准':q.status==='rejected'?'驳回':'已撤回'}</strong><p>{q.status==='pending'?`候 ${politicalName(q.approver)} 批示`:q.reply}</p><HoverHint label="审批依据" content={<>{(q.evaluation??grantFactors(w,q)).map(f=><p key={f.label}>{f.label} {f.value>=0?'+':''}{f.value}</p>)}<p>非玩家上级须评分至少 50 且公库足额。</p></>}><span>评分 {(q.evaluation??grantFactors(w,q)).reduce((n,f)=>n+f.value,0)} ⓘ</span></HoverHint>{q.status==='pending'&&<button disabled={pending||!!fiscalReason(w,{type:'fiscal',action:'cancel',id:q.id})} onClick={()=>send({type:'fiscal',action:'cancel',id:q.id})}>撤回</button>}</div></article>)}{entries.length>0&&<div className="treasury-ledger">{entries.map(e=><article key={e.id}><span>第 {e.day} 日 · {e.reason}</span><strong>{e.to===key?'+':'−'}{e.coins} 钱</strong><small>{accountName(e.from)} → {accountName(e.to)}</small></article>)}</div>}</div>;
}
