import {useEffect,useRef,useState} from 'react';
import {playerRealm,realmReason,armyDailyFood,armyMonthlyPay,type RealmId} from '../core/realm';
import type {War} from '../core/wars';
import type {World,GameCommand} from '../core/types';
import {siteById} from '../data/scenario';
import {RealmBadge} from './RealmBadge';
import {ArtIcon} from './ArtIcon';
import './warDeclaration.css';
const goals={territory:{label:'割地',effect:'要求割让所选目标地'},reparations:{label:'赔款',effect:'要求赔款 300 钱，按期偿付'},tributary:{label:'宗属',effect:'迫使对方称臣'},annexation:{label:'吞并',effect:'胜利议和后接管对方政权'}};
export function WarDeclaration({world:w,target,initialSite,pending,send,onClose}:{world:World;target:RealmId;initialSite?:string;pending:boolean;send:(c:GameCommand)=>void;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),[goal,setGoal]=useState<NonNullable<War['goal']>>('territory'),[chosen,setChosen]=useState(initialSite??'');
 useEffect(()=>{const d=ref.current!,prev=document.activeElement as HTMLElement|null;d.showModal();return()=>{d.close();prev?.focus();};},[]);
 const r=playerRealm(w),sites=Object.keys(w.realm!.cities).filter(id=>w.realm!.cities[id].owner===target),site=sites.includes(chosen)?chosen:sites.find(id=>!realmReason(w,{type:'realm',action:'war',site:id,goal}))??sites[0]??'',command={type:'realm',action:'war',site,goal} as const,reason=realmReason(w,command),armies=w.realm!.armies.filter(a=>a.realm===r);
 return <dialog ref={ref} className="war-declaration" aria-label="宣战议案" onCancel={e=>{e.preventDefault();onClose();}} onKeyDown={e=>e.stopPropagation()}><header><ArtIcon name="army"/><h3>宣战议案</h3></header><div className="war-parties"><article><small>进攻方</small><RealmBadge world={w} realm={r}/><b>现役 {armies.reduce((n,a)=>n+a.troops,0)} 人</b></article><ArtIcon name="army" size={40}/><article><small>防御方</small><RealmBadge world={w} realm={target}/><b>兵力情报待侦察</b></article></div><div className="war-plan"><nav aria-label="战争诉求">{(Object.keys(goals) as (keyof typeof goals)[]).map(id=><button key={id} aria-pressed={goal===id} onClick={()=>setGoal(id)}><ArtIcon name={id==='territory'?'city':id==='reparations'?'coins':'influence'} size={28}/>{goals[id].label}</button>)}</nav><section><h4>{goals[goal].effect}</h4><label>军事目标<select value={site} onChange={e=>setChosen(e.target.value)}>{sites.map(id=><option key={id} value={id}>{siteById[id].name}</option>)}</select></label><p>占领目标、赢得战斗后，才能争取有利和约。</p><div className="city-civic-metrics"><span><ArtIcon name="influence" size={24}/>宣战 {goal==='annexation'?120:40}</span><span><ArtIcon name="grain" size={24}/>现役每日最多 {armies.reduce((n,a)=>n+armyDailyFood(w,a),0)}</span><span><ArtIcon name="coins" size={24}/>每 30 日军饷 {armies.reduce((n,a)=>n+armyMonthlyPay(w,a),0)}</span></div><p>立即进入战争，通行与外交关系随之改变；盟约军援须在战争中另行请求。</p>{!armies.length&&<p className="service-warning">尚无现役军队，宣战后仍需征募与集训。</p>}{armies.some(a=>a.supply<armyDailyFood(w,a)*10)&&<p className="service-warning">部分军队随军粮不足十日，请先检查粮道。</p>}</section></div><footer>{reason&&<p role="status">{reason}</p>}<button onClick={onClose}>取消</button><button className="primary" disabled={pending||!!reason} onClick={()=>{send(command);onClose();}}>确认宣战</button></footer></dialog>;
}
