import {describe,it,expect} from 'vitest';
import {newCampaignWorld} from '../core/world';
import type {War} from '../core/wars';
import type {BattleRecord} from '../core/militaryAftermath';
import {engagementGroups,engagementMarkers,warOccupations,warBattles,battleKey} from './warPresentation';
import {armyMapPosition} from '../map/armyMapPresentation';
import {mapActivities} from '../core/mapActivities';
const setup=()=>{const w=newCampaignWorld('xiao-yan',undefined,'sandbox');w.day=10;w.realm!.wars=[{id:1,attacker:'liang',defender:'east',target:'luoyang',started:0,score:0}];w.militaryAftermath={nextId:1,pools:[],battles:[],spoils:[],intel:{},discipline:{},lastDay:9};return w;};
const battle=(more:Partial<BattleRecord>={}):BattleRecord=>({id:1,war:1,site:'luoyang',key:'1|luoyang',day:5,last:10,round:6,stage:'clash',a:1,b:2,lossA:30,lossB:40,...more});
describe('war detail and map projections',()=>{
 it('keeps current encounters, removes ended/stale/orphan records, and is read-only',()=>{const w=setup();w.militaryAftermath!.battles=[battle(),battle({id:2,ended:10}),battle({id:3,last:8}),battle({id:4,war:2})];w.realm!.sieges=[{war:1,site:'luoyang',side:'attack',progress:24,last:10},{war:2,site:'ye',side:'attack',progress:10,last:10}];const before=structuredClone(w),markers=engagementMarkers(w);expect(markers.map(m=>m.ref.kind)).toEqual(['battle','siege']);expect(w).toEqual(before);expect(mapActivities(w).flatMap(g=>g.items).some(i=>i.id.startsWith('siege:'))).toBe(false);w.realm!.wars=[];expect(engagementMarkers(w)).toEqual([]);});
 it('anchors road encounters to the army position instead of a city endpoint',()=>{const w=setup(),a={id:1,realm:'liang' as const,location:'jiankang',troops:500,morale:80,supply:300,siege:0,journey:{route:['jiankang','jingkou'],durations:[10],leg:0,elapsed:5,started:5}};w.realm!.armies=[a];w.militaryAftermath!.battles=[battle({site:'jingkou'})];const marker=engagementMarkers(w)[0];expect({lon:marker.lon,lat:marker.lat}).toEqual(armyMapPosition(a));});
 it('does not merge same-site sieges belonging to distinct wars or sides',()=>{const w=setup();w.realm!.wars!.push({...w.realm!.wars![0],id:2});w.realm!.sieges=[{war:1,site:'luoyang',side:'attack',progress:25,last:10},{war:2,site:'luoyang',side:'attack',progress:30,last:10},{war:1,site:'luoyang',side:'defend',progress:20,last:10}];expect(new Set(engagementMarkers(w).map(m=>m.key)).size).toBe(3);expect(engagementGroups(w)).toHaveLength(1);expect(engagementGroups(w)[0].items).toHaveLength(3);});
 it('attributes occupation only to the recorded war, or an unambiguous legacy match',()=>{const w=setup(),war=w.realm!.wars![0],c=w.realm!.cities.luoyang;c.owner='east';c.controller='liang';c.occupiedByWar=2;expect(warOccupations(w,war)).toEqual([]);c.occupiedByWar=1;expect(warOccupations(w,war).map(([id])=>id)).toEqual(['luoyang']);delete c.occupiedByWar;expect(warOccupations(w,war)).toHaveLength(1);w.realm!.wars!.push({...war,id:2});expect(warOccupations(w,war)).toEqual([]);});
 it('keeps historical battles in reports, with stable distinct keys and explicit war ownership',()=>{const w=setup(),old=battle({id:undefined,ended:8,day:1,last:8}),recent=battle({id:undefined,day:9});w.militaryAftermath!.battles=[old,recent,battle({id:3,war:undefined})];expect(warBattles(w,w.realm!.wars![0])).toEqual([recent,old]);expect(battleKey(old)).not.toBe(battleKey(recent));expect(warBattles(w,{...w.realm!.wars![0],id:undefined} as War)).toEqual([]);});
});

describe('compact combat marker data',()=>{
 it('retains independent siege progress for co-located conflicts',()=>{const w=setup();w.realm!.wars!.push({...w.realm!.wars![0],id:2});w.realm!.sieges=[{war:1,site:'luoyang',side:'attack',progress:25,last:10},{war:2,site:'luoyang',side:'attack',progress:100,last:10}];expect(engagementGroups(w)[0].items.map(i=>i.progress)).toEqual([25,100]);});
 it('does not leak enemy strength or invent strength for removed armies',()=>{const w=setup();w.realm!.armies=[{id:1,realm:'liang',location:'jiankang',troops:500,morale:80,supply:100,siege:0,journey:null},{id:2,realm:'east',location:'luoyang',troops:750,morale:80,supply:100,siege:0,journey:null}];w.militaryAftermath!.battles=[battle({attackers:[1],defenders:[2]})];const sides=engagementMarkers(w)[0].sides!;expect(sides[1].strength).toBe('未详');w.realm!.armies=[];expect(engagementMarkers(w)[0].sides!.every(s=>s.strength==='未详')).toBe(true);});
});

 it('does not add historical reinforcements to the current battle marker',()=>{const w=setup();w.realm!.armies=[{id:1,realm:'liang',location:'jiankang',troops:500,morale:80,supply:100,siege:0,journey:null}];w.militaryAftermath!.battles=[battle({attackers:[1],participants:[{army:1,realm:'liang',commander:'xiao-yan',troops:500,side:'attack'},{army:3,realm:'liang',commander:null,troops:400,side:'attack'}]})];expect(engagementMarkers(w)[0].sides![0].strength).toBe('500');});
