import {expect,it} from 'vitest';
import {ArmyMotion} from './ArmyMotion';
import {newCampaignWorld} from '../core/world';
import {sampleRoad} from '../core/routeGeometry';
import type {Army} from '../core/realm';
import {Vector3} from 'three';
import {armyModelHeading} from './MilitaryModels';
import {projectGround} from './three/geography';
import {roadHeading} from '../core/routeGeometry';
it('faces the actual projected road tangent in both directions, including oblique roads',()=>{
 for(const pair of [['jiankang','jingkou'],['jingkou','guangling'],['jiankang','xunyang'],['luoyang','changan']])for(const route of [pair,[...pair].reverse()])for(const fraction of [.15,.4,.75]){
  const j={route,durations:[100],leg:0,elapsed:fraction*100,started:0},a=sampleRoad(route[0],route[1],fraction),b=sampleRoad(route[0],route[1],fraction+.00001),p=projectGround(a.lon,a.lat),q=projectGround(b.lon,b.lat),direction=new Vector3(q.x-p.x,0,q.z-p.z).normalize(),forward=new Vector3(0,0,1).applyAxisAngle(new Vector3(0,1,0),armyModelHeading(roadHeading(j)));
  expect(forward.dot(direction),route.join(' → ')).toBeGreaterThan(.99999);
 }
});
it('keeps position continuous when updates arrive early or unrelated commands publish mid-march',()=>{
 const w=newCampaignWorld('xiao-yan',undefined,'sandbox');w.realm!.armies=[{id:1,realm:'liang',location:'jiankang',troops:500,morale:80,supply:100,siege:0,journey:{route:['jiankang','jingkou'],durations:[10],leg:0,elapsed:1,started:0}}];const m=new ArmyMotion();m.sync(w,0,true);const next=structuredClone(w);next.day++;next.realm!.armies[0].journey!.elapsed=2;m.sync(next,1000,true);
 const b=next.realm!.armies[0],before=m.position(b,1600),command=structuredClone(next);command.realm!.armies[0].supply--;m.sync(command,1600,true);expect(m.position(command.realm!.armies[0],1600)).toEqual(before);
 const following=structuredClone(command);following.day++;following.realm!.armies[0].journey!.elapsed=3;const at=m.position(command.realm!.armies[0],1750);m.sync(following,1750,true);expect(m.position(following.realm!.armies[0],1750)).toEqual(at);expect(m.moving(following.realm!.armies[0],1750)).toBe(true);expect(m.position(following.realm!.armies[0],2500)).toMatchObject(sampleRoad('jiankang','jingkou',.3));
});
it('samples confirmed road progress across legs and resets on pause, stop, changed orders and loading',()=>{const w=newCampaignWorld('xiao-yan',undefined,'sandbox'),a:Army={id:999,realm:'liang',location:'jiankang',troops:500,morale:80,supply:500,siege:0,journey:{route:['jiankang','jingkou','guangling'],durations:[2,2],leg:0,elapsed:1,started:0}};w.realm!.armies=[a];const m=new ArmyMotion();m.sync(w,0,true);const next=structuredClone(w);next.day=3;const b=next.realm!.armies[0];b.location='jingkou';b.journey!.leg=1;b.journey!.elapsed=1;m.sync(next,1000,true);expect(m.position(b,1000)).toMatchObject(sampleRoad('jiankang','jingkou',.5));expect(m.position(b,1500)).toMatchObject(sampleRoad('jingkou','guangling',0));expect(m.position(b,2000)).toMatchObject(sampleRoad('jingkou','guangling',.5));expect(m.moving(b,2000)).toBe(false);m.sync(next,1300,false);expect(m.position(b,1300)).toMatchObject({lon:sampleRoad('jingkou','guangling',.5).lon,lat:sampleRoad('jingkou','guangling',.5).lat});const loaded=structuredClone(w);m.sync(loaded,2000,true);expect(m.moving(loaded.realm!.armies[0],2000)).toBe(false);const halted=structuredClone(loaded);halted.day++;m.sync(halted,3000,true);expect(m.moving(halted.realm!.armies[0],3000)).toBe(false);});
it('keeps opposing representative roots at the same real contact with separate clickable banners',async()=>{const {anchoredArmyModels}=await import('./armyMapPresentation');const position={lon:119,lat:32},point={x:600,y:400},entries=[{key:'1',point,position,combatSide:'attack'},{key:'2',point,position,combatSide:'defend'}],first=anchoredArmyModels(entries,[],{width:1200,height:800}),selected=anchoredArmyModels(entries,['2'],{width:1200,height:800});expect(first.size).toBe(2);expect(first.get('1')?.offset.x).toBe(-52);expect(first.get('2')?.offset.x).toBe(52);expect(selected).toEqual(first);expect(entries[0].position).toEqual(position);});
it('does not anticipate tomorrow\'s road encounter when buffering today\'s confirmed movement',async()=>{const {declareRealmWar}=await import('../core/realm');const {awardInfluence}=await import('../core/personalInfluence');const w=newCampaignWorld('xiao-yan',undefined,'sandbox');awardInfluence(w,'xiao-yan',500);declareRealmWar(w,'xiao-yan','liang','luoyang');w.realm!.armies=[{id:1,realm:'liang',location:'jiankang',troops:500,morale:80,supply:500,siege:0,journey:{route:['jiankang','jingkou'],durations:[10],leg:0,elapsed:3,started:0}},{id:2,realm:'east',location:'jingkou',troops:500,morale:80,supply:500,siege:0,journey:{route:['jingkou','jiankang'],durations:[10],leg:0,elapsed:3,started:0}}];const m=new ArmyMotion();m.sync(w,0,true);const next=structuredClone(w);next.day=1;next.realm!.armies.forEach(a=>a.journey!.elapsed=4);m.sync(next,1000,true);expect(m.position(next.realm!.armies[0],1000)).toMatchObject(sampleRoad('jiankang','jingkou',.3));expect(m.moving(next.realm!.armies[0],1000)).toBe(true);});
