import {TerrainTint} from './terrainTint';
import {loadTableRoom,TABLE_COORDINATE} from './tableRoom';
import {cameraNearPlane} from './cameraDepth';
import {atlasPaperStrength,atlasRegionalStrength,normalizeAtlasCamera} from '../atlasPresentation';
import {PointerGesture} from './pointerGesture';
import {ACESFilmicToneMapping,Color,DirectionalLight,Fog,Group,HemisphereLight,PCFSoftShadowMap,PerspectiveCamera,Raycaster,Scene,ShaderMaterial,Vector2,Vector3,WebGLRenderer,type Object3D,type Texture} from 'three';
import {MapControls} from 'three/addons/controls/MapControls.js';
import type {FeatureCollection,Geometry} from 'geojson';
import type {MapOptions,StyleSpecification} from 'maplibre-gl';
import {prefetchCampaignSampleAssets} from '../CampaignSampleAssets';
import {hiddenTerrainMaterial} from './hiddenTerrain';
import {countrySurface} from './surface';
import {CampaignOverlays,coverageTexture,evaluate,type OverlayLayer} from './overlays';
import {campaignActors,type CampaignState} from './actors';
import {createSeasonState,seasons} from '../sample/seasons';
import {campaignSeason} from '../campaignSeason';
import {projectGround,unprojectGround,zoomDistance,distanceZoom} from './geography';
import {waterMaskContains} from '../campaignTerrain';
import type {ArmyMarkerPlacement} from '../armyMapPresentation';

type Point={x:number;y:number};
type AtlasEvent={point:Point;originalEvent:MouseEvent;error:Error;sourceId?:string;preventDefault:()=>void};
const empty:FeatureCollection={type:'FeatureCollection',features:[]};
/** Actual standalone renderer. Map-compatible event/data adapters retain existing game actions only. */
export class ThreeCampaignMap{
 readonly renderer:WebGLRenderer;readonly scene=new Scene();readonly camera:PerspectiveCamera;readonly controls:MapControls;readonly markers=new Set<ThreeMarker>();
 private room?:Awaited<ReturnType<typeof loadTableRoom>>;private roomRequested=false;
 private tint=new TerrainTint();
 private season=createSeasonState();private surface?:Awaited<ReturnType<typeof countrySurface>>;private actors?:Awaited<ReturnType<typeof campaignActors>>;
 private sun=new DirectionalLight('#ffe1ad',2.7);private sky=new HemisphereLight('#cadcde','#393d2d',.85);private overlays:CampaignOverlays;private clouds=new Group();private cloudMaterial:ShaderMaterial;private coverage?:Texture;
 private listeners=new Map<string,Set<(event:AtlasEvent)=>void>>();private sources=new Map<string,FeatureCollection>();private layers:OverlayLayer[];private states=new Map<string,Record<string,unknown>>();
 private stopped=false;private ready=false;private frame=0;private dirty=true;private overlaysDirty=true;private moving=false;private settlingUntil=0;private lastCameraMotion=-Infinity;private lastZoom=0;private lastSeason='';private lastSeasonSync='';private flat=false;private lastFrame=0;private lastRefine='';private refineTimer?:ReturnType<typeof setTimeout>;
 private flight?:{start:number;duration:number;from:Vector3;to:Vector3;fromTarget:Vector3;toTarget:Vector3};
 private state?:()=>CampaignState;private getPlacement:(id:number)=>ArmyMarkerPlacement|undefined=()=>undefined;
 private gesture=new PointerGesture();private cleanup:(()=>void)[]=[];private container:HTMLElement;
 constructor(options:Pick<MapOptions,'container'|'style'|'center'|'zoom'|'pitch'|'bearing'|'minZoom'|'maxZoom'>){
  if(!(options.container instanceof HTMLElement))throw new Error('地图容器不存在');this.container=options.container;this.layers=((options.style as StyleSpecification).layers??[]) as OverlayLayer[];
  for(const [id,source] of Object.entries((options.style as StyleSpecification).sources))if(source.type==='geojson'&&typeof source.data!=='string')this.sources.set(id,source.data as FeatureCollection);
  this.renderer=new WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace='srgb';this.renderer.toneMapping=ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=PCFSoftShadowMap;this.renderer.shadowMap.autoUpdate=false;this.renderer.debug.onShaderError=(gl,program)=>{throw new Error('三维着色器编译失败：'+gl.getProgramInfoLog(program));};this.container.append(this.renderer.domElement);this.renderer.domElement.dataset.renderer='three-campaign-world';
  this.camera=new PerspectiveCamera(39,1,1,40000);this.controls=new MapControls(this.camera,this.renderer.domElement);this.controls.enableDamping=!matchMedia('(prefers-reduced-motion: reduce)').matches;this.controls.dampingFactor=.18;this.controls.minDistance=zoomDistance(options.maxZoom??12);this.controls.maxDistance=zoomDistance(options.minZoom??1.1);this.controls.minPolarAngle=.001;this.controls.maxPolarAngle=1.2;this.controls.screenSpacePanning=false;this.controls.zoomSpeed=.55;
  this.scene.background=new Color('#bdc6c1');this.scene.fog=new Fog('#bdc6c1',140,440);this.scene.add(this.sky,this.sun,this.sun.target);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);this.sun.shadow.bias=-.00025;this.sun.shadow.normalBias=.13;this.sun.shadow.camera.near=1;this.sun.shadow.camera.far=650;this.sun.shadow.radius=2;
  this.overlays=new CampaignOverlays((lon,lat)=>this.height(lon,lat));this.scene.add(this.overlays.root,this.clouds);
  this.cloudMaterial=hiddenTerrainMaterial();
  this.controls.addEventListener('start',()=>{this.flight=undefined;this.settlingUntil=performance.now()+140;this.moving=true;this.emit('movestart');});this.controls.addEventListener('change',()=>{this.lastCameraMotion=performance.now();this.dirty=true;if(this.moving||this.settlingUntil)this.settlingUntil=performance.now()+140;this.camera.updateMatrixWorld();this.emit('move');this.triggerRepaint();});this.controls.addEventListener('end',()=>{this.moving=false;this.settlingUntil=performance.now()+140;this.triggerRepaint();});
  const canvas=this.renderer.domElement;canvas.tabIndex=0;
  const bind=(name:string,handler:EventListener)=>{canvas.addEventListener(name,handler);this.cleanup.push(()=>canvas.removeEventListener(name,handler));};
  // Capture before MapControls starts moving; observe the whole path, including off-canvas release.
  const pointerStart=(e:PointerEvent)=>this.gesture.begin(e.pointerId,e.clientX,e.clientY,e.pointerType==='touch',!!this.flight||this.moving||(this.settlingUntil>0&&performance.now()-this.lastCameraMotion<180));
  const pointerMove=(e:PointerEvent)=>this.gesture.move(e.pointerId,e.clientX,e.clientY);
  const pointerEnd=(e:PointerEvent)=>this.gesture.end(e.pointerId,e.clientX,e.clientY);
  const pointerCancel=()=>this.gesture.cancel();
  canvas.addEventListener('pointerdown',pointerStart,true);
  window.addEventListener('pointermove',pointerMove,true);window.addEventListener('pointerup',pointerEnd,true);
  window.addEventListener('pointercancel',pointerCancel,true);window.addEventListener('blur',pointerCancel);
  this.cleanup.push(()=>{canvas.removeEventListener('pointerdown',pointerStart,true);window.removeEventListener('pointermove',pointerMove,true);window.removeEventListener('pointerup',pointerEnd,true);window.removeEventListener('pointercancel',pointerCancel,true);window.removeEventListener('blur',pointerCancel);});
  for(const name of ['mousemove','click','dblclick','contextmenu'])bind(name,event=>{const e=event as MouseEvent;if(name==='contextmenu')e.preventDefault();if(((name==='click'||name==='dblclick')&&!this.gesture.allowsClick()||name==='contextmenu'&&!this.gesture.allowsContextMenu()))return;if(name==='contextmenu')e.preventDefault();const r=canvas.getBoundingClientRect();this.emit(name,{point:{x:e.clientX-r.left,y:e.clientY-r.top},originalEvent:e,preventDefault:()=>e.preventDefault()});});
  let wheelTarget:number|undefined,lastWheel=0;
  const smoothWheel=(e:WheelEvent)=>{
   e.preventDefault();e.stopImmediatePropagation();const now=performance.now();
   if(now-lastWheel>200||!this.flight)wheelTarget=this.getZoom();
   const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?this.container.clientHeight:1);
   wheelTarget=Math.max(options.minZoom??1.1,Math.min(options.maxZoom??12,(wheelTarget??this.getZoom())-Math.max(-120,Math.min(120,delta))*.003));lastWheel=now;
   if(!this.flight)this.emit('movestart');this.easeTo({zoom:wheelTarget,duration:160});
  };
  canvas.addEventListener('wheel',smoothWheel,{capture:true,passive:false});this.cleanup.push(()=>canvas.removeEventListener('wheel',smoothWheel,true));
  bind('webglcontextlost',e=>{e.preventDefault();this.emit('webglcontextlost');});
  bind('keydown',event=>{const e=event as KeyboardEvent;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const d=this.unitsPerPixel()*60,shift=new Vector3(e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0,0,e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0);this.controls.target.add(shift);this.camera.position.add(shift);this.changedView();}else if(e.key==='+'||e.key==='=')this.zoomIn();else if(e.key==='-')this.zoomOut();else if(e.key.toLowerCase()==='q'||e.key.toLowerCase()==='e')this.easeTo({bearing:this.getBearing()+(e.key.toLowerCase()==='q'?-20:20)});});
  const attribution=document.createElement('details');attribution.className='three-map-attribution';attribution.innerHTML='<summary>地图资料</summary><p>地形：<a href="https://registry.opendata.aws/terrain-tiles/" target="_blank" rel="noopener">Mapzen / AWS</a>，SRTM 与 GMTED2010 courtesy USGS，ETOPO1 courtesy NOAA。水系与陆地：<a href="https://www.naturalearthdata.com/" target="_blank" rel="noopener">Natural Earth</a>（公共领域）。雾外为本局已建模政权范围，非完整历史疆界；近景高程从本地全国分块按需细化。</p>';this.container.append(attribution);this.cleanup.push(()=>attribution.remove());
  this.resize();this.easeTo({center:(options.center as [number,number])??[110,32],zoom:options.zoom??4,pitch:options.pitch??0});
  void prefetchCampaignSampleAssets().catch(()=>{});void this.load();this.frame=requestAnimationFrame(this.render);
 }
 private async load(){try{const surface=await countrySurface(this.season);if(this.stopped){surface.dispose();return;}this.surface=surface;this.cloudMaterial.uniforms.parchment.value=surface.hiddenPaper;this.cloudMaterial.uniforms.paperExtent.value.fromArray(surface.parchment.userData.extent);surface.setFlat(this.flat);this.sources.set('land',surface.land);this.sources.set('local-rivers',surface.rivers);this.scene.add(surface.root);this.ready=true;this.overlaysDirty=true;this.updateClouds();this.emit('style.load');this.changedView();this.emit('sourcedata',{sourceId:'national-dem'});this.triggerRepaint();}catch(error){if(!this.stopped)this.emit('error',{sourceId:'national-dem',error:error instanceof Error?error:new Error(String(error))});}}
 attachWorld(state:()=>CampaignState,placement:(id:number)=>ArmyMarkerPlacement|undefined,ready:()=>void,warning:(message:string)=>void){this.state=state;this.getPlacement=placement;void campaignActors({scene:this.scene,height:(lon,lat)=>this.height(lon,lat),isRiver:(lon,lat)=>this.surface?.isRiver(lon,lat)??false,isLand:(lon,lat)=>this.surface?.isLand(lon,lat)??false,isMoving:()=>this.isMoving(),project:ll=>this.project(ll),getZoom:()=>this.getZoom(),getSize:()=>({width:this.container.clientWidth,height:this.container.clientHeight}),unitsPerPixel:()=>this.unitsPerPixel(),unitsPerPixelAt:(lon,lat)=>{const p=projectGround(lon,lat),v=new Vector3(p.x,this.height(lon,lat)??0,p.z).applyMatrix4(this.camera.matrixWorldInverse);return Math.max(0,-v.z)*2*Math.tan(this.camera.fov*Math.PI/360)/Math.max(1,this.container.clientHeight);},getTarget:()=>this.controls.target,getViewKey:()=>[this.container.clientWidth,this.container.clientHeight,...this.camera.quaternion.toArray().map(n=>n.toFixed(2))].join(":"),repaint:()=>this.triggerRepaint(),warning},state,id=>this.getPlacement(id)).then(actors=>{if(this.stopped){actors.dispose();return;}this.actors=actors;ready();this.triggerRepaint();}).catch(e=>warning('模型加载失败，保留铭牌操作：'+String(e)));}
 showsSite(id:string){return this.actors?.showsSite(id)??false;}
 siteAt(point:Point){if(!this.actors)return null;const ray=this.ray(point),hits=ray.intersectObjects(this.actors.cityRoots(),true);let root:Object3D|undefined=hits[0]?.object;while(root&&!root.userData.site)root=root.parent??undefined;const ground=this.groundAt(point);if(ground&&hits[0]&&hits[0].distance>ground.distance+1)return null;return root?.userData.site as string??null;}
 private ray(point:Point){const ray=new Raycaster();this.camera.updateMatrixWorld();ray.setFromCamera(new Vector2(point.x/this.container.clientWidth*2-1,1-point.y/this.container.clientHeight*2),this.camera);return ray;}
 private groundAt(point:Point){const ray=this.ray(point).ray;if(ray.direction.y>=0)return null;const limit=Math.min(30000,(ray.origin.y+200)/-ray.direction.y),at=new Vector3();let before=0;
  for(let i=1;i<=128;i++){const distance=limit*i/128;at.copy(ray.origin).addScaledVector(ray.direction,distance);const ll=unprojectGround(at.x,at.z),height=this.height(ll.lng,ll.lat);if(height!==null&&at.y<=height){let lo=before,hi=distance;for(let j=0;j<18;j++){const mid=(lo+hi)/2;at.copy(ray.origin).addScaledVector(ray.direction,mid);const p=unprojectGround(at.x,at.z);if(at.y>(this.height(p.lng,p.lat)??0))lo=mid;else hi=mid;}at.copy(ray.origin).addScaledVector(ray.direction,hi);return {...unprojectGround(at.x,at.z),distance:hi};}before=distance;}return null;
 }
 height(lon:number,lat:number){return this.surface?.height(lon,lat)??null;}
 queryTerrainElevation(ll:{lng:number;lat:number}){const height=this.height(ll.lng,ll.lat);return height===null?null:height*1000*Math.cos(ll.lat*Math.PI/180);}
 project(ll:[number,number]){const p=projectGround(ll[0],ll[1]),v=new Vector3(p.x,this.height(ll[0],ll[1])??0,p.z).project(this.camera);return v.z< -1||v.z>1?{x:-100000,y:-100000}:{x:(v.x*.5+.5)*this.container.clientWidth,y:(.5-v.y*.5)*this.container.clientHeight};}
 getCanvas(){return this.renderer.domElement;}getZoom(){return distanceZoom(this.camera.position.distanceTo(this.controls.target));}getPitch(){return this.controls.getPolarAngle()*180/Math.PI;}getBearing(){return -this.controls.getAzimuthalAngle()*180/Math.PI;}isMoving(){return this.moving||this.settlingUntil>0||!!this.flight;}areTilesLoaded(){return this.ready;}unitsPerPixel(){return this.camera.position.distanceTo(this.controls.target)*2*Math.tan(this.camera.fov*Math.PI/360)/Math.max(1,this.container.clientHeight);}
 easeTo(options:{center?:[number,number];zoom?:number;pitch?:number;bearing?:number;duration?:number}){
  options=normalizeAtlasCamera(options,this.getZoom());
  if(options.zoom!==undefined&&options.zoom<=1.3&&!options.center)options={...options,center:[TABLE_COORDINATE.lng,TABLE_COORDINATE.lat]};
  // Drain residual pan inertia before an explicit camera flight.
  const damping=this.controls.enableDamping;this.controls.enableDamping=false;this.controls.update();this.controls.enableDamping=damping;this.settlingUntil=0;
  const target=this.controls.target.clone();if(options.center){const p=projectGround(...options.center);target.set(p.x,this.height(...options.center)??0,p.z);}
  const d=zoomDistance(options.zoom??this.getZoom()),phi=(options.pitch??this.getPitch())*Math.PI/180,theta=-(options.bearing??this.getBearing())*Math.PI/180,to=new Vector3(target.x+d*Math.sin(phi)*Math.sin(theta),target.y+d*Math.cos(phi),target.z+d*Math.sin(phi)*Math.cos(theta));
  if(this.ready&&options.duration&&!matchMedia('(prefers-reduced-motion: reduce)').matches){this.flight={start:performance.now(),duration:options.duration,from:this.camera.position.clone(),to,fromTarget:this.controls.target.clone(),toTarget:target};this.triggerRepaint();return;}
  this.camera.position.copy(to);this.controls.target.copy(target);this.controls.update();this.camera.updateMatrixWorld();this.changedView();
 }
 fitBounds(bounds:[[number,number],[number,number]],options:{padding?:unknown;pitch?:number;bearing?:number;duration?:number;maxZoom?:number}){const a=projectGround(...bounds[0]),b=projectGround(...bounds[1]),aspect=this.container.clientWidth/Math.max(1,this.container.clientHeight),d=Math.max(Math.abs(a.z-b.z),Math.abs(a.x-b.x)/aspect)/Math.tan(this.camera.fov*Math.PI/360)*.68;this.easeTo({center:[(bounds[0][0]+bounds[1][0])/2,(bounds[0][1]+bounds[1][1])/2],zoom:Math.min(options.maxZoom??12,distanceZoom(Math.max(25,d))),pitch:options.pitch??0,bearing:options.bearing??0,duration:options.duration});}
 zoomIn(options?:{duration?:number}){this.easeTo({zoom:Math.min(12,this.getZoom()+.7),duration:options?.duration});}zoomOut(options?:{duration?:number}){this.easeTo({zoom:Math.max(1.1,this.getZoom()-.7),duration:options?.duration});}
 setTerrain(value:boolean){this.flat=!value;this.container.dataset.strategic=String(this.flat);this.cloudMaterial.uniforms.strategic.value=this.flat?1:0;this.surface?.setFlat(this.flat);this.updateClouds();this.actors?.refresh();this.overlaysDirty=true;this.triggerRepaint();}
 resize(){const w=Math.max(1,this.container.clientWidth),h=Math.max(1,this.container.clientHeight);this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.triggerRepaint();}
 on(name:string,callback:(event:AtlasEvent)=>void){const list=this.listeners.get(name)??new Set();list.add(callback);this.listeners.set(name,list);return this;}
 once(name:string,callback:(event:AtlasEvent)=>void){const once=(e:AtlasEvent)=>{this.listeners.get(name)?.delete(once);callback(e);};return this.on(name,once);}
 private emit(name:string,data:Partial<AtlasEvent>={}){for(const listener of this.listeners.get(name)??[])listener(data as AtlasEvent);}
 getSource(id:string){return {setData:(data:FeatureCollection)=>{this.sources.set(id,data);this.overlaysDirty=true;if(id==='realms')this.updateClouds(true);this.triggerRepaint();}};}
 getLayer(id:string){return this.layers.find(l=>l.id===id);}
 setFilter(id:string,filter:unknown){const l=this.getLayer(id);if(l&&JSON.stringify(l.filter)!==JSON.stringify(filter)){l.filter=filter;this.overlaysDirty=true;this.triggerRepaint();}}
 setLayoutProperty(id:string,key:string,value:unknown){const l=this.getLayer(id);if(l&&l.layout?.[key]!==value){l.layout={...l.layout,[key]:value};this.overlaysDirty=true;this.triggerRepaint();}}
 setPaintProperty(id:string,key:string,value:unknown){const l=this.getLayer(id);if(l&&JSON.stringify(l.paint?.[key])!==JSON.stringify(value)){l.paint={...l.paint,[key]:value};this.overlaysDirty=true;this.triggerRepaint();}}
 setFeatureState(ref:{source:string;id:string|number},state:Record<string,unknown>){const key=ref.source+':'+ref.id;this.states.set(key,{...this.states.get(key),...state});this.overlaysDirty=true;this.triggerRepaint();}
 queryRenderedFeatures(point:[number,number]|[[number,number],[number,number]],options:{layers:string[]}){
  const xy=typeof point[0]==='number'?{x:point[0],y:point[1] as number}:{x:(point[0][0]+(point[1] as number[])[0])/2,y:(point[0][1]+(point[1] as number[])[1])/2},ll=this.groundAt(xy);if(!ll)return [];const hits:{layer:{id:string};properties:Record<string,unknown>|null;geometry:Geometry}[]=[];
  for(const id of options.layers){const l=this.getLayer(id);if(!l||l.layout?.visibility==='none')continue;
   if(id==='ocean'){if(this.surface&&!this.surface.land.features.some(f=>waterMaskContains([ll.lng,ll.lat],f.geometry)))hits.push({layer:{id},properties:{},geometry:{type:'Point',coordinates:[ll.lng,ll.lat]}});continue;}
   for(const f of this.sources.get(l.source??'')?.features??[]){if(l.filter&&!evaluate(l.filter,f,this.getZoom()))continue;let inside=false;if(f.geometry.type==='Point'){const p=this.project(f.geometry.coordinates as [number,number]);inside=Math.hypot(p.x-xy.x,p.y-xy.y)<10;}else inside=waterMaskContains([ll.lng,ll.lat],f.geometry);if(inside)hits.push({layer:{id},properties:f.properties,geometry:f.geometry});}
  }return hits;
 }
 private updateClouds(rebuildCoverage=false){if(!this.coverage||rebuildCoverage){this.coverage?.dispose();this.coverage=coverageTexture(this.sources.get('realms')??empty,2048);this.cloudMaterial.uniforms.coverage.value=this.coverage;}this.clouds.clear();if(this.surface)for(const mesh of this.surface.fogMaterialMeshes(this.cloudMaterial)){mesh.renderOrder=1000;this.clouds.add(mesh);}}
 private changedView(){this.dirty=true;this.overlaysDirty=true;this.emit('move');this.emit('moveend');const z=Math.round(this.getZoom()*5);if(z!==this.lastZoom){this.lastZoom=z;this.overlaysDirty=true;this.emit('zoomend');}if(this.refineTimer)clearTimeout(this.refineTimer);if(this.ready&&this.getZoom()>5.4&&!this.flat){const ll=unprojectGround(this.controls.target.x,this.controls.target.z),key=Math.floor((ll.lng+180)/360*128)+':'+Math.floor((1-Math.asinh(Math.tan(ll.lat*Math.PI/180))/Math.PI)/2*128);if(key!==this.lastRefine)this.refineTimer=setTimeout(()=>{this.lastRefine=key;void this.surface!.refine(ll.lng,ll.lat,()=>!this.isMoving()).then(changed=>{if(!changed||this.stopped)return;this.updateClouds();this.overlaysDirty=true;this.actors?.refresh();this.emit('sourcedata',{sourceId:'detail-dem'});this.triggerRepaint();}).catch(error=>{if(!this.stopped){this.lastRefine='';this.emit('error',{sourceId:'detail-dem',error:new Error('本地近景高程加载失败，保留真实全国底图：'+String(error))});}});},400);}this.triggerRepaint();}
 triggerRepaint(){this.dirty=true;}
 private render=(now:number)=>{if(this.stopped)return;this.frame=requestAnimationFrame(this.render);if(!this.ready)return;if(!this.flight){this.controls.update();if(!this.moving&&this.settlingUntil&&now>=this.settlingUntil){this.settlingUntil=0;this.changedView();}}if(this.flight){const f=this.flight,t=Math.min(1,(now-f.start)/f.duration),u=t*t*(3-2*t);this.camera.position.lerpVectors(f.from,f.to,u);this.controls.target.lerpVectors(f.fromTarget,f.toTarget,u);this.controls.update();this.dirty=true;if(t===1){this.flight=undefined;this.changedView();}}const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!this.dirty&&(reduced||now-this.lastFrame<1000))return;this.lastFrame=now;
  try{const before=this.controls.target.clone(),ll=unprojectGround(before.x,before.z),clamped=projectGround(Math.max(64,Math.min(145,ll.lng)),Math.max(12,Math.min(60,ll.lat)));this.controls.target.set(clamped.x,this.height(Math.max(64,Math.min(145,ll.lng)),Math.max(12,Math.min(60,ll.lat)))??0,clamped.z);this.camera.position.add(this.controls.target.clone().sub(before));const cameraLL=unprojectGround(this.camera.position.x,this.camera.position.z);this.camera.position.y=Math.max(this.camera.position.y,(this.height(cameraLL.lng,cameraLL.lat)??0)+7);this.camera.lookAt(this.controls.target);if(before.distanceToSquared(this.controls.target)>.0001){this.camera.updateMatrixWorld();this.emit('move');}const state=this.state?.();if(state){const value=state.seasonPreview??campaignSeason(state.world);if(value!==this.lastSeason){this.lastSeason=value;const p=seasons[value];this.season.set(value);(this.scene.background as Color).set(p.fog);(this.scene.fog as Fog).color.set(p.fog);this.cloudMaterial.uniforms.fogColor.value.set(p.fog);this.sun.color.set(p.sun);this.sun.intensity=p.intensity;this.sky.color.set(p.sky);this.surface!.water.color.set(p.water);}}
   if(this.getZoom()<3.2&&!this.roomRequested){this.roomRequested=true;void loadTableRoom(this.surface!.hiddenPaper).then(room=>{if(this.stopped){room.dispose();return;}this.room=room;this.scene.add(room.root);this.triggerRepaint();}).catch(error=>{this.emit('error',{sourceId:'atlas-study',error:new Error(String(error))});});}this.room?.update(this.getZoom());
   const paper=atlasPaperStrength(this.getZoom(),this.flat);this.surface!.setPaperStrength(paper);this.surface!.setRegionalStyle(atlasRegionalStrength(this.getZoom(),this.flat));this.cloudMaterial.uniforms.strategic.value=paper;const paperLabel=String(paper>=.5);if(this.container.dataset.paper!==paperLabel)this.container.dataset.paper=paperLabel;
   const animate=this.actors?.update(now)??false;if(this.actors&&!this.isMoving())this.surface!.setFarms(this.actors.farmCenters());const seasonSync=this.lastSeason+':'+(this.actors?.revision()??0);if(seasonSync!==this.lastSeasonSync){this.lastSeasonSync=seasonSync;this.season.sync(this.scene);}const d=this.camera.position.distanceTo(this.controls.target),fog=this.scene.fog as Fog;const near=cameraNearPlane(d);if(Math.abs(this.camera.near-near)>.001){this.camera.near=near;this.camera.updateProjectionMatrix();}fog.near=d*.95;fog.far=d*2.8;
   if(!this.isMoving()){this.sun.position.copy(this.controls.target).add(new Vector3(-135,155,80));this.sun.target.position.copy(this.controls.target);const size=Math.max(55,Math.min(290,d*.9)),sc=this.sun.shadow.camera;sc.left=sc.bottom=-size;sc.right=sc.top=size;sc.updateProjectionMatrix();this.sun.castShadow=this.getZoom()>=6.2;}
   if(this.overlaysDirty&&!this.isMoving()){const range=this.unitsPerPixel()*Math.max(this.container.clientWidth,this.container.clientHeight)*1.4,a=unprojectGround(this.controls.target.x-range,this.controls.target.z+range),b=unprojectGround(this.controls.target.x+range,this.controls.target.z-range);const extent:[number,number,number,number]=[this.controls.target.x-range,this.controls.target.z-range,range*2,range*2];if(!this.flat)this.tint.update(this.layers,this.sources,this.getZoom(),this.states,extent);this.surface!.setTint(this.tint.texture,extent,!this.flat);this.overlays.rebuild(this.layers,this.sources,this.getZoom(),this.unitsPerPixel(),this.states,[a.lng,a.lat,b.lng,b.lat],this.flat,!this.flat);this.overlaysDirty=false;}
   this.camera.updateMatrixWorld();this.renderer.shadowMap.needsUpdate=(this.dirty||animate)&&!this.isMoving();this.renderer.render(this.scene,this.camera);for(const marker of this.markers)marker.render();this.dirty=animate;this.emit('idle');
  }catch(error){this.stopped=true;cancelAnimationFrame(this.frame);this.emit('error',{error:error instanceof Error?error:new Error(String(error))});}
 };
 remove(){this.stopped=true;cancelAnimationFrame(this.frame);if(this.refineTimer)clearTimeout(this.refineTimer);this.cleanup.forEach(f=>f());this.controls.dispose();this.room?.dispose();this.actors?.dispose();this.overlays.clear();this.tint.dispose();this.coverage?.dispose();this.cloudMaterial.dispose();this.surface?.dispose();this.renderer.dispose();this.renderer.domElement.remove();this.listeners.clear();}
}
export class ThreeMarker{
 private ll:[number,number]=[0,0];private offset:[number,number]=[0,0];private map?:ThreeCampaignMap;private element:HTMLElement;private anchor:string;private transform='';
 constructor(options:{element:HTMLElement;anchor?:string;offset?:[number,number];opacityWhenCovered?:number}){this.element=options.element;this.anchor=options.anchor??'center';this.offset=options.offset??[0,0];this.element.style.position='absolute';this.element.style.left='0';this.element.style.top='0';this.element.style.pointerEvents='auto';}
 setLngLat(ll:[number,number]){this.ll=ll;this.render();return this;}setOffset(offset:[number,number]){this.offset=offset;this.render();return this;}getOffset(){return {x:this.offset[0],y:this.offset[1]};}getLngLat(){return {lng:this.ll[0],lat:this.ll[1]};}getElement(){return this.element;}
 addTo(map:ThreeCampaignMap){this.map=map;map.markers.add(this);map.getCanvas().parentElement!.append(this.element);this.render();return this;}
 render(){if(!this.map)return;const p=this.map.project(this.ll);const transform=`translate(${(p.x+this.offset[0]).toFixed(1)}px,${(p.y+this.offset[1]).toFixed(1)}px) translate(${this.anchor==='left'?'0':'-50%'},${this.anchor==='bottom'?'-100%':'-50%'})`;if(transform!==this.transform){this.transform=transform;this.element.style.transform=transform;}}
 remove(){this.map?.markers.delete(this);this.element.remove();this.map=undefined;}
}
