import {awardDeed} from './deeds';
import {relationshipPeople} from '../data/relationships';
import {describe,it,expect} from 'vitest';
import {newCampaignWorld} from './world';
import {advanceMilitaryAI,defensiveReserve} from './militaryAI';
import {ensureArmyOrganization} from './armyOrganization';
import {ensureWars} from './wars';
import {advanceRealm} from './realm';
import {nextMonthStart} from './calendar';
import {governmentOf} from './government';
import {regencyBalance,advanceRelationships,syncRelationships} from './relationships';
import {politicalAction} from './politicalActions';
import {serviceDomain} from './serviceNeeds';
import {advancePowerPolitics,actPower,powerSupport} from './powerPolitics';
import {validateWorld} from './save';
const start=()=>newCampaignWorld('guest-west',undefined,'sandbox');
function battleWorld(){const w=start(),s=w.realm!;s.armies=[];s.war={attacker:'east',defender:'west',target:'changan',started:0,score:0};delete s.wars;ensureWars(w);for(const [realm,location,count] of [['east','ye',1],['east','luoyang',2],['west','changan',3]] as const)for(let i=0;i<count;i++)s.armies.push({realm,location,troops:600,morale:100,supply:120,journey:null,siege:0,automation:'delegated'});ensureArmyOrganization(w);w.day=nextMonthStart(0);return w;}
describe('opening AI regressions',()=>{
 it('routine farming is welfare and completion does not charge ideological opposition again',()=>{const w=start();expect(serviceDomain('agriculture')).toBe('welfare');expect(serviceDomain('greatworks')).toBe('welfare');const context={source:'test',site:'changan',localService:true,stage:'completion' as const,burden:0,benefit:0};expect(politicalAction(w,'west','reform',context).rawSupport).toBe(0);expect(Math.abs(politicalAction(w,'west','reform',{...context,stage:'commitment'}).effort)).toBeLessThan(Math.abs(politicalAction(w,'west','reform').effort));});
 it('recruits against the field force deficit despite equal national totals, with actual costs',()=>{const w=battleWorld(),s=w.realm!,coins=s.treasuries.east.coins,pop=Object.values(s.cities).filter(c=>c.owner==='east').reduce((n,c)=>n+c.population,0);advanceMilitaryAI(w);expect(s.armies.filter(a=>a.realm==='east')).toHaveLength(4);expect(s.treasuries.east.coins).toBe(coins-120);expect(Object.values(s.cities).filter(c=>c.owner==='east').reduce((n,c)=>n+c.population,0)).toBe(pop-600);expect(s.armies.at(-1)!.trainingUntil).toBe(w.day+30);});
 it('dispatches the whole assembled army, preserves reserve and reaches real combat',()=>{const w=battleWorld(),s=w.realm!;w.day=10;for(let i=0;i<2;i++)s.armies.push({realm:'east',location:'luoyang',troops:600,morale:100,supply:120,journey:null,siege:0,automation:'delegated'});ensureArmyOrganization(w);const reserve=defensiveReserve(w,'east')!;for(const r of ['east','west'] as const){const people=relationshipPeople.filter(p=>p.realm===r);w.mobility!.armyCommanders??={};s.armies.filter(a=>a.realm===r).forEach((a,i)=>w.mobility!.armyCommanders![a.id!]=people[i].id);}advanceMilitaryAI(w);expect(reserve.journey).toBeNull();expect(s.armies.filter(a=>a.realm==='east'&&a!==reserve).map(a=>a.journey?.route.at(-1))).toEqual(['changan','changan','changan','changan']);for(let i=0;i<20;i++){w.day++;advanceRealm(w);}expect(w.militaryAftermath?.battles.length).toBeGreaterThan(0);});
 it('stable actual executive control has no automatic monthly expiry',()=>{const w=start();for(const r of ['east','west'] as const){expect(regencyBalance(w,r).delta).toBeGreaterThanOrEqual(0);const grip=w.relationships!.regencies[r]!.grip;w.day=nextMonthStart(w.day);advanceRelationships(w);expect(w.relationships!.regencies[r]!.grip).toBeGreaterThanOrEqual(grip);}validateWorld(w);});
 it('an incumbent with earned military deeds can negotiate a historical dynasty, never force it by date',()=>{const w=start(),g=governmentOf(w,'east')!;w.day=nextMonthStart(365*5);g.executives=['gao-yang'];g.ruler='yuan-shanjian';g.support=90;g.merit['gao-yang']=20;for(let i=0;i<3;i++)awardDeed(w,'east','gao-yang','battle:'+i,8,'战胜');syncRelationships(w);w.relationships!.regencies.east!.since=0;w.realm!.personalInfluence!['gao-yang']=500;advancePowerPolitics(w);expect(w.politics?.proposals.east?.sourceStage).toBe('qi-accession');expect(g.ruler).toBe('yuan-shanjian');expect(g.dynasty).toBe('east');for(let i=0;i<180&&g.dynasty==='east';i++){w.day++;advancePowerPolitics(w);}expect(g.ruler).toBe('gao-yang');expect(g.dynasty).not.toBe('east');validateWorld(w);});
 it('reaches a real siege against an undefended war objective',()=>{const w=battleWorld();w.realm!.armies=w.realm!.armies.filter(a=>a.realm==='east');w.realm!.treasuries.west.coins=0;w.day=10;w.mobility!.armyCommanders={};const people=relationshipPeople.filter(p=>p.realm==='east');w.realm!.armies.forEach((a,i)=>w.mobility!.armyCommanders![a.id!]=people[i].id);for(let i=0;i<20;i++){w.day++;advanceRealm(w);}expect(w.realm!.sieges?.some(s=>s.site==='changan')).toBe(true);});
 it('keeps direct-control troops out of an AI assembled attack',()=>{const w=battleWorld();w.day=10;w.realm!.armies.push({realm:'east',location:'luoyang',troops:3000,morale:100,supply:120,journey:null,siege:0,automation:'direct'});ensureArmyOrganization(w);advanceMilitaryAI(w);expect(w.realm!.armies.at(-1)!.journey).toBeNull();expect(w.realm!.armies.filter(a=>a.realm==='east').every(a=>!a.journey||a.journey.route.at(-1)!=='changan')).toBe(true);});
 it('AI pays for real office promises once, without deciding for the player',()=>{const w=start(),g=governmentOf(w,'east')!;g.court!.ministries.secretariat='gao-yang';g.court!.ministries.finance='gao-cheng';w.realm!.personalInfluence!['gao-yang']=200;actPower(w,{type:'power',action:'propose',goal:'executive',beneficiary:g.ruler,executive:'gao-yang'},'gao-yang');const p=w.politics!.proposals.east!;const row=powerSupport(w,'east',p).find(q=>q.id!==p.sponsor&&q.stance!=='support'&&q.score>=-15&&Object.values(g.court!.ministries).includes(q.id));expect(row).toBeDefined();w.day=7;advancePowerPolitics(w);expect(Object.keys(p.promises).length).toBe(1);expect(w.realm!.personalInfluence!['gao-yang']).toBe(150);const first=Object.keys(p.promises)[0];advancePowerPolitics(w);expect(p.approached[first]).toBe(w.day);expect(w.realm!.personalInfluence!['gao-yang']).toBe(150);expect(Object.keys(p.promises)).not.toContain(w.characterId);});

});
