import {getPerson} from './personRegistry';
import {worldRealms} from './polityRuntime';
import type {World} from './types';
import {type RealmId} from './realm';
import {allegianceRealm,reconcileOfficeAllegiance} from './officeEligibility';
import {governmentOf,governingAuthority,governingExecutives} from './government';
import {armyCommander} from './mobility';
import {personResidence,presentAt} from './residence';
import {isAlive} from './lifeState';
import {detained} from './custodyState';
import {relationOpinion,changeRelationOpinion,oathCycle} from './relationships';
import {personInfluence,awardInfluence} from './personalInfluence';
import {actMilitaryDefection,militaryDefectionQuote} from './militaryDefection';
import {detachRetainer,retainPersonalFollowers} from './allegianceTransition';
import {civilWar,civilReason,actCivilWar} from './civilWars';
import {activeWars} from './wars';
import {planRoute} from './world';
import {capital} from './realm';
import {armyCampaign} from './militaryCampaigns';
import {isMonthStart} from './calendar';

export type ReceptionTerms='retain'|'reform'|'personal';
export const receptionNames={retain:'保留部曲',reform:'逐步改编',personal:'只接纳个人'};
export interface AllegiancePact {id:number;person:string;from:RealmId;to:RealmId;army:number|null;created:number;due:number;terms:ReceptionTerms;status:'pending'|'active'|'rejected'|'ended';breaches:string[];reviewed:number}
export interface AllegiancePacts {nextId:number;items:AllegiancePact[]}
export type PactCommand={type:'pact';action:'request';realm:RealmId;army?:number;terms:ReceptionTerms}|{type:'pact';action:'answer';id:number;accept:boolean}|{type:'pact';action:'renegotiate';id:number;terms:ReceptionTerms};
function log(w:World,text:string){w.chronicle.push({day:w.day,person:'player',text});w.chronicle=w.chronicle.slice(-100);}
function ensure(w:World){return w.allegiancePacts??={nextId:1,items:[]};}
export function pactQuote(w:World,p:Pick<AllegiancePact,'person'|'from'|'to'|'army'|'terms'>){const a=w.realm?.armies.find(a=>a.id===p.army),id=p.person,chief=governingAuthority(w,p.to),units=a?.regiments??[],following=units.filter(u=>a?.owner===id||u.loyalTo===id&&(u.commanderLoyalty??0)>=60&&(u.commanderLoyalty??0)>(u.institution??60)),troops=p.terms==='personal'?0:following.reduce((n,u)=>n+u.troops,0);return {troops,remaining:(a?.troops??0)-troops,protection:p.terms==='personal'?0:100,acceptance:relationOpinion(w,id,chief)+(p.terms==='retain'?20:p.terms==='personal'?5:-15),route:chief?planRoute(personResidence(w,id).site,capital(p.to,w),site=>site===personResidence(w,id).site||w.realm!.cities[site].controller===p.from||w.realm!.cities[site].controller===p.to):null};}
export function pactReason(w:World,c:PactCommand,actor=w.characterId!){if(!w.realm||!w.relationships||!isAlive(w,actor)||detained(w,actor)||w.campaign?.status!=='active')return '须在世自由人物与有效政权';const r=allegianceRealm(w,actor)!;
 if(c.action==='request'){if(!worldRealms(w).includes(c.realm)||c.realm===r||w.realm.annexed?.[c.realm])return '须选择另一个存续政权';if(governmentOf(w,r)?.ruler===actor)return '在位君主须先交接君位，不能以个人归附转国';if(governingExecutives(w,r).includes(actor))return '执政者须通过国家外交办理';if(!['retain','reform','personal'].includes(c.terms))return '未知安置方案';if((w.allegiancePacts?.items??[]).some(p=>p.person===actor&&(p.status==='pending'||p.status==='active'||w.day-p.created<180)))return '已有归附议案或正在冷却';if(personResidence(w,actor).traveling)return '须在驻地交涉';if(personInfluence(w,actor)<20)return '归附请求需个人影响力 20';if(w.diplomacy?.missions.some(m=>m.envoy===actor)||w.service?.tasks.some(t=>t.phase!=='closed'&&(t.officer===actor||t.helper===actor))||w.mobility?.activities.some(q=>!['done','cancelled'].includes(q.phase)&&(q.actor===actor||q.delegate===actor)))return '须先交接使团和在办差事';if(oathCycle(w,actor,governingAuthority(w,c.realm)))return '新誓约会形成循环';
 const a=w.realm.armies.find(a=>a.id===c.army);if(c.terms!=='personal'){if(w.retinue?.members[actor])return '须先解除旧国幕府归属';if(!a||a.realm!==r||a.journey||!presentAt(w,actor,a.location)||a.owner&&a.owner!==actor||armyCommander(w,a)!==actor&&a.owner!==actor)return '须本人随实际统领或所有的部队驻留';if(armyCampaign(w,a))return '须先交接战役委任与专款';const q=pactQuote(w,{person:actor,from:r,to:c.realm,army:a.id!,terms:c.terms});if(q.troops<100||q.remaining>0&&q.remaining<100)return '追随或留守兵团不足独立编制';if(q.remaining&&w.realm.armies.length>=48)return '无剩余编制容纳留守部队';}return pactQuote(w,{person:actor,from:r,to:c.realm,army:c.army??null,terms:c.terms}).route?'':'没有通往接纳朝廷的实际道路';}
 const p=w.allegiancePacts?.items.find(p=>p.id===c.id);if(!p)return '归附事项已不存在';if(c.action==='answer'){if(p.status!=='pending')return '归附事项已裁定';if(!governingExecutives(w,p.to).includes(actor))return '须接纳国实际执政者裁定';if(typeof c.accept!=='boolean')return '须明确接受或拒绝';if(!c.accept)return '';if(!isAlive(w,p.person)||detained(w,p.person)||allegianceRealm(w,p.person)!==p.from||governmentOf(w,p.from)?.ruler===p.person||governingExecutives(w,p.from).includes(p.person))return '请求人身份已经变化';if(personResidence(w,p.person).traveling||w.retinue?.members[p.person]&&p.terms!=='personal'||w.diplomacy?.missions.some(m=>m.envoy===p.person||m.actor===p.person)||w.service?.tasks.some(t=>t.phase!=='closed'&&(t.officer===p.person||t.helper===p.person))||w.mobility?.activities.some(q=>!['done','cancelled'].includes(q.phase)&&(q.actor===p.person||q.delegate===p.person)))return '须先交接使团、在办差事和行程';if(!pactQuote(w,p).route||oathCycle(w,p.person,governingAuthority(w,p.to)))return '接纳道路或誓约已失效';if(p.terms!=='personal'){const why=militaryDefectionQuote(w,{type:'militaryDefection',realm:p.to,army:p.army!},p.person,true).reason;if(why)return why;}const q=pactQuote(w,p);return w.realm.treasuries[p.to].coins<q.protection?'接纳武装归附需中央保护预算 100 钱':p.terms!=='personal'&&activeWars(w).filter(v=>!v.civil).length>=6?'外战名额不足，无法承担保护战争':'';}
 if(p.status!=='active'||p.person!==actor)return '须由归附本人提出重新约定';if(!['retain','reform'].includes(c.terms)||p.terms==='personal')return '个人归附没有可重议的部曲';return relationOpinion(w,p.person,governingAuthority(w,p.to))<0?'接纳方暂不接受调整兵权':personInfluence(w,actor)<10?'重议需个人影响力 10':'';
}
function personalDefection(w:World,p:AllegiancePact){retainPersonalFollowers(w,p.person,p.from);detachRetainer(w,p.person);const rs=w.relationships!,lord=governingAuthority(w,p.to);delete rs.oaths[p.person];(rs.allegiances??={})[p.person]={realm:p.to,from:p.from,since:w.day,army:0,source:'pact'};if(lord&&lord!==p.person)rs.oaths[p.person]={lord,since:w.day,loyalty:60};for(const [key,id] of Object.entries(w.mobility?.armyCommanders??{}))if(id===p.person)delete w.mobility!.armyCommanders![Number(key)];for(const r of worldRealms(w))if(w.mobility?.commanders[r]===p.person)delete w.mobility.commanders[r];reconcileOfficeAllegiance(w);}
export function actPact(w:World,c:PactCommand,actor=w.characterId!){const next=structuredClone(w);perform(next,c,actor);Object.assign(w,next);}
function perform(w:World,c:PactCommand,actor:string){const why=pactReason(w,c,actor);if(why)throw new Error(why);const s=ensure(w);
 if(c.action==='request'){awardInfluence(w,actor,-20);s.items.push({id:s.nextId++,person:actor,from:allegianceRealm(w,actor)!,to:c.realm,army:c.terms==='personal'?null:c.army??null,created:w.day,due:w.day+30,terms:c.terms,status:'pending',breaches:[],reviewed:w.day});log(w, getPerson(w,actor)!.name+'请求'+receptionNames[c.terms]+'归附，等待接纳国回应。');return;}
 const p=s.items.find(p=>p.id===c.id)!;if(c.action==='renegotiate'){awardInfluence(w,actor,-10);p.terms=c.terms;p.due=w.day+90;p.breaches=[];changeRelationOpinion(w,p.person,governingAuthority(w,p.to),10);return;}
 if(!c.accept){p.status='rejected';return;}const q=pactQuote(w,p);if(p.terms==='personal')personalDefection(w,p);else {w.realm!.treasuries[p.to].coins-=q.protection;actMilitaryDefection(w,{type:'militaryDefection',army:p.army!,realm:p.to},p.person,true);const a=w.realm!.armies.find(a=>a.id===p.army)!;a.payer='central:'+p.to;}
 p.status='active';p.due=w.day+90;p.reviewed=w.day;log(w, getPerson(w,p.person)!.name+'获准'+receptionNames[p.terms]+'归附；'+q.troops+' 人真实转投，地方归属保留，'+(q.protection?'接纳国承担保护预算及公饷。':'个人效忠改变。'));}
export function advancePacts(w:World){if(!w.realm)return;const s=ensure(w);if(isMonthStart(w.day,w.scriptId)){for(const r of worldRealms(w)){const chief=governingAuthority(w,r),candidate=w.realm.armies.find(a=>a.realm===r&&!a.journey&&(a.owner??armyCommander(w,a))!==w.characterId&&!!(a.owner??armyCommander(w,a))&&relationOpinion(w,chief,(a.owner??armyCommander(w,a))!)<=-30);if(!candidate)continue;const person=candidate.owner??armyCommander(w,candidate)!;const hosts=worldRealms(w).filter(to=>to!==r&&!w.realm!.annexed?.[to]).sort((a,b)=>relationOpinion(w,person,governingAuthority(w,b))-relationOpinion(w,person,governingAuthority(w,a)));for(const to of hosts){const request={type:'pact',action:'request',realm:to,army:candidate.id,terms:'retain'} as const;if(!pactReason(w,request,person)){perform(w,request,person);break;}}}}for(const p of s.items){if(p.status==='pending'){if(!isAlive(w,p.person)||detained(w,p.person)||allegianceRealm(w,p.person)!==p.from||w.day>=p.due){p.status='rejected';continue;}const chief=governingAuthority(w,p.to);if(chief&&chief!==w.characterId){const c={type:'pact',action:'answer',id:p.id,accept:true} as const;if(relationOpinion(w,chief,p.person)>=-10&&!pactReason(w,c,chief))perform(w,c,chief);}continue;}if(p.status!=='active')continue;if(!isAlive(w,p.person)||allegianceRealm(w,p.person)!==p.to){p.status='ended';continue;}const a=w.realm.armies.find(a=>a.id===p.army),chief=governingAuthority(w,p.to),breaches=[...(detained(w,p.person)?['安全保证失效']:[]),...(p.terms==='retain'&&a&&(armyCommander(w,a)!==p.person&&a.owner!==p.person)?['撤去约定兵权']:[]),...(a&&(a.arrears??0)>0?['连续欠饷']:[])];
 if(isMonthStart(w.day,w.scriptId)&&p.reviewed<w.day){p.reviewed=w.day;for(const cause of breaches){if(!p.breaches.includes(cause)){p.breaches.push(cause);changeRelationOpinion(w,p.person,chief,-20);const oath=w.relationships?.oaths[p.person];if(oath)oath.loyalty=Math.max(1,oath.loyalty-20);log(w, getPerson(w,p.person)!.name+'就「'+cause+'」提出交涉。');}}
 if(p.terms==='reform'&&w.day>=p.due&&a&&!a.arrears&&!detained(w,p.person)&&relationOpinion(w,p.person,chief)>=0){delete a.owner;a.payer='central:'+p.to;for(const u of a.regiments??[])u.institution=Math.max(60,u.institution??0);p.terms='retain';log(w, getPerson(w,p.person)!.name+'依归附约定完成改编，原籍、经验与个人忠诚保留。');}
 if(p.person!==w.characterId&&p.breaches.length&&relationOpinion(w,p.person,chief)<-40&&!civilWar(w,p.to)){const c={type:'civilWar',action:'rise',name:'新朝'} as const;if(!civilReason(w,c,p.person))actCivilWar(w,c,p.person);}
 }}s.items=s.items.filter(p=>p.status==='pending'||p.status==='active'||w.day-p.created<360).slice(-100);}
export function pactBreachRisk(w:World,person:string|undefined,army:number|undefined){return !!person&&w.allegiancePacts?.items.some(p=>p.status==='active'&&p.person===person&&p.army===army&&p.terms==='retain'&&relationOpinion(w,person,governingAuthority(w,p.to))<20);}

export function validPacts(w:World){const s=w.allegiancePacts;if(s===undefined)return true;const integer=(n:number,max:number)=>Number.isSafeInteger(n)&&n>=0&&n<=max;if(!s||!integer(s.nextId,1e9)||s.nextId<1||!Array.isArray(s.items)||s.items.length>100||new Set(s.items.map(p=>p.id)).size!==s.items.length)return false;return s.items.every(p=>p&&integer(p.id,s.nextId-1)&&p.id>0&&!! getPerson(w,p.person)!&&worldRealms(w).includes(p.from)&&worldRealms(w).includes(p.to)&&p.from!==p.to&&(p.army===null||integer(p.army,(w.realm?.nextArmyId??1)-1)&&p.army>0)&&integer(p.created,w.day)&&integer(p.due,w.day+90)&&integer(p.reviewed,w.day)&&['retain','reform','personal'].includes(p.terms)&&['pending','active','rejected','ended'].includes(p.status)&&Array.isArray(p.breaches)&&p.breaches.length<=3&&new Set(p.breaches).size===p.breaches.length&&p.breaches.every(v=>['安全保证失效','撤去约定兵权','连续欠饷'].includes(v)));}
