import {describe,it,expect} from 'vitest';
import {newCampaignWorld} from './world';
import {advanceAppointments,actAppointments,appointmentReason,appointmentChange,makeAppointmentRound,appointmentFactors,appointmentPauses} from './appointmentCycle';
import {countyOfficials,historicalLocalAppointments} from '../data/localOfficials';
import {localHolder,setLocalHolder,countyTerritory,completeLocalAppointment} from './localAdministration';
import {governmentOf} from './government';
import {parseWorld,serializeWorld} from './save';
import {pauseSnapshot,pauseEvents,pauseHasActions} from './pauseEvents';
const start=()=>newCampaignWorld('xiao-yan',undefined,'sandbox');
function review(){const w=start();advanceAppointments(w);w.day=1096;advanceAppointments(w);return w;}
describe('开局任官与三年铨选',()=>{
 it('县官逐县补齐，不把君主或名将当县令；未知州郡空缺',()=>{const w=start();for(const p of countyOfficials)expect(w.realm!.cities[p.home].governor).toBe(p.id);expect(w.holdings.governedCities).toEqual([]);expect(Object.values(w.realm!.local!.seats).filter(s=>s.holder).length).toBe(historicalLocalAppointments.length);expect(localHolder(w,'province:liang:益州','liang')).toBe('xiao-ji');expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('按日历三年触发，一轮一份，暂停面向实际最高执政者',()=>{const w=start();advanceAppointments(w);w.day=1095;advanceAppointments(w);expect(appointmentPauses(w)).toHaveLength(0);const before=pauseSnapshot(w);w.day++;advanceAppointments(w);const events=pauseEvents(before,w).filter(e=>e.kind==='appointments');expect(events).toHaveLength(1);expect(pauseHasActions(w,events[0])).toBe(true);const round=structuredClone(w.realm!.local!.cycle!.rounds.liang);advanceAppointments(w);expect(w.realm!.local!.cycle!.rounds.liang).toEqual(round);expect(w.realm!.local!.cycle!.rounds.east!.approver).toBe('gao-huan');expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('三项真实评分影响排序和晋升，不能靠虚构成功率',()=>{const w=start(),id='county-official-wucheng';governmentOf(w,'liang')!.merit[id]=90;w.families!.prestige[id]=200;const factors=appointmentFactors(w,id,'liang');expect(factors.score).toBe(112);const q=makeAppointmentRound(w,'liang');const row=q.rows.find(row=>row.candidate===id)!;expect(appointmentChange(row)).toBe('晋升');expect(q.rows.filter(row=>row.candidate===id)).toHaveLength(1);});
 it('改名单扣真实影响力，重复命令不扣费；批准沿用赴任并可存读',()=>{const w=review(),q=w.realm!.local!.cycle!.rounds.liang!,row=q.rows.find(row=>row.territory===countyTerritory('wucheng'))!;w.realm!.influence=100;const edit={type:'appointments',action:'edit',realm:'liang',year:q.year,territory:row.territory,candidate:'xu-ling'} as const;expect(appointmentReason(w,edit)).toBe('');actAppointments(w,edit);expect(w.realm!.influence).toBe(80);expect(()=>actAppointments(w,edit)).toThrow('未变化');const cmd={type:'appointments',action:'approve',realm:'liang',year:q.year} as const;actAppointments(w,cmd);expect(w.realm!.cities.wucheng.governor).toBeNull();const o=w.realm!.offices.find(o=>o.candidate==='xu-ling')!;expect(o).toBeDefined();w.mobility!.residences['xu-ling']={site:o.site,journey:null};expect(completeLocalAppointment(w,o)).toBe(true);w.realm!.offices=w.realm!.offices.filter(p=>p!==o);expect(w.realm!.cities.wucheng.governor).toBe('xu-ling');expect(()=>actAppointments(w,cmd)).toThrow('结束');expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('失守、改朝、权限变化不能颁下旧名单；否决不改变职位',()=>{const w=review(),q=w.realm!.local!.cycle!.rounds.liang!,cmd={type:'appointments',action:'approve',realm:'liang',year:q.year} as const;expect(appointmentReason(w,cmd,'xiao-gang')).toContain('最高');w.realm!.cities.wucheng.controller='east';expect(appointmentReason(w,cmd)).toContain('变化');const before=structuredClone(w.realm!.cities);actAppointments(w,{...cmd,action:'reject'});expect(w.realm!.cities).toEqual(before);const w2=review();governmentOf(w2,'liang')!.regimeId='new-dynasty';advanceAppointments(w2);expect(w2.realm!.local!.cycle!.rounds.liang!.status).toBe('cancelled');const lost=review(),event=appointmentPauses(lost)[0];lost.campaign!.status='lost';expect(appointmentPauses(lost)).toEqual([]);expect(pauseHasActions(lost,event)).toBe(false);});
 it('旧版本补人物但不重置任官、资金或复活已有死者',()=>{const w=start();setLocalHolder(w,countyTerritory('wucheng'),'liang','xu-ling');const coins=w.people[0].coins;w.contentVersion='546-map-0.2';const next=parseWorld(serializeWorld(w));expect(next.realm!.cities.wucheng.governor).toBe('xu-ling');expect(next.people[0].coins).toBe(coins);expect(parseWorld(serializeWorld(next))).toEqual(next);});
 it('交换拟任者按两处扣费，资金不足原样拒绝；批量赴任不互相清除',()=>{const w=review(),q=w.realm!.local!.cycle!.rounds.liang!,a=q.rows.find(r=>r.territory===countyTerritory('wucheng'))!,b=q.rows.find(r=>r.territory===countyTerritory('jiankang'))!,first=a.candidate!,second=b.candidate!,c={type:'appointments',action:'edit',realm:'liang',year:q.year,territory:a.territory,candidate:second} as const;w.realm!.influence=39;const before=structuredClone(w);expect(()=>actAppointments(w,c)).toThrow('影响力');expect(w).toEqual(before);w.realm!.influence=100;actAppointments(w,c);expect(w.realm!.influence).toBe(60);expect(a.candidate).toBe(second);expect(b.candidate).toBe(first);actAppointments(w,{type:'appointments',action:'approve',realm:'liang',year:q.year});const orders=w.realm!.offices.filter(o=>[first,second].includes(o.candidate));expect(orders).toHaveLength(2);for(const o of orders){w.mobility!.residences[o.candidate]={site:o.site,journey:null};expect(completeLocalAppointment(w,o)).toBe(true);w.realm!.offices=w.realm!.offices.filter(v=>v!==o);}expect(localHolder(w,a.territory,'liang')).toBe(second);expect(localHolder(w,b.territory,'liang')).toBe(first);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('其他政权自行审批，玩家的审批不被代替；损坏清单被存档校验拒绝',()=>{const w=review();w.day+=7;advanceAppointments(w);expect(w.realm!.local!.cycle!.rounds.liang!.status).toBe('pending');expect(w.realm!.local!.cycle!.rounds.east!.status).toBe('approved');expect(w.realm!.local!.cycle!.rounds.west!.status).toBe('approved');expect(parseWorld(serializeWorld(w))).toEqual(w);for(const mutate of [(x:typeof w)=>{x.realm!.local!.cycle!.rounds.liang!.rows[0].score++;},(x:typeof w)=>{x.realm!.local!.cycle!.rounds.liang!.rows[0].territory='__proto__';},(x:typeof w)=>{x.realm!.local!.cycle!.rounds.liang!.rows.push({...x.realm!.local!.cycle!.rounds.liang!.rows[0]});}]){const bad=structuredClone(w);mutate(bad);expect(()=>serializeWorld(bad)).toThrow('存档');}});

});
