import {describe,it,expect} from 'vitest';
import {newCampaignWorld,act} from './world';
import {armyCommander,commandArmy,syncArmyTravel} from './mobility';
import {serializeWorld,parseWorld} from './save';
import {serviceBusy} from './assignments';
import {lifeOf} from './lifeState';
function setup(){const w=newCampaignWorld('xiao-yan',undefined,'sandbox');w.realm!.cities.jiankang.grain=1000;for(let i=0;i<2;i++)act(w,{type:'army',action:'raise',site:'jiankang',kind:'shield',service:'levy'});w.mobility!.residences['xiao-gang']={site:'jiankang',journey:null};return w;}
describe('per-army commanders',()=>{
 it('assigns two distinct leaders, persists them and blocks double booking',()=>{const w=setup(),[a,b]=w.realm!.armies;
  act(w,{type:'mobility',action:'command',army:a.id,person:'xiao-gang'});act(w,{type:'mobility',action:'command',army:b.id,person:'xiao-yan'});
  expect(armyCommander(w,a)).toBe('xiao-gang');expect(commandArmy(w,'xiao-yan')?.id).toBe(b.id);expect(serviceBusy(w,'xiao-gang')).toBe(true);
  expect(()=>act(w,{type:'mobility',action:'command',army:b.id,person:'xiao-gang'})).toThrow('统领');expect(parseWorld(serializeWorld(w))).toEqual(w);
 });
 it('follows only the appointed army and disbands without injuring its leader',()=>{const w=setup(),[a,b]=w.realm!.armies;act(w,{type:'mobility',action:'command',army:b.id,person:'xiao-yan'});b.trainingUntil=0;act(w,{type:'realm',action:'march',army:b.id,site:'jingkou'});syncArmyTravel(w);expect(w.people[0].journey).toEqual(b.journey);expect(a.journey).toBeNull();b.journey=null;syncArmyTravel(w);const health=lifeOf(w,'xiao-yan')!.health;act(w,{type:'realm',action:'disband',army:b.id});syncArmyTravel(w);expect(commandArmy(w,'xiao-yan')).toBeUndefined();expect(w.realm!.armies).toHaveLength(1);expect(lifeOf(w,'xiao-yan')!.health).toBe(health);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('dismisses one army commander without touching another and permits later merging',()=>{const w=setup(),[a,b]=w.realm!.armies;act(w,{type:'mobility',action:'command',army:a.id,person:'xiao-gang'});act(w,{type:'mobility',action:'command',army:b.id,person:'xiao-yan'});act(w,{type:'mobility',action:'dismiss-command',army:b.id!});expect(armyCommander(w,a)).toBe('xiao-gang');expect(armyCommander(w,b)).toBeUndefined();act(w,{type:'army',action:'merge',army:a.id!,target:b.id!});expect(a.troops).toBe(400);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('hands a standing commander to a campaign and restores command on cancellation',()=>{const w=setup(),a=w.realm!.armies[0];act(w,{type:'mobility',action:'command',army:a.id,person:'xiao-gang'});a.trainingUntil=0;w.realm!.wars=[{id:1,attacker:'liang',defender:'east',target:'ye',started:0,score:0}];w.realm!.nextWarId=2;w.realm!.war=w.realm!.wars[0];act(w,{type:'militaryCampaign',action:'commission',army:a.id!,war:1,commander:'xiao-gang',target:'ye',goal:'capture',budget:100,lossLimit:50});expect(armyCommander(w,a)).toBe('xiao-gang');expect(w.mobility!.armyCommanders![a.id!]).toBeUndefined();act(w,{type:'militaryCampaign',action:'cancel',id:w.militaryCampaigns!.items[0].id});expect(armyCommander(w,a)).toBe('xiao-gang');expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('clears dead leaders and rejects orphan or duplicate saved assignments',()=>{const w=setup(),[a,b]=w.realm!.armies;act(w,{type:'mobility',action:'command',army:a.id,person:'xiao-gang'});const broken=structuredClone(w);broken.mobility!.armyCommanders![b.id!]='xiao-gang';expect(()=>serializeWorld(broken)).toThrow();const orphan=structuredClone(w);orphan.mobility!.armyCommanders![9999]='xiao-yan';expect(()=>serializeWorld(orphan)).toThrow();lifeOf(w,'xiao-gang')!.death={day:w.day,cause:'age'};syncArmyTravel(w);expect(armyCommander(w,a)).toBeUndefined();});
});
