import {validLocalAdministration} from './localAdministrationSave';
import {validFiscal} from './treasurySave';
import {validRealm} from './realmSave';
import {validGovernments} from './governmentSave';
import {validDiplomacy} from './diplomacySave';
import {describe,it,expect} from 'vitest';
import {newCampaignWorld,act,advance} from './world';
import {parseWorld,serializeWorld,validateWorld} from './save';
import {ensureFiscal,fiscalPath,collectFiscal} from './treasury';
import {enterpriseReason,advanceEnterprises} from './enterprises';
import {campaignReason,advanceMilitaryCampaigns} from './militaryCampaigns';
import {ensureArmyOrganization,payArmy} from './armyOrganization';
import {ensureWars,activeWars,peaceQuote} from './wars';
import {annexationReason} from './polityLifecycle';
import {settleWar,realmReason} from './realm';
import {allegianceRealm} from './officeEligibility';
import {civilReason,civilWar,armyControls,armiesHostile} from './civilWars';
import {governmentOf} from './government';
function w0(id='xiao-yan'){return newCampaignWorld(id,undefined,'sandbox');}
function army(w:ReturnType<typeof w0>,r:'liang'|'east'='liang',site='jiankang'){w.realm!.armies.push({realm:r,location:site,troops:400,morale:80,supply:120,journey:null,siege:0});ensureArmyOrganization(w);return w.realm!.armies.at(-1)!;}
function war(w:ReturnType<typeof w0>){ensureWars(w);const s=w.realm!;s.wars!.push({id:s.nextWarId!++,attacker:'liang',defender:'east',target:'ye',score:100,started:w.day,goal:'territory'});s.war=s.wars![0];return s.war;}
function entrepreneur(){const w=w0('chen-baxian'),site=w.people[0].location;w.realm!.cities[site].governor=null;w.realm!.cities[site].prosperity=40;const f=ensureFiscal(w)!;f.balances[fiscalPath(w,site)[0]]=500;w.people[0].coins=500;return w;}
function revolt(){const w=w0('xiao-yi'),site=w.people[0].location;w.realm!.cities[site].owner='liang';w.realm!.cities[site].controller='liang';w.realm!.cities[site].governor=w.characterId!;w.realm!.cities[site].grain=300;w.realm!.influence=200;w.people[0].coins=500;const f=ensureFiscal(w)!;const source=fiscalPath(w,site)[0];f.balances[source]=300;const a=army(w,'liang',site);a.payer=source;return {w,a,site,source};}
describe('private enterprises',()=>{
 it('moves private capital and a real public escrow, then settles income only once',()=>{const w=entrepreneur(),site=w.people[0].location,key=fiscalPath(w,site)[0];act(w,{type:'enterprise',action:'open',kind:'workshop'});expect(w.people[0].coins).toBe(380);expect(enterpriseReason(w,{type:'enterprise',action:'order',id:1,method:'careful'})).toBe('');act(w,{type:'enterprise',action:'order',id:1,method:'careful'});expect(w.realm!.fiscal!.balances[key]).toBe(400);const e=w.enterprises!.items[0];expect(e.capital).toBe(60);expect({local:validLocalAdministration(w),fiscal:validFiscal(w),realm:validRealm(w),government:validGovernments(w),diplomacy:validDiplomacy(w)}).toEqual({local:true,fiscal:true,realm:true,government:true,diplomacy:true});expect(parseWorld(serializeWorld(w))).toEqual(w);for(let d=1;d<=30;d++){w.day=d;advanceEnterprises(w);}expect(e.earned).toBe(100);expect(e.capital).toBe(160);advanceEnterprises(w);expect(e.capital).toBe(160);expect(w.realm!.cities[site].prosperity).toBe(48);act(w,{type:'enterprise',action:'close',id:1});expect(w.people[0].coins).toBe(540);});
 it('preserves spent cost on cancellation and blocks self-dealing',()=>{const w=entrepreneur(),site=w.people[0].location;act(w,{type:'enterprise',action:'open',kind:'agriculture'});act(w,{type:'enterprise',action:'order',id:1,method:'swift'});act(w,{type:'enterprise',action:'cancel',id:1});expect(w.enterprises!.items[0].capital).toBe(90);expect(w.realm!.fiscal!.balances[fiscalPath(w,site)[0]]).toBe(500);const emperor=w0();act(emperor,{type:'enterprise',action:'open',kind:'workshop'});expect(enterpriseReason(emperor,{type:'enterprise',action:'order',id:1,method:'careful'})).toContain('自己');});
 it('stops work away from the site and rejects forged escrow',()=>{const w=entrepreneur();act(w,{type:'enterprise',action:'open',kind:'workshop'});act(w,{type:'enterprise',action:'order',id:1,method:'careful'});w.people[0].location='ye';w.day=1;advanceEnterprises(w);expect(w.enterprises!.items[0].order!.progress).toBe(0);w.enterprises!.items[0].order!.escrow=101;expect(()=>validateWorld(w)).toThrow();});
});
describe('military campaign mandates',()=>{
 it('pays the actual army from escrow and refunds its exact remaining budget',()=>{const w=w0(),a=army(w),v=war(w),source=w.realm!.treasuries.liang;const c={type:'militaryCampaign',action:'commission',army:a.id!,war:v.id!,commander:w.characterId!,target:'ye',goal:'capture',budget:200,lossLimit:50} as const;expect(campaignReason(w,c)).toBe('');const before=source.coins;act(w,c);expect(source.coins).toBe(before-200);payArmy(w,a,35);expect(source.coins).toBe(before-200);expect(w.militaryCampaigns!.items[0].remaining).toBe(165);expect({local:validLocalAdministration(w),fiscal:validFiscal(w),realm:validRealm(w),government:validGovernments(w),diplomacy:validDiplomacy(w)}).toEqual({local:true,fiscal:true,realm:true,government:true,diplomacy:true});expect(parseWorld(serializeWorld(w))).toEqual(w);expect(realmReason(w,{type:'realm',action:'march',army:a.id,site:'ye'})).toContain('撤销');act(w,{type:'militaryCampaign',action:'cancel',id:1});expect(source.coins).toBe(before-35);expect({local:validLocalAdministration(w),fiscal:validFiscal(w),realm:validRealm(w),government:validGovernments(w),diplomacy:validDiplomacy(w)}).toEqual({local:true,fiscal:true,realm:true,government:true,diplomacy:true});expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('terminates at the agreed loss limit and never awards failed work',()=>{const w=w0(),a=army(w),v=war(w);act(w,{type:'militaryCampaign',action:'commission',army:a.id!,war:v.id!,commander:w.characterId!,target:'ye',goal:'capture',budget:200,lossLimit:25});const merit=governmentOf(w)!.merit[w.characterId!];a.troops=300;advanceMilitaryCampaigns(w);expect(w.militaryCampaigns!.items[0].status).toBe('failed');expect(governmentOf(w)!.merit[w.characterId!]).toBe(merit);});
});
describe('annexation settlement',()=>{
 it('requires every real territory and effective resistance to be resolved',()=>{const w=w0();expect(annexationReason(w,'liang','east')).toContain('全部');for(const c of Object.values(w.realm!.cities))if(c.owner==='east')c.controller='liang';army(w,'east','ye');expect(annexationReason(w,'liang','east')).toContain('有效抵抗');});
 it('closes the old polity and transfers actual balances and debts without duplicating cash',()=>{const w=w0(),s=w.realm!,v=war(w);v.goal='annexation';for(const c of Object.values(s.cities))if(c.owner==='east')c.controller='liang';const total=s.treasuries.liang.coins+s.treasuries.east.coins;s.armyDebts=[{realm:'east',account:'central:east',coins:37}];expect(peaceQuote(w,v,'liang','demand').reason).toBe('');settleWar(w,v,'demand');expect(s.treasuries.east.coins).toBe(0);expect(s.treasuries.liang.coins).toBe(total);expect(s.armyDebts[0].realm).toBe('liang');expect(allegianceRealm(w,'gao-huan')).toBe('liang');expect(Object.values(s.cities).some(c=>c.owner==='east')).toBe(false);expect(activeWars(w)).toHaveLength(0);expect({local:validLocalAdministration(w),fiscal:validFiscal(w),realm:validRealm(w),government:validGovernments(w),diplomacy:validDiplomacy(w)}).toEqual({local:true,fiscal:true,realm:true,government:true,diplomacy:true});expect(parseWorld(serializeWorld(w))).toEqual(w);advance(w,1);validateWorld(w);});
});
describe('civil wars share armies, sieges and public accounts',()=>{
 it('requires a real local base and military support, then separates supply and tax control',()=>{const {w,a,site,source}=revolt();const before=w.realm!.treasuries.liang.coins;expect(civilReason(w,{type:'civilWar',action:'rise',name:'新梁'})).toBe('');act(w,{type:'civilWar',action:'rise',name:'新梁'});const loyal=army(w,'liang','jiankang');expect(armiesHostile(w,a,loyal)).toBe(true);expect(armyControls(w,a,site)).toBe(true);expect(armyControls(w,loyal,site)).toBe(false);const reserve=w.realm!.fiscal!.balances[source];collectFiscal(w,'liang',new Map(Object.keys(w.realm!.cities).map(id=>[id,{coins:id===site?20:0}])));expect(w.realm!.fiscal!.balances[source]).toBe(reserve+20);expect(w.realm!.treasuries.liang.coins).toBe(before);expect({local:validLocalAdministration(w),fiscal:validFiscal(w),realm:validRealm(w),government:validGovernments(w),diplomacy:validDiplomacy(w)}).toEqual({local:true,fiscal:true,realm:true,government:true,diplomacy:true});expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('cannot win by spending influence; conquest and surviving resistance determine peace',()=>{const {w}=revolt();act(w,{type:'civilWar',action:'rise',name:'新梁'});const v=civilWar(w,'liang')!;expect(peaceQuote(w,v,'liang','demand').reason).toContain('权力中心');v.civil!.cities.push('jiankang');const loyal=army(w,'liang','jiankang');expect(peaceQuote(w,v,'liang','demand').reason).toContain('抵抗');loyal.morale=0;expect(peaceQuote(w,v,'liang','demand').reason).toBe('');settleWar(w,v,'demand');expect(governmentOf(w)!.ruler).toBe(w.characterId);expect({local:validLocalAdministration(w),fiscal:validFiscal(w),realm:validRealm(w),government:validGovernments(w),diplomacy:validDiplomacy(w)}).toEqual({local:true,fiscal:true,realm:true,government:true,diplomacy:true});expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('runs a short daily step and keeps internal control in the save',()=>{const {w}=revolt();act(w,{type:'civilWar',action:'rise',name:'新梁'});advance(w,2);expect(civilWar(w,'liang')).toBeTruthy();expect(w.realm!.armies.length).toBeGreaterThan(1);expect({local:validLocalAdministration(w),fiscal:validFiscal(w),realm:validRealm(w),government:validGovernments(w),diplomacy:validDiplomacy(w)}).toEqual({local:true,fiscal:true,realm:true,government:true,diplomacy:true});expect(parseWorld(serializeWorld(w))).toEqual(w);});
});

describe('settlement and authority boundaries',()=>{
 it('does not let a repeated same-day update accelerate a private contract',()=>{const w=entrepreneur();act(w,{type:'enterprise',action:'open',kind:'workshop'});act(w,{type:'enterprise',action:'order',id:1,method:'careful'});w.day=1;advanceEnterprises(w);advanceEnterprises(w);expect(w.enterprises!.items[0].order!.progress).toBe(1);});
 it('retains unreturnable public escrow without paying an accepted contract twice',()=>{const w=entrepreneur(),key=fiscalPath(w,w.people[0].location)[0];act(w,{type:'enterprise',action:'open',kind:'workshop'});act(w,{type:'enterprise',action:'order',id:1,method:'swift'});w.realm!.fiscal!.balances[key]=1_000_000;for(let d=1;d<=20;d++){w.day=d;advanceEnterprises(w);}const e=w.enterprises!.items[0];expect(e.earned).toBe(65);expect(e.order!.escrow).toBe(35);w.day++;advanceEnterprises(w);expect(e.earned).toBe(65);w.realm!.fiscal!.balances[key]-=35;w.day++;advanceEnterprises(w);expect(e.order).toBeNull();expect(w.realm!.fiscal!.balances[key]).toBe(1_000_000);});
 it('blocks the rebel from commanding loyal troops or taking their supply',()=>{const {w}=revolt();act(w,{type:'civilWar',action:'rise',name:'新梁'});const loyal=army(w,'liang','jiankang');expect(realmReason(w,{type:'realm',action:'march',army:loyal.id,site:'ye'})).toContain('对方军队');expect(()=>act(w,{type:'army',action:'split',army:loyal.id!,regiment:loyal.regiments![0].id})).toThrow('对方军队');});
 it('cannot annex a country whose city is occupied by a third country',()=>{const w=w0(),v=war(w);v.goal='annexation';for(const c of Object.values(w.realm!.cities))if(c.owner==='east')c.controller='liang';w.realm!.cities.jinyang.controller='west';expect(peaceQuote(w,v,'liang','demand').reason).toContain('第三国');});
 it('retains takeover overflow as an old treasury claim instead of deleting it',()=>{const w=w0(),s=w.realm!,v=war(w);v.goal='annexation';for(const c of Object.values(s.cities))if(c.owner==='east')c.controller='liang';s.treasuries.liang.coins=999999;s.treasuries.east.coins=200;settleWar(w,v,'demand');expect(s.treasuries.liang.coins).toBe(1_000_000);expect(s.treasuries.east.coins).toBe(199);expect(s.annexed!.east!.coins).toBe(1);expect(parseWorld(serializeWorld(w))).toEqual(w);});
});

describe('career continuity',()=>{
 it('lets an NPC claimant use the same actual funds and military requirements',async()=>{const {advanceCivilPolitics}=await import('./civilWars'),{awardInfluence}=await import('./personalInfluence'),{changeRelationOpinion}=await import('./relationships'),{personResidence}=await import('./residence');const w=w0(),id='xiao-yi',site=personResidence(w,id).site;w.realm!.cities[site].governor=id;w.realm!.cities[site].grain=200;const key=fiscalPath(w,site)[0];ensureFiscal(w)!.balances[key]=300;army(w,'liang',site).payer=key;awardInfluence(w,id,80);changeRelationOpinion(w,id,w.characterId!,-100);governmentOf(w)!.support=10;governmentOf(w)!.legitimacy=10;w.day=90;advanceCivilPolitics(w);expect(civilWar(w,'liang')?.civil?.claimant).toBe(id);expect(w.relationships!.reserves[id]).toBe(20);expect(w.realm!.fiscal!.balances[key]).toBe(400);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('hands a dead proprietor business to a recorded surviving descendant',()=>{const w=w0('xiao-yi');act(w,{type:'enterprise',action:'open',kind:'workshop'});const e=w.enterprises!.items[0];w.life!.people[w.characterId!].health=0;w.life!.people[w.characterId!].death={day:w.day,cause:'illness'};advanceEnterprises(w);expect(e.owner).not.toBe(w.characterId);expect(e.capital).toBe(120);});
 it('reports completed contracts and campaign exceptions through pause events',async()=>{const {pauseSnapshot,pauseEvents}=await import('./pauseEvents');const w=entrepreneur();act(w,{type:'enterprise',action:'open',kind:'workshop'});act(w,{type:'enterprise',action:'order',id:1,method:'swift'});const before=pauseSnapshot(w);act(w,{type:'enterprise',action:'cancel',id:1});expect(pauseEvents(before,w).some(e=>e.title==='承包结算')).toBe(true);});
});

// Ending a mandate must not teleport a marching army back to the previous city.
it('requires physical arrival before cancelling a marching campaign',()=>{const w=w0(),a=army(w),v=war(w);act(w,{type:'militaryCampaign',action:'commission',army:a.id!,war:v.id!,commander:w.characterId!,target:'ye',goal:'capture',budget:200,lossLimit:50});w.day=1;advanceMilitaryCampaigns(w);expect(a.journey).toBeTruthy();expect(campaignReason(w,{type:'militaryCampaign',action:'cancel',id:1})).toContain('抵达');});
it('does not allow a civil-war claimant to stroll into the opposing capital',()=>{const {w}=revolt();act(w,{type:'civilWar',action:'rise',name:'新梁'});expect(()=>act(w,{type:'travel',destination:'jiankang'})).toThrow('通行');});
it('keeps the army and its campaign commander on the same physical journey',()=>{const w=w0(),a=army(w),v=war(w),food=w.people[0].food;act(w,{type:'militaryCampaign',action:'commission',army:a.id!,war:v.id!,commander:w.characterId!,target:'ye',goal:'capture',budget:200,lossLimit:50});advance(w,3);expect(w.people[0].location).toBe(a.location);expect(w.people[0].journey).toEqual(a.journey);expect(w.people[0].food).toBeLessThanOrEqual(food);expect(parseWorld(serializeWorld(w))).toEqual(w);});
