import {syncRulerHistory} from './rulerHistory';
import {describe,it,expect} from 'vitest';
import {newCampaignWorld} from './world';
import {supportClaim} from './claims';
import {governmentOf,governingAuthority} from './government';
import {advanceRealm,declareRealmWar,declareRealmWarReason,settleWar,cancelInvalidClaimantWars} from './realm';
import {activeWars,peaceQuote,validClaimantWar} from './wars';
import {warObjectiveSites,warDeclarationCost} from './warTerritories';
import {actCourt,courtReason,courtOf,courtBonus,courtPolicyPressure,courtPolicyActive} from './court';
import {lifeOf} from './lifeState';
import {warScoreBreakdown} from './warScoring';
import {parseWorld,serializeWorld} from './save';
import {advanceRealmStrategy,supportHostedClaimant,strategicClaimantTargets} from './realmStrategy';
import {advanceRealmGovernanceAI,commissionPolicyService} from './realmGovernanceAI';
import {allegianceRealm} from './officeEligibility';
import {changeRelationOpinion} from './relationships';

function setup(){const w=newCampaignWorld('xiao-yan',undefined,'sandbox'),actor=governingAuthority(w,'east')!;w.realm!.personalInfluence![actor]=500;supportClaim(w,'west','yuan-qin',actor);const site=Object.keys(w.realm!.cities).find(id=>!declareRealmWarReason(w,actor,'east',id,'claimant',false,undefined,'yuan-qin'))!;expect(site).toBeDefined();return {w,actor,site};}
describe('actual claimant wars and stable policies',()=>{
 it('requires an explicitly supported true claimant and snapshots the patron independently of commander',()=>{const {w,actor,site}=setup();expect(declareRealmWarReason(w,actor,'east',site,'claimant',false,undefined,'yuwen-tai')).toBeTruthy();expect(declareRealmWarReason(w,actor,'east',site,'claimant',false,'province:west:雍州','yuan-qin')).toContain('仅用于割地');expect(declareRealmWarReason(w,actor,'east',site,'claimant',false,undefined,'yuan-baoju')).toContain('已经在位');const war=declareRealmWar(w,actor,'east',site,'claimant',undefined,'yuan-qin');expect(war.claimant).toMatchObject({person:'yuan-qin',patron:actor,realm:'west',source:'yuan-baoju'});expect(warDeclarationCost('claimant')).toBe(100);expect(warObjectiveSites(war,w)).toEqual([site]);expect(warObjectiveSites(war)).toEqual([site]);const relocated={...w,realm:{...w.realm!,identities:{...w.realm!.identities,west:{origin:'west' as const,capital:site,created:0,predecessor:null}}}};expect(warObjectiveSites(war,relocated)).toEqual([site]);expect(validClaimantWar(w,war)).toBe(true);expect(parseWorld(serializeWorld(w)).realm!.wars![0].claimant).toEqual(war.claimant);war.claimant!.source='yuwen-tai';expect(validClaimantWar(w,war)).toBe(false);expect(()=>serializeWorld(w)).toThrow();});
 it('victory enthrones without transferring land, cash, armies or granting the patron target executive power',()=>{const {w,actor,site}=setup(),war=declareRealmWar(w,actor,'east',site,'claimant',undefined,'yuan-qin'),s=w.realm!;for(const c of Object.values(s.cities))if(c.owner==='west'){c.controller='east';c.occupiedByWar=war.id;c.occupiedSince=0;}w.relationships!.allegiances??={};w.relationships!.allegiances['yuan-qin']={realm:'east',from:'west',since:0,army:0,source:'retained'};w.day=400;const owners=Object.fromEntries(Object.entries(s.cities).map(([id,c])=>[id,c.owner])),money=structuredClone(s.treasuries),armies=structuredClone(s.armies);expect(peaceQuote(w,war,'east','annex').reason).toBeTruthy();expect(peaceQuote(w,war,'east','demand').reason).toBeTruthy();expect(peaceQuote(w,war,'east','enthrone',[],100).reason).toBeTruthy();const q=peaceQuote(w,war,'east','enthrone');expect(q.reason).toBe('');expect(q.cessions).toEqual([]);settleWar(w,war,'enthrone','east');expect(governmentOf(w,'west')!.ruler).toBe('yuan-qin');expect(allegianceRealm(w,'yuan-qin')).toBe('west');expect(governmentOf(w,'west')!.executives).not.toContain(actor);expect(governmentOf(w,'west')!.executives).toEqual([q.enthroneExecutive]);expect(s.treasuries).toEqual(money);expect(s.armies).toEqual(armies);expect(Object.fromEntries(Object.entries(s.cities).map(([id,c])=>[id,c.owner]))).toEqual(owners);expect(Object.values(s.cities).filter(c=>c.owner==='west').every(c=>c.controller==='west')).toBe(true);expect(activeWars(w)).toHaveLength(0);expect(()=>parseWorld(serializeWorld(w))).not.toThrow();});
 it('death invalidates a day-one objective, restores only its occupations and never turns into annexation',()=>{const {w,actor,site}=setup(),war=declareRealmWar(w,actor,'east',site,'claimant',undefined,'yuan-qin'),s=w.realm!;s.cities.changan.controller='east';s.cities.changan.occupiedByWar=war.id;s.cities.changan.occupiedSince=0;s.wars!.push({id:s.nextWarId!++,attacker:'liang',defender:'west',target:'luoyang',score:0,started:0});const other=Object.entries(s.cities).find(([id,c])=>id!=='changan'&&c.owner==='west')!;other[1].controller='liang';other[1].occupiedByWar=s.wars![1].id;lifeOf(w,'yuan-qin')!.death={day:0,cause:'battle'};expect(peaceQuote(w,war,'east','enthrone').reason).toBeTruthy();cancelInvalidClaimantWars(w);expect(s.cities.changan.controller).toBe('west');expect(other[1].controller).toBe('liang');expect(activeWars(w)).toHaveLength(1);expect(s.annexed?.west).toBeUndefined();cancelInvalidClaimantWars(w);expect(activeWars(w)).toHaveLength(1);});
 it('phase gates policy bonuses and peaceful expansion while political pressure uses real power and mood',()=>{const {w}=setup(),c=courtOf(w,'west')!;c.policy='expansion';for(const id of Object.keys(c.members))if(id!==governmentOf(w,'west')!.ruler)c.members[id]='reform';expect(courtPolicyPressure(w,'west')[0].policy).toBe('reform');expect(courtPolicyActive(w,'west')).toBe('expansion');expect(courtBonus(w,'west').attack).toBe(10);for(const phase of ['strained','chaos'] as const){c.phase=phase;expect(courtPolicyActive(w,'west')).toBeNull();expect(courtBonus(w,'west').attack).toBe(0);w.day=31;w.realm!.strategy=undefined;advanceRealmStrategy(w);expect(activeWars(w)).toHaveLength(0);expect(w.realm!.strategy!.west?.phase).toBe('recover');}});
 it('stable reform opens real staffed economic and friendly diplomatic work with conserved earmarked budgets',()=>{const {w}=setup(),r='west',actor=governingAuthority(w,r)!;w.realm!.treasuries[r].coins=10000;w.realm!.treasuries[r].grain=10000;w.realm!.personalInfluence![actor]=100;actCourt(w,{type:'court',action:'appoint',ministry:'personnel',candidate:'dugu-xin'},actor);syncRulerHistory(w);const before={...w.realm!.treasuries[r]},first=w.service!.tasks.length;expect(commissionPolicyService(w,r,actor,['agriculture'])).toBe(true);const t=w.service!.tasks[first];expect(t.phase).toBe('ready');expect(t.funds).toEqual({coins:65,grain:25});expect(w.realm!.treasuries[r].coins).toBe(before.coins-65);expect(w.realm!.treasuries[r].grain).toBe(before.grain-25);courtOf(w,r)!.policy='reform';w.day=31;advanceRealmGovernanceAI(w);expect(w.service!.tasks.some(t=>t.realm===r&&t.kind==='envoy'&&t.target==='liang')).toBe(true);const snapshot=structuredClone(w);advanceRealmGovernanceAI(w);expect(w).toEqual(snapshot);expect(()=>parseWorld(serializeWorld(w))).not.toThrow();});

 it('expansion patrons can explicitly support a hosted rightful NPC heir using actual kinship, allegiance and relationship',()=>{const w=newCampaignWorld('xiao-yan',undefined,'sandbox'),actor=governingAuthority(w,'east')!;supportClaim(w,'west','yuan-qin','yuan-qin','designated');w.relationships!.allegiances??={};w.relationships!.allegiances['yuan-qin']={realm:'east',from:'west',since:0,army:0,source:'retained'};w.mobility!.residences['yuan-qin']={site:'ye',journey:null};changeRelationOpinion(w,actor,'yuan-qin',100);supportHostedClaimant(w,'east',actor);expect(w.claims!.records.some(c=>c.patron===actor)).toBe(false);courtOf(w,'east')!.policy='expansion';const stocks=structuredClone(w.realm!.treasuries);supportHostedClaimant(w,'east',actor);expect(w.claims!.records.some(c=>c.person==='yuan-qin'&&c.patron===actor&&c.kind==='support')).toBe(true);expect(strategicClaimantTargets(w,'east').every(t=>t.goal==='claimant'&&t.claimant==='yuan-qin')).toBe(true);expect(w.realm!.treasuries).toEqual(stocks);});

 it('NPC policy promises spend the genuine executive influence and cannot charge or impersonate the player',()=>{const {w}=setup(),actor=governingAuthority(w,'west')!,before=w.realm!.influence,c=courtOf(w,'west')!;w.realm!.personalInfluence![actor]=40;const command={type:'court',action:'policy',policy:'reform'} as const;expect(courtReason(w,command,'dugu-xin')).toContain('执政');expect(courtReason(w,command,actor)).toBe('');actCourt(w,command,actor);expect(w.realm!.personalInfluence![actor]).toBe(20);expect(w.realm!.influence).toBe(before);expect(c.policy).toBe('reform');expect(c.cooldowns.policy).toBe(30);expect(courtOf(w,'liang')!.policy).toBe('consolidation');const state=structuredClone(w);expect(()=>actCourt(w,command,actor)).toThrow('冷却');expect(w).toEqual(state);});
 it('a claimant war is political and does not run territorial default settlement when another war changes its positioning county owner',()=>{const {w,actor,site}=setup(),war=declareRealmWar(w,actor,'east',site,'claimant',undefined,'yuan-qin'),c=w.realm!.cities[site];c.owner='liang';c.controller='liang';c.governor=null;syncRulerHistory(w);w.day=1;expect(()=>advanceRealm(w)).not.toThrow();expect(activeWars(w)).toContain(war);expect(war.goal).toBe('claimant');expect(c.owner).toBe('liang');});

 it('another concurrent allied war cannot donate its occupation score or decisive victory to an enthronement claim',()=>{const {w,actor,site}=setup(),war=declareRealmWar(w,actor,'east',site,'claimant',undefined,'yuan-qin'),s=w.realm!,other={id:s.nextWarId!++,attacker:'liang' as const,defender:'west' as const,target:site,started:0,score:0,allies:{east:'attack' as const}};s.wars!.push(other);for(const c of Object.values(s.cities))if(c.owner==='west'){c.controller='east';c.occupiedByWar=other.id;c.occupiedSince=0;}w.day=100;const own=warScoreBreakdown(w,war);expect(own.parts.find(p=>p.key==='occupation')!.value).toBe(0);expect(own.parts.find(p=>p.key==='objective')!.value).toBe(0);expect(own.decisive).toBe(false);expect(warScoreBreakdown(w,other).total).toBe(100);expect(peaceQuote(w,war,'east','enthrone').reason).toBeTruthy();});

});
