import {armyVisualState} from './armyPresentation';
import type {World} from './types';
import type {Army,Siege} from './realm';
import type {BattleRecord} from './militaryAftermath';
import type {CombatArmySnapshot,CombatSide,SiegeSceneEvent} from './combatSnapshots';
import {combatArmySnapshot} from './combatSnapshots';
import {militaryArmyView} from './militaryView';
import {troopKinds,type TroopKind} from './armyOrganization';
import {activeWars} from './wars';
import {warArmySide} from './civilWars';
export interface FormationGroup {realm:CombatArmySnapshot['realm'];key:string;side:CombatSide;kind:TroopKind|'unknown';name:string;troops:number|null;loss:number|null;morale:number|null;withdrawn:boolean;armies:number[];experience:number|null}
export interface CombatSceneView {controller?:Army['realm']|'frontier';site?:string;besiegingSide?:CombatSide;kind:'battle'|'siege';phase:string;groups:FormationGroup[];active:boolean;fort:number;breach:number;blockade:number;gateOpen:boolean;assault:boolean;departing?:boolean;round:number;eventId?:number;note:string}
export function snapshotVisible(w:World,row:CombatArmySnapshot){const current=w.realm?.armies.find(a=>a.id===row.army&&a.realm===row.realm),a:Army=current??{id:row.army,realm:row.realm,location:row.location,owner:row.commander??undefined,troops:0,morale:0,supply:0,siege:0,journey:null};return militaryArmyView(w,a).exact;}
export function formationGroups(w:World,rows:CombatArmySnapshot[],before:CombatArmySnapshot[]=rows):FormationGroup[]{const groups=new Map<string,FormationGroup>();for(const row of rows){const exact=snapshotVisible(w,row),units=exact?row.regiments:[{id:'unknown',kind:'unknown' as const,troops:0,experience:0}];for(const u of units){if(exact&&!u.troops)continue;const key=row.side+':'+u.kind;let g=groups.get(key);if(!g){g={realm:row.realm,key,side:row.side,kind:u.kind,name:exact?troopKinds[u.kind as TroopKind].name:'兵种未详',troops:exact?0:null,loss:exact?0:null,morale:exact?row.morale:null,withdrawn:row.withdrawn,armies:[],experience:exact?0:null};groups.set(key,g);}if(!g.armies.includes(row.army))g.armies.push(row.army);g.withdrawn=g.withdrawn&&row.withdrawn;if(exact){g.troops!+=u.troops;const old=before.find(a=>a.army===row.army)?.regiments.find(r=>r.id===u.id);g.loss!+=Math.max(0,(old?.troops??u.troops)-u.troops);g.morale=Math.min(g.morale??row.morale,row.morale);g.experience=Math.max(g.experience??0,u.experience);g.withdrawn=g.withdrawn&&row.withdrawn;}}}
 // Removed regiments retain their recorded losses and never reappear as surviving units.
 for(const row of before)if(snapshotVisible(w,row))for(const u of row.regiments){if(rows.find(a=>a.army===row.army)?.regiments.some(r=>r.id===u.id))continue;const g=groups.get(row.side+':'+u.kind);if(g)g.loss!+=u.troops;else groups.set(row.side+':'+u.kind,{realm:row.realm,key:row.side+':'+u.kind,side:row.side,kind:u.kind,name:troopKinds[u.kind].name,troops:0,loss:u.troops,morale:0,withdrawn:true,armies:[row.army],experience:u.experience});}
 return [...groups.values()];}
export const combatPhaseNames={skirmish:'前哨交锋',clash:'主力交战',pursuit:'追击阶段'};
/** Current presence is read from actual armies; historical numbers remain settlement snapshots. */
export function liveBattleArmies(w:World,b:BattleRecord,side:CombatSide){const war=activeWars(w).find(v=>v.id===b.war),ids=side==='attack'?b.attackers??[b.a]:b.defenders??[b.b];return (w.realm?.armies??[]).filter(a=>ids.includes(a.id!)&&a.troops>=100&&!a.withdrawalUntil&&(!war||warArmySide(w,war,a)===side)&&(!a.journey?a.location===b.site:b.contact?.key.startsWith('road:')?'road:'+a.journey.route.slice(a.journey.leg,a.journey.leg+2).sort().join('|')===b.contact.key:a.journey.route[a.journey.leg+1]===b.site&&a.journey.elapsed+1>=a.journey.durations[a.journey.leg]));}
export function armyBattle(w:World,a:Army){return w.militaryAftermath?.battles.find(b=>b.ended===undefined&&b.last===w.day&&(b.war===undefined||activeWars(w).some(v=>v.id===b.war))&&liveBattleArmies(w,b,'attack').length>0&&liveBattleArmies(w,b,'defend').length>0&&(['attack','defend'] as const).some(side=>liveBattleArmies(w,b,side).some(v=>v.id===a.id)));}
export function battleSceneView(w:World,b:BattleRecord):CombatSceneView {const r=b.rounds?.at(-1),recent=b.ended===undefined&&w.day-b.last<=1,present=[...liveBattleArmies(w,b,'attack'),...liveBattleArmies(w,b,'defend')],active=recent&&liveBattleArmies(w,b,'attack').length>0&&liveBattleArmies(w,b,'defend').length>0,rows=r?.after.map(row=>({...row,withdrawn:row.withdrawn||(b.withdrawals?.[row.army]??-1)>=r.day||recent&&!present.some(a=>a.id===row.army)}));return {site:b.site,kind:'battle',phase:b.ended!==undefined?'交战结束':active?combatPhaseNames[b.stage]:'交战暂歇',groups:r&&rows?formationGroups(w,rows,r.before):[],active,fort:0,breach:0,blockade:0,gateOpen:false,assault:false,departing:recent&&Object.values(b.withdrawals??{}).some(day=>day===w.day),round:b.round,note:r?'军阵人数为本轮结算快照，退出状态即时更新；站位示意，不独立结算翼侧与包抄。':'该记录不含军阵过程；不以现役兵力回填历史军阵。'};}
export function siegeSceneView(w:World,s:Siege|undefined,e?:SiegeSceneEvent):CombatSceneView{const state=s??e?.after,war=activeWars(w).find(v=>v.id===state?.war),armies=s&&war?(w.realm?.armies??[]).filter(a=>a.location===s.site&&!a.journey&&!a.withdrawalUntil&&a.troops>=100&&warArmySide(w,war,a)!==null):[],besiegers=armies.filter(a=>warArmySide(w,war!,a)===s?.side),defenders=armies.filter(a=>warArmySide(w,war!,a)!==s?.side),stalled=!!s&&(!besiegers.length||besiegers.every(a=>a.supply<=0)),blocked=(state?.blockade??0)<100,assault=!!e&&(e.kind==='assaultWon'||e.kind==='assaultLost'),recent=!!e&&e.day===w.day,phase=assault?'本次强攻回放':!s?'围城已结束':defenders.length?'城下野战，围城暂缓':stalled?'围城停滞':s.playerDecision?'等待守城裁定':blocked?'扎营封锁':recent&&(e.kind==='works'||e.kind==='breach')?'工事推进':'围困待命';return {controller:s?w.realm?.cities[s.site]?.controller:e?.after.controller,besiegingSide:state?.side,site:state?.site,kind:'siege',phase,groups:formationGroups(w,assault?e!.after.armies:armies.map(a=>combatArmySnapshot(w,a,warArmySide(w,war!,a)!)),assault?e!.before.armies:undefined),active:!!s&&!defenders.length&&!stalled&&(!blocked&&recent&&(e?.kind==='works'||e?.kind==='breach')),fort:s?w.realm?.cities[s.site]?.fortification?.level??0:e?.after.fort??0,breach:state?.breach??0,blockade:state?.blockade??0,gateOpen:e?.kind==='assaultWon'||e?.kind==='surrender',assault,round:s?.round??0,eventId:e?.id,note:'围城进展不是城墙生命值；无实际驻军时仅呈现城防抵抗。'};}
/** A visual action cannot inflict damage. Retreat requires an actual recorded withdrawal. */
export function formationAction(view:CombatSceneView,g:FormationGroup,seconds=0){if(g.withdrawn)return 'retreat';if(view.assault)return seconds<3.5?'battle':!view.gateOpen&&seconds<6?'retreat':'garrison';if(!view.active)return 'garrison';if(view.kind==='siege')return g.kind==='siege'?'siege':'garrison';if(view.phase===combatPhaseNames.skirmish)return g.kind==='archer'?'battle':'garrison';return g.kind==='siege'?'garrison':'battle';}

/** Shared phase and contact decisions for the campaign actor layer. */
export function armyCombatVisual(w:World,a:Army,kind:TroopKind|'foot'){
 let state=armyVisualState(w,a);const battle=armyBattle(w,a),recorded=w.militaryAftermath?.battles.some(b=>b.ended===undefined&&b.last===w.day&&(b.attackers?.includes(a.id!)||b.defenders?.includes(a.id!)));
 if(state==='battle'&&!battle&&(a.journey||recorded))state=a.journey?'marching':'garrison';
 if(state==='battle'&&battle?.stage==='skirmish'&&kind!=='archer')state='garrison';
 if(state==='siege'){const siege=w.realm?.sieges?.find(s=>s.site===a.location),event=w.militaryAftermath?.siegeEvents?.filter(e=>e.after.site===a.location&&e.after.war===siege?.war&&e.after.side===siege?.side).at(-1);state=a.supply>0&&siege&&(siege.blockade??0)>=100&&event?.day===w.day&&(event.kind==='works'||event.kind==='breach')&&kind==='siege'?'siege':'garrison';}
 return {state,battle,side:battle?.attackers?.includes(a.id!)?'attack' as const:'defend' as const,besieging:!!w.realm?.sieges?.some(s=>s.site===a.location)};
}
/** Display representatives, never individual soldiers. Unknown forces have a constant budget. */
/** At most 96 skeletons, even when each side has known troops plus concealed allies. */
export function formationCapacity(kind:FormationGroup['kind']){return kind==='unknown'?12:kind==='siege'?1:kind==='lightHorse'||kind==='heavyHorse'?4:9;}
export function formationRepresentatives(g:FormationGroup){if(g.troops===null)return formationCapacity('unknown');if(!g.troops)return 0;return Math.min(formationCapacity(g.kind),Math.max(1,Math.ceil(g.troops/60)));}
/** Public status can stay in battle while a specific front rank is standing by. */
export function armyDisplayState(w:World,a:Army){const v=armyCombatVisual(w,a,'foot');return v.battle?'battle' as const:v.state;}
