import type {World} from './types';
import type {Army,RealmId,Siege} from './realm';
import type {TroopKind} from './armyOrganization';
import type {BattleRecord} from './militaryAftermath';
import {ensureAftermath} from './militaryAftermath';
import {armyCommander} from './mobility';
import {fortificationLevel} from './realm';
import {siteById} from '../data/scenario';
import {getPerson} from './personRegistry';
import {worldRealms} from './polityRuntime';
export type CombatSide='attack'|'defend';
/** Historical metadata only. These copies never supply or consume troops. */
export interface CombatArmySnapshot {army:number;realm:RealmId;side:CombatSide;commander:string|null;location:string;troops:number;morale:number;withdrawn:boolean;regiments:{id:string;kind:TroopKind;troops:number;experience:number}[]}
export interface BattleRoundSnapshot {day:number;round:number;stage:BattleRecord['stage'];before:CombatArmySnapshot[];after:CombatArmySnapshot[];lossA:number;lossB:number}
export interface CombatContact {key:string;lon:number;lat:number}
export type SiegeEventKind='works'|'breach'|'stalled'|'hold'|'assaultWon'|'assaultLost'|'surrender'|'withdrawal';
export interface SiegeSceneSnapshot {war:number;site:string;side:CombatSide;progress:number;blockade:number;breach:number;fort:number;controller:RealmId|'frontier';armies:CombatArmySnapshot[]}
export interface SiegeSceneEvent {id:number;day:number;kind:SiegeEventKind;before:SiegeSceneSnapshot;after:SiegeSceneSnapshot;loss:number}
export function combatArmySnapshot(w:World,a:Army,side:CombatSide):CombatArmySnapshot{return {army:a.id!,realm:a.realm,side,commander:armyCommander(w,a)??null,location:a.location,troops:a.troops,morale:a.morale,withdrawn:!!a.withdrawalUntil||a.troops<100,regiments:(a.regiments??[]).map(u=>({id:u.id,kind:u.kind,troops:u.troops,experience:u.experience}))};}
export function battleRoundArmies(w:World,attack:Army[],defend:Army[]){return [...attack.map(a=>combatArmySnapshot(w,a,'attack')),...defend.map(a=>combatArmySnapshot(w,a,'defend'))];}
export function saveBattleRound(w:World,b:BattleRecord,before:CombatArmySnapshot[],attack:Army[],defend:Army[],lossA:number,lossB:number){if(b.rounds?.some(r=>r.day===w.day))return;b.rounds=[...(b.rounds??[]),{day:w.day,round:b.round,stage:b.stage,before,after:battleRoundArmies(w,attack,defend),lossA,lossB}].slice(-24);const archives=ensureAftermath(w).battles.filter(v=>v!==b&&v.ended!==undefined&&v.rounds).sort((a,c)=>c.last-a.last);for(const old of archives.slice(64))delete old.rounds;}
export function siegeSceneSnapshot(w:World,s:Siege,armies:Army[]):SiegeSceneSnapshot{return {war:s.war,site:s.site,side:s.side,progress:s.progress,blockade:s.blockade??0,breach:s.breach??0,fort:fortificationLevel(w,s.site),controller:w.realm!.cities[s.site].controller,armies:armies.map(a=>combatArmySnapshot(w,a,s.side))};}
export function saveSiegeEvent(w:World,kind:SiegeEventKind,before:SiegeSceneSnapshot,after:SiegeSceneSnapshot,loss=0){const s=ensureAftermath(w);s.nextSceneEventId??=1;s.siegeEvents=[...(s.siegeEvents??[]),{id:s.nextSceneEventId++,day:w.day,kind,before,after,loss}].slice(-64);}
export function validCombatSnapshots(w:World,b:BattleRecord){const int=(v:unknown,max=1e9)=>Number.isSafeInteger(v)&&Number(v)>=0&&Number(v)<=max;return (b.contact===undefined||!!b.contact&&typeof b.contact.key==='string'&&b.contact.key.length<160&&Number.isFinite(b.contact.lon)&&Math.abs(b.contact.lon)<=180&&Number.isFinite(b.contact.lat)&&Math.abs(b.contact.lat)<=90)&&(b.rounds===undefined||Array.isArray(b.rounds)&&b.rounds.length<=24&&b.rounds.every((r,i)=>r&&int(r.day,w.day)&&int(r.round,b.round)&&r.round>0&&(!i||r.day>b.rounds![i-1].day)&&['skirmish','clash','pursuit'].includes(r.stage)&&int(r.lossA)&&int(r.lossB)&&validCombatArmies(w,r.before)&&validCombatArmies(w,r.after)&&r.before.length===r.after.length&&r.after.every(a=>r.before.some(b=>b.army===a.army&&b.realm===a.realm&&b.side===a.side&&b.troops>=a.troops))&&r.before.reduce((n,a)=>n+a.troops,0)-r.after.reduce((n,a)=>n+a.troops,0)===r.lossA+r.lossB));}
export function validCombatArmies(w:World,rows:CombatArmySnapshot[]){const int=(v:unknown,max=1e9)=>Number.isSafeInteger(v)&&Number(v)>=0&&Number(v)<=max;return Array.isArray(rows)&&rows.length<=96&&new Set(rows.map(a=>a?.army)).size===rows.length&&rows.every(a=>a&&int(a.army)&&worldRealms(w).includes(a.realm)&&['attack','defend'].includes(a.side)&&!!siteById[a.location]&&(a.commander===null||typeof a.commander==='string'&&!!getPerson(w,a.commander))&&int(a.troops,6000)&&int(a.morale,100)&&typeof a.withdrawn==='boolean'&&Array.isArray(a.regiments)&&a.regiments.length<=120&&new Set(a.regiments.map(u=>u?.id)).size===a.regiments.length&&a.regiments.every(u=>u&&typeof u.id==='string'&&['shield','spear','archer','lightHorse','heavyHorse','siege'].includes(u.kind)&&int(u.troops,6000)&&int(u.experience,100))&&(!a.regiments.length||a.regiments.reduce((n,u)=>n+u.troops,0)===a.troops));}
export function validSiegeEvents(w:World){const s=w.militaryAftermath;if(!s)return true;const int=(v:unknown,max=1e9)=>Number.isSafeInteger(v)&&Number(v)>=0&&Number(v)<=max;const scene=(v:SiegeSceneSnapshot)=>!!v&&int(v.war)&&!!siteById[v.site]&&['attack','defend'].includes(v.side)&&int(v.progress,100)&&int(v.blockade,100)&&int(v.breach,3)&&int(v.fort,3)&&(v.controller==='frontier'||worldRealms(w).includes(v.controller))&&validCombatArmies(w,v.armies);return (s.nextSceneEventId===undefined||int(s.nextSceneEventId))&&(s.siegeEvents===undefined||Array.isArray(s.siegeEvents)&&s.siegeEvents.length<=64&&s.siegeEvents.every((e,i)=>e&&int(e.id)&&e.id>0&&e.id<(s.nextSceneEventId??0)&&(!i||e.id>s.siegeEvents![i-1].id)&&int(e.day,w.day)&&['works','breach','stalled','hold','assaultWon','assaultLost','surrender','withdrawal'].includes(e.kind)&&scene(e.before)&&scene(e.after)&&e.before.war===e.after.war&&e.before.site===e.after.site&&e.before.side===e.after.side&&int(e.loss)));}
