import {describe,it,expect} from 'vitest';
import {newCampaignWorld,act} from './world';
import {declareRealmWar,advanceRealm,type Army} from './realm';
import {awardInfluence} from './personalInfluence';
import {ensureArmyOrganization} from './armyOrganization';
import {battleSceneView,formationAction,siegeSceneView} from './combatPresentation';
import {ensureAftermath,validAftermath} from './militaryAftermath';
import {parseWorld,serializeWorld} from './save';
import {battleRoundArmies,saveBattleRound,validCombatSnapshots} from './combatSnapshots';
function setup(){const w=newCampaignWorld('xiao-yan',undefined,'sandbox');awardInfluence(w,'xiao-yan',500);const war=declareRealmWar(w,'xiao-yan','liang','luoyang');w.realm!.armies=[];return {w,war};}
function army(realm:Army['realm'],troops=1200):Army{return {realm,location:'luoyang',troops,morale:80,supply:1000,journey:null,siege:0,automation:'direct'};}
describe('combat scenes follow real settlements',()=>{
 it('records before and after an actual field round, serializes, and never changes rules when viewed',()=>{const {w,war}=setup();w.realm!.armies=[army('liang'),army('east')];ensureArmyOrganization(w);w.day=1;advanceRealm(w);const b=w.militaryAftermath!.battles.find(b=>b.war===war.id)!;expect(b.rounds).toHaveLength(1);const r=b.rounds![0];expect(r.before.reduce((n,a)=>n+a.troops,0)-r.after.reduce((n,a)=>n+a.troops,0)).toBe(r.lossA+r.lossB);const data=serializeWorld(w);const view=battleSceneView(w,b);expect(view.groups.some(g=>g.side==='attack'&&g.troops!==null)).toBe(true);expect(view.groups.filter(g=>g.side==='defend').map(g=>g.kind)).toEqual(['unknown']);expect(serializeWorld(w)).toBe(data);expect(parseWorld(data).militaryAftermath!.battles[0].rounds).toEqual(b.rounds);const count=b.rounds!.length;advanceRealm(w);expect(b.rounds).toHaveLength(count);});
 it('bounds history, rejects corrupt snapshots and keeps legacy archives empty',()=>{const {w}=setup();w.realm!.armies=[army('liang'),army('east')];ensureArmyOrganization(w);const b={id:1,key:'1',day:0,last:0,round:0,stage:'clash' as const,a:1,b:2,lossA:0,lossB:0};for(let day=1;day<30;day++){w.day=day;b.round=day;b.last=day;saveBattleRound(w,b,battleRoundArmies(w,[w.realm!.armies[0]],[w.realm!.armies[1]]),[w.realm!.armies[0]],[w.realm!.armies[1]],0,0);}expect((b as import('./militaryAftermath').BattleRecord).rounds).toHaveLength(24);expect(validCombatSnapshots(w,b)).toBe(true);const bad=structuredClone(b) as import('./militaryAftermath').BattleRecord;bad.rounds![0].after[0].regiments[0].troops++;expect(validCombatSnapshots(w,bad)).toBe(false);expect(battleSceneView(w,{...b,rounds:undefined}).groups).toEqual([]);});
 it.each([600,3000])('preserves a %i-person assault event after success or failure without double charging',troops=>{const {w,war}=setup();w.day=5;const a=army('liang',troops);a.morale=100;a.siege=5;w.realm!.armies=[a];ensureArmyOrganization(w);const city=w.realm!.cities.luoyang;city.population=10000;city.order=70;w.realm!.sieges=[{war:war.id!,site:'luoyang',side:'attack',progress:5,last:5}];act(w,{type:'militaryAction',army:a.id!,site:'luoyang',action:'assault'});const e=w.militaryAftermath!.siegeEvents!.at(-1)!;expect(e.kind).toBe(troops===3000?'assaultWon':'assaultLost');expect(e.before.armies[0].troops-e.after.armies[0].troops).toBe(e.loss);expect(validAftermath(w)).toBe(true);const state=serializeWorld(w);const scene=siegeSceneView(w,w.realm!.sieges?.[0],e);expect(scene.assault).toBe(true);expect(scene.gateOpen).toBe(troops===3000);for(let i=0;i<5;i++)siegeSceneView(w,w.realm!.sieges?.[0],e);expect(serializeWorld(w)).toBe(state);expect(parseWorld(state).militaryAftermath!.siegeEvents).toEqual([e]);expect(()=>act(w,{type:'militaryAction',army:a.id!,site:'luoyang',action:'assault'})).toThrow();expect(serializeWorld(w)).toBe(state);});
 it('does not turn pursuit into a fabricated rout and stops siege action without supplies',()=>{const {w,war}=setup();w.realm!.armies=[army('liang')];ensureArmyOrganization(w);const s={war:war.id!,site:'luoyang',side:'attack' as const,progress:60,blockade:100,last:0};w.realm!.armies[0].supply=0;const view=siegeSceneView(w,s);expect(view.phase).toBe('围城停滞');expect(view.active).toBe(false);const g=view.groups[0];expect(formationAction({...view,kind:'battle',phase:'追击阶段',active:true},g)).toBe('battle');expect(formationAction({...view,kind:'battle',active:true},{...g,withdrawn:true})).toBe('retreat');});
});
it('shrinks known representative formations with real casualties while unknown silhouettes stay fixed',async()=>{const {formationRepresentatives}=await import('./combatPresentation');const g={realm:'liang' as const,key:'attack:shield',side:'attack' as const,kind:'shield' as const,name:'刀盾兵',troops:600,loss:0,morale:80,withdrawn:false,armies:[1],experience:30};expect(formationRepresentatives(g)).toBe(9);expect(formationRepresentatives({...g,troops:390})).toBe(7);expect(formationRepresentatives({...g,troops:0})).toBe(0);expect(formationRepresentatives({...g,kind:'unknown',troops:null})).toBe(12);});
it('shows actual defending armies and pauses siege work when a field force is still present',()=>{const {w,war}=setup();w.realm!.armies=[army('liang'),army('east')];ensureArmyOrganization(w);const view=siegeSceneView(w,{war:war.id!,site:'luoyang',side:'attack',progress:20,blockade:100,last:0});expect(view.phase).toBe('城下野战，围城暂缓');expect(view.active).toBe(false);expect(view.groups.find(g=>g.side==='defend')?.kind).toBe('unknown');});
it('bounds completed formation history without deleting final battle summaries',()=>{const {w}=setup();w.realm!.armies=[army('liang'),army('east')];ensureArmyOrganization(w);w.day=100;const row=battleRoundArmies(w,[w.realm!.armies[0]],[w.realm!.armies[1]]),base={key:'history',day:1,last:1,round:1,stage:'clash' as const,a:1,b:2,lossA:0,lossB:0,ended:1,winner:'draw' as const,rounds:[{day:1,round:1,stage:'clash' as const,before:row,after:row,lossA:0,lossB:0}]};const active={...base,day:100,last:100,ended:undefined,rounds:undefined};ensureAftermath(w).battles=[...Array.from({length:70},(_,i)=>({...structuredClone(base),id:i+1,last:i+1})),active];saveBattleRound(w,active,row,[w.realm!.armies[0]],[w.realm!.armies[1]],0,0);expect(w.militaryAftermath!.battles.filter(b=>b.ended!==undefined&&b.rounds)).toHaveLength(64);expect(w.militaryAftermath!.battles).toHaveLength(71);expect(w.militaryAftermath!.battles[0].winner).toBe('draw');});
it('stops depicting an army as engaged immediately after a real retreat command',async()=>{const {armyCombatVisual}=await import('./combatPresentation');const {w}=setup();w.realm!.armies=[{...army('liang'),location:'jiankang'},{...army('east'),location:'jiankang'}];ensureArmyOrganization(w);w.day=1;advanceRealm(w);const b=w.militaryAftermath!.battles[0];act(w,{type:'militaryAction',army:w.realm!.armies[0].id!,site:'jingkou',action:'retreat'});expect(battleSceneView(w,b).groups.find(g=>g.side==='attack')?.withdrawn).toBe(true);expect(battleSceneView(w,b).active).toBe(false);expect(armyCombatVisual(w,w.realm!.armies[1],'archer').state).toBe('garrison');expect(parseWorld(serializeWorld(w)).militaryAftermath!.battles[0]).toEqual(b);});

it('bounds the complete mixed and concealed two-sided formation to 96 skeletons',async()=>{const {formationCapacity}=await import('./combatPresentation');const kinds=['shield','spear','archer','lightHorse','heavyHorse','siege','unknown'] as const;expect(kinds.reduce((sum,kind)=>sum+formationCapacity(kind),0)*2).toBeLessThanOrEqual(96);});
