import {worldRealms} from './polityRuntime';
import type {World,Journey} from './types';
import type {RealmId} from './realm';
import {siteById} from '../data/scenario';
import {economyHost} from './personalEconomyAdapter';
import {personResidence} from './residence';
import {isAlive} from './lifeState';
import {civilianFood,grainCapacity} from './population';
import {fiscalPath,publicBalance,ensureFiscal,fiscalRecord} from './treasury';
import {canEnter} from './diplomacy';
import {planRoute} from './world';
import {loadRoad} from './roadCapacity';
import {allegianceRealm} from './officeEligibility';
export interface TradeStock {enterprise:number;grain:number;tools:number;production:{work:number;last:number}|null}
export interface TradeContract {id:number;enterprise:number;from:string;to:string;realm:RealmId;buyer:RealmId;goods:'grain'|'tools';sent:number;remaining:number;arrived:number;lost:number;price:number;escrow:number;paid:number;refund:number;status:'moving'|'done'|'cancelled';journey:Journey;loaded:number;last:number;deadline:number;guard:boolean;location:string}
export interface Commerce {nextId:number;stocks:TradeStock[];contracts:TradeContract[];lastDay:number}
export type CommerceCommand={type:'commerce';action:'buy'|'produce';enterprise:number}|{type:'commerce';action:'deliver';enterprise:number;goods:'grain'|'tools';to:string;guard:boolean}|{type:'commerce';action:'cancel';id:number};
export function tradeStock(w:World,id:number){return w.commerce?.stocks.find(s=>s.enterprise===id);}
export function tradePrice(w:World,to:string,goods:'grain'|'tools'){return goods==='tools'?4:w.realm!.cities[to].grain<civilianFood(w,to)?3:2;}
export function commerceReason(w:World,c:CommerceCommand){if(!w.realm||!w.characterId)return '当前无法经营';const id=c.action==='cancel'?w.commerce?.contracts.find(t=>t.id===c.id)?.enterprise:c.enterprise,e=w.enterprises?.items.find(e=>e.id===id);if(!e||e.closed||e.owner!==w.characterId||!isAlive(w,e.owner))return '不是你经营的事业';const stock=tradeStock(w,e.id),host=economyHost(w),r=allegianceRealm(w,e.owner);if(!r)return '没有合法通行身份';
 if(c.action==='cancel'){const t=w.commerce?.contracts.find(t=>t.id===c.id);return !t||t.status!=='moving'?'合同已结束':'';}
 const at=personResidence(w,e.owner);if(at.traveling||at.site!==e.site)return '须亲赴事业所在地安排';if(!host.actor(e.owner)?.available)return '请先交接当前公务';if(w.realm.cities[e.site].controller!==r)return '事业所在地已经失守';
 if(c.action==='produce')return e.kind!=='workshop'?'只有作坊能够制作农具':e.order||stock?.production?'正在办理其他生产':e.capital<20?'需要事业资本 20':(stock?.tools??0)>990?'农具仓储容量不足':'';
 if(c.action==='buy'){const city=w.realm.cities[e.site],key=fiscalPath(w,e.site)[0];return e.capital<50?'需要事业资本 50':city.grain-civilianFood(w,e.site)*2<50?'出售后须保留两期民食':publicBalance(w,key)>999950?'卖方公库容量不足':(stock?.grain??0)>950?'粮货仓储容量不足':host.managedAccounts(e.owner).some(a=>a.id===key)||host.auditableAccounts(e.owner).some(a=>a.id===key)?'不得经营由自己审批或监察的买卖':'';}
 if(c.action!=='deliver'||!['grain','tools'].includes(c.goods)||typeof c.guard!=='boolean')return '无效商业合同';const city=w.realm.cities[c.to];if(!city||city.controller==='frontier'||city.controller!==city.owner||c.to===e.site)return '请选择另一处安定城市';const key=fiscalPath(w,c.to)[0],units=c.goods==='grain'?50:10,price=units*tradePrice(w,c.to,c.goods);
 return (stock?.[c.goods]??0)<units?'货物库存不足':e.capital<(c.guard?20:5)?'资本不足运费与护卫费用':w.commerce?.contracts.some(t=>t.to===c.to&&t.goods===c.goods&&t.status==='moving')?'该城已签订同类收货合同':host.managedAccounts(e.owner).some(a=>a.id===key)||host.auditableAccounts(e.owner).some(a=>a.id===key)?'不得向自己审批或监察的公库售货':publicBalance(w,key)<price?'买方公库不足预付货款':c.goods==='grain'&&city.grain>=civilianFood(w,c.to)*2?'买方粮食储备已满足':c.goods==='tools'&&city.prosperity>=85?'买方农具修缮需求已满足':!planRoute(e.site,c.to,site=>canEnter(w,r,w.realm!.cities[site].controller,e.owner))?'没有合法商路':'';
}
export function actCommerce(w:World,c:CommerceCommand){const why=commerceReason(w,c);if(why)throw new Error(why);const s=w.commerce??={nextId:1,stocks:[],contracts:[],lastDay:Math.max(0,w.day-1)};
 if(c.action==='cancel'){const t=s.contracts.find(t=>t.id===c.id)!;t.status='cancelled';t.loaded=0;return;}
 const e=w.enterprises!.items.find(e=>e.id===c.enterprise)!;let stock=tradeStock(w,e.id);if(!stock){stock={enterprise:e.id,grain:0,tools:0,production:null};s.stocks.push(stock);}
 if(c.action==='produce'){e.capital-=20;e.spent+=20;stock.production={work:0,last:w.day};return;}
 if(c.action==='buy'){e.capital-=50;e.spent+=50;w.realm!.cities[e.site].grain-=50;const key=fiscalPath(w,e.site)[0];ensureFiscal(w)!.balances[key]=publicBalance(w,key)+50;fiscalRecord(w,w.realm!.cities[e.site].controller as RealmId,'enterprise:'+e.id,key,50,'私人事业购入余粮');stock.grain+=50;return;}
 if(c.action!=='deliver')throw new Error('无效商旅命令');
 const units=c.goods==='grain'?50:10,r=allegianceRealm(w,e.owner)!,route=planRoute(e.site,c.to,site=>canEnter(w,r,w.realm!.cities[site].controller,e.owner))!,price=tradePrice(w,c.to,c.goods),key=fiscalPath(w,c.to)[0],id=s.nextId++;stock[c.goods]-=units;e.capital-=c.guard?20:5;e.spent+=c.guard?20:5;ensureFiscal(w)!.balances[key]=publicBalance(w,key)-price*units;fiscalRecord(w,w.realm!.cities[c.to].owner as RealmId,key,'trade:'+id,price*units,'收货合同预付款');s.contracts.push({id,enterprise:e.id,from:e.site,to:c.to,realm:r,buyer:w.realm!.cities[c.to].owner as RealmId,goods:c.goods,sent:units,remaining:units,arrived:0,lost:0,price,escrow:price*units,paid:0,refund:0,status:'moving',journey:{route:route.route,durations:route.durations,leg:0,elapsed:0,started:w.day},loaded:0,last:w.day,deadline:w.day+route.days+120,guard:c.guard,location:e.site});
}
export function advanceCommerce(w:World){const s=w.commerce;if(!s||!w.realm||s.lastDay>=w.day)return;s.lastDay=w.day;
 for(const stock of s.stocks){const e=w.enterprises?.items.find(e=>e.id===stock.enterprise),p=stock.production;if(!p||!e||p.last>=w.day)continue;p.last=w.day;const at=personResidence(w,e.owner);if(e.closed||!isAlive(w,e.owner)){stock.production=null;continue;}if(at.traveling||at.site!==e.site||!economyHost(w).actor(e.owner)?.available||e.order)continue;p.work++;if(p.work>=20){stock.tools+=10;stock.production=null;}}
 for(const t of s.contracts){const e=w.enterprises?.items.find(e=>e.id===t.enterprise);if(!e)continue;t.realm=allegianceRealm(w,e.owner)??t.realm;
 if(t.status==='moving'&&(w.day>t.deadline||w.realm.cities[t.to].controller!==t.buyer||w.realm.cities[t.to].owner!==t.buyer)){t.status='cancelled';t.loaded=0;}
 if(t.status==='moving'&&t.last<w.day){t.last=w.day;const j=t.journey,next=j.route[j.leg+1];if(next&&canEnter(w,t.realm,w.realm.cities[next].controller,e.owner)){t.loaded+=loadRoad(w,t.location,next,t.remaining-t.loaded);if(t.loaded>=t.remaining){j.elapsed++;if(j.elapsed>=j.durations[j.leg]){t.location=j.route[++j.leg];j.elapsed=0;t.loaded=0;if(j.leg<j.durations.length){const loss=Math.min(t.remaining,Math.floor(t.remaining*(t.guard?.01:.06)));t.remaining-=loss;t.lost+=loss;}}}}
 if(t.location===t.to){const city=w.realm.cities[t.to],units=t.goods==='grain'?Math.min(t.remaining,grainCapacity(w,t.to)-city.grain):t.remaining,paid=Math.min(Math.max(0,units)*t.price,1_000_000-e.capital);const delivered=Math.floor(paid/t.price);if(delivered){if(t.goods==='grain')city.grain+=delivered;else city.prosperity=Math.min(100,city.prosperity+delivered);t.remaining-=delivered;t.arrived+=delivered;t.escrow-=delivered*t.price;t.paid+=delivered*t.price;e.capital+=delivered*t.price;e.earned+=delivered*t.price;fiscalRecord(w,t.buyer,'trade:'+t.id,'enterprise:'+e.id,delivered*t.price,'商旅按实收货结算');}if(!t.remaining)t.status='done';}
 }
 if(t.status!=='moving'){const key=t.buyer+'|city:'+t.to,n=Math.min(t.escrow,1_000_000-publicBalance(w,key));ensureFiscal(w)!.balances[key]=publicBalance(w,key)+n;t.escrow-=n;t.refund+=n;fiscalRecord(w,t.buyer,'trade:'+t.id,key,n,'退还未交货价款');if(t.remaining){const city=w.realm.cities[t.location];if(t.goods==='grain')city.grain+=Math.min(t.remaining,Math.max(0,grainCapacity(w,t.location)-city.grain));t.lost+=t.remaining;t.remaining=0;}}
 }
}
export function validCommerce(w:World){const s=w.commerce;if(s===undefined)return true;const n=(x:unknown,max=1e9)=>Number.isSafeInteger(x)&&Number(x)>=0&&Number(x)<=max,exists=(id:number)=>w.enterprises?.items.some(e=>e.id===id);return !!s&&n(s.nextId)&&n(s.lastDay,w.day)&&Array.isArray(s.stocks)&&s.stocks.length<=256&&new Set(s.stocks.map(t=>t.enterprise)).size===s.stocks.length&&s.stocks.every(t=>t&&exists(t.enterprise)&&n(t.grain,1000)&&n(t.tools,1000)&&(t.production===null||t.production&&n(t.production.work,19)&&n(t.production.last,w.day)))&&Array.isArray(s.contracts)&&s.contracts.length<=10000&&new Set(s.contracts.map(t=>t.id)).size===s.contracts.length&&s.contracts.every(t=>t&&n(t.id,s.nextId-1)&&exists(t.enterprise)&&worldRealms(w).includes(t.realm)&&worldRealms(w).includes(t.buyer)&&[t.from,t.to,t.location].every(id=>!!siteById[id])&&['grain','tools'].includes(t.goods)&&['moving','done','cancelled'].includes(t.status)&&typeof t.guard==='boolean'&&n(t.last,w.day)&&n(t.deadline)&&[t.sent,t.remaining,t.arrived,t.lost,t.price,t.escrow,t.paid,t.refund,t.loaded].every(v=>n(v))&&t.sent===(t.goods==='grain'?50:10)&&[2,3,4].includes(t.price)&&t.remaining+t.arrived+t.lost===t.sent&&t.escrow+t.paid+t.refund===t.sent*t.price&&t.loaded<=t.remaining&&!!t.journey&&t.journey.route.every(id=>!!siteById[id])&&t.journey.durations.length===t.journey.route.length-1&&n(t.journey.leg,t.journey.durations.length)&&n(t.journey.elapsed)&&t.journey.route[t.journey.leg]===t.location&&t.journey.durations.every(d=>n(d)&&d>0));}
