import { describe,it,expect } from 'vitest';
import { newCampaignWorld,act,advance,planRoute } from './world';
import { parseWorld,serializeWorld } from './save';
import { diplomaticPair,diplomaticQuote,canEnter,personalRoute,warState,treaty,advanceDiplomacy,syncDiplomacy,arriveDiplomacy,type DiplomacyAction } from './diplomacy';
import { governmentOf } from './government';
import { realmReason,type RealmId } from './realm';
import { roads } from '../data/scenario';
import type { World } from './types';
const start=(id='gao-huan')=>{const w=newCampaignWorld(id,undefined,'sandbox');w.realm!.influence=900;for(const t of Object.values(w.realm!.treasuries)){t.coins=10000;t.grain=10000;}w.people[0].food=10000;return w;};
const dip=(w:World,action:DiplomacyAction,target:RealmId='west')=>act(w,{type:'diplomacy',action,target});
function pass(w:World,n:number){for(let i=0;i<n;i++){if(w.realm!.event)act(w,{type:'realm',action:'event',choice:'decline'});advance(w);}if(w.realm!.event)act(w,{type:'realm',action:'event',choice:'decline'});}
function receive(w:World){const due=Math.max(...w.diplomacy!.missions.map(m=>m.due));pass(w,due-w.day);}
const save=(w:World)=>expect(parseWorld(serializeWorld(w))).toEqual(w);
function friendly(w:World,a:RealmId='east',b:RealmId='west'){diplomaticPair(w,a,b)!.opinion=90;}
const border=(w:World,a:RealmId,b:RealmId)=>{const e=roads.find(e=>w.realm!.cities[e.from].owner===a&&w.realm!.cities[e.to].owner===b||w.realm!.cities[e.to].owner===a&&w.realm!.cities[e.from].owner===b)!;return w.realm!.cities[e.from].owner===b?e.from:e.to;};
describe('国家外交与边境',()=>{
 it('高欢不能以普通旅行进入长安，拒绝时不扣粮且保持原世界',()=>{const w=start(),old=structuredClone(w);expect(planRoute(w.people[0].location,'changan')).not.toBeNull();expect(personalRoute(w,'changan')).toBeNull();expect(()=>act(w,{type:'travel',destination:'changan'})).toThrow('通行');expect(w).toEqual(old);save(w);});
 it('敌对、和平、停战独立；私交不授予国家通行',()=>{const w=start();w.social!.opinions['gao-huan|yuwen-tai']=100;expect(warState(w,'east','west')).toBe('和平');expect(diplomaticPair(w,'east','west')!.opinion).toBe(-70);w.realm!.truces['east|west']=180;expect(warState(w,'east','west')).toBe('停战期');expect(canEnter(w,'east','west','gao-huan')).toBe(false);save(w);});
 it('使团有成本、路程、冷却和到达答复；低接受度不会伪造许可',()=>{const w=start(),before=w.realm!.treasuries.east.coins;dip(w,'safe');expect(w.realm!.treasuries.east.coins).toBe(before-60);expect(w.diplomacy!.missions[0].due).toBeGreaterThan(w.day);expect(()=>dip(w,'safe')).toThrow();save(w);receive(w);expect(treaty(w,'east','west','safe','gao-huan')).toBeUndefined();expect(w.diplomacy!.history.at(-1)!.text).toContain('拒绝');save(w);});
 it('外交修好可推进国家关系；读档途中与连续推进相同',()=>{const w=start();dip(w,'improve');pass(w,3);const clone=parseWorld(serializeWorld(w));const days=w.diplomacy!.missions[0].due-w.day;pass(w,days);pass(clone,days);expect(w).toEqual(clone);expect(diplomaticPair(w,'east','west')!.opinion).toBe(-45);save(w);});
 it('安全通行允许实际出行，民事通行与军队借道不能替代它',()=>{const w=start();friendly(w);dip(w,'transit');receive(w);expect(canEnter(w,'east','west','gao-huan')).toBe(false);expect(canEnter(w,'east','west','gao-yang')).toBe(true);dip(w,'safe');receive(w);expect(canEnter(w,'east','west','gao-huan')).toBe(true);expect(canEnter(w,'east','west',undefined,true)).toBe(false);expect(canEnter(w,'east','west','gao-cheng')).toBe(false);act(w,{type:'travel',destination:'changan'});expect(w.people[0].journey).not.toBeNull();pass(w,2);save(w);});
 it('高澄代表国家取得的安全通行绑定高澄而非高欢',()=>{const w=start('gao-cheng');friendly(w);dip(w,'safe');receive(w);expect(treaty(w,'east','west','safe','gao-cheng')).toBeDefined();expect(canEnter(w,'east','west','gao-huan')).toBe(false);save(w);});
 it('不能在多个未授权国家之间借道，路线必须全程许可',()=>{const w=start();friendly(w);dip(w,'safe');receive(w);for(const id of personalRoute(w,'changan')!.route.slice(1))expect(canEnter(w,'east',w.realm!.cities[id].controller,'gao-huan')).toBe(true);expect(canEnter(w,'east','liang','gao-huan')).toBe(false);});
 it('撤约后途中逐段复核、退还未用行粮，读档状态合法',()=>{const w=start();friendly(w);dip(w,'safe');receive(w);const target=border(w,'east','west'),edge=roads.find(e=>[e.from,e.to].includes(target)&&w.realm!.cities[e.from===target?e.to:e.from].controller==='east')!;w.people[0].location=edge.from===target?edge.to:edge.from;act(w,{type:'travel',destination:target});const after=w.people[0].food;dip(w,'revoke');advance(w);expect(w.people[0].journey).toBeNull();expect(w.people[0].food).toBeGreaterThan(after);expect(w.realm!.cities[w.people[0].location].controller).toBe('east');save(w);});
 it('互不侵犯与同盟阻止宣战，毁约损害信用，交战立即撤销通行',()=>{const w=start();friendly(w);dip(w,'pact');receive(w);const site=border(w,'east','west');expect(realmReason(w,{type:'realm',action:'war',site})).toContain('终止');const credit=w.diplomacy!.credit.east;dip(w,'revoke');expect(w.diplomacy!.credit.east).toBe(credit-20);act(w,{type:'realm',action:'war',site});expect(warState(w,'east','west')).toBe('交战');expect(canEnter(w,'east','west','gao-huan')).toBe(false);expect(canEnter(w,'east','west',undefined,true)).toBe(true);pass(w,30);act(w,{type:'realm',action:'peace'});expect(warState(w,'east','west')).toBe('停战期');save(w);});
 it('名义君主与仅有军务授权者不能代表国家缔约或宣战',()=>{const w=start('yuan-shanjian');expect(diplomaticQuote(w,{type:'diplomacy',action:'improve',target:'west'}).reason).toContain('执政');w.realm!.mandate=true;expect(realmReason(w,{type:'realm',action:'war',site:border(w,'east','west')})).toContain('执政');});
 it('称臣有朝贡与外交约束；独立恢复权限并损害信用',()=>{const w=start();friendly(w);dip(w,'submit');receive(w);expect(w.diplomacy!.subjects.east).toBe('west');expect(diplomaticQuote(w,{type:'diplomacy',action:'alliance',target:'liang'}).reason).toContain('臣属');const before=w.realm!.treasuries.west.coins;w.day=Math.ceil((w.day+1)/30)*30;if(w.economy)w.economy.lastDay=w.day;advanceDiplomacy(w);expect(w.realm!.treasuries.west.coins).toBe(before+20);dip(w,'independence');expect(w.diplomacy!.subjects.east).toBeUndefined();save(w);});
 it('同盟军援实际转移国库钱粮，不凭空生成资源',()=>{const w=start();friendly(w,'east','liang');dip(w,'alliance','liang');receive(w);act(w,{type:'realm',action:'war',site:border(w,'east','west')});dip(w,'aid','liang');const m=w.diplomacy!.missions.find(m=>m.action==='aid')!;pass(w,m.due-w.day-1);w.day++;const a=w.realm!.treasuries.east.coins,b=w.realm!.treasuries.liang.coins;advanceDiplomacy(w);expect(w.realm!.treasuries.east.coins).toBe(a+120);expect(w.realm!.treasuries.liang.coins).toBe(b-120);expect(()=>dip(w,'aid','liang')).toThrow('冷却');});
 it('非玩家国家主动派使，可接纳或拒绝并留下往事',()=>{const w=start();pass(w,180);const m=w.diplomacy!.missions.find(m=>m.to==='east')!;expect(m).toBeDefined();pass(w,m.due-w.day);expect(m.status).toBe('audience');act(w,{type:'diplomacy',action:'accept',mission:m.id});expect(m.status).toBe('returning');expect(w.diplomacy!.history.at(-1)!.text).toContain('接受');pass(w,m.due-w.day);expect(w.diplomacy!.missions).not.toContain(m);save(w);});
 it('条约到期与国号更替会收回通行，历史记录保留',()=>{const w=start();friendly(w);dip(w,'safe');receive(w);const t=treaty(w,'east','west','safe','gao-huan')!;pass(w,t.until-w.day);expect(treaty(w,'east','west','safe','gao-huan')).toBeUndefined();dip(w,'safe');receive(w);governmentOf(w,'west')!.regimeId='test-regime';syncDiplomacy(w);expect(treaty(w,'east','west','safe','gao-huan')).toBeUndefined();expect(w.diplomacy!.history.at(-1)!.text).toContain('国号');});
 it('旧存档迁移不赠送通行，教学局保留原旅行体验',()=>{const w=start();delete w.diplomacy;const old=parseWorld(serializeWorld(w));expect(old.diplomacy).toBeDefined();expect(personalRoute(old,'changan')).toBeNull();const tutorial=newCampaignWorld();expect(tutorial.diplomacy).toBeUndefined();expect(personalRoute(tutorial,'changan')).not.toBeNull();});
 it('军队借道单独授权；第三方不能围城，撤约中断行军',()=>{const w=start();friendly(w);dip(w,'military');receive(w);expect(canEnter(w,'east','west',undefined,true)).toBe(true);expect(canEnter(w,'east','west','gao-huan')).toBe(false);act(w,{type:'realm',action:'muster'});act(w,{type:'realm',action:'march',site:'changan'});expect(w.realm!.armies[0].journey).not.toBeNull();const army=w.realm!.armies[0],j=army.journey!;const k=j.route.findIndex(id=>w.realm!.cities[id].controller==='west');army.location=j.route[k-1];army.journey=planRoute(army.location,'changan')?{route:planRoute(army.location,'changan')!.route,durations:planRoute(army.location,'changan')!.durations,leg:0,elapsed:0,started:w.day}:null;dip(w,'revoke');pass(w,1);expect(army.journey).toBeNull();expect(w.realm!.cities.changan.controller).toBe('west');save(w);});
 it('会盟必须本人抵达都城，收益只结算一次',()=>{const w=start();friendly(w);dip(w,'meeting');receive(w);const t=treaty(w,'east','west','safe','gao-huan')!;expect(t.meeting).toBe('invited');w.people[0].location='changan';diplomaticPair(w,'east','west')!.opinion=50;diplomaticPair(w,'east','west')!.opinionFactors={base:50,effects:{}};arriveDiplomacy(w);expect(t.meeting).toBe('held');expect(diplomaticPair(w,'east','west')!.opinion).toBe(65);arriveDiplomacy(w);expect(diplomaticPair(w,'east','west')!.opinion).toBe(65);save(w);});
 it('旧档在外国的人物可以请求限定返国，不能选择外国目的地',()=>{const w=start();w.people[0].location='changan';act(w,{type:'diplomacy',action:'repatriate'});const j=w.people[0].journey!;expect(w.realm!.cities[j.route.at(-1)!].controller).toBe('east');const copy=parseWorld(serializeWorld(w));pass(w,j.durations.reduce((n,d)=>n+d,0));pass(copy,j.durations.reduce((n,d)=>n+d,0));expect(w).toEqual(copy);expect(w.diplomacy!.returning).toBeNull();expect(w.realm!.cities[w.people[0].location].controller).toBe('east');save(w);});
 it('未答复来使到期返程；过期议案不能再次执行',()=>{const w=start();pass(w,180);const m=w.diplomacy!.missions.find(m=>m.to==='east')!;pass(w,m.expires-w.day);expect(m.status).toBe('returning');expect(()=>act(w,{type:'diplomacy',action:'accept',mission:m.id})).toThrow('不在');pass(w,m.due-w.day);expect(w.diplomacy!.missions.some(v=>v.id===m.id)).toBe(false);save(w);});
 it('使团发出后执政者变更，不继承旧发起人的议案',()=>{const w=start();friendly(w);dip(w,'safe');const old=w.diplomacy!.missions[0];act(w,{type:'relationship',action:'liberate',target:'yuan-shanjian'});receive(w);expect(w.diplomacy!.missions.some(m=>m.id===old.id)).toBe(false);expect(treaty(w,'east','west','safe','gao-huan')).toBeUndefined();save(w);});
 it.each(['opinion','cycle','mission','treaty','credit','basis'])('拒绝篡改的外交存档：%s',field=>{const w=start(),s=w.diplomacy!;if(field==='opinion')s.pairs['east|west'].opinion=101;if(field==='cycle'){s.subjects.east='west';s.subjects.west='east';}if(field==='mission'){dip(w,'safe');s.missions[0].actor='ghost';}if(field==='treaty')s.pairs['east|west'].treaties.push({kind:'safe',from:'east',to:'west',actor:'xiao-yan',since:0,until:240});if(field==='credit')s.credit.east=-1;if(field==='basis')s.bases.east='ghost';expect(()=>serializeWorld(w)).toThrow();});
});
