import {advanceArmyLogistics} from './armyLogistics';
import {politicalAction} from './politicalActions';
import {describe,it,expect} from 'vitest';
import {newCampaignWorld,act,advance} from './world';
import {cityYield,actRealm,realmReason} from './realm';
import {actPopulation,populationReason,populationQuote,advancePopulation} from './population';
import {serializeWorld,parseWorld} from './save';
import {governmentOf} from './government';
import {movementPowerParts,courtReason} from './court';
import {serviceNeed} from './serviceNeeds';
import {actService,serviceTask} from './assignments';
const start=()=>newCampaignWorld('xiao-yan',undefined,'sandbox');
describe('population-led governance',()=>{
 it('population increases output, geography matters, granaries do not create food',()=>{const w=start(),c=w.realm!.cities.guangzhou;c.population=3000;const first=cityYield(w,'guangzhou').grain;c.population=6000;expect(cityYield(w,'guangzhou').grain).toBeGreaterThan(first);w.holdings.cities.guangzhou={levels:{market:0,granary:3,hostel:0},project:null};const food=cityYield(w,'guangzhou').grain;w.holdings.cities.guangzhou.levels.granary=0;expect(cityYield(w,'guangzhou').grain).toBe(food);const mountain=Object.keys(w.realm!.cities).find(id=>cityYield(w,id).region.fertility<1)!;w.realm!.cities[mountain].population=6000;expect(cityYield(w,mountain).grain).toBeLessThan(food);});
 it('migration conserves population through transit, losses and one-time settlement',()=>{const w=start(),s=w.realm!,before=s.cities.jiankang.population+s.cities.jingkou.population;actPopulation(w,{type:'population',action:'transfer',from:'jiankang',to:'jingkou',kind:'assisted',amount:100});const t=s.population!.transfers[0];expect(s.cities.jiankang.population+s.cities.jingkou.population+t.sent).toBe(before);const restored=parseWorld(serializeWorld(w));for(let i=0;i<100&&t.status==='traveling';i++){w.day++;advancePopulation(w);restored.day++;advancePopulation(restored);}expect(t.status).toBe('arrived');expect(s.cities.jiankang.population+s.cities.jingkou.population+t.lost).toBe(before);expect(restored).toEqual(w);const n=s.cities.jingkou.population;advancePopulation(w);expect(s.cities.jingkou.population).toBe(n);});
 it('blocked routes pause and a return never refunds transport expenses',()=>{const w=start();actPopulation(w,{type:'population',action:'transfer',from:'jiankang',to:'jingkou',kind:'forced',amount:100});const t=w.realm!.population!.transfers[0],coins=w.realm!.treasuries.liang.coins;w.realm!.cities.jingkou.controller='east';w.day++;advancePopulation(w);expect(t.elapsed).toBe(0);actPopulation(w,{type:'population',action:'return',id:t.id});w.day++;advancePopulation(w);expect(t.status).toBe('returned');expect(w.realm!.treasuries.liang.coins).toBe(coins);expect(t.sent).toBe(t.arrived+t.lost);});
 it('rejects invented values and civilian raids without mutation',()=>{const w=start(),copy=structuredClone(w);expect(populationReason(w,{type:'population',action:'transfer',from:'jiankang',to:'jingkou',kind:'raid',amount:100})).toContain('占领');expect(()=>actPopulation(w,{type:'population',action:'transfer',from:'jiankang',to:'jingkou',kind:'assisted',amount:NaN})).toThrow();expect(w).toEqual(copy);});
 it('raids require war, occupation and soldiers and leave legal ownership intact',()=>{const w=start(),s=w.realm!;s.war={attacker:'liang',defender:'east',target:'guangling',started:0,score:50};s.cities.guangling.owner='east';s.cities.guangling.controller='liang';s.armies.push({realm:'liang',location:'guangling',troops:600,morale:80,supply:100,journey:null,siege:0});const c={type:'population',action:'transfer',from:'guangling',to:'jiankang',kind:'raid',amount:100} as const;expect(populationReason(w,c)).toBe('');const n=s.cities.guangling.population;actPopulation(w,c);expect(s.cities.guangling.population).toBe(n-100);expect(s.cities.guangling.owner).toBe('east');expect(governmentOf(w)!.legitimacy).toBeLessThan(65);});
 it('Chen Baxian can receive an appointment and must reach Guangzhou before taking office',()=>{const w=start();expect(realmReason(w,{type:'realm',action:'appoint',site:'guangzhou',candidate:'chen-baxian'})).toBe('');actRealm(w,{type:'realm',action:'appoint',site:'guangzhou',candidate:'chen-baxian'});expect(w.realm!.cities.guangzhou.governor).toBe('county-official-guangzhou');for(let i=0;i<240&&w.realm!.cities.guangzhou.governor!=='chen-baxian';i++){if(w.realm!.event)act(w,{type:'realm',action:'event',choice:'decline'});advance(w);}expect(w.realm!.cities.guangzhou.governor).toBe('chen-baxian');expect(w.mobility!.residences['chen-baxian'].site).toBe('guangzhou');expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('sovereigns cannot join factions; real local population increases an officer’s weight',()=>{const w=start();expect(courtReason(w,{type:'court',action:'join',group:'reform'})).toContain('君主');w.realm!.cities.guangzhou.governor='xiao-yi';const before=movementPowerParts(w,'liang','xiao-yi').find(p=>p.label==='地方人口与税基')!.value;w.realm!.cities.guangzhou.population+=20000;expect(movementPowerParts(w,'liang','xiao-yi').find(p=>p.label==='地方人口与税基')!.value).toBeGreaterThan(before);});
 it('recommendation urgency follows local shortages rather than a fixed task order',()=>{const w=start(),city=w.realm!.cities.guangzhou;const before=serviceNeed(w,'relief','guangzhou').score;city.order=20;expect(serviceNeed(w,'relief','guangzhou').score).toBeGreaterThan(before);expect(serviceNeed(w,'relief','guangzhou').tier).toBe('必须处理');});
 it('cancellation returns only unspent funds and cannot pay twice',()=>{const w=start();actService(w,{type:'service',action:'begin'});actService(w,{type:'service',action:'open',site:'jiankang',kind:'relief',officer:'xiao-gang'});const t=serviceTask(w,1)!;actService(w,{type:'service',action:'plan',id:1,plan:'balanced'},'xiao-gang');actService(w,{type:'service',action:'approve',id:1});actService(w,{type:'service',action:'start',id:1},'xiao-gang');t.progress=Math.floor(t.required/2);t.contributors['xiao-gang']={lead:t.progress,support:0};const before=w.realm!.treasuries.liang.coins;actService(w,{type:'service',action:'cancel',id:1});expect(w.realm!.treasuries.liang.coins).toBe(before+Math.floor(t.funds.coins/2));expect(()=>actService(w,{type:'service',action:'cancel',id:1})).toThrow();});
 it('new population fields reject corruption',()=>{const w=start();w.realm!.cities.jiankang.population=NaN;expect(()=>serializeWorld(w)).toThrow('存档');});
 it('old households migrate once without minting stored grain or money',()=>{const w=start();for(const c of Object.values(w.realm!.cities)){const old=c as unknown as Record<string,number>;old.households=1600;delete old.population;delete old.grain;delete old.irrigation;}delete w.realm!.population;const money=w.realm!.treasuries.liang.coins,loaded=parseWorld(serializeWorld(w));expect(loaded.realm!.cities.jiankang.population).toBe(8000);expect(loaded.realm!.cities.jiankang.grain).toBe(0);expect(loaded.realm!.treasuries.liang.coins).toBe(money);expect(parseWorld(serializeWorld(loaded))).toEqual(loaded);});
 it('rejects corrupted migration conservation, duplicated IDs and altered route durations',()=>{const w=start();actPopulation(w,{type:'population',action:'transfer',from:'jiankang',to:'jingkou',amount:100,kind:'assisted'});for(const change of [(x:typeof w)=>{x.realm!.population!.transfers[0].arrived=100;},(x:typeof w)=>{x.realm!.population!.transfers.push({...x.realm!.population!.transfers[0]});},(x:typeof w)=>{x.realm!.population!.transfers[0].durations[0]++;}]){const copy=structuredClone(w);change(copy);expect(()=>serializeWorld(copy)).toThrow('存档');}});
 it('migration advances once per day and forced migration has greater losses',()=>{const w=start();actPopulation(w,{type:'population',action:'transfer',from:'jiankang',to:'jingkou',amount:100,kind:'forced'});const t=w.realm!.population!.transfers[0];w.day++;advancePopulation(w);const before=structuredClone(w);advancePopulation(w);expect(w).toEqual(before);expect(t.lossRate).toBeGreaterThan(populationQuote(w,{type:'population',action:'transfer',from:'jiankang',to:'jingkou',amount:100,kind:'assisted'}).lossRate);});
 it('muster and disband conserve surviving people',()=>{const w=start(),before=w.realm!.cities.jiankang.population;actRealm(w,{type:'realm',action:'muster'});expect(w.realm!.cities.jiankang.population+w.realm!.armies[0].troops).toBe(before);actRealm(w,{type:'realm',action:'disband'});expect(w.realm!.cities.jiankang.population).toBe(before);});

 it('extensions require authority, carry a political cost and cannot repeat',()=>{const w=start();actService(w,{type:'service',action:'begin'});actService(w,{type:'service',action:'open',site:'jiankang',kind:'relief',officer:'xiao-gang'});actService(w,{type:'service',action:'plan',id:1,plan:'balanced'},'xiao-gang');actService(w,{type:'service',action:'approve',id:1});actService(w,{type:'service',action:'start',id:1},'xiao-gang');const t=serviceTask(w,1)!,deadline=t.deadline,support=governmentOf(w)!.support;expect(()=>actService(w,{type:'service',action:'extend',id:1},'xiao-gang')).toThrow('主管');actService(w,{type:'service',action:'extend',id:1});expect(t.deadline).toBe(deadline+30);expect(governmentOf(w)!.support).toBe(support-3);expect(()=>actService(w,{type:'service',action:'extend',id:1})).toThrow('已经');expect(parseWorld(serializeWorld(w))).toEqual(w);});

 it('capital grain transfers debit the central depot without creating grain',()=>{const w=start(),before=w.realm!.treasuries.liang.grain;expect(w.realm!.cities.jiankang.grain).toBe(0);actPopulation(w,{type:'population',action:'transfer',from:'jiankang',to:'jingkou',kind:'grain',amount:100});expect(w.realm!.treasuries.liang.grain).toBe(before-100);const t=w.realm!.population!.transfers[0];expect(t.sent).toBe(100);for(let i=0;i<100&&t.status==='traveling';i++){w.day++;advancePopulation(w);}expect(w.realm!.cities.jingkou.grain+t.lost).toBe(100);});
 it('army grain is debited at departure and reaches troops only after transport',()=>{const w=start(),s=w.realm!;s.armies.push({realm:'liang',location:'jingkou',troops:600,morale:80,supply:0,journey:null,siege:0});const a=s.armies[0],before=s.treasuries.liang.grain;advanceArmyLogistics(w,a);const sent=a.convoy!.grain,days=a.convoy!.durations.reduce((n,d)=>n+d,0);expect(a.supply).toBe(0);expect(s.treasuries.liang.grain).toBe(before-sent);let elapsed=0;for(;elapsed<100&&a.convoy;elapsed++){w.day++;advanceArmyLogistics(w,a);}expect(elapsed).toBeGreaterThan(days);expect(a.supply).toBe(Math.floor(sent*.95));expect(a.convoy).toBeNull();});
 it('changing the dominant group changes real action support and execution efficiency',()=>{const w=start(),c=governmentOf(w)!.court!;for(const id of Object.keys(c.members))c.members[id]='reform';const reform=politicalAction(w,'liang','reform');for(const id of Object.keys(c.members))c.members[id]='conservative';const conservative=politicalAction(w,'liang','reform');expect(reform.support).toBeGreaterThan(conservative.support);expect(reform.effort).toBeGreaterThan(conservative.effort);});

});
