import {describe,it,expect} from 'vitest';
import {newCampaignWorld,act} from './world';
import {parseWorld,serializeWorld} from './save';
import {advanceRealm,cityYield} from './realm';
import {governmentOf} from './government';
import {officeHierarchy,superiorOffice} from './offices';
import {countyTerritory,localAncestors,localTitle,localHolder,localKey,localCanAppoint,localReason,actLocal,setLocalHolder,advanceLocal,localSeatSite,completeLocalAppointment,localEfficiency,localOfficeLoad,clearLocalPerson} from './localAdministration';
import {collectFiscal,localBalance,fiscalPath,publicBalance,territoryAccount,actFiscal,advanceFiscal,payFiscalOperations,migrateCountyAccounts} from './treasury';
import {pauseSnapshot,pauseEvents,pauseHasActions} from './pauseEvents';
import {lifeOf} from './lifeState';
import {officialDutyReason} from './officialDuties';
const start=(id='xiao-yan')=>newCampaignWorld(id,undefined,'sandbox');
const county=countyTerritory('wucheng'),pref=localAncestors(county).at(-1)!.id,province=localAncestors(county)[0].id;
const total=(w:ReturnType<typeof start>)=>Object.values(w.realm!.treasuries).reduce((n,t)=>n+t.coins,0)+Object.values(w.realm!.fiscal!.balances).reduce((n,v)=>n+v,0);
function arrived(w:ReturnType<typeof start>,t:string,id:string){const o=w.realm!.offices.find(o=>o.territory===t)!;w.mobility!.residences[id]={site:o.site,journey:null};w.day=o.due;advanceRealm(w);}
describe('州郡县地方官链条',()=>{
 it('县城同一职务与钱包，州郡为真实上级；中央越级授官不改隶属',()=>{const w=start();w.realm!.personalInfluence!['xiao-yi']=100;setLocalHolder(w,province,'liang','xiao-yi');setLocalHolder(w,pref,'liang','xu-chi');act(w,{type:'local',action:'appoint',territory:county,candidate:'xu-ling'});arrived(w,county,'xu-ling');expect(localHolder(w,county,'liang')).toBe('xu-ling');const all=officeHierarchy(w),n=all.find(n=>n.site==='wucheng')!;expect(superiorOffice(all,n)?.holder).toBe('xu-chi');expect(n.name).toBe(localTitle(county));expect(all.filter(n=>n.territory===county)).toHaveLength(1);expect(fiscalPath(w,'wucheng')).toHaveLength(4);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('授权者仅任命辖下，不能同级跨区；授权撤回令未到任文书失效',()=>{const w=start();w.realm!.personalInfluence!['xiao-yi']=100;setLocalHolder(w,province,'liang','xiao-yi');expect(localCanAppoint(w,'xiao-yi',pref,'liang')).toBe(false);actLocal(w,{type:'local',action:'delegate',territory:province,enabled:true});expect(localCanAppoint(w,'xiao-yi',pref,'liang')).toBe(true);expect(localCanAppoint(w,'xiao-yi',province,'liang')).toBe(false);actLocal(w,{type:'local',action:'appoint',territory:pref,candidate:'xu-chi'},'xiao-yi');actLocal(w,{type:'local',action:'delegate',territory:province,enabled:false});arrived(w,pref,'xu-chi');expect(localHolder(w,pref,'liang')).toBeNull();});
 it('举荐产生待批决策，不能代玩家批准，重复申请不扣款',()=>{const w=start();w.realm!.personalInfluence!['xiao-yi']=100;setLocalHolder(w,province,'liang','xiao-yi');const snap=pauseSnapshot(w),cmd={type:'local',action:'recommend',territory:pref,candidate:'xu-chi'} as const;actLocal(w,cmd,'xiao-yi');const q=w.realm!.local!.requests[0];w.day=8;advanceLocal(w);expect(q.status).toBe('pending');const event=pauseEvents(snap,w).find(e=>e.kind==='local')!;expect(pauseHasActions(w,event)).toBe(true);expect(()=>actLocal(w,cmd,'xiao-yi')).toThrow('待批');act(w,{type:'local',action:'approve',id:q.id});expect(pauseHasActions(w,event)).toBe(false);expect(w.realm!.offices).toHaveLength(1);expect(()=>act(w,{type:'local',action:'approve',id:q.id})).toThrow();expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('代行有真实期限，失守暂停权限，死亡与改朝不继承公职',()=>{const w=start();actLocal(w,{type:'local',action:'acting',territory:pref,candidate:'xu-chi'});arrived(w,pref,'xu-chi');const until=w.realm!.local!.seats[localKey('liang',pref)].actingUntil!;expect(until).toBe(w.day+90);w.day=until;advanceLocal(w);expect(localHolder(w,pref,'liang')).toBeNull();setLocalHolder(w,pref,'liang','xu-chi');const seat=localSeatSite(w,pref,'liang')!;w.realm!.cities[seat].controller='east';expect(localCanAppoint(w,'xu-chi',county,'liang')).toBe(false);w.realm!.cities[seat].controller='liang';lifeOf(w,'xu-chi')!.death={day:w.day,cause:'illness'};advanceLocal(w);expect(w.realm!.local!.seats[localKey('liang',pref)].holder).toBeNull();setLocalHolder(w,pref,'liang','xu-ling');governmentOf(w)!.regimeId='new-court';expect(localHolder(w,pref,'liang')).toBeNull();});
 it('州郡任职有实绩、下辖公务与税务效果，不靠人口绝对值刷考绩',()=>{const w=start();setLocalHolder(w,pref,'liang','xu-chi');expect(officialDutyReason(w,'xu-chi','marketworks','wucheng')).toBe('');expect(officialDutyReason(w,'xu-chi','marketworks','changan')).not.toBe('');const before=governmentOf(w)!.merit['xu-chi']??0;w.realm!.cities.wucheng.order=90;w.day=90;advanceLocal(w);expect(governmentOf(w)!.merit['xu-chi']).toBeGreaterThan(before);expect(w.realm!.local!.seats[localKey('liang',pref)].assessment).toContain('考绩');expect(Number.isFinite(localEfficiency(w,'wucheng'))).toBe(true);});
 it('任命县令与太守可同治所同时在途，并拒绝伪造职位和文书',()=>{const w=start();actLocal(w,{type:'local',action:'appoint',territory:pref,candidate:'xu-chi'});actLocal(w,{type:'local',action:'appoint',territory:county,candidate:'xu-ling'});expect(parseWorld(serializeWorld(w))).toEqual(w);const bad=structuredClone(w);bad.realm!.offices[0].territory='province:liang:不存在';expect(()=>serializeWorld(bad)).toThrow('存档');expect(localReason(w,{type:'local',action:'appoint',territory:'realm:liang',candidate:'xu-chi'})).toContain('无效');});
 it('不能自我任命、任命幼童或在失守后靠旧文书掌权',()=>{const w=start();expect(localReason(w,{type:'local',action:'appoint',territory:pref,candidate:'xiao-yan'})).not.toBe('');expect(localReason(w,{type:'local',action:'appoint',territory:pref,candidate:'xiao-fangzhi'})).not.toBe('');actLocal(w,{type:'local',action:'appoint',territory:pref,candidate:'xu-chi'});w.realm!.cities[w.realm!.offices[0].site].controller='east';expect(completeLocalAppointment(w,w.realm!.offices[0])).toBe(true);expect(localHolder(w,pref,'liang')).toBeNull();});
});
describe('地方财政与旧档兼容',()=>{
 it('逐级留用与上缴严格守恒，旧余额不重复征税',()=>{const w=start(),before=total(w),tax=Object.entries(w.realm!.cities).filter(([,c])=>c.controller==='liang').reduce((n,[id])=>n+cityYield(w,id).coins,0),expected=Math.floor(cityYield(w,'wucheng').coins*.35);collectFiscal(w,'liang');expect(total(w)).toBe(before+tax);expect(localBalance(w,'wucheng')).toBe(expected);expect(publicBalance(w,territoryAccount(w,'liang',pref))).toBeGreaterThan(0);collectFiscal(w,'liang');expect(total(w)).toBe(before+2*tax);expect(localBalance(w,'wucheng')).toBe(expected*2);});
 it('县向郡请款只扣郡库；郡缺款向州申请，中央不被越权扣款',()=>{const w=start();w.realm!.personalInfluence!['xiao-yi']=100;setLocalHolder(w,province,'liang','xiao-yi');setLocalHolder(w,pref,'liang','xu-chi');setLocalHolder(w,county,'liang','xu-ling');const provinceKey=territoryAccount(w,'liang',province),prefKey=territoryAccount(w,'liang',pref);w.realm!.fiscal!.balances[provinceKey]=200;const central=w.realm!.treasuries.liang.coins,old=total(w);actFiscal(w,{type:'fiscal',action:'request',site:'wucheng',amount:100,purpose:'construction'},'xu-ling');const q=w.realm!.fiscal!.requests[0];expect(q.approver).toBe('xu-chi');expect(()=>actFiscal(w,{type:'fiscal',action:'approve',id:q.id},'xu-chi')).toThrow('不足');expect(w.realm!.treasuries.liang.coins).toBe(central);actFiscal(w,{type:'fiscal',action:'request',site:localSeatSite(w,pref,'liang')!,territory:pref,amount:100,purpose:'construction'},'xu-chi');const higher=w.realm!.fiscal!.requests[1];actFiscal(w,{type:'fiscal',action:'approve',id:higher.id},'xiao-yi');expect(publicBalance(w,prefKey)).toBe(100);actFiscal(w,{type:'fiscal',action:'approve',id:q.id},'xu-chi');expect(localBalance(w,'wucheng')).toBe(100);expect(total(w)).toBe(old);expect(w.realm!.treasuries.liang.coins).toBe(central);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('撤换上级后重新路由申请；县主官撤换取消旧申请',()=>{const w=start();setLocalHolder(w,pref,'liang','xu-chi');setLocalHolder(w,county,'liang','xu-ling');actFiscal(w,{type:'fiscal',action:'request',site:'wucheng',amount:100,purpose:'construction'},'xu-ling');setLocalHolder(w,pref,'liang','yu-jianwu');advanceFiscal(w);expect(w.realm!.fiscal!.requests[0].approver).toBe('yu-jianwu');setLocalHolder(w,county,'liang',null);advanceFiscal(w);expect(w.realm!.fiscal!.requests[0].status).toBe('cancelled');});
 it('旧档不把县主官升为刺史；县城钱包合并一次，不增发',()=>{const w=start('xiao-gang');delete w.realm!.local;w.realm!.fiscal!.balances['liang|county:jiankang']=30;w.realm!.fiscal!.balances['liang|city:jiankang']=20;const before=total(w),restored=parseWorld(serializeWorld(w));expect(total(restored)).toBe(before);expect(localBalance(restored,'jiankang')).toBe(50);expect(restored.realm!.cities.jiankang.governor).toBe('xiao-gang');expect(Object.values(restored.realm!.local!.seats).some(s=>s.holder==='xiao-gang')).toBe(false);const snapshot=structuredClone(restored);migrateCountyAccounts(restored);expect(restored).toEqual(snapshot);expect(parseWorld(serializeWorld(restored))).toEqual(restored);});
 it('州郡俸禄来自本级公库且确实支付给任职者',()=>{const w=start();setLocalHolder(w,pref,'liang','xu-chi');const key=territoryAccount(w,'liang',pref),before=w.relationships!.reserves['xu-chi'];w.realm!.fiscal!.balances[key]=8;payFiscalOperations(w,'liang');expect(w.relationships!.reserves['xu-chi']).toBe(before+8);expect(publicBalance(w,key)).toBe(0);});
});

describe('兼任、自动选官与操作后即时存档',()=>{
 it('兼领保留原职，正常调任交接；撤免后立即可保存',()=>{const w=start();w.realm!.influence=200;setLocalHolder(w,county,'liang','xu-chi');actLocal(w,{type:'local',action:'appoint',territory:pref,candidate:'xu-chi',concurrent:true});arrived(w,pref,'xu-chi');expect(localHolder(w,county,'liang')).toBe('xu-chi');expect(localOfficeLoad(w,'xu-chi')).toBe(2);actLocal(w,{type:'local',action:'remove',territory:pref});expect(localHolder(w,county,'liang')).toBe('xu-chi');expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('交接玩家地方职务立即同步实际治理权，不等下一日修复',()=>{const w=start('xiao-gang');clearLocalPerson(w,'xiao-gang');expect(w.holdings.governedCities).toEqual([]);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('NPC 按季申请空缺并支付影响力，重复推进同日不再次申请',()=>{const w=start();for(const p of Object.keys(w.realm!.personalInfluence!))w.realm!.personalInfluence![p]=100;w.day=90;advanceLocal(w);const requests=w.realm!.local!.requests;expect(requests.length).toBeGreaterThan(0);for(const q of requests)expect(w.realm!.personalInfluence![q.actor]).toBe(90);const snapshot=structuredClone(w.realm!.local);advanceLocal(w);expect(w.realm!.local).toEqual(snapshot);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('超额兼领、重复奏请、负余额和未知命令不留下部分写入',()=>{const w=start();const before=structuredClone(w);expect(()=>actLocal(w,{type:'local',action:'unknown',id:1} as never)).toThrow();expect(w).toEqual(before);for(const site of ['wucheng','yuhang','qiantang'])setLocalHolder(w,countyTerritory(site),'liang','xu-chi');expect(localReason(w,{type:'local',action:'appoint',territory:pref,candidate:'xu-chi',concurrent:true})).toContain('三项');const bad=structuredClone(w);bad.realm!.fiscal!.balances['liang|'+pref]=-1;expect(()=>serializeWorld(bad)).toThrow('存档');});
});

it('地方授官不绕过封建异族领有保护，审批后的实际赴任也复核人物身份',()=>{const w=start();setLocalHolder(w,pref,'liang','xu-chi');governmentOf(w)!.type='feudal';expect(localReason(w,{type:'local',action:'appoint',territory:pref,candidate:'yu-xin'})).toContain('异族');expect(localReason(w,{type:'local',action:'remove',territory:pref})).toContain('封建');governmentOf(w)!.type='celestial';setLocalHolder(w,pref,'liang',null);actLocal(w,{type:'local',action:'appoint',territory:pref,candidate:'xu-chi'});governmentOf(w)!.executives.push('xu-chi');expect(completeLocalAppointment(w,w.realm!.offices[0])).toBe(true);expect(localHolder(w,pref,'liang')).toBeNull();});
