import {civilCanAdmin} from './civilWars';
import {awardDeed} from './deeds';
import {relationshipPersonById} from '../data/relationships';
import {relationshipPeople} from '../data/relationships';
import {personInfluence,awardInfluence} from './personalInfluence';
import {ancestorsOf,descendantSites,territoryNodes} from '../data/territorialHierarchy';
import {countyOfficials,historicalLocalAppointments} from '../data/localOfficials';
import {advanceAppointments,type AppointmentCycle} from './appointmentCycle';
import {siteById} from '../data/scenario';
import {allegianceRealm,appointmentAuthorityReason,officeName,publicOfficeReason} from './officeEligibility';
import {governmentOf,governingAuthority,governingExecutives} from './government';
import {attributes} from './social';
import {isAlive} from './lifeState';
import {clanStanding} from './clans';
import {relationOpinion,creditPersonalCoins,changeRelationOpinion} from './relationships';
import {personResidence,presentAt} from './residence';
import {dispatchNPC,npcRoute} from './mobility';
import {planRoute} from './world';
import {realms,type RealmId} from './realm';
import type {World} from './types';
export interface LocalSeat {holder:string|null;delegated:boolean;actingUntil:number|null;since:number;regime:string;order:number;prosperity:number;population:number;assessed:number;assessment:string}
export interface LocalRequest {id:number;realm:RealmId;territory:string;candidate:string;actor:string;approver:string;created:number;changed:number;status:'pending'|'approved'|'rejected'|'cancelled';reply:string}
export interface LocalAdministration {version:1;lastRecruitment:number;lastNPCRecruitment?:number;seats:Record<string,LocalSeat>;requests:LocalRequest[];nextId:number;cycle?:AppointmentCycle}
export type LocalCommand={type:'local';action:'appoint'|'recommend'|'apply'|'acting';territory:string;candidate:string;concurrent?:boolean}|{type:'local';action:'delegate';territory:string;enabled:boolean}|{type:'local';action:'remove';territory:string}|{type:'local';action:'approve'|'reject'|'cancel';id:number};
const descendants=Object.fromEntries(Object.keys(territoryNodes).map(id=>[id,descendantSites(id)]));
export const localKey=(r:RealmId,t:string)=>r+'|'+canonicalTerritory(t);
const canonicalTerritories=Object.fromEntries(Object.keys(territoryNodes).map(t=>[t,t.startsWith('city:')&&territoryNodes['county:'+t.slice(5)]?'county:'+t.slice(5):t]));
export function canonicalTerritory(t:string){return Object.hasOwn(canonicalTerritories,t)?canonicalTerritories[t]:t;}
export function countyTerritory(site:string){return canonicalTerritory('city:'+site);}
export const localLevel=(t:string)=>territoryNodes[canonicalTerritory(t)]?.level;
export function localTitle(t:string){const n=territoryNodes[canonicalTerritory(t)];if(!n)return '地方官';return n.level==='province'?n.name+'刺史':n.level==='prefecture'?(/尹$/.test(n.name)?n.name:n.name+'太守'):n.level==='county'&&n.name.endsWith('县')?n.name+'令':n.name+'守官';}
export function localSites(w:World,t:string,r:RealmId,controlled=false){return (descendants[canonicalTerritory(t)]??[]).filter(id=>w.realm?.cities[id]?.owner===r&&(!controlled||w.realm.cities[id].controller===r));}
export function localSeatSite(w:World,t:string,r:RealmId){const list=localSites(w,t,r);return list.find(id=>siteById[id].capital)??list[0];}
export function localHolder(w:World,t:string,r:RealmId):string|null {t=canonicalTerritory(t);const n=territoryNodes[t];if(!n)return null;if(['province','prefecture'].includes(n.level)&&w.realm?.local?.seats[localKey(r,t)]?.regime!==governmentOf(w,r)?.regimeId)return null;const id=n.level==='county'||n.level==='city'?w.realm?.cities[descendants[t][0]]?.governor:w.realm?.local?.seats[localKey(r,t)]?.holder;return id&&isAlive(w,id)&&allegianceRealm(w,id)===r?id:null;}
export function localActive(w:World,t:string,r:RealmId){const site=localSeatSite(w,t,r);return !!site&&w.realm!.cities[site].controller===r;}
const ancestorNodes=Object.fromEntries(Object.keys(territoryNodes).map(t=>[t,ancestorsOf(t).filter(n=>n.level!=='realm'&&n.id!==t)]));
export function localAncestors(t:string){return (ancestorNodes[canonicalTerritory(t)]??[]).slice();}
export function localSuperior(w:World,t:string,r:RealmId,person=localHolder(w,t,r)):{territory:string;holder:string}|undefined{for(const n of localAncestors(t).reverse()){const id=localHolder(w,n.id,r);if(id&&id!==person&&localActive(w,n.id,r))return {territory:n.id,holder:id};}const holder=governingExecutives(w,r).find(id=>id!==person)??governmentOf(w,r)?.ruler;return holder&&holder!==person?{territory:'realm:'+r,holder}:undefined;}
export function localHasJurisdiction(w:World,actor:string,t:string,r:RealmId){return localAncestors(t).some(n=>localHolder(w,n.id,r)===actor&&localActive(w,n.id,r));}
export function localCentral(w:World,actor:string,r:RealmId){if(governingExecutives(w,r).includes(actor))return true;return governmentOf(w,r)?.ruler===actor&&(actor===w.characterId?!appointmentAuthorityReason(w,r):!governingExecutives(w,r).some(id=>id!==actor));}
export function localCanAppoint(w:World,actor:string,t:string,r:RealmId){return localCentral(w,actor,r)||localAncestors(t).some(n=>localHolder(w,n.id,r)===actor&&localActive(w,n.id,r)&&w.realm?.local?.seats[localKey(r,n.id)]?.delegated);}
export function localAppointer(w:World,t:string,r:RealmId,exclude?:string){for(const n of localAncestors(t).reverse()){const holder=localHolder(w,n.id,r);if(holder&&holder!==exclude&&localCanAppoint(w,holder,t,r))return holder;}return governingExecutives(w,r).find(id=>id!==exclude)??governmentOf(w,r)!.ruler;}
function metrics(w:World,t:string,r:RealmId){const rows=localSites(w,t,r,true).map(id=>w.realm!.cities[id]);return {order:Math.round(rows.reduce((n,c)=>n+c.order,0)/(rows.length||1)),prosperity:Math.round(rows.reduce((n,c)=>n+c.prosperity,0)/(rows.length||1)),population:rows.reduce((n,c)=>n+c.population,0)};}
export function ensureLocalAdministration(w:World,seed=false){if(!w.realm)return;const fresh=!w.realm.local;const s=w.realm.local??={version:1,lastRecruitment:w.day,seats:{},requests:[],nextId:1};if(fresh&&seed){for(const c of Object.values(w.realm.cities))c.governor=null;for(const p of countyOfficials){const c=w.realm.cities[p.home];if(c?.owner===p.realm){c.governor=p.id;governmentOf(w,p.realm)!.merit[p.id]=20;}}for(const o of historicalLocalAppointments){const n=Object.values(territoryNodes).find(n=>n.level===o.level&&n.id.startsWith('province:'+o.realm+':')&&n.name===o.name);if(n)s.seats[localKey(o.realm,n.id)]={holder:o.person,delegated:false,actingUntil:null,since:w.day,regime:governmentOf(w,o.realm)!.regimeId,...metrics(w,n.id,o.realm),assessed:w.day,assessment:''};}refreshGoverned(w);}if(fresh)for(const [site,c] of Object.entries(w.realm.cities))if(c.governor&&c.owner!=='frontier'){const t=countyTerritory(site);s.seats[localKey(c.owner,t)]={holder:null,delegated:false,actingUntil:null,since:w.day,regime:governmentOf(w,c.owner)!.regimeId,...metrics(w,t,c.owner),assessed:w.day,assessment:''};}return s;}
export function localOfficeCost(action:'appoint'|'acting'|'recommend'|'apply'){return action==='acting'?10:action==='recommend'||action==='apply'?10:20;}
/** Qualified idle candidates fill vacancies as ordinary administration. Moving an
 * incumbent, replacing a holder, and appointments below the merit reference stay political. */
export function localInfluenceCost(w:World,c:LocalCommand,actor=w.characterId!):number{
 if(c.action==='remove')return 20;if(c.action==='delegate'||c.action==='reject'||c.action==='cancel')return 0;
 if(c.action==='acting'||c.action==='apply'||c.action==='recommend')return 10;
 const q='id'in c?w.realm?.local?.requests.find(q=>q.id===c.id):undefined,r=q?.realm??allegianceRealm(w,actor),t=canonicalTerritory(q?.territory??('territory'in c?c.territory:'')),id=q?.candidate??('candidate'in c?c.candidate:'');
 const g=r&&governmentOf(w,r);
 return r&&g&&!localHolder(w,t,r)&&(g.merit[id]??0)>=localMeritReference(t)&&!localOfficeLoad(w,id)&&!Object.values(g.court?.ministries??{}).includes(id)?0:20;
}
export function localMeritFactors(w:World,t:string,id:string,approver:string,r:RealmId){return [{label:'管理能力',value:attributes(w,id).stewardship*2},{label:'功绩',value:Math.min(30,governmentOf(w,r)?.merit[id]??0)},{label:'门第',value:clanStanding(w,id)?.petition??0},{label:'上级关系',value:Math.round(relationOpinion(w,approver,id)/5)},{label:'职位资历',value:Object.entries(w.realm?.local?.seats??{}).some(([,s])=>s.holder===id)?10:0},{label:'任职门槛',value:localLevel(t)==='province'?-35:localLevel(t)==='prefecture'?-20:-10}];}
export function localReason(w:World,c:LocalCommand,actor=w.characterId!):string {if(!['appoint','acting','recommend','apply','delegate','remove','approve','reject','cancel'].includes(c.action))return '无效授官行动';if(!w.realm||!actor||!isAlive(w,actor)||w.campaign?.status!=='active')return '当前无法办理地方官职';const r=allegianceRealm(w,actor);if(!r)return '无所属政权';if(w.realm.event)return '先处理待决事务';
 if('id'in c){const q=w.realm.local?.requests.find(q=>q.id===c.id);if(!q||q.status!=='pending')return '申请已结案';if(c.action==='cancel')return q.actor===actor?'':'只能撤回自己的申请';if(q.approver!==actor||!localCanAppoint(w,actor,q.territory,q.realm))return '须由当前有授官权的上级批示';if(c.action==='reject')return '';if(!civilCanAdmin(w,actor,localSeatSite(w,q.territory,q.realm)!))return '不能向内战对方控制地区授官';return candidateReason(w,q.territory,q.candidate,q.realm)||(personInfluence(w,actor)<localInfluenceCost(w,c,actor)?'影响力不足 '+localInfluenceCost(w,c,actor):'');}
 const t=canonicalTerritory(c.territory);if(!Object.hasOwn(territoryNodes,t)||localLevel(t)==='realm')return '无效地方职位';if(!localSites(w,t,r).length||!localActive(w,t,r))return '仅能管理本国拥有且治所未失守的辖区';
 if(!civilCanAdmin(w,actor,localSeatSite(w,t,r)!))return '不能向内战对方控制地区授官';
 if(c.action==='delegate'&&typeof c.enabled!=='boolean')return '无效授权';if(c.action==='delegate')return !['province','prefecture'].includes(localLevel(t)!)?'县级无下属主官授任权':!localCentral(w,actor,r)?'须由朝廷授权':!localHolder(w,t,r)?'须先任命主官':w.realm.local?.seats[localKey(r,t)]?.delegated===c.enabled?'授权未变化':'';
 if(c.action==='remove'&&governmentOf(w,r)?.type==='feudal')return '封建领有不能直接撤免，须先改革制度';if(c.action==='remove')return !localCanAppoint(w,actor,t,r)?'没有该辖区授免权':!localHolder(w,t,r)?'职位已空缺':localHolder(w,t,r)===actor?'不能自行撤免自己':personInfluence(w,actor)<20?'撤免需影响力 20':'';
 if(!['appoint','recommend','apply','acting'].includes(c.action))return '无效授官行动';if(c.action==='apply'&&c.candidate!==actor)return '只能为自己请任';if((c.action==='appoint'||c.action==='acting')&&!localCanAppoint(w,actor,t,r))return '须有朝廷授官权或上级授官授权，可先举荐';if(c.action==='recommend'&&!localCentral(w,actor,r)&&!localHasJurisdiction(w,actor,t,r))return '仅能举荐自己辖下的职位';if(c.action==='acting'&&localHolder(w,t,r))return '代行只适用于空缺职位';
 if(c.concurrent!==undefined&&typeof c.concurrent!=='boolean')return '无效兼领选项';if(c.concurrent&&c.action!=='appoint')return '仅正式授官可兼领';if(c.concurrent&&localOfficeLoad(w,c.candidate)>=3)return '最多兼领三项地方职务';const reason=candidateReason(w,t,c.candidate,r);if(reason)return reason;if((c.action==='apply'||c.action==='recommend')&&w.realm.local?.requests.some(q=>q.status==='pending'&&q.candidate===c.candidate&&q.territory===t))return '已有同一职位的待批申请';if(personInfluence(w,actor)<localInfluenceCost(w,c,actor))return '影响力不足 '+localInfluenceCost(w,c,actor);return '';}
export function candidateReason(w:World,t:string,id:string,r:RealmId){if(allegianceRealm(w,id)!==r)return '须当前效忠本国';const why=publicOfficeReason(w,id);if(why)return why;if(!localActive(w,t,r))return '治所失守或不属本国';if(localHolder(w,t,r)===id)return '此人已在任';if(w.realm!.offices.some(o=>canonicalTerritory(o.territory??countyTerritory(o.site))===t))return '任命正在送达';const g=governmentOf(w,r)!;const incumbent=localHolder(w,t,r);if(g.type==='feudal'&&incumbent&&relationshipPersonById[incumbent]?.family!==relationshipPersonById[id]?.family)return '封建领有不得改授异族，须先改革制度';if(g.ruler===id||governingExecutives(w,r).includes(id))return '君主和执政者不兼任新授地方职位';if(!npcRoute(w,id,localSeatSite(w,t,r)!))return '赴任道路不通，需先恢复通行';return '';}
function log(w:World,text:string){w.chronicle.push({day:w.day,person:'player',text});w.chronicle=w.chronicle.slice(-100);}
export function consequence(w:World,t:string,r:RealmId,actor:string){const old=localHolder(w,t,r),superior=localSuperior(w,t,r);if(old&&old!==actor){const g=governmentOf(w,r)!;g.support=Math.max(0,g.support-3);changeRelationOpinion(w,old,actor,-10);if(superior&&superior.holder!==actor){g.support=Math.max(0,g.support-2);changeRelationOpinion(w,superior.holder,actor,-5);log(w,'越级撤换'+localTitle(t)+'，直属上级'+officeName(superior.holder)+'受到影响，朝野支持 −2。');}}}
export const localMeritReference=(t:string)=>localLevel(t)==='province'?50:localLevel(t)==='prefecture'?30:20;
export function issue(w:World,t:string,id:string,r:RealmId,issuer:string,acting=false,concurrent=false){const site=localSeatSite(w,t,r)!;if(!civilCanAdmin(w,issuer,site))throw new Error('不能向内战对方控制地区授官');const days=planRoute(personResidence(w,issuer).site,site)?.days??7;const g=governmentOf(w,r)!;if(!acting&&(g.merit[id]??0)<localMeritReference(t)){g.support=Math.max(0,g.support-5);w.realm!.cities[site].order=Math.max(0,w.realm!.cities[site].order-3);log(w,'破格授'+localTitle(t)+'：朝野支持 −5、治所秩序 −3。');}w.realm!.offices.push({site,candidate:id,due:w.day+days+7,territory:t,issuer,realm:r,acting,concurrent,issued:w.day});log(w,officeName(issuer)+'授'+officeName(id)+'为'+(acting?'代行':'')+localTitle(t)+'，候赴任。');}
export function actLocal(w:World,c:LocalCommand,actor=w.characterId!){const why=localReason(w,c,actor);if(why)throw new Error(why);const s=ensureLocalAdministration(w)!,r=allegianceRealm(w,actor)!;
 const cost=localInfluenceCost(w,c,actor);awardInfluence(w,actor,-cost);
 if('id'in c){const q=s.requests.find(q=>q.id===c.id)!;q.status=c.action==='approve'?'approved':c.action==='reject'?'rejected':'cancelled';q.changed=w.day;q.reply=c.action==='approve'?'准予授官，候赴任':c.action==='reject'?'上级未准此次申请':'申请撤回';if(c.action==='approve')issue(w,q.territory,q.candidate,q.realm,actor);log(w,localTitle(q.territory)+'：'+q.reply);return;}
 const t=canonicalTerritory(c.territory);if(c.action==='delegate'){s.seats[localKey(r,t)].delegated=c.enabled;log(w,localTitle(t)+(c.enabled?'获准授任辖下主官。':'收回授官授权。'));return;}if(c.action==='remove'){consequence(w,t,r,actor);setLocalHolder(w,t,r,null);log(w,localTitle(t)+'撤免，暂由上级代管。');return;}
 if(c.action==='recommend'||c.action==='apply'){const approver=localAppointer(w,t,r,actor);s.requests=s.requests.filter(q=>q.status==='pending').concat(s.requests.filter(q=>q.status!=='pending').slice(-59));s.requests.push({id:s.nextId++,realm:r,territory:t,candidate:c.candidate,actor,approver,created:w.day,changed:w.day,status:'pending',reply:''});return;}issue(w,t,c.candidate,r,actor,c.action==='acting',c.concurrent);}
export function setLocalHolder(w:World,t:string,r:RealmId,id:string|null,acting=false){t=canonicalTerritory(t);const n=territoryNodes[t];if(n.level==='county'||n.level==='city'){w.realm!.cities[descendants[t][0]].governor=id;}
 const s=ensureLocalAdministration(w)!;s.seats[localKey(r,t)]={holder:n.level==='county'||n.level==='city'?null:id,delegated:false,actingUntil:acting?w.day+90:null,since:w.day,regime:governmentOf(w,r)!.regimeId,...metrics(w,t,r),assessed:w.day,assessment:''};refreshGoverned(w);}
function refreshGoverned(w:World){w.holdings.governedCities=Object.entries(w.realm!.cities).filter(([,c])=>c.governor===w.characterId&&c.controller===allegianceRealm(w,w.characterId!)).map(([id])=>id);}
export function clearLocalPerson(w:World,id:string){for(const c of Object.values(w.realm!.cities))if(c.governor===id)c.governor=null;for(const [key,s] of Object.entries(w.realm?.local?.seats??{}))if(s.holder===id){s.holder=null;s.delegated=false;s.actingUntil=null;log(w,localTitle(key.split('|')[1])+'完成原职交接。');}refreshGoverned(w);}
export function completeLocalAppointment(w:World,o:NonNullable<World['realm']>['offices'][number]){const r=o.realm??w.realm!.cities[o.site].owner as RealmId,t=canonicalTerritory(o.territory??countyTerritory(o.site));if(!isAlive(w,o.candidate)||allegianceRealm(w,o.candidate)!==r||o.territory&&(governmentOf(w,r)?.ruler===o.candidate||governingExecutives(w,r).includes(o.candidate))||!localActive(w,t,r)||w.realm!.cities[o.site].owner!==r||w.realm!.cities[o.site].controller!==r||o.issuer&&(!isAlive(w,o.issuer)||!localCanAppoint(w,o.issuer,t,r))||o.issued!==undefined&&w.day-o.issued>180){log(w,localTitle(t)+'任命因权限、人物、辖地变化或逾期失效。');return true;}if(!presentAt(w,o.candidate,o.site)){dispatchNPC(w,o.candidate,o.site);o.due=w.day+1;return false;}consequence(w,t,r,o.issuer??governingAuthority(w,r));if(!o.concurrent)clearLocalPerson(w,o.candidate);const g=governmentOf(w,r)!;if(g.court)for(const key of Object.keys(g.court.ministries) as (keyof typeof g.court.ministries)[])if(g.court.ministries[key]===o.candidate)g.court.ministries[key]=null;setLocalHolder(w,t,r,o.candidate,o.acting);log(w,officeName(o.candidate)+'赴任'+localTitle(t)+(o.concurrent?'，兼领原职。':'，完成原职交接。'));return true;}
export function localOfficeLoad(w:World,id:string){return Object.values(w.realm?.cities??{}).filter(c=>c.governor===id).length+Object.values(w.realm?.local?.seats??{}).filter(s=>s.holder===id).length;}
export function localEfficiency(w:World,site:string){const r=w.realm?.cities[site]?.controller;if(!r||r==='frontier')return 0;return Math.max(-10,Math.min(10,localAncestors(countyTerritory(site)).reduce((n,t)=>{const id=localActive(w,t.id,r)?localHolder(w,t.id,r):null;if(!id)return n;const load=localOfficeLoad(w,id);return n+Math.round((attributes(w,id).stewardship-8)/3)-Math.max(0,load-1)*2;},0)));}
export function advanceLocal(w:World){const s=ensureLocalAdministration(w);if(!s)return;
 for(const [key,seat] of Object.entries(s.seats)){const [r,t]=key.split('|') as [RealmId,string];const id=localHolder(w,t,r);if(seat.regime!==governmentOf(w,r)?.regimeId||seat.holder&&!id||seat.actingUntil!==null&&seat.actingUntil<=w.day){setLocalHolder(w,t,r,null);log(w,localTitle(t)+'因任职条件变化或代行期满空缺。');continue;}if(!id||!localActive(w,t,r))continue;if(w.day-seat.assessed>=90){const now=metrics(w,t,r);const delta=Math.max(-5,Math.min(8,Math.round((now.order-seat.order)/5+(now.prosperity-seat.prosperity)/5)+(now.order>=70?2:0)-(now.population<seat.population*.9?4:0)));awardDeed(w,r,id,'local:'+t+':'+Math.floor(w.day/90),delta,'任内秩序变化 '+(now.order-seat.order)+'、繁荣变化 '+(now.prosperity-seat.prosperity)+'、人口变化 '+(now.population-seat.population));seat.assessment='本季考绩 '+(delta>=0?'+':'')+delta+'；秩序 '+(now.order-seat.order)+'、繁荣 '+(now.prosperity-seat.prosperity)+'、人口 '+(now.population-seat.population);Object.assign(seat,now,{assessed:w.day});if(id===w.characterId)log(w,localTitle(t)+'：'+seat.assessment);}}
 for(const q of s.requests.filter(q=>q.status==='pending').sort((a,b)=>localMeritFactors(w,b.territory,b.candidate,b.approver,b.realm).reduce((n,p)=>n+p.value,0)-localMeritFactors(w,a.territory,a.candidate,a.approver,a.realm).reduce((n,p)=>n+p.value,0)||a.id-b.id)){if(!isAlive(w,q.actor)||allegianceRealm(w,q.actor)!==q.realm||!isAlive(w,q.candidate)||allegianceRealm(w,q.candidate)!==q.realm||!localActive(w,q.territory,q.realm)||w.day-q.created>=60||localHolder(w,q.territory,q.realm)===q.candidate){q.status='cancelled';q.changed=w.day;q.reply='人物、任职、辖地变化或逾期，申请结案';continue;}const approver=localAppointer(w,q.territory,q.realm,q.actor);if(approver!==q.approver){q.approver=approver;q.changed=w.day;}if(!isAlive(w,q.approver)){q.status='cancelled';q.changed=w.day;q.reply='上级无人承接，申请结案';continue;}if(q.approver===w.characterId||w.day-q.changed<5||w.realm!.event)continue;const command={type:'local',action:'approve',id:q.id} as const,qualified=localMeritFactors(w,q.territory,q.candidate,q.approver,q.realm).reduce((n,p)=>n+p.value,0)>=20;if(qualified&&personInfluence(w,q.approver)<localInfluenceCost(w,command,q.approver))continue;const approved=qualified&&!localReason(w,command,q.approver);actLocal(w,{type:'local',action:approved?'approve':'reject',id:q.id},q.approver);}
 advanceAppointments(w);
 if(w.day-s.lastRecruitment>=90){s.lastRecruitment=w.day;recruitLocal(w);}
}
/** One salary per upper office; paid only from its actual public balance. */
export function payLocalOfficials(w:World,r:RealmId,pay:(key:string,amount:number,reason:string)=>number){for(const [key,s] of Object.entries(w.realm?.local?.seats??{})){const t=key.split('|')[1];if(!key.startsWith(r+'|')||!['province','prefecture'].includes(localLevel(t)!)||!s.holder||!localActive(w,t,r))continue;const room=s.holder===w.characterId?1_000_000-w.people[0].coins:1_000_000-(w.relationships?.reserves[s.holder]??1_000_000);const n=pay(key,Math.min(Math.max(0,room),localLevel(t)==='province'?12:8),localTitle(t)+'俸禄');creditPersonalCoins(w,s.holder,n);}}

/** One voluntary, affordable NPC application per realm and quarter; no invented candidates. */
function recruitLocal(w:World){const state=w.realm!.local!;for(const r of realms){const candidates=relationshipPeople.filter(p=>p.id!==w.characterId&&allegianceRealm(w,p.id)===r&&!publicOfficeReason(w,p.id)&&personInfluence(w,p.id)>=10&&!state.requests.some(q=>q.candidate===p.id&&q.status==='pending'));let best:{person:string;territory:string;score:number}|undefined;
 for(const p of candidates){const scores=new Map<string,number>();const held=Object.entries(state.seats).filter(([key])=>key.startsWith(r+'|')&&localHolder(w,key.split('|')[1],r)===p.id).map(([key])=>key.split('|')[1]);const rank=held.some(t=>localLevel(t)==='province')?3:held.some(t=>localLevel(t)==='prefecture')?2:Object.values(w.realm!.cities).some(c=>c.governor===p.id)?1:0;
 for(const t of Object.values(territoryNodes)){const targetRank=t.level==='province'?3:t.level==='prefecture'?2:t.level==='county'?1:0;if(!targetRank||targetRank!==rank+1||!localSites(w,t.id,r).length||localHolder(w,t.id,r)||!localActive(w,t.id,r))continue;const approver=localAppointer(w,t.id,r,p.id),key=targetRank+'|'+approver;let score=scores.get(key);if(score===undefined){score=localMeritFactors(w,t.id,p.id,approver,r).reduce((n,v)=>n+v.value,0);scores.set(key,score);}if(score<20||best&&score<=best.score)continue;const cmd={type:'local',action:'apply',territory:t.id,candidate:p.id} as const;if(!localReason(w,cmd,p.id))best={person:p.id,territory:t.id,score};}}
 if(best)actLocal(w,{type:'local',action:'apply',territory:best.territory,candidate:best.person},best.person);
}}
