import type {World} from './types';
import {playerRealm} from './realm';
import {armyCommander,commandArmy,installCommander} from './mobility';
import {isAlive,ageAt} from './lifeState';
import {presentAt} from './residence';
import {governingExecutives,governingAuthority} from './government';
import {attributes} from './social';
import {appointmentEvaluation} from './appointmentRules';
import {allegianceRealm,publicOfficeReason} from './officeEligibility';
import {relationshipPersonById} from '../data/relationships';
export interface MilitaryNomination {id:number;person:string;army:number;realm:'liang'|'east'|'west';created:number;due:number;status:'pending'|'accepted'|'rejected';reason:string}
export interface MilitaryNominations {nextId:number;items:MilitaryNomination[]}
export type MilitaryNominationCommand={type:'militaryNomination';action:'apply';army:number}|{type:'militaryNomination';action:'approve'|'reject';id:number};
export function nominationReason(w:World,c:MilitaryNominationCommand){if(!w.realm||!w.characterId||w.campaign?.status!=='active')return '须有效人物身份';const r=playerRealm(w);if(c.action!=='apply'){const q=w.militaryNominations?.items.find(q=>q.id===c.id);return !q||q.status!=='pending'?'自荐已结束':!governingExecutives(w,q.realm).includes(w.characterId)?'须实际执政者裁定':'';}
 const a=w.realm.armies.find(a=>a.id===c.army&&a.realm===r),id=w.characterId;return !a?'没有此军队':a.owner?'私人部曲可在统帅席位直接安排本人领军，公军才需自荐':armyCommander(w,a)||a.journey?'军队须停驻且统帅空缺':!presentAt(w,id,a.location)?'须亲自驻留军营':(ageAt(w,id)??0)<16?'须成年':commandArmy(w,id)?'已有军权，须先交接':publicOfficeReason(w,id)?publicOfficeReason(w,id):attributes(w,id).martial<12?'军事能力需达到 12，可先研习兵法':w.militaryNominations?.items.some(q=>q.status==='pending'&&q.person===id)?'已有自荐待答复':'';}
function finish(w:World,q:MilitaryNomination,approve:boolean){const a=w.realm!.armies.find(a=>a.id===q.army);if(approve&&a&&isAlive(w,q.person)&&allegianceRealm(w,q.person)===q.realm&&!armyCommander(w,a)&&!a.journey&&presentAt(w,q.person,a.location)&&!commandArmy(w,q.person)&&!publicOfficeReason(w,q.person)){installCommander(w,a,q.person);q.status='accepted';q.reason='朝廷接受自荐，实际接掌本军';}else{q.status='rejected';q.reason=approve?'军营、人物或席位已变化':'朝廷未接受自荐';}w.chronicle.push({day:w.day,person:'player',text:q.reason});w.chronicle=w.chronicle.slice(-100);}
export function actMilitaryNomination(w:World,c:MilitaryNominationCommand){const why=nominationReason(w,c);if(why)throw new Error(why);const s=w.militaryNominations??={nextId:1,items:[]};if(c.action==='apply'){s.items=s.items.filter(q=>q.status==='pending').concat(s.items.filter(q=>q.status!=='pending').slice(-60));s.items.push({id:s.nextId++,person:w.characterId!,army:c.army,realm:playerRealm(w),created:w.day,due:w.day+7,status:'pending',reason:'待朝廷答复'});}else finish(w,s.items.find(q=>q.id===c.id)!,c.action==='approve');}
export function advanceMilitaryNominations(w:World){if(!w.realm)return;for(const q of w.militaryNominations?.items??[]){if(q.status!=='pending'||w.day<q.due||governingExecutives(w,q.realm).includes(w.characterId!))continue;const a=w.realm.armies.find(a=>a.id===q.army),evaluation=appointmentEvaluation(w,q.realm,q.person,{ministry:'military',site:a?.location},governingAuthority(w,q.realm));finish(w,q,evaluation.score>=evaluation.threshold);}}
export function validMilitaryNominations(w:World){const s=w.militaryNominations;if(s===undefined)return true;return !!s&&Number.isSafeInteger(s.nextId)&&s.nextId>0&&Array.isArray(s.items)&&s.items.length<=128&&new Set(s.items.map(q=>q.id)).size===s.items.length&&s.items.every(q=>q&&Number.isSafeInteger(q.id)&&q.id>0&&q.id<s.nextId&&!!relationshipPersonById[q.person]&&['liang','east','west'].includes(q.realm)&&Number.isSafeInteger(q.army)&&q.army>0&&Number.isSafeInteger(q.created)&&q.created>=0&&q.created<=w.day&&q.due===q.created+7&&['pending','accepted','rejected'].includes(q.status)&&typeof q.reason==='string'&&q.reason.length<=200);}
