import {detainPerson} from './custody';
import {changeRelationOpinion} from './relationships';
import {governingAuthority} from './government';
import {describe,it,expect} from 'vitest';
import {newCampaignWorld,act,advance,planRoute} from './world';
import {activityQuote,mobilityReason,advanceMobility,syncArmyTravel,activities} from './mobility';
import {personResidence,presentAt,mapTravelers} from './residence';
import {parseWorld,serializeWorld,validateWorld} from './save';
import {pauseSnapshot,pauseEvents} from './pauseEvents';
import {relationshipQuote} from './relationships';
import {lifeOf} from './lifeState';
import {syncGovernance} from './realm';
import {residentsAt} from './placePeople';
import {sites} from '../data/scenario';
import {relationshipPeople} from '../data/relationships';
import {lifestyleFocuses} from '../data/lifestyles';
import {lifestyleLearning} from './lifestyle';
import {governmentOf} from './government';
import {actService,assignmentEffort,assignmentPause} from './assignments';
import type {World} from './types';
import type {ActivityKind} from './mobilityState';
const start=(id='xiao-gang')=>newCampaignWorld(id,undefined,'sandbox');
function tick(w:World){if(w.realm?.event)act(w,{type:'realm',action:'event',choice:'decline'});advance(w);validateWorld(w);}
function until(w:World,check:()=>boolean,max=150){for(let i=0;i<max&&!check();i++)tick(w);expect(check()).toBe(true);}
function finish(w:World){const a=w.mobility!.activities.at(-1)!;until(w,()=>a.phase==='ready');act(w,{type:'mobility',action:'begin',id:a.id});until(w,()=>a.phase==='decision');act(w,{type:'mobility',action:'resolve',id:a.id,choice:'measured'});expect(a.phase).toBe('done');expect(a.result.length).toBeGreaterThan(0);expect(parseWorld(serializeWorld(w))).toEqual(w);return a;}
describe('location-driven journeys',()=>{
 it('travels to an appointment, holds its target, pauses on arrival and resolves exactly once',()=>{
  const w=start(),target='xiao-yi',site=personResidence(w,target).site;
  expect(relationshipQuote(w,{type:'relationship',action:'befriend',target}).reason).toContain('同城');
  act(w,{type:'mobility',action:'plan',kind:'visit',target,site});const a=w.mobility!.activities[0];
  expect(w.people[0].journey).not.toBeNull();expect(w.mobility!.appointments[target].site).toBe(site);const before=pauseSnapshot(w);
  until(w,()=>a.phase==='ready');expect(pauseEvents(before,w).some(e=>e.kind==='mobility'&&e.activityId===a.id)).toBe(true);
  expect(personResidence(w,target).site).toBe(site);const money=w.people[0].coins;finish(w);expect(()=>act(w,{type:'mobility',action:'resolve',id:a.id,choice:'measured'})).toThrow('结束');expect(w.people[0].coins).toBeGreaterThanOrEqual(money);expect(w.mobility!.appointments[target]).toBeUndefined();
  expect(activityQuote(w,{type:'mobility',action:'plan',kind:'visit',target,site}).reason).toContain('冷却');
 });
 it('remote gifts are possible while traveling; marriage and deep meetings are not',()=>{const w=start();act(w,{type:'travel',destination:'jingkou'});expect(relationshipQuote(w,{type:'relationship',action:'gift',target:'xiao-yi'}).reason).toBe('');expect(relationshipQuote(w,{type:'relationship',action:'marry',target:'guest-liang'}).reason).not.toBe('');});
 it.each(['banquet','audience','mentor','family','succession'] as ActivityKind[])('%s has a complete playable lifecycle',kind=>{
  const w=start(kind==='succession'||kind==='family'?'xiao-yan':kind==='mentor'?'yuan-qin':'xiao-gang');
  if(kind==='mentor')act(w,{type:'lifestyle',action:'focus',focus:Object.keys(lifestyleFocuses)[0]});
  if(kind==='succession')act(w,{type:'heir',target:'xiao-gang'});
  const candidates=relationshipPeople.flatMap(p=>{const site=['family','succession'].includes(kind)?w.holdings.estate.location:personResidence(w,p.id).site;return [{type:'mobility' as const,action:'plan' as const,kind,site,target:p.id}];});
  const c=candidates.find(c=>!activityQuote(w,c).reason);expect(c,kind+' needs an eligible target').toBeDefined();act(w,c!);const a=finish(w);expect(a.result).toMatch(kind==='succession'?'治理历练':kind==='family'?'家族威望':'交往');
 });
 it('studying in person adds daily focus experience, without allowing departure mid-session',()=>{const w=start('yuan-qin');act(w,{type:'lifestyle',action:'focus',focus:Object.keys(lifestyleFocuses)[0]});const c=relationshipPeople.map(p=>({type:'mobility' as const,action:'plan' as const,kind:'mentor' as const,target:p.id,site:personResidence(w,p.id).site})).find(c=>!activityQuote(w,c).reason)!;act(w,c);const a=w.mobility!.activities[0];until(w,()=>a.phase==='ready');const before=lifestyleLearning(w).total;act(w,{type:'mobility',action:'begin',id:a.id});expect(lifestyleLearning(w).total).toBe(before+1);expect(()=>act(w,{type:'travel',destination:'tianshui'})).toThrow('事务');});
 it('personal tours and delegated tours improve the site and attribute merit to the actual visitor',()=>{for(const delegated of [false,true]){const w=start('yuwen-tai'),city=w.realm!.cities.changan;city.order=30;const merit=governmentOf(w)!.merit['yuan-qin'];act(w,{type:'mobility',action:'plan',kind:'tour',site:'changan',...(delegated?{delegate:'yuan-qin'}:{})});const a=w.mobility!.activities[0];if(delegated)until(w,()=>a.phase==='done');else finish(w);expect(city.order).toBeGreaterThan(30);if(delegated){expect(governmentOf(w)!.merit['yuan-qin']).toBeGreaterThan(merit);expect(w.people[0].journey).toBeNull();}validateWorld(w);}});
 it('training improves the garrison, while unrelated cities cannot offer training',()=>{const w=start('yuwen-tai');act(w,{type:'realm',action:'muster'});const army=w.realm!.armies[0];army.troops=400;army.morale=40;expect(activityQuote(w,{type:'mobility',action:'plan',kind:'training',site:'tianshui'}).reason).not.toBe('');act(w,{type:'mobility',action:'plan',kind:'training',site:army.location});const population=w.realm!.cities[army.location].population;finish(w);expect(army.troops).toBe(400);expect(army.morale).toBeGreaterThan(40);expect(w.realm!.cities[army.location].population).toBe(population);});
 it('NPCs travel roads to their assignment, never contribute remotely, and survive save/resume',()=>{const w=start('yuwen-tai');act(w,{type:'service',action:'begin'});act(w,{type:'service',action:'open',kind:'agriculture',site:'tianshui',officer:'yuan-qin'});const t=w.service!.tasks[0];actService(w,{type:'service',action:'plan',id:t.id,plan:'balanced'},'yuan-qin');act(w,{type:'service',action:'approve',id:t.id});tick(w);expect(personResidence(w,'yuan-qin').traveling).toBe(true);expect(assignmentPause(w,t)).toContain('到场');expect(t.progress).toBe(0);expect(residentsAt(w,sites.map(s=>s.id)).some(p=>p.id==='yuan-qin')).toBe(false);expect(mapTravelers(w).find(p=>p.id==='yuan-qin')?.journey).not.toBeNull();const copy=parseWorld(serializeWorld(w));tick(w);tick(copy);expect(copy).toEqual(w);until(w,()=>t.started);expect(presentAt(w,'yuan-qin','tianshui')).toBe(true);});
 it('on-site helpers can continue eligible work without crediting an absent officer',()=>{const w=start('dugu-xin');act(w,{type:'service',action:'begin'});act(w,{type:'service',action:'open',kind:'agriculture',site:'tianshui',officer:'dugu-xin'});const t=w.service!.tasks[0];actService(w,{type:'service',action:'approve',id:t.id},'yuwen-tai');act(w,{type:'service',action:'plan',id:t.id,plan:'balanced'});actService(w,{type:'service',action:'approve',id:t.id},'yuwen-tai');act(w,{type:'service',action:'start',id:t.id});act(w,{type:'service',action:'invite',id:t.id,person:'yuan-qin'});actService(w,{type:'service',action:'accept',id:t.id},'yuan-qin');w.mobility!.residences['yuan-qin']={site:t.site,journey:null};act(w,{type:'travel',destination:'changan'});expect(assignmentEffort(w,t).executor).toBe('yuan-qin');expect(assignmentPause(w,t)).toBe('');tick(w);expect(t.contributors['yuan-qin'].lead).toBeGreaterThan(0);expect(t.contributors['dugu-xin']).toBeUndefined();});
 it('binds the player to army movement and supply; disbanding is safe',()=>{const w=start('yuwen-tai');act(w,{type:'realm',action:'muster'});act(w,{type:'mobility',action:'command',person:'yuwen-tai'});const army=w.realm!.armies[0],food=w.people[0].food;act(w,{type:'mobility',action:'stance',stance:'guard'});act(w,{type:'realm',action:'march',site:'tianshui'});expect(()=>act(w,{type:'travel',destination:'tianshui'})).toThrow('随军');tick(w);expect(w.people[0].journey).toEqual(army.journey);expect(w.people[0].food).toBe(food);until(w,()=>!army.journey);expect(w.people[0].location).toBe('tianshui');const hp=lifeOf(w,'yuwen-tai')!.health;act(w,{type:'realm',action:'disband'});tick(w);expect(lifeOf(w,'yuwen-tai')!.health).toBe(hp);expect(w.mobility!.captivity).toBeNull();});
 it('army removal does not invent a captor; actual custody blocks action until a conserved ransom',()=>{const w=start('yuwen-tai');act(w,{type:'realm',action:'muster'});act(w,{type:'mobility',action:'command',person:'yuwen-tai'});w.realm!.war={attacker:'east',defender:'west',target:'changan',started:w.day,score:0};w.realm!.cities.changan.controller='east';w.realm!.armies=[];syncArmyTravel(w);syncGovernance(w);expect(w.mobility!.captivity).toBeNull();detainPerson(w,'yuwen-tai','east','changan','battle','battle:fixture');expect(()=>act(w,{type:'diplomacy',action:'repatriate'})).toThrow('拘押');const total=w.people[0].coins+w.realm!.treasuries.east.coins;expect(()=>act(w,{type:'mobility',action:'ransom'})).toThrow('不接受赎还');expect(w.people[0].coins+w.realm!.treasuries.east.coins).toBe(total);changeRelationOpinion(w,governingAuthority(w,'east')!,'yuwen-tai',100);expect(()=>act(w,{type:'mobility',action:'ransom'})).toThrow('不接受赎还');expect(w.people[0].coins+w.realm!.treasuries.east.coins).toBe(total);w.custody!.records['yuwen-tai'].treatment='honored';act(w,{type:'mobility',action:'ransom'});expect(w.mobility!.captivity).toBeNull();expect(w.people[0].coins+w.realm!.treasuries.east.coins).toBe(total);expect(w.people[0].location).toBe('changan');validateWorld(w);});
 it('cancels for death, illness, war and expiry and releases appointments without refund',()=>{for(const cause of ['death','illness','war','expiry']){const w=start();act(w,{type:'mobility',action:'plan',kind:'visit',site:'jiankang',target:'xiao-yan'});const a=w.mobility!.activities[0],money=w.people[0].coins;act(w,{type:'mobility',action:'begin',id:a.id});if(cause==='death')lifeOf(w,'xiao-yan')!.death={day:0,cause:'age'};if(cause==='illness')lifeOf(w,'xiao-yan')!.illness={kind:'fever',severity:3,since:0};if(cause==='expiry')w.day=a.deadline;if(cause==='war'){w.realm!.cities.jiankang.controller='east';w.realm!.war={attacker:'east',defender:'liang',target:'jiankang',started:w.day,score:0};}w.day++;advanceMobility(w);expect(a.phase).toBe('cancelled');expect(w.mobility!.appointments['xiao-yan']).toBeUndefined();expect(w.people[0].coins).toBe(money);}});
 it('rejects malformed mobility saves and upgrades old saves',()=>{const w=start();const old=structuredClone(w);delete old.mobility;expect(parseWorld(serializeWorld(old)).mobility).toBeDefined();for(const change of [(v:World)=>{v.mobility!.residences['xiao-yi'].site='nowhere';},(v:World)=>{v.mobility!.appointments['xiao-yi']={site:'jiankang',until:30};},(v:World)=>{v.mobility!.commanders.east='xiao-yan';},(v:World)=>{const route=planRoute('jiankang','jingkou')!;v.mobility!.residences['xiao-yi']={site:'jiankang',journey:{route:route.route,durations:route.durations,leg:0,elapsed:999,started:0}};}]){const v=structuredClone(w);change(v);expect(()=>serializeWorld(v)).toThrow('存档');}expect(mobilityReason(w,{type:'mobility',action:'command',person:'xiao-yan'})).not.toBe('');expect(Object.keys(activities)).toHaveLength(8);});
});
it('disbanding an NPC-led army does not cancel the player’s independent journey',()=>{const w=start('yuwen-tai');act(w,{type:'realm',action:'muster'});act(w,{type:'mobility',action:'command',person:'yuan-qin'});act(w,{type:'travel',destination:'tianshui'});const journey=structuredClone(w.people[0].journey);act(w,{type:'realm',action:'disband'});expect(w.people[0].journey).toEqual(journey);});
it('appointed commanders and held appointments cannot also accept service assignments',()=>{const w=start('yuwen-tai');act(w,{type:'realm',action:'muster'});act(w,{type:'mobility',action:'command',person:'yuan-qin'});act(w,{type:'service',action:'begin'});expect(()=>act(w,{type:'service',action:'open',kind:'agriculture',site:'tianshui',officer:'yuan-qin'})).toThrow();});

it('severe illness prevents assuming command',()=>{const w=start('yuwen-tai');act(w,{type:'realm',action:'muster'});lifeOf(w,'yuan-qin')!.illness={kind:'fever',severity:3,since:0};expect(mobilityReason(w,{type:'mobility',action:'command',person:'yuan-qin'})).toContain('重病');});
