import type {World} from './types';
import {economyHost} from './personalEconomyAdapter';
import {relationshipPersonById} from '../data/relationships';
import {relatives} from '../data/families';
import {isAlive} from './lifeState';
import {survivingRealm} from './polityLifecycle';
import type {RealmId} from './realm';
import {publicBalance,ensureFiscal,fiscalRecord} from './treasury';
export interface Obligation {id:number;source:string;from:string;to:string;original:number;remaining:number;paid:number;offset:number;next:number;instalment:number;reason:string;created:number}
export interface Obligations {nextId:number;items:Obligation[]}
export function accountWallet(w:World,key:string){if(key.startsWith('person:'))return economyHost(w).personal(key.slice(7));if(!w.realm)return;
 const r=key.startsWith('central:')?key.slice(8):key.split('|')[0];if(!['liang','east','west'].includes(r))return;
 if(!key.startsWith('central:')&&!Object.hasOwn(w.realm.fiscal?.balances??{},key))return;
 return {key,capacity:1_000_000,read:()=>publicBalance(w,key),write:(n:number)=>{if(key.startsWith('central:'))w.realm!.treasuries[r as RealmId].coins=n;else ensureFiscal(w)!.balances[key]=n;}};
}
export function transferAccount(w:World,from:string,to:string,amount:number,reason:string){const a=accountWallet(w,from),b=accountWallet(w,to);if(!a||!b||a.key===b.key||!Number.isSafeInteger(amount)||amount<0||a.read()<amount||b.read()+amount>b.capacity)throw new Error('款项来源、余额或收款容量不足');a.write(a.read()-amount);b.write(b.read()+amount);const r=(from.startsWith('person:')?to:from).replace('central:','').split('|')[0] as RealmId;if(['liang','east','west'].includes(r))fiscalRecord(w,r,from,to,amount,reason);}
/** Debt is a claim, never a second cash balance. Sources identify the original authorization. */
export function incurObligation(w:World,source:string,from:string,to:string,amount:number,reason:string){const s=w.obligations??={nextId:1,items:[]};const old=s.items.find(d=>d.source===source);if(old){if(old.from!==from||old.to!==to||old.original!==amount)throw new Error('同一债权来源不能重复记入不同款项');return;}if(!accountWallet(w,from)||!accountWallet(w,to)||from===to||!Number.isSafeInteger(amount)||amount<=0)throw new Error('无效债权');s.items.push({id:s.nextId++,source,from,to,original:amount,remaining:amount,paid:0,offset:0,next:w.day+30,instalment:50,reason,created:w.day});}
function successorAccount(w:World,key:string){if(key.startsWith('central:'))return 'central:'+survivingRealm(w,key.slice(8) as RealmId);if(key.includes('|')){const [r,...tail]=key.split('|');return survivingRealm(w,r as RealmId)+'|'+tail.join('|');}const id=key.slice(7);if(!isAlive(w,id)){const at=w.social?.lineage.findIndex(p=>p.id===id)??-1,heir=at>=0?w.social?.lineage[at+1]?.id:relatives(id,'descendants').find(p=>isAlive(w,p.id))?.id;if(heir&&relationshipPersonById[heir])return 'person:'+heir;}return key;}
export function advanceObligations(w:World){for(const d of w.obligations?.items??[]){if(!d.remaining)continue;d.from=successorAccount(w,d.from);d.to=successorAccount(w,d.to);if(d.from===d.to){d.offset+=d.remaining;d.remaining=0;continue;}if(d.next>w.day)continue;const from=accountWallet(w,d.from),to=accountWallet(w,d.to);if(!from||!to)continue;const amount=Math.min(d.remaining,d.instalment,from.read(),to.capacity-to.read());if(amount>0){transferAccount(w,d.from,d.to,amount,d.reason);d.remaining-=amount;d.paid+=amount;}d.next=w.day+30;}if(w.realm?.reparations){for(const mirror of w.realm.reparations){if(mirror.obligation===undefined)continue;const d=w.obligations?.items.find(q=>q.id===mirror.obligation);if(d){mirror.remaining=d.remaining;mirror.next=d.next;}}w.realm.reparations=w.realm.reparations.filter(d=>d.remaining>0);}}
export function validObligations(w:World){const s=w.obligations;if(s===undefined)return true;const n=(v:unknown,max=1e9)=>Number.isSafeInteger(v)&&Number(v)>=0&&Number(v)<=max;return !!s&&n(s.nextId)&&Array.isArray(s.items)&&s.items.length<=10000&&new Set(s.items.map(d=>d?.source)).size===s.items.length&&new Set(s.items.map(d=>d?.id)).size===s.items.length&&s.items.every(d=>d&&n(d.id,s.nextId-1)&&d.id>0&&typeof d.source==='string'&&d.source.length<=200&&!!accountWallet(w,d.from)&&!!accountWallet(w,d.to)&&n(d.original)&&n(d.remaining,d.original)&&n(d.paid,d.original)&&n(d.offset,d.original)&&d.paid+d.remaining+d.offset===d.original&&n(d.next,w.day+30)&&n(d.created,w.day)&&n(d.instalment,10000)&&d.instalment>0&&typeof d.reason==='string'&&d.reason.length<=200);}
