import {describe,it,expect} from 'vitest';
import {newCampaignWorld,act,advance} from './world';
import {governmentOf} from './government';
import {serviceReason,serviceTask,actService,type ServiceCommand} from './assignments';
import {isSovereign,officialDutyReason} from './officialDuties';
import {retinueQuote,advanceRetinue} from './retinue';
import {buildQuote} from './construction';
import {parseWorld,serializeWorld,validateWorld} from './save';
import {attributes,abilityBreakdown,buildingModifiers,acceptance} from './social';
import {ensureLifestyle} from './lifestyle';
import {personInfluence} from './personalInfluence';
import type {AssignmentKind} from '../data/assignments';
import type {MinistryId} from '../data/court';
const setup=(office:MinistryId='secretariat')=>{const w=newCampaignWorld('xiao-yan',undefined,'sandbox');const g=governmentOf(w)!;g.merit['xiao-gang']=50;act(w,{type:'court',action:'appoint',ministry:office,candidate:'xiao-gang'});act(w,{type:'service',action:'begin'});return w;};
function finish(w:ReturnType<typeof setup>,id:number){for(let day=0;day<180;day++){const t=serviceTask(w,id)!;if(t.phase==='closed')return t;const chief='xiao-yan';let cmd:ServiceCommand|undefined;if(['petition','approval'].includes(t.phase))cmd={type:'service',action:'approve',id};else if(t.phase==='aid')cmd={type:'service',action:'grant',id};else if(t.phase==='report')cmd={type:'service',action:'close',id};if(cmd&&!serviceReason(w,cmd,chief))actService(w,cmd,chief);if(w.realm!.event)act(w,{type:'realm',action:'event',choice:'decline'});advance(w);validateWorld(w);}throw new Error('公务未能结束');}
describe('中央职掌与公共工程',()=>{
 it('君主不再招募幕僚；旧幕职解除，不影响普通官员',()=>{const w=setup();expect(isSovereign(w)).toBe(true);expect(retinueQuote(w,{type:'retinue',action:'recruit',person:'guest-liang'}).reason).toContain('中央官职');w.retinue!.members['guest-liang']={host:'xiao-yan',post:'engineer',site:'jiankang',joined:0,arrears:0};expect(parseWorld(serializeWorld(w)).retinue!.members['guest-liang']).toBeUndefined();const money=w.people[0].coins;advanceRetinue(w);expect(w.retinue!.members['guest-liang']).toBeUndefined();expect(w.people[0].coins).toBe(money);expect(isSovereign(w,'xiao-gang')).toBe(false);});
 it.each([['marketworks','secretariat'],['granaryworks','finance'],['hostelworks','secretariat'],['greatworks','secretariat'],['recruitment','military'],['taxation','finance']] as [AssignmentKind,MinistryId][])('%s 可委派、赴任、完工、存读并发放个人考绩', (kind,office)=>{const w=setup(office),before=structuredClone(w);act(w,{type:'service',action:'open',kind,site:'jiankang',officer:'xiao-gang'});const id=w.service!.tasks.at(-1)!.id;const done=finish(w,id);expect(done.result?.success).toBe(true);expect(done.result?.effects.length).toBeGreaterThan(0);expect(governmentOf(w)!.merit['xiao-gang']).toBeGreaterThan(50);expect(personInfluence(w,'xiao-gang')).toBeGreaterThan(0);expect(parseWorld(serializeWorld(w))).toEqual(w);if(kind==='marketworks')expect(w.holdings.cities.jiankang.levels.market).toBe(1);if(kind==='granaryworks')expect(w.holdings.cities.jiankang.levels.granary).toBe(1);if(kind==='hostelworks')expect(w.holdings.cities.jiankang.levels.hostel).toBe(1);if(kind==='greatworks')expect(w.realm!.cities.jiankang.households).toBeGreaterThan(before.realm!.cities.jiankang.households);if(kind==='recruitment')expect(w.realm!.armies.find(a=>a.realm==='liang')?.troops).toBeGreaterThan(0);if(kind==='taxation')expect(done.result!.effects.some(e=>e.includes('追征税款'))).toBe(true);});
 it('错误职掌、重复营建、卸任、跨国城市均受到规则限制',()=>{const w=setup('finance');expect(officialDutyReason(w,'xiao-gang','recruitment')).not.toBe('');expect(serviceReason(w,{type:'service',action:'open',kind:'marketworks',site:'changan',officer:'xiao-gang'})).toContain('本国');act(w,{type:'service',action:'open',kind:'marketworks',site:'jiankang',officer:'xiao-gang'});expect(buildQuote(w,{type:'build',scope:'city',site:'jiankang',building:'granary'}).reason).toContain('中央营建');governmentOf(w)!.court!.ministries.finance=null;const t=w.service!.tasks.at(-1)!;expect(serviceReason(w,{type:'service',action:'start',id:t.id},t.officer)).not.toBe('');});
 it('中央官员可自行立项，仍须批款；较高预算的大型工程可存读',()=>{const w=newCampaignWorld('xiao-gang',undefined,'sandbox');governmentOf(w)!.court!.ministries.secretariat='xiao-gang';act(w,{type:'service',action:'begin'});act(w,{type:'service',action:'open',kind:'greatworks',site:'jiankang',officer:'xiao-gang'});const t=w.service!.tasks.at(-1)!;expect(t.phase).toBe('proposal');act(w,{type:'service',action:'plan',id:t.id,plan:'urgent'});expect(serviceReason(w,{type:'service',action:'approve',id:t.id})).toContain('执政');actService(w,{type:'service',action:'approve',id:t.id},'xiao-yan');expect(t.funds.coins).toBe(252);expect(parseWorld(serializeWorld(w))).toEqual(w);});
});
describe('人物能力与积累',()=>{
 it('生活重心、已学技能与研习影响管理能力和真实工程造价',()=>{const w=newCampaignWorld('xiao-gang');const base=attributes(w).stewardship,before=buildingModifiers(w).costRate;act(w,{type:'lifestyle',action:'focus',focus:'architecture'});act(w,{type:'lifestyle',action:'unlock',perk:'surveying'});w.day=100;ensureLifestyle(w).xp.stewardship=360;expect(attributes(w).stewardship).toBe(base+4);expect(buildingModifiers(w).costRate).toBeLessThan(before);expect(abilityBreakdown(w).stewardship.parts.some(p=>p.label==='长期研习')).toBe(true);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('外交生活重心改变交涉接受度，重病扣减能力',()=>{const w=newCampaignWorld('xiao-gang'),before=acceptance(w,'xiao-yan').reduce((n,p)=>n+p.value,0);act(w,{type:'lifestyle',action:'focus',focus:'etiquette'});expect(acceptance(w,'xiao-yan').reduce((n,p)=>n+p.value,0)).toBeGreaterThan(before);const base=attributes(w).martial;w.life!.people['xiao-gang'].illness={kind:'fever',severity:3,since:w.day};expect(attributes(w).martial).toBe(base-6);});
 it('影响力按人物积累、交接不继承；旧档迁移和篡改验证',()=>{const w=setup();w.realm!.influence=87;w.realm!.personalInfluence!['xiao-gang']=21;act(w,{type:'heir',target:'xiao-gang'});act(w,{type:'handover'});expect(personInfluence(w,'xiao-yan')).toBe(87);expect(personInfluence(w,'xiao-gang')).toBe(21);expect(parseWorld(serializeWorld(w))).toEqual(w);delete w.realm!.personalInfluence;const restored=parseWorld(serializeWorld(w));expect(personInfluence(restored,'xiao-gang')).toBe(21);restored.realm!.personalInfluence!['xiao-yan']=-1;expect(()=>serializeWorld(restored)).toThrow('存档');});
});
