import {armyCommander,commandArmy} from './mobility';
import {loadingDays} from './roadCapacity';
import {serviceAuthority,serviceException} from './serviceMandates';
import {localTitle} from './localAdministration';
import type {World,Journey} from './types';
import {siteById} from '../data/scenario';
import {relationshipPersonById} from '../data/relationships';
import {assignmentTemplates,assignmentPhases} from '../data/assignments';
import {assignmentPause} from './assignments';
import {dutyPause,dutyPhaseNames,chiefOfDuty} from './duties';
import {activities} from './mobility';
import {governmentOf,governmentTaskPause,governingExecutives} from './government';
import {courtOf,foundingPause} from './court';
import {playerRealm,siegeRequirement} from './realm';
import {diplomacyActions} from './diplomacy';
import {cityBuildings,estateBuildings} from './construction';
export type OngoingKind='travel'|'activity'|'service'|'petition'|'diplomacy'|'construction'|'reform'|'scheme'|'military'|'retinue';
export type OngoingTarget={page:'territory';territory:string}|{page:'person';person:string;tab?:'economy'}|{page:'service';id?:number}|{page:'duties'}|{page:'city';site:string;tab:'travel'|'build'|'military'}|{page:'estate'}|{page:'diplomacy';realm:ReturnType<typeof playerRealm>}|{page:'court'|'government'|'politics'|'retinue'|'treasury'|'audit'};
export interface OngoingItem {id:string;kind:OngoingKind;title:string;started:number;progress:number|null;days:number|null;clock:'remaining'|'deadline'|'estimate'|'waiting';status:string;target:OngoingTarget}
const ratio=(done:number,total:number)=>total>0?Math.max(0,Math.min(1,done/total)):null;
const name=(id:string)=>relationshipPersonById[id]?.name??id;
function journeyProgress(j:Journey){const total=j.durations.reduce((n,d)=>n+d,0),done=j.durations.slice(0,j.leg).reduce((n,d)=>n+d,0)+j.elapsed;return {progress:ratio(done,total),days:Math.max(0,total-done)};}
/** Read-only projection of actual world state; no extra task timers or saved copies. */
export function ongoingItems(w:World):OngoingItem[]{
 const items:OngoingItem[]=[],actor=w.characterId??'player',r=w.realm?playerRealm(w):null,chief=r?governingExecutives(w,r).includes(actor):false;
 const add=(item:OngoingItem)=>items.push(item);
 for(const q of w.militaryCampaigns?.items??[])if(q.status==='active'&&(q.commander===actor||q.issuer===actor))add({id:'campaign:'+q.id,kind:'military',title:siteById[q.target].name+'战役',started:q.started,progress:q.goal==='defend'?ratio(q.held,30):null,days:Math.max(0,q.deadline-w.day),clock:'deadline',status:q.reason||'执行委任',target:{page:'city',site:q.target,tab:'military'}});
 for(const siege of w.realm?.sieges??[]){const war=w.realm!.wars?.find(v=>v.id===siege.war);if(!war||r!==war.attacker&&r!==war.defender)continue;const army=w.realm!.armies.find(a=>a.location===siege.site&&!a.journey&&a.realm===r),required=army?siegeRequirement(w,army):siteById[siege.site].capital?40:20;add({id:'siege:'+siege.war+':'+siege.site,kind:'military',title:siteById[siege.site].name+'围城',started:war.started,progress:ratio(siege.progress,required),days:null,clock:'estimate',status:`进度 ${siege.progress}/${required}${siege.last<w.day?' · 围军已撤，工事消退':army?.supply===0?' · 缺粮停滞':''}`,target:{page:'city',site:siege.site,tab:'military'}});}
 for(const t of w.commerce?.contracts??[])if(t.status==='moving'&&w.enterprises?.items.find(e=>e.id===t.enterprise)?.owner===actor)add({id:'trade:'+t.id,kind:'service',title:siteById[t.to].name+'商旅交货',started:t.journey.started,progress:journeyProgress(t.journey).progress,days:Math.max(0,t.deadline-w.day),clock:'deadline',status:'在途 '+t.remaining+' · 实收 '+t.arrived,target:{page:'person',person:actor,tab:'economy'}});
 for(const e of w.enterprises?.items??[])if(e.owner===actor&&e.order)add({id:'enterprise:'+e.id,kind:'service',title:siteById[e.site].name+'承包',started:e.order.started,progress:ratio(e.order.progress,e.order.required),days:Math.max(0,e.order.deadline-w.day),clock:'deadline',status:'履约 '+e.order.progress+'/'+e.order.required+' 日',target:{page:'person',person:actor,tab:'economy'}});
 const timed=(id:string,kind:OngoingKind,title:string,started:number,due:number,target:OngoingTarget,status='进行中')=>add({id,kind,title,started,progress:ratio(w.day-started,due-started),days:Math.max(0,due-w.day),clock:'remaining',status,target});
 for(const a of w.realm?.armies??[])if(a.realm===r){const recruit=a.regiments?.filter(u=>(u.readyDay??0)>w.day).sort((x,y)=>(y.readyDay??0)-(x.readyDay??0))[0],due=Math.max(a.trainingUntil??0,recruit?.readyDay??0),started=due===(a.trainingUntil??0)?a.trainingStarted??w.day:recruit?.trainingStarted??w.day;if(due>w.day)timed('training:'+a.id,'military','第 '+a.id+' 军新兵集训',started,due,{page:'city',site:a.location,tab:'military'});}
 for(const t of w.realm?.population?.transfers??[]){if(t.realm!==r||t.status!=='traveling'||t.serviceTask&&w.service?.tasks.some(a=>a.id===t.serviceTask&&a.phase!=='closed'))continue;const total=t.durations.reduce((n,d)=>n+d,0),done=t.durations.slice(0,t.leg).reduce((n,d)=>n+d,0)+t.elapsed,blocked=w.realm!.cities[t.route[t.leg+1]].controller!==r||w.realm!.cities[t.to].controller!==r;add({id:'population:'+t.id,kind:t.kind==='raid'?'military':'travel',title:(t.kind==='grain'?'转运公粮':t.kind==='demobilized'?'退伍返乡':'迁送人口')+' · '+siteById[t.to].name,started:t.created,progress:ratio(done,total),days:blocked?null:total-done+t.durations.slice(t.leg).reduce((n,_,i)=>n+loadingDays(t.route[t.leg+i],t.route[t.leg+i+1],t.sent-(i===0?(t.loaded??0):0)),0),clock:blocked?'waiting':'estimate',status:blocked?'道路受阻':t.elapsed===0&&(t.loaded??0)<t.sent?'等待道路运力':t.returning?'返还中':'在途',target:{page:'city',site:t.from,tab:'military'}});}
 for(const p of w.economy?.programmes??[])if(p.actor===actor&&p.status==='active')add({id:'economy-activity:'+p.id,kind:'activity',title:p.kind==='study'?'延师研习':'私人宴请',started:p.started,progress:null,days:Math.max(0,p.due-w.day),clock:'estimate',status:'驻留办理，公务出行顺延',target:{page:'person',person:actor,tab:'economy'}});
 for(const q of w.economy?.investigations??[])if((q.commissioner===actor||q.inspector===actor)&&q.phase!=='closed')add({id:'economy-case:'+q.id,kind:'service',title:'公库查核',started:q.started,progress:null,days:q.phase==='report'?null:Math.max(0,q.due-w.day),clock:q.phase==='report'?'waiting':'estimate',status:q.phase==='report'?'待裁决':'赴任与查核',target:{page:'audit'}});
 const active=w.mobility?.activities.filter(a=>!['done','cancelled'].includes(a.phase)&&(a.actor===actor||a.delegate===actor))??[];
 const ledArmy=commandArmy(w,actor);
 const journey=ledArmy?.journey??w.people[0].journey;
 const linked=active.find(a=>!a.delegate&&a.phase==='travel'&&journey?.route.at(-1)===a.site);
 if(journey&&!linked&&!w.diplomacy?.missions.some(m=>m.envoy===actor))add({id:ledArmy?'army:'+r+':'+journey.started:'travel:'+journey.started+':'+journey.route.join('-'),kind:ledArmy?'military':'travel',title:(ledArmy?'随军前往':'前往')+siteById[journey.route.at(-1)!].name,started:journey.started,...journeyProgress(journey),clock:'remaining',status:'出行中',target:{page:'city',site:journey.route.at(-1)!,tab:'travel'}});
 for(const a of active){const traveling=a.delegate?w.mobility?.residences[a.delegate]?.journey:linked?.id===a.id?journey:null;const working=a.phase==='working'&&a.due!==null;add({id:'activity:'+a.id,kind:'activity',title:activities[a.kind].name+' · '+siteById[a.site].name,started:a.created,progress:traveling?journeyProgress(traveling).progress:working?ratio(w.day-a.started!,a.due!-a.started!):a.phase==='decision'?1:null,days:traveling?journeyProgress(traveling).days:working?Math.max(0,a.due!-w.day):Math.max(0,a.deadline-w.day),clock:traveling||working?'remaining':'deadline',status:({travel:'赴约途中',ready:'待开始',working:'驻留办理',decision:'待定夺'})[a.phase as 'travel'|'ready'|'working'|'decision'],target:{page:'person',person:actor}});}
 for(const t of w.service?.tasks??[]){if(t.phase==='closed'||t.officer!==actor&&t.helper!==actor&&t.invitation?.person!==actor&&!(r===t.realm&&serviceAuthority(w,t,actor)&&serviceException(w,t)))continue;add({id:'service:'+t.id,kind:'service',title:siteById[t.site].name+' · '+assignmentTemplates[t.kind].name,started:t.created,progress:ratio(t.progress,t.required),days:Math.max(0,t.deadline-w.day),clock:'deadline',status:assignmentPause(w,t)||assignmentPhases[t.phase],target:{page:'service',id:t.id}});}
 for(const q of w.realm?.fiscal?.requests??[])if(q.status==='pending'&&(q.actor===actor||q.approver===actor))add({id:'fiscal:'+q.id,kind:'petition',title:siteById[q.site].name+'拨款 '+q.amount+' 钱',started:q.created,progress:null,days:Math.max(0,q.created+60-w.day),clock:'deadline',status:q.approver===actor?'待批复':'候批',target:{page:'treasury'}});
 const duty=w.duties?.task;if(duty&&duty.phase!=='closed'&&(duty.officer===actor||chiefOfDuty(w)===actor))add({id:'duty:'+duty.created,kind:'service',title:'天水粮务',started:duty.created,progress:ratio(duty.progress,duty.required),days:Math.max(0,duty.deadline-w.day),clock:'deadline',status:dutyPause(w)||dutyPhaseNames[duty.phase],target:{page:'duties'}});
 if(r){const court=courtOf(w,r),g=governmentOf(w,r),petition=court?.petition;
  if(petition&&(petition.sponsor===actor||chief))add({id:'petition:'+petition.sponsor+':'+petition.due,kind:'petition',title:'集团奏议',started:petition.due,progress:null,days:Math.max(0,petition.due-w.day),clock:'deadline',status:chief?'待批复':'候旨',target:{page:'court'}});
  const proposal=w.service?.councils[r].proposal;if(proposal&&(proposal.actor===actor||chief))add({id:'council:'+proposal.actor+':'+proposal.day,kind:'petition',title:'本季议事奏请',started:proposal.day,progress:null,days:null,clock:'waiting',status:'待批复',target:{page:'service'}});
  const task=g?.task;if(task&&(task.sponsor===actor||chief))add({id:'reform:'+task.started+':'+task.target,kind:'reform',title:task.kind==='law'?'推行新法':task.kind==='succession'?'继位议程':'政体改革',started:task.started,progress:ratio(task.progress,task.required),days:governmentTaskPause(w,r)?null:Math.max(0,task.required-task.progress),clock:'estimate',status:governmentTaskPause(w,r)||'推行中',target:{page:'government'}});
  const founding=court?.founding;if(founding&&(founding.sponsor===actor||chief))add({id:'founding:'+founding.started,kind:'reform',title:'建朝 · '+founding.name,started:founding.started,progress:ratio(founding.progress,founding.required),days:foundingPause(w,r)?null:Math.max(0,founding.required-founding.progress),clock:'estimate',status:foundingPause(w,r)||'筹备中',target:{page:'court'}});
  for(const q of w.realm!.local?.requests??[])if(q.status==='pending'&&(q.actor===actor||q.approver===actor))add({id:'local:'+q.id,kind:'petition',title:localTitle(q.territory)+'奏请',started:q.created,progress:null,days:Math.max(0,60-w.day+q.created),clock:'deadline',status:'等待批复',target:{page:'territory',territory:q.territory}});
  for(const o of w.realm!.offices)if(o.candidate===actor||chief&&w.realm!.cities[o.site].owner===r)add({id:'office:'+o.site+':'+o.candidate,kind:'petition',title:localTitle(o.territory??'city:'+o.site)+'任命',started:0,progress:null,days:o.due-w.day<=1?null:o.due-w.day,clock:o.due-w.day<=1?'waiting':'remaining',status:o.due-w.day<=1?'等待本人赴任':'文书送达中',target:{page:'territory',territory:o.territory??'city:'+o.site}});
  for(const m of w.diplomacy?.missions??[])if(m.envoy===actor||m.actor===actor||chief&&(m.from===r||m.to===r)){if(m.status==='returning')timed('envoy:'+m.id,'diplomacy',diplomacyActions[m.action],m.returnStarted??m.sent,m.due,{page:'diplomacy',realm:m.from===r?m.to:m.from},'使者返程');else if(m.status==='traveling')timed('envoy:'+m.id,'diplomacy',diplomacyActions[m.action],m.sent,m.due,{page:'diplomacy',realm:m.from===r?m.to:m.from},m.arrived===undefined?'使团在途':'驻都交涉');else add({id:'envoy:'+m.id,kind:'diplomacy',title:diplomacyActions[m.action],started:m.sent,progress:1,days:Math.max(0,m.expires-w.day),clock:'deadline',status:'等待接见',target:{page:'diplomacy',realm:m.from===r?m.to:m.from}});}
  for(const army of w.realm!.armies)if(army.realm===r&&army.journey&&armyCommander(w,army)!==actor&&(chief||w.realm!.mandate))add({id:'army:'+(army.id??r),kind:'military',title:'行军 · '+siteById[army.journey.route.at(-1)!].name,started:army.journey.started,...journeyProgress(army.journey),clock:'remaining',status:army.withdrawalUntil?'依约撤离':'行军中',target:{page:'city',site:army.location,tab:'military'}});
 }
 for(const [site,h] of Object.entries(w.holdings.cities)){const p=h.project;if(p&&w.holdings.governedCities.includes(site))timed('city:'+site+':'+p.started,'construction',siteById[site].name+' · '+cityBuildings[p.building as keyof typeof cityBuildings].name,p.started,p.due,{page:'city',site,tab:'build'});}
 const p=w.holdings.estate.project;if(p)timed('estate:'+p.started,'construction',estateBuildings[p.building as keyof typeof estateBuildings].name,p.started,p.due,{page:'estate'});
 for(const [key,s] of [['social',w.social?.scheme],['relationship',w.relationships?.scheme]] as const)if(s)timed('scheme:'+key+':'+s.started+':'+s.target,'scheme',('kind'in s&&s.kind==='control'?'挟制':'交好')+' · '+name(s.target),s.started,s.due,{page:'person',person:s.target});
 for(const [id,m] of Object.entries(w.retinue?.members??{})){const j=w.mobility?.residences[id]?.journey;if(m.host===actor&&j)add({id:'retinue:'+id+':'+j.started,kind:'retinue',title:name(id)+'赴任',started:j.started,...journeyProgress(j),clock:'remaining',status:'赴任途中',target:{page:'retinue'}});}
 return items.sort((a,b)=>a.started-b.started||a.id.localeCompare(b.id));
}
