import {roads} from '../data/scenario';
import {die} from './life';
import {describe,it,expect} from 'vitest';
import {newCampaignWorld,act,advance} from './world';
import type {World} from './types';
import {ensureArmyOrganization,payArmy} from './armyOrganization';
import {powerReason,powerSupport,powerSummary,applyPowerArrangement,actPower,advancePowerPolitics} from './powerPolitics';
import {pactReason,pactQuote,actPact,advancePacts} from './allegiancePacts';
import {actCivilWar,civilWar,settleCivilWar,armyControls,armiesHostile,civilResponseReason,warArmySide,civilCityCapture} from './civilWars';
import {actPolity,polityReason,advanceSeparations} from './politySeparation';
import {worldRealms} from './polityRuntime';
import {capital} from './realm';
import {allegianceRealm} from './officeEligibility';
import {governingAuthority,governmentOf} from './government';
import {fiscalPath,ensureFiscal,fiscalSnapshot,reconcileFiscal} from './treasury';
import {parseWorld,serializeWorld,validateWorld} from './save';
import {validGovernments} from './governmentSave';
import {validRealm} from './realmSave';
import {validFiscal} from './treasurySave';
import {validDiplomacy} from './diplomacySave';
import {validRelationships} from './relationshipSave';
import {validLocalAdministration} from './localAdministrationSave';
import {nextMonthStart} from './calendar';
import {diplomaticPair} from './diplomacy';
import {setLocalHolder,countyTerritory} from './localAdministration';
import {changeRelationOpinion} from './relationships';
import {awardInfluence} from './personalInfluence';
import {ensureWars} from './wars';
import {realmClans} from './clans';

const start=(id='xiao-yi')=>newCampaignWorld(id,undefined,'sandbox');
function army(w:World,site=w.people[0].location,realm:import('./realm').RealmId='liang',leader=w.characterId!){const a={realm,location:site,troops:400,morale:80,supply:120,journey:null,siege:0};w.realm!.armies.push(a);ensureArmyOrganization(w);const actual=w.realm!.armies.at(-1)!;w.mobility!.armyCommanders??={};w.mobility!.armyCommanders[actual.id!]=leader;w.mobility!.residences[leader]={site,journey:null};return actual;}
function revolt(){const w=start(),site=w.people[0].location,c=w.realm!.cities[site];setLocalHolder(w,countyTerritory(site),'liang',w.characterId!);c.grain=300;w.realm!.influence=400;w.people[0].coins=500;const source=fiscalPath(w,site)[0];ensureFiscal(w)!.balances[source]=300;const a=army(w);a.payer=source;return {w,site,source,a};}
function saved(w:World){expect({realm:validRealm(w),government:validGovernments(w),fiscal:validFiscal(w),diplomacy:validDiplomacy(w),relationships:validRelationships(w),local:validLocalAdministration(w)}).toEqual({realm:true,government:true,fiscal:true,diplomacy:true,relationships:true,local:true});expect(parseWorld(serializeWorld(w))).toEqual(w);}

describe('political arrangements and actual camps',()=>{
 it('changes the executive while preserving emperor, money, troops, debt and treaties',()=>{const w=start(),a=army(w),r='liang',g=governmentOf(w,r)!;a.arrears=80;const money=structuredClone(w.realm!.treasuries),id=g.regimeId,pair=diplomaticPair(w,r,'east')!;pair.treaties.push({kind:'alliance',from:r,to:'east',actor:null,since:w.day,until:w.day+720});applyPowerArrangement(w,r,{goal:'executive',sponsor:'xiao-yi',beneficiary:'xiao-yan',executive:'xiao-yi',name:''});expect(g.ruler).toBe('xiao-yan');expect(g.executives).toEqual(['xiao-yi']);expect(g.regimeId).toBe(id);expect(w.realm!.treasuries).toEqual(money);expect(a.troops).toBe(400);expect(a.arrears).toBe(80);expect(pair.treaties).toHaveLength(1);saved(w);});
 it('allows a stable court to arrange distinct sponsor, young emperor and executive',()=>{const w=start('yuwen-hu'),g=governmentOf(w,'west')!;army(w,'changan','west','yuwen-hu');w.realm!.influence=100;g.support=90;g.legitimacy=90;const c={type:'power',action:'propose',goal:'dynasty',beneficiary:'yuwen-jue',executive:'yuwen-hu',name:'北周'} as const;expect(powerReason(w,c)).toBe('');actPower(w,c);applyPowerArrangement(w,'west',w.politics!.proposals.west!);expect(g.ruler).toBe('yuwen-jue');expect(g.executives).toEqual(['yuwen-hu']);expect(g.ruler).not.toBe(g.executives[0]);saved(w);});
 it('does not count a disloyal institutional army as political military support',()=>{const w=start(),a=army(w);for(const u of a.regiments!){u.loyalTo='xiao-yi';u.commanderLoyalty=20;u.institution=90;}const p={goal:'executive',sponsor:'xiao-yi',beneficiary:'xiao-yan',executive:'xiao-yi',name:''} as const;expect(powerSupport(w,'liang',p).find(v=>v.id==='xiao-yi')!.troops).toBe(0);expect(powerSummary(w,'liang',p).armies).not.toContain(a.id);});
 it('charges each pledge once and rejects stale political candidates',()=>{const {w}=revolt();actPower(w,{type:'power',action:'propose',goal:'executive',beneficiary:'xiao-yan',executive:'xiao-yi'});const cash=w.realm!.influence;expect(powerReason(w,{type:'power',action:'present'})).toContain('30');expect(powerReason(w,{type:'power',action:'pledge',person:'xiao-yan',promise:'command'})).not.toBe('');expect(w.realm!.influence).toBe(cash);w.life!.people['xiao-yi'].death={day:w.day,cause:'illness'};advancePowerPolitics(w);expect(w.politics!.proposals.liang).toBeUndefined();});
 it('starts a political civil war alongside an existing foreign war and retains it after executive victory',()=>{const {w,a}=revolt();act(w,{type:'civilWar',action:'rise',name:'军政',arrangement:{goal:'executive',sponsor:'xiao-yi',beneficiary:'xiao-yan',executive:'xiao-yi',name:''}});const internal=civilWar(w,'liang')!,foreign={id:w.realm!.nextWarId!++,attacker:'liang' as const,defender:'east' as const,target:'luoyang',started:w.day,score:0};w.realm!.wars!.push(foreign);w.realm!.sieges=[{war:internal.id!,side:'attack',site:'jiankang',progress:1,last:w.day},{war:foreign.id,side:'attack',site:'luoyang',progress:1,last:w.day}];const regime=governmentOf(w,'liang')!.regimeId;settleCivilWar(w,internal,'demand','rebel');expect(governmentOf(w,'liang')!.ruler).toBe('xiao-yan');expect(governmentOf(w,'liang')!.regimeId).toBe(regime);expect(w.realm!.wars).toEqual([foreign]);expect(w.realm!.sieges).toHaveLength(1);expect(w.realm!.sieges![0].war).toBe(foreign.id);expect(a.troops).toBe(400);saved(w);});
 it('distinguishes native camps and a foreign supporter without granting hostile local supplies',()=>{const {w,a,site}=revolt();actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁'});const v=civilWar(w,'liang')!;v.allies={east:'attack'};const loyal=army(w,'jiankang','liang','xiao-yan'),ally=army(w,'ye','east','gao-yang');expect(warArmySide(w,v,a)).toBe('attack');expect(warArmySide(w,v,loyal)).toBe('defend');expect(warArmySide(w,v,ally)).toBe('attack');expect(armiesHostile(w,ally,loyal)).toBe(true);expect(armiesHostile(w,ally,a)).toBe(false);expect(armyControls(w,loyal,site)).toBe(false);expect(armyControls(w,ally,site)).toBe(false);saved(w);});
 it('taking the emperor creates custody control while outside provinces continue resisting',()=>{const {w,a}=revolt();actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁'});const v=civilWar(w,'liang')!;a.location='jiankang';w.mobility!.residences['xiao-yan']={site:'jiankang',journey:null};civilCityCapture(w,v,'jiankang','attack',a);expect(w.custody!.records['xiao-yan']).toMatchObject({war:v.id,side:'attack'});expect(governmentOf(w,'liang')!.ruler).toBe('xiao-yan');expect(governingAuthority(w,'liang')).toBe('xiao-yi');expect(v.civil!.cities).not.toContain('jingkou');expect(w.realm!.cities.jingkou.owner).toBe('liang');saved(w);});
 it('rescue supply conserves actual grain and passive response consumes no treasury',()=>{const {w,a,site}=revolt();actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁'});const v=civilWar(w,'liang')!,before=w.realm!.cities[site].grain+a.supply;actCivilWar(w,{type:'civilWar',action:'respond',war:v.id!,choice:'supply',army:a.id});expect(w.realm!.cities[site].grain+a.supply).toBe(before);const money=structuredClone(w.realm!.treasuries);actCivilWar(w,{type:'civilWar',action:'respond',war:v.id!,choice:'wait'});expect(w.realm!.treasuries).toEqual(money);a.location='jiankang';expect(civilResponseReason(w,{type:'civilWar',action:'respond',war:v.id!,choice:'troops',army:a.id})).toContain('已在');saved(w);});
});

describe('conditional defection and limited runtime polities',()=>{
 it('makes every preview pure and a rejected request leaves assets unchanged',()=>{const {w,a}=revolt(),c={type:'pact',action:'request',realm:'east',army:a.id,terms:'personal'} as const,before=structuredClone(w);pactReason(w,c);pactQuote(w,{person:w.characterId!,from:'liang',to:'east',army:a.id!,terms:'personal'});polityReason(w,{type:'polity',action:'partition',name:'新梁'});expect(w).toEqual(before);actPact(w,c);const armies=structuredClone(w.realm!.armies);actPact(w,{type:'pact',action:'answer',id:1,accept:false},'gao-huan');expect(w.realm!.armies).toEqual(armies);expect(allegianceRealm(w,w.characterId!)).toBe('liang');saved(w);});
 it('personal reception retains soldiers, provinces and followers in the old realm without starting war',()=>{const {w,a,site}=revolt();w.relationships!.oaths['xiao-gang']={lord:'xiao-yi',since:w.day,loyalty:80};actPact(w,{type:'pact',action:'request',realm:'east',terms:'personal'});actPact(w,{type:'pact',action:'answer',id:1,accept:true},'gao-huan');expect(allegianceRealm(w,'xiao-yi')).toBe('east');expect(allegianceRealm(w,'xiao-gang')).toBe('liang');expect(w.realm!.armies[0].realm).toBe('liang');expect(w.realm!.armies[0].troops).toBe(a.troops);expect(w.realm!.cities[site].owner).toBe('liang');expect(w.realm!.wars??[]).toHaveLength(0);saved(w);});
 it('splits actual following regiments and supplies, leaves old wages owed and starts a protection war',()=>{const {w,a,site}=revolt();const first=a.regiments![0];first.troops=200;first.loyalTo='xiao-yi';first.commanderLoyalty=90;first.institution=30;a.regiments!.push({...first,id:a.id+':2',troops:200,loyalTo:'xiao-yan',commanderLoyalty:90,institution:80});a.arrears=80;const central=w.realm!.treasuries.east.coins;actPact(w,{type:'pact',action:'request',realm:'east',army:a.id,terms:'retain'});actPact(w,{type:'pact',action:'answer',id:1,accept:true},'gao-huan');expect(w.realm!.armies.map(a=>a.troops).reduce((n,v)=>n+v,0)).toBe(400);expect(w.realm!.armies.reduce((n,a)=>n+a.supply,0)).toBe(120);expect(w.realm!.armyDebts!.reduce((n,d)=>n+d.coins,0)+w.realm!.armies.reduce((n,a)=>n+(a.arrears??0),0)).toBe(80);expect(w.realm!.treasuries.east.coins).toBe(central-100);expect(w.realm!.cities[site].owner).toBe('liang');expect(w.realm!.wars![0]).toMatchObject({attacker:'east',defender:'liang',goal:'defection',target:site});saved(w);});
 it('rejects a stale accepted pact atomically when an actor starts new work or funds disappear',()=>{const {w}=revolt();actPact(w,{type:'pact',action:'request',realm:'east',terms:'personal'});w.people[0].journey={route:['jiangling','xiangyang'],durations:[10],leg:0,elapsed:0,started:w.day};const before=structuredClone(w);expect(()=>actPact(w,{type:'pact',action:'answer',id:1,accept:true},'gao-huan')).toThrow();expect(w).toEqual(before);});
 it('checks ongoing promises once per month and preserves real regiments when reforming',()=>{const {w,a}=revolt();a.owner='xiao-yi';actPact(w,{type:'pact',action:'request',realm:'east',army:a.id,terms:'reform'});actPact(w,{type:'pact',action:'answer',id:1,accept:true},'gao-huan');const before=structuredClone(w.realm!.armies[0].regiments);w.day=nextMonthStart(100,w.scriptId);changeRelationOpinion(w,'xiao-yi','gao-huan',200);advancePacts(w);expect(w.realm!.armies[0].owner).toBeUndefined();expect(w.realm!.armies[0].regiments!.map(u=>u.id)).toEqual(before!.map(u=>u.id));expect(w.realm!.armies[0].troops).toBe(400);saved(w);});
 it('partitions only responding cities and soldiers without minting central cash or carrying silent followers',()=>{const {w,a,site}=revolt();w.relationships!.oaths['xiao-gang']={lord:'xiao-yi',since:w.day,loyalty:80};actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁'});w.day=180;const money=Object.values(w.realm!.treasuries).reduce((n,t)=>n+t.coins,0),local=Object.values(w.realm!.fiscal!.balances).reduce((n,t)=>n+t,0),snap=fiscalSnapshot(w);actPolity(w,{type:'polity',action:'partition',name:'后梁'});saved(w);actPolity(w,{type:'polity',action:'partition-answer',accept:true},'xiao-yan');reconcileFiscal(w,snap,'割据结算');expect(worldRealms(w)).toContain('realm-1');expect(capital('realm-1',w)).toBe(site);expect(allegianceRealm(w,'xiao-yi')).toBe('realm-1');expect(allegianceRealm(w,'xiao-gang')).toBe('liang');expect(Object.values(w.realm!.treasuries).reduce((n,t)=>n+t.coins,0)).toBe(money);expect(Object.values(w.realm!.fiscal!.balances).reduce((n,t)=>n+t,0)).toBe(local);expect(w.realm!.treasuries['realm-1'].coins).toBe(0);expect(w.realm!.cities.jiankang.owner).toBe('liang');expect(w.realm!.armies[0].troops).toBe(a.troops);expect(w.realm!.armies[0].realm).toBe('realm-1');saved(w);});
 it('rechecks partition conditions at final acceptance and relocates court only after physical arrival',()=>{const {w,a}=revolt();actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁'});w.day=180;actPolity(w,{type:'polity',action:'partition',name:'后梁'});w.realm!.armies.find(v=>v.id===a.id)!.troops=100;const before=structuredClone(w);expect(()=>actPolity(w,{type:'polity',action:'partition-answer',accept:true},'xiao-yan')).toThrow();expect(w).toEqual(before);const chief=start('xiao-yan');expect(polityReason(chief,{type:'polity',action:'relocate',site:'jingkou'})).toContain('抵达');chief.people[0].location='jingkou';const cash=chief.realm!.treasuries.liang.coins;actPolity(chief,{type:'polity',action:'relocate',site:'jingkou'});expect(capital('liang',chief)).toBe('jingkou');expect(chief.realm!.treasuries.liang.coins).toBe(cash-100);saved(chief);});
 it('lets a runtime polity pay real military wages and rejects forged polity identities',()=>{const {w}=revolt();actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁'});w.day=180;actPolity(w,{type:'polity',action:'partition',name:'后梁'});actPolity(w,{type:'polity',action:'partition-answer',accept:true},'xiao-yan');const a=w.realm!.armies[0];a.payer='central:realm-1';w.realm!.treasuries['realm-1'].coins=100;const cash=w.realm!.treasuries['realm-1'].coins;payArmy(w,a,40);expect(w.realm!.treasuries['realm-1'].coins).toBeLessThan(cash);saved(w);const bad=structuredClone(w);bad.realm!.identities!['realm-1']!.origin='invented' as never;expect(()=>validateWorld(bad)).toThrow();});
 it('uses the same guarded request for an NPC commander under political pressure',()=>{const w=start('xiao-yan'),a=army(w,'ye','east','gao-yang');a.owner='gao-yang';awardInfluence(w,'gao-yang',40);changeRelationOpinion(w,'gao-huan','gao-yang',-200);w.day=nextMonthStart(w.day,w.scriptId);advancePacts(w);expect(w.allegiancePacts!.items.find(p=>p.person==='gao-yang')).toBeTruthy();saved(w);});
});

import {dispatchCommissionedEnvoy,advanceDiplomacy,actDiplomacy,diplomaticQuote} from './diplomacy';
import {envoyReason} from './envoyTravel';
import {advanceCivilPolitics} from './civilWars';
describe('cross-system political boundaries',()=>{
 it('keeps a foreign territorial objective alive when its actual defender becomes independent',()=>{const {w,site}=revolt();actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁'});const foreign={id:w.realm!.nextWarId!++,attacker:'east' as const,defender:'liang' as const,target:site,started:0,score:0,goal:'territory' as const};w.realm!.wars!.push(foreign);w.day=180;actPolity(w,{type:'polity',action:'partition',name:'后梁'});actPolity(w,{type:'polity',action:'partition-answer',accept:true},'xiao-yan');expect(w.realm!.wars![0]).toMatchObject({id:foreign.id,target:site,defender:'realm-1',allies:{liang:'defend'}});saved(w);});
 it('relocates an incoming envoy by completing real travel rather than invalidating the save',()=>{const w=start('xiao-yan');dispatchCommissionedEnvoy(w,'east','liang');const mid=w.diplomacy!.missions[0].id;w.people[0].location='jingkou';actPolity(w,{type:'polity',action:'relocate',site:'jingkou'});expect(w.diplomacy!.missions.find(m=>m.id===mid)!.arrivalSite).toBe('jiankang');saved(w);for(let i=0;i<150&&w.diplomacy!.missions.find(m=>m.id===mid)?.status!=='audience';i++){w.day++;advanceDiplomacy(w);}const m=w.diplomacy!.missions.find(m=>m.id===mid)!;expect(m.status).toBe('audience');expect(m.arrivalSite).toBe('jingkou');expect(w.mobility!.residences[m.envoy!].site).toBe('jingkou');saved(w);});
 it('requires a matching envoy camp and charges foreign support from the real rebel public account',()=>{const {w,a,site,source}=revolt();a.owner='xiao-yi';actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁'});const v=civilWar(w,'liang')!,pair=diplomaticPair(w,'liang','east')!;pair.treaties.push({kind:'alliance',from:'liang',to:'east',actor:null,since:0,until:720});pair.opinion=100;pair.opinionFactors={base:100,effects:{}};const why=envoyReason(w,'xiao-yan','liang','east','xiao-yi');expect(why).toContain('阵营');a.location='xiangyang';w.people[0].location='xiangyang';civilCityCapture(w,v,'xiangyang','attack',a);w.mobility!.armyCommanders![a.id!]='xiao-gang';w.mobility!.residences['xiao-gang']={site:a.location,journey:null};v.civil!.supporters.push('xiao-gang');const c={type:'diplomacy',action:'join',target:'east',war:v.id!,envoy:'xiao-yi'} as const,q=diplomaticQuote(w,c);expect(q.reason).toBe('');const local=w.realm!.fiscal!.balances[source],central=w.realm!.treasuries.liang.coins;actDiplomacy(w,c);expect(w.realm!.fiscal!.balances[source]).toBe(local-q.coins);expect(w.realm!.treasuries.liang.coins).toBe(central);expect(w.diplomacy!.missions[0]).toMatchObject({actor:'xiao-yi',civilSide:'attack'});expect(w.realm!.cities[site].owner).toBe('liang');saved(w);});
 it('terminates dead political beneficiaries without resurrecting them or deleting the real war',()=>{const {w}=revolt();actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁',arrangement:{goal:'ruler',sponsor:'xiao-yi',beneficiary:'xiao-gang',executive:'xiao-yi',name:''}});die(w,'xiao-gang','illness');advanceCivilPolitics(w);expect(civilWar(w,'liang')!.civil!.arrangement!.goal).toBe('executive');expect(civilWar(w,'liang')!.civil!.arrangement!.beneficiary).toBe('xiao-yan');saved(w);});
 it('does not accept stale political arrangements or false boolean commands',()=>{const {w}=revolt();actPower(w,{type:'power',action:'propose',goal:'executive',beneficiary:'xiao-yan',executive:'xiao-yi'});w.politics!.proposals.liang!.stage='presented';expect(powerReason(w,{type:'power',action:'answer',accept:'yes' as never},'xiao-yan')).not.toBe('');w.life!.people['xiao-yi'].death={day:w.day,cause:'illness'};const before=structuredClone(w);expect(()=>actPower(w,{type:'power',action:'answer',accept:true},'xiao-yan')).toThrow('失效');expect(w).toEqual(before);});
});
it('executes a reviewed political vote, retains its cost and rejects repeated completion',()=>{const {w}=revolt();actPower(w,{type:'power',action:'propose',goal:'executive',beneficiary:'xiao-yan',executive:'xiao-yi'});const p=w.politics!.proposals.liang!,rows=powerSupport(w,'liang',p);for(const row of rows){if(row.id!=='xiao-yi')changeRelationOpinion(w,'xiao-yi',row.id,200);if(row.id!=='xiao-yan')changeRelationOpinion(w,'xiao-yan',row.id,200);}w.day+=30;expect(powerReason(w,{type:'power',action:'present'})).toBe('');actPower(w,{type:'power',action:'present'});actPower(w,{type:'power',action:'answer',accept:true},'xiao-yan');expect(governmentOf(w,'liang')!.executives).toEqual(['xiao-yi']);expect(w.politics!.proposals.liang).toBeUndefined();expect(()=>actPower(w,{type:'power',action:'answer',accept:true},'xiao-yan')).toThrow();expect(w.realm!.influence).toBe(360);saved(w);});
it('rejects a forged current foreign ruler despite known identities and a plausible arrangement',()=>{const w=start();const g=governmentOf(w,'liang')!;g.ruler='gao-huan';g.arrangement={goal:'ruler',sponsor:'xiao-yan',beneficiary:'gao-huan',executive:'xiao-yan',name:'',since:w.day};expect(validGovernments(w)).toBe(false);});
it('keeps a loyal provincial resistance after capture of the emperor and actual chief',()=>{const {w,a}=revolt();actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁'});const v=civilWar(w,'liang')!;army(w,'jingkou','liang','xiao-gang');governmentOf(w,'liang')!.merit['xiao-gang']=100;a.location='jiankang';w.mobility!.residences['xiao-yan']={site:'jiankang',journey:null};civilCityCapture(w,v,'jiankang','attack',a);advanceCivilPolitics(w);expect(civilWar(w,'liang')).toBe(v);expect(v.civil!.loyalist).toBe('xiao-gang');expect(w.realm!.cities.jingkou.owner).toBe('liang');saved(w);});
it('moves an NPC court only to its chief’s actual owned residence and spends the real budget',()=>{const w=start();ensureWars(w);const id=w.realm!.nextWarId!++;w.realm!.wars!.push({id,attacker:'west',defender:'east',target:'ye',started:w.day,score:0});ensureWars(w);w.realm!.cities.ye.controller='west';w.realm!.cities.ye.occupiedByWar=id;w.realm!.cities.ye.occupiedSince=w.day;w.mobility!.residences['gao-huan']={site:'luoyang',journey:null};const cash=w.realm!.treasuries.east.coins;advanceSeparations(w);expect(capital('east',w)).toBe('luoyang');expect(w.realm!.treasuries.east.coins).toBe(cash-100);saved(w);advanceSeparations(w);expect(w.realm!.treasuries.east.coins).toBe(cash-100);});
it('advances real runtime governments through daily rules and keeps the resulting save valid',()=>{const {w}=revolt();actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁'});w.day=180;actPolity(w,{type:'polity',action:'partition',name:'后梁'});actPolity(w,{type:'polity',action:'partition-answer',accept:true},'xiao-yan');advance(w);expect(worldRealms(w)).toContain('realm-1');expect(w.day).toBe(181);saved(w);});
it('requires an emperor to surrender the throne before asking for personal reception',()=>{const w=start('yuan-shanjian');expect(pactReason(w,{type:'pact',action:'request',realm:'west',terms:'personal'})).toContain('交接君位');});
it('rejects duplicated national names and a forged historical source attached to a different arrangement',()=>{const {w}=revolt();expect(powerReason(w,{type:'power',action:'propose',goal:'dynasty',beneficiary:'xiao-yi',executive:'xiao-yi',name:'东魏'})).toContain('同一国号');actPower(w,{type:'power',action:'propose',goal:'executive',beneficiary:'xiao-yan',executive:'xiao-yi'});w.politics!.proposals.liang!.sourceStage='zhou-accession';expect(()=>serializeWorld(w)).toThrow();});
it('lets a runtime polity transport real grain, fill a vacant command and display its actual families',()=>{const {w,site}=revolt(),edge=roads.find(e=>(e.from===site&&w.realm!.cities[e.to].owner==='liang')||(e.to===site&&w.realm!.cities[e.from].owner==='liang'))!,target=edge.from===site?edge.to:edge.from;setLocalHolder(w,countyTerritory(target),'liang','xiao-yi');actCivilWar(w,{type:'civilWar',action:'rise',name:'新梁'});w.day=180;actPolity(w,{type:'polity',action:'partition',name:'后梁'});actPolity(w,{type:'polity',action:'partition-answer',accept:true},'xiao-yan');w.realm!.treasuries['realm-1'].coins=100;const grain=w.realm!.cities[site].grain;act(w,{type:'population',action:'transfer',from:site,to:target,amount:10,kind:'grain'});expect(w.realm!.cities[site].grain).toBe(grain-10);expect(w.realm!.population!.transfers[0]).toMatchObject({realm:'realm-1',sent:10});const a=w.realm!.armies[0];delete w.mobility!.armyCommanders![a.id!];delete w.mobility!.commanders.liang;delete w.mobility!.commanders['realm-1'];w.militaryCareer??={lastDay:w.day,xp:{},studies:{}};w.militaryCareer.xp['xiao-yi']=240;act(w,{type:'militaryNomination',action:'apply',army:a.id!});expect(w.militaryNominations!.items[0].realm).toBe('realm-1');expect(realmClans(w,'realm-1').some(f=>f.members.some(p=>p.id==='xiao-yi'))).toBe(true);saved(w);});
