import {isMonthStart} from './calendar';
import {relationOpinion} from './relationships';
import {redirectCourtEnvoys} from './diplomacy';
import {armyCommander} from './mobility';
import {ensureService} from './assignments';
import {detachRetainer,retainPersonalFollowers} from './allegianceTransition';
import type {World} from './types';
import {capital,syncGovernance,type RealmId} from './realm';
import {worldRealms,realmOrigin,isRealmId} from './polityRuntime';
import {governmentOf,governingExecutives,regimeName} from './government';
import {civilWar,warArmySide} from './civilWars';
import {activeWars} from './wars';
import {validDynastyName} from './courtSave';
import {allegianceRealm,reconcileOfficeAllegiance} from './officeEligibility';
import {syncRelationships} from './relationships';
import {returnArmyConvoy} from './armyLogistics';
import {finishCampaign} from './militaryCampaigns';
import {fiscalRecord,ensureFiscal} from './treasury';
import {newCourt,syncCourt} from './court';
import {siteById} from '../data/scenario';
import {isAlive} from './lifeState';
import {detained} from './custodyState';
import {personResidence} from './residence';
export type PolityCommand={type:'polity';action:'relocate';site:string}|{type:'polity';action:'partition';name:string}|{type:'polity';action:'partition-answer';accept:boolean};
export function polityReason(w:World,c:PolityCommand,actor=w.characterId!){if(!w.realm?.governments||!actor||!isAlive(w,actor)||detained(w,actor)||w.campaign?.status!=='active')return '当前不能办理政权安排';const r=allegianceRealm(w,actor)!,war=civilWar(w,r);
 if(c.action==='relocate'){const city=w.realm.cities[c.site];return !governingExecutives(w,r).includes(actor)?'须当前实际执政者决定朝廷驻地':!city||city.owner!==r||city.controller!==r||!warCityCompatible(w,r,c.site,actor)?'须本方实际控制的法理辖地':capital(r,w)===c.site?'朝廷已驻此地':personResidence(w,actor).site!==c.site||personResidence(w,actor).traveling?'执政者须实际抵达新驻地':w.realm.treasuries[r].coins<100?'迁移朝廷需中央公款 100 钱':'';}
 if(!war?.civil)return '须有本国正在持续的内战';const civil=war.civil;
 if(c.action==='partition-answer'){if(typeof c.accept!=='boolean')return '须明确接受或拒绝';if(!civil.partitionOffer||civil.partitionOffer.until<w.day)return '没有有效的割据议案';if(actor!==civil.loyalist)return '须原朝廷领袖裁定';if(!c.accept)return '';return partitionBasisReason(w,war,civil.partitionOffer.name,civil.claimant);}
 const basis=partitionBasisReason(w,war,c.name,actor);return basis||(civil.partitionOffer&&civil.partitionOffer.until>=w.day?'已有割据议案候复':'');
}
function partitionBasisReason(w:World,war:import('./wars').War,name:string,actor:string){const r=war.attacker,c=war.civil!,cities=c.cities.filter(id=>w.realm!.cities[id].controller===r&&w.realm!.cities[id].owner===r),troops=w.realm!.armies.filter(a=>a.realm===r&&warArmySide(w,war,a)==='attack').reduce((n,a)=>n+a.troops,0);return actor!==c.claimant||!isAlive(w,actor)||detained(w,actor)||allegianceRealm(w,actor)!==r?'须当前自由起兵领袖提出割据和解':!validDynastyName(name)?'须议定 1—6 个汉字的新国号':worldRealms(w).some(id=>!w.realm!.annexed?.[id]&&regimeName(w,id)===name)?'不能与存续政权使用同一国号':worldRealms(w).length>=9?'本局并立政权已达上限':w.day-war.started<180?'须有至少 180 日的持续阵营':!cities.includes(c.base)||troops<300?'须有实际控制的根据地及至少 300 人军队':governmentOf(w,r)!.ruler===actor?'不能同时继承原朝廷与另建割据政权':Math.abs(war.score)>30?'军事压力差距过大，对方不接受割据和解':'';}
function warCityCompatible(w:World,r:RealmId,site:string,actor:string){const war=civilWar(w,r);return !war||war.civil!.supporters.includes(actor)===war.civil!.cities.includes(site);}
function log(w:World,text:string){w.chronicle.push({day:w.day,person:'player',text});w.chronicle=w.chronicle.slice(-100);}
export function actPolity(w:World,c:PolityCommand,actor=w.characterId!){const next=structuredClone(w);perform(next,c,actor);Object.assign(w,next);}
function perform(w:World,c:PolityCommand,actor:string){const why=polityReason(w,c,actor);if(why)throw new Error(why);const s=w.realm!,r=allegianceRealm(w,actor)!;
 if(c.action==='relocate'){const previous=capital(r,w);s.treasuries[r].coins-=100;(s.identities??={})[r]={origin:realmOrigin(w,r) as 'liang'|'east'|'west',capital:c.site,created:s.identities?.[r]?.created??s.governments!.since,predecessor:s.identities?.[r]?.predecessor??null};redirectCourtEnvoys(w,r,previous);log(w,'朝廷迁驻'+siteById[c.site].name+'，使团、公务与补给按新驻地办理。');return;}
 const war=civilWar(w,r)!,civil=war.civil!;
 if(c.action==='partition'){civil.partitionOffer={from:actor,name:c.name,created:w.day,until:w.day+15};log(w,'起兵方提出承认实际割据的和解，等待原朝廷回应。');return;}
 if(!c.accept){delete civil.partitionOffer;return;}formSeparateRealm(w,war.id!,civil.partitionOffer!.name);
}
/** A separate identity owns actual responding places, people and regiments only; creation never mints a treasury. */
export function formSeparateRealm(w:World,warId:number,name:string){const s=w.realm!,war=activeWars(w).find(v=>v.id===warId)!,c=war.civil!,origin=war.attacker,g=governmentOf(w,origin)!,r=Array.from({length:6},(_,i)=>('realm-'+(i+1)) as RealmId).find(id=>!s.governments!.realms[id]);const basis=partitionBasisReason(w,war,name,c.claimant);if(basis)throw new Error(basis);if(!r||!validDynastyName(name))throw new Error('无法建立并立政权');
 const cities=c.cities.filter(id=>s.cities[id].owner===origin&&s.cities[id].controller===origin),people=[...new Set([c.claimant,...c.supporters,...cities.map(id=>s.cities[id].governor).filter((id):id is string=>!!id)])].filter(id=>id!==g.ruler&&isAlive(w,id)&&allegianceRealm(w,id)===origin);
 if(!cities.includes(c.base)||!people.includes(c.claimant))throw new Error('割据根据地与领袖已失效');
 const armies=s.armies.filter(a=>warArmySide(w,war,a)==='attack'&&a.realm===origin),rs=w.relationships!;const commanders=new Map(armies.map(a=>[a.id!,armyCommander(w,a)]));for(const p of people)retainPersonalFollowers(w,p,origin,people);for(const p of people){if(rs.oaths[p]&&!people.includes(rs.oaths[p].lord))delete rs.oaths[p];if(w.retinue?.members[p]&&!people.includes(w.retinue.members[p].host))detachRetainer(w,p);(rs.allegiances??={})[p]={realm:r,from:origin,since:w.day,army:armies.find(a=>a.owner===p)?.id??0,source:'partition'};}
 const ruler=c.arrangement?.beneficiary&&people.includes(c.arrangement.beneficiary)?c.arrangement.beneficiary:c.claimant,chief=c.arrangement?.executive&&people.includes(c.arrangement.executive)?c.arrangement.executive:c.claimant;
 for(const p of people)if(p!==chief&&rs.oaths[p]&&!people.includes(rs.oaths[p].lord))rs.oaths[p]={lord:chief,since:w.day,loyalty:60};
 const newGovernment=structuredClone(g);newGovernment.ruler=ruler;newGovernment.executives=[chief];newGovernment.dynasty=r;newGovernment.regimeId=r+'-0';newGovernment.arrangement={goal:'dynasty',sponsor:c.claimant,beneficiary:ruler,executive:chief,name,since:w.day};newGovernment.heirs={ruler:null,executive:null,dynasty:null};newGovernment.task=null;newGovernment.stages=[];newGovernment.cooldowns={};delete newGovernment.resignedExecutives;delete newGovernment.court;newGovernment.support=50;newGovernment.legitimacy=40;s.governments!.realms[r]=newGovernment;s.treasuries[r]={coins:0,grain:0,lastIncome:0,lastExpense:0,lastFood:0};(s.identities??={})[r]={origin:realmOrigin(w,origin) as 'liang'|'east'|'west',capital:c.base,created:w.day,predecessor:origin};s.governments!.regimes.push({id:r+'-0',realm:r,dynasty:r,ruler,executives:[chief],name,kind:'political',from:w.day,until:null,predecessor:null,source:null,cities});
 for(const id of cities){s.cities[id].owner=r;s.cities[id].controller=r;delete s.cities[id].occupiedByWar;delete s.cities[id].occupiedSince;if(s.cities[id].governor&&!people.includes(s.cities[id].governor!))s.cities[id].governor=null;}
 // Shared higher district accounts are divided by their real controlled population; every source keeps its remainder.
 const fiscal=ensureFiscal(w)!;fiscal.net[r]=0;for(const [key,balance] of Object.entries(fiscal.balances)){if(!key.startsWith(origin+'|'))continue;const territory=key.slice(origin.length+1),nodes=territory.startsWith('county:')||territory.startsWith('city:')?[territory.split(':')[1]]:localSitesForSeparation(w,territory),total=nodes.filter(id=>s.cities[id]?.owner===origin||s.cities[id]?.owner===r).reduce((n,id)=>n+s.cities[id].population,0),part=nodes.filter(id=>cities.includes(id)).reduce((n,id)=>n+s.cities[id].population,0),amount=total?Math.floor(balance*part/total):0;if(amount){fiscal.balances[key]-=amount;const to=r+'|'+territory;fiscal.balances[to]=(fiscal.balances[to]??0)+amount;fiscalRecord(w,r,key,to,amount,'割据和解按实际辖地分割地方公库');}}
 for(const [key,seat] of Object.entries(s.local?.seats??{})){if(!key.startsWith(origin+'|')||!seat.holder||!people.includes(seat.holder))continue;const sites=localSitesForSeparation(w,key.slice(origin.length+1));if(sites.some(id=>cities.includes(id))){s.local!.seats[r+'|'+key.slice(origin.length+1)]={...seat,regime:r+'-0'};seat.holder=null;seat.delegated=false;}}
 for(const a of armies){returnArmyConvoy(w,a);const campaign=w.militaryCampaigns?.items.find(q=>q.status==='active'&&q.army===a.id);if(campaign)finishCampaign(w,campaign,'failed','所属阵营承认割据，原委任专款按原账户退回');const oldPayer=a.payer??'central:'+origin;if(a.arrears)(s.armyDebts??=[]).push({realm:origin,account:oldPayer,coins:a.arrears});a.arrears=0;a.realm=r;if(w.mobility&&commanders.get(a.id!)&&people.includes(commanders.get(a.id!)!)){w.mobility.armyCommanders??={};w.mobility.armyCommanders[a.id!]=commanders.get(a.id!)!;}a.payer=a.owner?'person:'+a.owner:'central:'+r;a.siege=0;}
 if(w.politics?.proposals[origin]?.sponsor===c.claimant){delete w.politics.proposals[origin];w.politics.cooldowns[origin]=w.day+180;}s.wars=s.wars!.filter(v=>v!==war);s.war=s.wars[0]??null;s.sieges=s.sieges?.filter(q=>q.war!==warId);for(const other of activeWars(w)){if(other.civil)continue;const side=origin===other.attacker?'attack':origin===other.defender?'defend':other.allies?.[origin];if(other.defender===origin&&cities.includes(other.target)){other.defender=r;(other.allies??={})[origin]='defend';delete other.allies[r];log(w,'外战目标辖地成为并立政权，守方由其承接，原朝廷继续以盟军参战。');}else if(side)(other.allies??={})[r]=side;}
 if(w.diplomacy){w.diplomacy.credit[r]=40;w.diplomacy.bases[r]=r+'-0';for(const other of worldRealms(w).filter(id=>id!==r)){const key=[r,other].sort().join('|');w.diplomacy.pairs[key]={a:r,b:other,opinion:other===origin?-30:0,recognized:false,treaties:[],cooldowns:{}};}}
 s.truces[[origin,r].sort().join('|')]=w.day+360;ensureService(w);newGovernment.court=newCourt(w,r);reconcileOfficeAllegiance(w);syncRelationships(w);syncCourt(w,origin);syncGovernance(w);log(w,name+'成立：只承接'+cities.length+'处响应辖地与'+armies.length+'支真实军队，旧国债务与其他战场继续结算。');}
import {descendantSites} from '../data/territorialHierarchy';
const localSitesForSeparation=(_w:World,territory:string)=>descendantSites(territory);
export function advanceSeparations(w:World){if(!w.realm?.governments||w.campaign?.status!=='active')return;for(const r of worldRealms(w)){const chief=governingExecutives(w,r)[0],seat=capital(r,w),at=chief&&personResidence(w,chief);if(chief&&chief!==w.characterId&&at&&!at.traveling&&(w.realm.cities[seat].owner!==r||w.realm.cities[seat].controller!==r||!warCityCompatible(w,r,seat,chief))&&!polityReason(w,{type:'polity',action:'relocate',site:at.site},chief))perform(w,{type:'polity',action:'relocate',site:at.site},chief);}
 for(const war of activeWars(w)){if(war.civil&&!war.civil.partitionOffer&&war.civil.claimant!==w.characterId&&isMonthStart(w.day,w.scriptId)&&w.day-war.started>=180&&relationOpinion(w,war.civil.loyalist,war.civil.claimant)<=-30){const command={type:'polity',action:'partition',name:war.civil.name} as const;if(!polityReason(w,command,war.civil.claimant))perform(w,command,war.civil.claimant);}const p=war.civil?.partitionOffer;if(!p)continue;if(w.day>p.until){delete war.civil!.partitionOffer;continue;}if(war.civil!.loyalist!==w.characterId&&!polityReason(w,{type:'polity',action:'partition-answer',accept:true},war.civil!.loyalist))formSeparateRealm(w,war.id!,p.name);}}
export function validRealmIdentities(w:World){const ids=worldRealms(w);if(ids.length>9||!['liang','east','west'].every(id=>ids.includes(id as RealmId))||!ids.every(isRealmId))return false;const state=w.realm?.identities;if(state===undefined)return ids.every(id=>!id.startsWith('realm-'));if(!state||typeof state!=='object'||Array.isArray(state))return false;return Object.entries(state).every(([id,v])=>ids.includes(id as RealmId)&&v&&['liang','east','west'].includes(v.origin)&&!!siteById[v.capital]&&Number.isSafeInteger(v.created)&&v.created>=0&&v.created<=w.day&&(v.predecessor===null||ids.includes(v.predecessor)&&v.predecessor!==id))&&ids.filter(id=>id.startsWith('realm-')).every(id=>!!state[id]&&state[id]!.predecessor!==null);}
