import {governmentYear} from './government';
import {successionDefinitions,dynastyNames,canonicalDynastyName} from '../data/governments';
import type {World} from './types';
import type {PowerArrangement} from './powerPolitics';
import {relationshipPersonById} from '../data/relationships';
import {validDynastyName} from './courtSave';
export function validArrangement(p:unknown):p is PowerArrangement {if(!p||typeof p!=='object')return false;const v=p as PowerArrangement;return ['executive','ruler','dynasty'].includes(v.goal)&&[v.sponsor,v.beneficiary,v.executive].every(id=>typeof id==='string'&&!!relationshipPersonById[id])&&typeof v.name==='string'&&(v.goal!=='dynasty'||validDynastyName(v.name));}
export function validPowerPolitics(w:World){const s=w.politics;if(s===undefined)return true;const realms=Object.keys(w.realm?.governments?.realms??{}),person=(id:string)=>typeof id==='string'&&!!relationshipPersonById[id],day=(n:number,max=w.day)=>Number.isSafeInteger(n)&&n>=0&&n<=max,object=(v:unknown)=>!!v&&typeof v==='object'&&!Array.isArray(v);if(!s||s.version!==1||!object(s.proposals)||!object(s.cooldowns)||!object(s.chiefs)||!Array.isArray(s.assurances)||s.assurances.length>30||!Array.isArray(s.history)||s.history.length>60)return false;
 if(s.commitments!==undefined&&(!Array.isArray(s.commitments)||s.commitments.length>270||!s.commitments.every(q=>q&&realms.includes(q.realm)&&person(q.person)&&person(q.chief)&&['office','command'].includes(q.kind)&&day(q.until,w.day+180)&&typeof q.broken==='boolean')))return false;
 if(Object.entries(s.proposals).some(([r,p])=>!realms.includes(r)||!validArrangement(p)||p.sourceStage!==undefined&&(!Object.hasOwn(successionDefinitions,p.sourceStage)||successionDefinitions[p.sourceStage].realm!==r||governmentYear(w,p.started)<successionDefinitions[p.sourceStage].year||successionDefinitions[p.sourceStage].ruler!==p.beneficiary||successionDefinitions[p.sourceStage].executives[0]!==p.executive||(successionDefinitions[p.sourceStage].nextDynasty?p.goal!=='dynasty'||canonicalDynastyName(p.name)!==dynastyNames[successionDefinitions[p.sourceStage].nextDynasty!]:p.goal==='dynasty'||p.name!==''))||!day(p.started)||!day(p.due,w.day+180)||!['support','presented','refused'].includes(p.stage)||!object(p.promises)||!object(p.approached)||Object.entries(p.promises).some(([id,v])=>!person(id)||!['office','command'].includes(v)||!day(p.approached[id]))||Object.entries(p.approached).some(([id,d])=>!person(id)||!day(d)||!p.promises[id])))return false;
 if(Object.entries(s.cooldowns).some(([r,d])=>!realms.includes(r)||!day(d!,w.day+180))||Object.entries(s.chiefs).some(([r,id])=>!realms.includes(r)||!person(id!)))return false;
 return s.assurances.every(q=>q&&realms.includes(q.realm)&&person(q.person)&&person(q.chief)&&q.person!==q.chief&&day(q.due,w.day+30)&&['pending','kept','refused'].includes(q.status))&&s.history.every(q=>q&&day(q.day)&&realms.includes(q.realm)&&typeof q.text==='string'&&q.text.length<=500)&&Object.values(w.realm?.governments?.realms??{}).every(g=>!g.arrangement||validArrangement(g.arrangement)&&day(g.arrangement.since));
}
