import {schemeSupportBonus,consumeSchemeSupport} from './intrigue';
import {allPeople,getPerson} from './personRegistry';
import {culturalMilitarySupport} from './culture';
import {successionDefinitions,successionIds,dynastyNames,type SuccessionId} from '../data/governments';
import {worldRealms} from './polityRuntime';
import {governmentYear} from './government';
import {isMonthStart} from './calendar';
import {regimeName} from './government';
import type {World} from './types';
import {capital,syncGovernance,type RealmId} from './realm';
import {governmentOf,governingAuthority,governingExecutives} from './government';
import {allegianceRealm} from './officeEligibility';

import {relationOpinion,changeRelationOpinion,syncRelationships} from './relationships';
import {dynasticKin,rulerEligibility,claimantProvenance,supportClaim,activeClaim} from './claims';
import {ensureRulerHistory,syncRulerHistory,announceSuccession} from './rulerHistory';
import {nobilityPoliticalWeight} from './nobility';
import {detachRetainer,retainPersonalFollowers} from './allegianceTransition';
import {personInfluence,awardInfluence} from './personalInfluence';
import {armyCommander} from './mobility';
import {localPoliticalBasis} from './officePower';
import {isAlive,ageAt} from './lifeState';
import {detained} from './custodyState';
import {syncCourt} from './court';
import {syncDiplomacy} from './diplomacy';
import {civilWar,civilReason,actCivilWar} from './civilWars';
import {validDynastyName} from './courtSave';
import {dynastyNameOptions} from './dynastyNaming';
export type PowerGoal='executive'|'ruler'|'dynasty';
export interface PowerArrangement {goal:PowerGoal;sponsor:string;beneficiary:string;executive:string;name:string}
export interface PowerProposal extends PowerArrangement {sourceStage?:SuccessionId;started:number;stage:'support'|'presented'|'refused';due:number;promises:Record<string,'office'|'command'>;approached:Record<string,number>}
export interface PowerPolitics {version:1;reassessments?:{realm:RealmId;person:string;day:number;from:string;to:string;choice:'pending'|'accept'|'oppose'|'wait'|'expired';reason?:string;jurisdictions:string[];armies:number[]}[];proposals:Partial<Record<RealmId,PowerProposal>>;cooldowns:Partial<Record<RealmId,number>>;chiefs:Partial<Record<RealmId,string>>;commitments?:{realm:RealmId;person:string;chief:string;kind:'office'|'command';until:number;broken:boolean}[];assurances:{realm:RealmId;person:string;chief:string;due:number;status:'pending'|'kept'|'refused'}[];history:{day:number;realm:RealmId;text:string}[]}
export type PowerCommand={type:'power';action:'stance';realm:RealmId;choice:'accept'|'oppose'|'wait'}|{type:'power';action:'propose';goal:PowerGoal;beneficiary:string;executive:string;name?:string;sourceStage?:SuccessionId}|{type:'power';action:'pledge';person:string;promise:'office'|'command'}|{type:'power';action:'present'|'cancel'|'rise'}|{type:'power';action:'answer';accept:boolean}|{type:'power';action:'assure';person:string;accept:boolean};
export const powerGoalNames={executive:'更换执政',ruler:'拥立君主',dynasty:'改朝换代'};
export function ensurePowerPolitics(w:World){return w.politics??={version:1,proposals:{},cooldowns:{},chiefs:{},assurances:[],history:[]};}
function log(w:World,r:RealmId,text:string){const s=ensurePowerPolitics(w);s.history.push({day:w.day,realm:r,text});s.history=s.history.slice(-60);w.chronicle.push({day:w.day,person:'player',text});w.chronicle=w.chronicle.slice(-100);}
export function powerCandidates(w:World,r:RealmId,office:'ruler'|'executive'='executive'){return allPeople(w).filter(p=>allegianceRealm(w,p.id)===r&&isAlive(w,p.id)&&!detained(w,p.id)&&(office==='ruler'?!rulerEligibility(w,r,p.id):(ageAt(w,p.id)??0)>=16));}
export function powerStakeholders(w:World,r:RealmId,p:PowerArrangement){const g=governmentOf(w,r)!,ids=[g.ruler,...g.executives,...Object.values(g.court?.ministries??{}),...Object.values(w.realm!.cities).filter(c=>c.owner===r&&c.controller===r).map(c=>c.governor),...Object.entries(w.realm!.local?.seats??{}).filter(([key])=>key.startsWith(r+'|')).map(([,seat])=>seat.holder),...w.realm!.armies.filter(a=>a.realm===r).map(a=>armyCommander(w,a)),p.sponsor,p.beneficiary,p.executive];return [...new Set(ids)].filter((id):id is string=>!!id&&isAlive(w,id)&&allegianceRealm(w,id)===r);}
export function powerSupport(w:World,r:RealmId,p:PowerArrangement){const g=governmentOf(w,r)!,draft=w.politics?.proposals[r],militarySupport=Math.min(20,dynastyReadiness(w,r,p.sponsor).victories*4);return powerStakeholders(w,r,p).map(id=>{const armies=w.realm!.armies.filter(a=>a.realm===r&&(a.owner===id||armyCommander(w,a)===id)),troops=armies.reduce((n,a)=>n+(a.regiments?.filter(u=>u.loyalTo===id&&(u.commanderLoyalty??0)>(u.institution??60)||a.owner===id).reduce((m,u)=>m+u.troops,0)??a.troops),0),weight=1+Math.min(8,Math.floor(localPoliticalBasis(w,id,r)/10))+Math.min(8,Math.ceil(troops/300))+(g.executives.includes(id)?4:0)+nobilityPoliticalWeight(w,id,r),old=p.goal==='executive'?g.executives[0]:g.ruler;
 const parts=[{label:'秘密政治承诺',value:schemeSupportBonus(w,r,p,id)},{label:'旧有文化待遇',value:p.executive===old?0:-culturalMilitarySupport(w,r,id)},{label:'与新安排关系',value:Math.round((relationOpinion(w,p.beneficiary,id)+relationOpinion(w,p.executive,id))/4)},{label:'旧主与誓约',value:-(w.relationships?.oaths[id]?.lord===old?Math.round((w.relationships.oaths[id].loyalty??0)/3):Math.max(0,Math.round(relationOpinion(w,old,id)/4)))},{label:'同族与既得职位',value:dynasticKin(w,id,p.beneficiary)?20:dynasticKin(w,id,old)&&p.goal!=='executive'?-25:0},{label:'君主合法性',value:p.goal==='executive'?0:-Math.round(g.legitimacy/5)},{label:'发起者实战威望',value:militarySupport},{label:'朝廷失陷',value:detained(w,old)||g.executives.some(id=>detained(w,id))?20:0},{label:'保留职权承诺',value:draft?.promises[id]?30:0},{label:'议案政治倾向',value:g.court?.members[id]==='dynastic'&&p.goal!=='executive'?-15:g.court?.members[id]==='reform'&&p.goal==='executive'?5:0}];if(id===p.sponsor||id===p.executive||p.goal!=='executive'&&id===p.beneficiary)parts.push({label:id===p.sponsor?'发起本次安排':'受益人与执政安排',value:100-parts.reduce((n,v)=>n+v.value,0)});const score=parts.reduce((n,v)=>n+v.value,0),stance=score>=15?'support':score<=-15?'oppose':'wait';return {id,weight,troops,armies:armies.filter(a=>(a.regiments?.filter(u=>a.owner===id||u.loyalTo===id&&(u.commanderLoyalty??0)>=60&&(u.commanderLoyalty??0)>(u.institution??60)).reduce((n,u)=>n+u.troops,0)??0)>=100).map(a=>a.id!),parts,score,stance};});}
export function powerSummary(w:World,r:RealmId,p:PowerArrangement){const rows=powerSupport(w,r,p),total=rows.reduce((n,v)=>n+v.weight,0),support=rows.filter(v=>v.stance==='support'),power=support.reduce((n,v)=>n+v.weight,0);return {rows,support,share:total?Math.floor(power*100/total):0,armies:[...new Set(support.flatMap(v=>v.armies))]};}
/** Derived from durable, deduplicated battle/city settlements; ordinary civil merit is not military achievement. */
export function dynastyReadiness(w:World,r:RealmId,actor:string){
 const g=governmentOf(w,r)!,prefix=r+'|'+actor+'|';
 let victories=0;
 for(const [key,ranges] of Object.entries(w.deeds?.settled??{}))if(key.startsWith(prefix)&&(key.slice(prefix.length)==='battle'||key.slice(prefix.length).startsWith('siege:')))for(let i=0;i<ranges.length;i+=2)victories+=ranges[i+1]-ranges[i]+1;
 const regency=w.relationships?.regencies[r],incumbent=governingExecutives(w,r).includes(actor),merit=g.merit[actor]??0;
 const reason=victories<3?'改朝换代须积累至少 3 次战胜或攻城成果（当前 '+victories+' 次）':merit<40?'改朝换代须功绩达到 40':incumbent&&g.ruler!==actor&&(!regency||regency.controller!==actor||regency.grip<60||w.day-regency.since<360)?'须持续掌政至少 360 日且掌控达到 60':'';
 return {victories,merit,reason};
}
export function powerReason(w:World,c:PowerCommand,actor=w.characterId!){if(!w.realm?.governments||!w.relationships||w.campaign?.status!=='active'||!actor)return '当前无法议定权力安排';const r=allegianceRealm(w,actor);if(!r||!isAlive(w,actor)||detained(w,actor)||(ageAt(w,actor)??0)<16)return '须本国在世成年且自由的人物';const g=governmentOf(w,r)!,s=w.politics,p=s?.proposals[r];
 if(c.action==='stance'){const q=s?.reassessments?.filter(q=>q.person===actor&&q.realm===c.realm).at(-1);return !['accept','oppose','wait'].includes(c.choice)?'未知朝廷立场':c.realm!==r||!q||q.choice!=='pending'?'没有待决的本朝统属选择':'';}
 if(c.action==='assure'){if(typeof c.accept!=='boolean')return '须明确接受或拒绝';const q=s?.assurances.find(q=>q.realm===r&&q.person===c.person&&q.status==='pending');return !q?'交接事项已结束':q.chief!==actor?'须新执政者回应':c.accept&&personInfluence(w,actor)<10?'确认待遇需影响力 10':'';}
 if(civilWar(w,r))return '权力争夺已进入内战，请在战况中办理';if(c.action==='propose'){if(c.sourceStage){const d=successionDefinitions[c.sourceStage];if(!d||d.realm!==r||governmentYear(w)<d.year||g.dynasty!==r||g.stages.includes(c.sourceStage)||d.ruler!==c.beneficiary||d.executives[0]!==c.executive||c.goal!==(d.nextDynasty?'dynasty':d.ruler!==g.ruler?'ruler':'executive')||c.name!==(d.nextDynasty?dynastyNames[d.nextDynasty]:undefined))return '历史议案身份、年份或参与安排已变化';}if(!['executive','ruler','dynasty'].includes(c.goal))return '未知政治目标';if(rulerEligibility(w,r,c.beneficiary,{allowFounder:c.goal==='dynasty'})||!powerCandidates(w,r).some(p=>p.id===c.executive))return rulerEligibility(w,r,c.beneficiary,{allowFounder:c.goal==='dynasty'})||'执政者须为本国自由成年人物';if(c.goal==='dynasty'&&w.realm.governments!.regimes.filter(v=>v.realm===r).length>=12)return '本局国统记录已满';if(c.goal==='dynasty'&&!validDynastyName(c.name?.trim()))return '请议定 1—6 个汉字的新国号';if(c.goal==='dynasty'&&worldRealms(w).some(id=>!w.realm!.annexed?.[id]&&regimeName(w,id)===c.name?.trim()))return '不能与存续政权使用同一国号';if(civilWar(w,r)||p||g.task||g.court?.founding)return '本国已有主要政治议程';if((s?.cooldowns[r]??0)>w.day)return '上次权力争夺后正在休整';if(!governingExecutives(w,r).includes(actor)&&localPoliticalBasis(w,actor,r)<=0&&!Object.values(g.court?.ministries??{}).includes(actor)&&!w.realm.armies.some(a=>a.realm===r&&(a.owner===actor||armyCommander(w,a)===actor)))return '需中央任职、地方辖地或实际兵权';if(c.goal==='executive'&&g.executives.length===1&&g.executives[0]===c.executive)return '执政安排未变化';if(c.goal==='ruler'&&g.ruler===c.beneficiary)return '此人已在君位';if(c.goal==='dynasty'&&dynastyReadiness(w,r,actor).reason)return dynastyReadiness(w,r,actor).reason;return personInfluence(w,actor)<40?'发起议案需个人影响力 40':'';}
 if(!p)return '没有当前权力争夺';if(c.action==='answer')return typeof c.accept!=='boolean'?'须明确接受或拒绝':![p.sponsor,p.beneficiary,p.executive].every(id=>isAlive(w,id)&&allegianceRealm(w,id)===r)||detained(w,p.executive)||p.goal!=='executive'&&detained(w,p.beneficiary)?'议案参与人已失效':p.stage!=='presented'?'议案尚未公开呈请':actor!==governingAuthority(w,r)&&actor!==g.ruler?'须现任君主或执政者回应':p.sponsor===actor&&actor!==g.ruler?'发起者不能替反对方批准自己的议案':'';
 if(![p.sponsor,p.beneficiary,p.executive].every(id=>isAlive(w,id)&&allegianceRealm(w,id)===r))return '议案参与人已失效';if(actor!==p.sponsor)return '须议案发起人办理';if(c.action==='cancel')return '';
 if(c.action==='pledge')return !['office','command'].includes(c.promise)?'未知保留职权承诺':p.stage!=='support'?'公开摊牌后不能改许承诺':!powerStakeholders(w,r,p).includes(c.person)||c.person===actor?'须向关键重臣或将领争取支持':p.approached[c.person]!==undefined?'此人已经交涉，不可重复刷取支持':c.promise==='command'&&!w.realm.armies.some(a=>a.realm===r&&(a.owner===c.person||armyCommander(w,a)===c.person))?'此人没有实际兵权':c.promise==='office'&&!Object.values(g.court?.ministries??{}).includes(c.person)&&!Object.values(w.realm.cities).some(v=>v.governor===c.person)?'此人没有可保留的官职':personInfluence(w,actor)<10?'争取支持需影响力 10':'';
 if(c.action==='present'){if(p.goal==='dynasty'&&dynastyReadiness(w,r,p.sponsor).reason)return dynastyReadiness(w,r,p.sponsor).reason;if(detained(w,p.executive)||p.goal!=='executive'&&detained(w,p.beneficiary))return '议案参与人已失效';const q=powerSummary(w,r,p);return p.stage!=='support'?'已公开摊牌':w.day-p.started<30?'须先交涉至少 30 日':q.share<60?'关键人物支持权重须达 60%':!w.realm.cities[capital(r,w)].controller||w.realm.cities[capital(r,w)].controller!==r?'朝廷驻地由他国控制':'';}
 if(c.action==='rise')return p.stage!=='refused'?'须在议案被拒绝后决定冲突':civilReason(w,{type:'civilWar',action:'rise',name:p.name||'新朝',arrangement:p},actor);return '未知政治行动';}
/** Shared completion retains accepting officials, actual territory, all military stores and debts. */
export function applyPowerArrangement(w:World,r:RealmId,p:PowerArrangement,opponents:string[]=[],source:string|null=null,options:{foreignClaimant?:boolean}={}){const s=w.realm!,g=governmentOf(w,r)!,ruler=p.goal==='executive'?g.ruler:p.beneficiary; const why=rulerEligibility(w,r,ruler,{allowForeign:!!options.foreignClaimant,allowFounder:p.goal==='dynasty'});if(why||!getPerson(w,p.executive)||!isAlive(w,p.executive)||detained(w,p.executive)||(ageAt(w,p.executive)??0)<16||allegianceRealm(w,p.executive)!==r&&!(options.foreignClaimant&&p.executive===ruler))throw new Error(why||'权力安排的执政人已失效');
 if(options.foreignClaimant&&(p.goal!=='ruler'||!activeClaim(w,r,ruler)||!w.claims?.records.some(c=>c.realm===r&&c.person===ruler&&c.patron===p.sponsor&&c.until===null)))throw new Error('外来拥立须有实际承统来源和明确支持');
 ensureRulerHistory(w);const reactionRows=powerSupport(w,r,p);const previous=g.ruler,provenance=claimantProvenance(w,r,ruler),restoration=p.goal==='ruler'&&!dynasticKin(w,previous,ruler)&&provenance?.dynasty!==g.dynasty;if((p.goal==='dynasty'||restoration)&&s.governments!.regimes.filter(v=>v.realm===r).length>=12)throw new Error('本局国统记录已满');
 if(previous!==ruler&&isAlive(w,previous))supportClaim(w,r,previous,previous,'deposed');
 if(options.foreignClaimant&&allegianceRealm(w,ruler)!==r){const from=allegianceRealm(w,ruler)!;retainPersonalFollowers(w,ruler,from);delete w.relationships!.oaths[ruler];detachRetainer(w,ruler);(w.relationships!.allegiances??={})[ruler]={realm:r,from,since:w.day,army:0,source:'retained'};}
 opponents=[...new Set([...opponents,...(p.goal==='executive'?[]:powerSupport(w,r,p).filter(q=>q.stance==='oppose').map(q=>q.id))])].filter(id=>id!==w.characterId);

 if(p.goal==='dynasty'||restoration){source??=w.politics?.proposals[r]?.sourceStage?successionDefinitions[w.politics.proposals[r]!.sourceStage!].source.url:null;const old=s.governments!.regimes.find(v=>v.id===g.regimeId)!;old.until=w.day;const id=r+'-political-'+w.day+'-'+s.governments!.regimes.filter(v=>v.realm===r).length;g.dynasty=restoration?provenance!.dynasty:id;g.regimeId=id;s.governments!.regimes.push({id,realm:r,dynasty:g.dynasty,name:restoration?s.governments!.regimes.find(v=>v.realm===r&&v.dynasty===provenance!.dynasty)?.name??dynastyNames[provenance!.dynasty]:p.name,kind:'political',ruler,executives:[p.executive],from:w.day,until:null,predecessor:old.id,source,cities:Object.keys(s.cities).filter(id=>s.cities[id].owner===r&&s.cities[id].controller===r)});g.legitimacy=Math.max(40,Math.min(75,g.legitimacy));}
 const reactions=ensurePowerPolitics(w).reassessments??=[];if(previous!==ruler)for(const q of reactionRows){const jurisdictions=Object.entries(s.cities).filter(([,c])=>c.owner===r&&c.controller===r&&c.governor===q.id).map(([site])=>site);jurisdictions.push(...Object.entries(s.local?.seats??{}).filter(([key,seat])=>key.startsWith(r+'|')&&seat.holder===q.id).map(([key])=>key));reactions.push({realm:r,person:q.id,day:w.day,from:previous,to:ruler,choice:q.id===w.characterId?'pending':q.stance==='support'?'accept':q.stance==='oppose'?'oppose':'wait',jurisdictions,armies:s.armies.filter(a=>a.realm===r&&(a.owner===q.id||armyCommander(w,a)===q.id)).map(a=>a.id!).filter(id=>Number.isSafeInteger(id))});}ensurePowerPolitics(w).reassessments=reactions.slice(-300);
 g.ruler=ruler;g.executives=[p.executive];g.arrangement={...p,beneficiary:ruler,since:w.day};g.heirs={ruler:null,executive:null,dynasty:null};delete g.resignedExecutives;g.task=null;syncRulerHistory(w,p.goal==='dynasty'?'founding':'power',source);
 let dissent:ReturnType<typeof civilWar>;if(previous!==ruler&&isAlive(w,previous)&&!civilWar(w,r))for(const candidate of reactionRows.filter(q=>q.id!==w.characterId&&q.stance==='oppose').sort((a,b)=>b.troops-a.troops)){const command={type:'civilWar',action:'rise',name:regimeName(w,r),arrangement:{goal:'ruler',sponsor:candidate.id,beneficiary:previous,executive:candidate.id,name:''}} as const;if(!civilReason(w,command,candidate.id)){actCivilWar(w,command,candidate.id);dissent=civilWar(w,r);break;}}if(dissent)opponents=opponents.filter(id=>!dissent!.civil!.supporters.includes(id));
 for(const city of Object.values(s.cities))if(city.owner===r&&city.governor&&opponents.includes(city.governor))city.governor=null;
 for(const [key,seat] of Object.entries(s.local?.seats??{}))if(key.startsWith(r+'|')){seat.regime=g.regimeId;if(seat.holder&&opponents.includes(seat.holder)){seat.holder=null;seat.delegated=false;}}
 if(g.court)for(const k of Object.keys(g.court.ministries) as (keyof typeof g.court.ministries)[])if(opponents.includes(g.court.ministries[k]??''))g.court.ministries[k]=null;
 delete w.relationships!.regencies[r];syncRelationships(w);syncCourt(w,r);syncGovernance(w);if(allegianceRealm(w,w.characterId!)===r)s.mandate=governingExecutives(w,r).includes(w.characterId!)||s.armies.some(a=>a.realm===r&&(a.owner===w.characterId||armyCommander(w,a)===w.characterId));syncDiplomacy(w);consumeSchemeSupport(w,r,p);if(previous!==ruler)announceSuccession(w,r,previous);const state=ensurePowerPolitics(w);const proposal=state.proposals[r],promises=proposal?.promises??{};if(proposal?.sourceStage&&!g.stages.includes(proposal.sourceStage))g.stages=successionIds.filter(id=>g.stages.includes(id)||id===proposal.sourceStage);delete state.proposals[r];state.cooldowns[r]=w.day+180;for(const [person,kind] of Object.entries(promises))(state.commitments??=[]).push({realm:r,person,chief:p.executive,kind,until:w.day+180,broken:false});state.commitments=state.commitments?.slice(-270);log(w,r,powerGoalNames[p.goal]+'完成：'+ getPerson(w,ruler)!.name+'居君位，'+ getPerson(w,p.executive)!.name+'执政；官员按表态承接，钱粮、军队、欠款及条约继续结算。');}
export function actPower(w:World,c:PowerCommand,actor=w.characterId!){const why=powerReason(w,c,actor);if(why)throw new Error(why);const r=allegianceRealm(w,actor)!,s=ensurePowerPolitics(w),p=s.proposals[r];
 if(c.action==='stance'){const q=s.reassessments!.filter(q=>q.person===actor&&q.realm===c.realm).at(-1)!;q.choice=c.choice;changeRelationOpinion(w,actor,q.to,c.choice==='accept'?10:c.choice==='oppose'?-15:0);return;}
 if(c.action==='propose'){if(c.goal==='ruler')supportClaim(w,r,c.beneficiary,actor);awardInfluence(w,actor,-40);s.proposals[r]={goal:c.goal,sponsor:actor,beneficiary:c.beneficiary,executive:c.executive,name:c.name?.trim()??'',...(c.sourceStage?{sourceStage:c.sourceStage}:{}),started:w.day,stage:'support',due:w.day+180,promises:{},approached:{}};log(w,r, getPerson(w,actor)!.name+'提出'+powerGoalNames[c.goal]+'议案。');return;}
 if(c.action==='assure'){if(typeof c.accept!=='boolean')return '须明确接受或拒绝';const q=s.assurances.find(q=>q.realm===r&&q.person===c.person&&q.status==='pending')!;q.status=c.accept?'kept':'refused';if(c.accept)awardInfluence(w,actor,-10);changeRelationOpinion(w,q.person,actor,c.accept?15:-20);log(w,r,(c.accept?'确认':'拒绝')+ getPerson(w,q.person)!.name+'的交接待遇；原有兵权与供饷仍依实际军队结算。');return;}
 if(c.action==='cancel'){delete s.proposals[r];s.cooldowns[r]=w.day+90;return;}
 if(c.action==='pledge'){awardInfluence(w,actor,-10);p!.approached[c.person]=w.day;p!.promises[c.person]=c.promise;return;}
 if(c.action==='present'){p!.stage='presented';p!.due=w.day+15;log(w,r,'权力议案公开呈请，现任朝廷须在十五日内回应。');return;}
 if(c.action==='answer'){if(c.accept)applyPowerArrangement(w,r,p!,powerSupport(w,r,p!).filter(q=>q.stance==='oppose').map(q=>q.id));else {p!.stage='refused';p!.due=w.day+90;}return;}
 if(c.action==='rise'){actCivilWar(w,{type:'civilWar',action:'rise',name:p!.name||'新朝',arrangement:{goal:p!.goal,sponsor:p!.sponsor,beneficiary:p!.beneficiary,executive:p!.executive,name:p!.name}},actor);}
}
function viableAIProposal(w:World,r:RealmId,p:PowerArrangement){
 const q=powerSummary(w,r,p),g=governmentOf(w,r)!;let power=q.support.reduce((n,v)=>n+v.weight,0),budget=personInfluence(w,p.sponsor)-40;
 for(const row of q.rows.filter(v=>v.id!==w.characterId&&v.stance!=='support'&&v.score>=-15).sort((a,b)=>b.weight-a.weight)){const holds=Object.values(g.court?.ministries??{}).includes(row.id)||Object.values(w.realm!.cities).some(c=>c.owner===r&&c.governor===row.id)||w.realm!.armies.some(a=>a.realm===r&&(a.owner===row.id||armyCommander(w,a)===row.id));if(holds&&budget>=10){power+=row.weight;budget-=10;}}
 return power*100>=q.rows.reduce((n,v)=>n+v.weight,0)*60;
}
export function advancePowerPolitics(w:World){if(!w.realm?.governments)return;const s=ensurePowerPolitics(w);for(const r of Object.keys(w.realm.governments.realms) as RealmId[]){const g=governmentOf(w,r)!,chief=governingAuthority(w,r),old=s.chiefs[r],captiveCourt=g.executives.some(id=>detained(w,id));if(old&&chief&&old!==chief){const leaders=w.realm.armies.filter(a=>a.realm===r&&a.owner&&a.owner!==chief&&!detained(w,a.owner)&&relationOpinion(w,a.owner,chief)<10).map(a=>a.owner!);for(const person of [...new Set(leaders)].slice(0,3))s.assurances.push({realm:r,person,chief,due:w.day+30,status:'pending'});}if(chief)s.chiefs[r]=chief;
 if(isMonthStart(w.day,w.scriptId)&&!s.proposals[r]&&!civilWar(w,r)&&!g.task&&!g.court?.founding&&(s.cooldowns[r]??0)<=w.day&&chief&&chief!==w.characterId){const contender=powerCandidates(w,r).filter(p=>p.id!==w.characterId&&((g.merit[p.id]??0)>=60||!dynastyReadiness(w,r,p.id).reason||p.id===chief&&(w.relationships?.regencies[r]?.grip??0)>=60&&w.day-(w.relationships?.regencies[r]?.since??w.day)>=360)&&(p.id===chief&&g.ruler!==chief&&g.support>=65||localPoliticalBasis(w,p.id,r)>0&&(relationOpinion(w,chief,p.id)<=-30||g.court?.phase==='chaos'&&relationOpinion(w,chief,p.id)<0||g.court?.phase==='strained'&&relationOpinion(w,chief,p.id)<=-15||captiveCourt&&!dynastyReadiness(w,r,p.id).reason))).sort((a,b)=>(g.merit[b.id]??0)-(g.merit[a.id]??0))[0];if(contender){const historical=successionIds.map(id=>({id,...successionDefinitions[id]})).filter(d=>d.realm===r&&d.year<=governmentYear(w)&&d.executives[0]===contender.id&&g.dynasty===r&&!g.stages.includes(d.id)&&[d.ruler,...d.executives].every(id=>isAlive(w,id)&&!detained(w,id)&&allegianceRealm(w,id)===r)&&(d.nextDynasty||d.ruler!==g.ruler||g.executives.join('|')!==d.executives.join('|'))).at(-1);const goal=contender.id===chief||captiveCourt&&!dynastyReadiness(w,r,contender.id).reason?'dynasty':'executive',proposal:PowerCommand={type:'power',action:'propose',goal,beneficiary:goal==='executive'?g.ruler:contender.id,executive:contender.id,name:goal==='dynasty'?dynastyNameOptions(w,r,contender.id)[0]?.name:undefined};if(historical){proposal.goal=historical.nextDynasty?'dynasty':historical.ruler!==g.ruler?'ruler':'executive';proposal.beneficiary=historical.ruler;proposal.executive=historical.executives[0];proposal.name=historical.nextDynasty?dynastyNames[historical.nextDynasty]:undefined;proposal.sourceStage=historical.id;}if(((g.merit[contender.id]??0)>=60||historical||!dynastyReadiness(w,r,contender.id).reason)&&!powerReason(w,proposal,contender.id)&&viableAIProposal(w,r,{...proposal,sponsor:contender.id,name:proposal.name??''}))actPower(w,proposal,contender.id);}}const p=s.proposals[r];if(!p||civilWar(w,r))continue;if(![p.sponsor,p.beneficiary,p.executive].every(id=>isAlive(w,id)&&allegianceRealm(w,id)===r)||detained(w,p.executive)||p.goal!=='executive'&&detained(w,p.beneficiary)){delete s.proposals[r];s.cooldowns[r]=w.day+90;log(w,r,'权力议案因参与人去世、改投或被拘押而终止。');continue;}
 if(p.stage==='support'&&p.sponsor!==w.characterId&&(w.day-p.started)%7===0&&!Object.values(p.approached).includes(w.day)){const rows=powerSupport(w,r,p).filter(q=>q.id!==w.characterId&&q.stance!=='support'&&q.score>=-15&&p.approached[q.id]===undefined).sort((a,b)=>b.weight-a.weight);for(const q of rows){const command:PowerCommand={type:'power',action:'pledge',person:q.id,promise:w.realm.armies.some(a=>a.realm===r&&(a.owner===q.id||armyCommander(w,a)===q.id))?'command':'office'};if(!powerReason(w,command,p.sponsor)){actPower(w,command,p.sponsor);break;}}}
 const readiness=powerSummary(w,r,p),consents=readiness.rows.find(q=>q.id===(chief===p.sponsor?g.ruler:chief))?.stance==='support';
 if(p.stage==='support'&&p.sponsor!==w.characterId&&w.day-p.started>=30&&(readiness.share>=75||consents||w.day-p.started>=175)&&readiness.share>=60&&!powerReason(w,{type:'power',action:'present'},p.sponsor))actPower(w,{type:'power',action:'present'},p.sponsor);if(p.stage==='refused'&&p.sponsor!==w.characterId&&w.day-p.started>=60){const command={type:'civilWar',action:'rise',name:p.name||'新朝',arrangement:{goal:p.goal,sponsor:p.sponsor,beneficiary:p.beneficiary,executive:p.executive,name:p.name}} as const;if(!civilReason(w,command,p.sponsor)){actCivilWar(w,command,p.sponsor);continue;}}if(p.stage==='presented'&&chief!==w.characterId&&g.ruler!==w.characterId){const q=powerSummary(w,r,p),chiefStance=q.rows.find(q=>q.id===(chief===p.sponsor?g.ruler:chief))?.stance;if(q.share>=75||chiefStance==='support')applyPowerArrangement(w,r,p,q.rows.filter(q=>q.stance==='oppose').map(q=>q.id));else {p.stage='refused';p.due=w.day+90;}}
 else if(w.day>=p.due){if(p.stage==='presented'){p.stage='refused';p.due=w.day+90;}else {delete s.proposals[r];s.cooldowns[r]=w.day+90;log(w,r,'权力议案逾期撤回，已付政治成本保留。');}}
 }
 for(const q of s.assurances.filter(q=>q.status==='pending')){if(!isAlive(w,q.person)||governingAuthority(w,q.realm)!==q.chief){q.status='refused';continue;}if(q.chief!==w.characterId){q.status=relationOpinion(w,q.person,q.chief)>-30?'kept':'refused';changeRelationOpinion(w,q.person,q.chief,q.status==='kept'?10:-15);}else if(w.day>=q.due){q.status='refused';changeRelationOpinion(w,q.person,q.chief,-15);}}
 for(const q of s.commitments??[]){if(q.broken||q.until<w.day||!isAlive(w,q.person))continue;const held=q.kind==='office'?Object.values(governmentOf(w,q.realm)?.court?.ministries??{}).includes(q.person)||Object.values(w.realm.cities).some(c=>c.owner===q.realm&&c.governor===q.person):w.realm.armies.some(a=>a.realm===q.realm&&(a.owner===q.person||armyCommander(w,a)===q.person));if(!held||detained(w,q.person)){q.broken=true;changeRelationOpinion(w,q.chief,q.person,-25);log(w,q.realm,'权力交接的保留职权承诺失效，'+ getPerson(w,q.person)!.name+'要求交涉。');}}s.commitments=s.commitments?.filter(q=>q.until>=w.day).slice(-270);s.assurances=s.assurances.filter(q=>q.status==='pending'||w.day-q.due<180).slice(-30);
}
