import {getPerson} from './personRegistry';
import {governmentOf,governingAuthority,governingExecutives} from './government';
import {worldRealms} from './polityRuntime';
import {allegianceRealm} from './officeEligibility';
import {isAlive,isDeceased,lifeOf} from './lifeState';
import {detained} from './custodyState';
import {territoryNodes} from '../data/territorialHierarchy';
import {siteById} from '../data/scenario';
import type {RealmId} from './realm';
import type {World} from './types';

export type TenureBasis='initial'|'migration'|'succession'|'designation'|'power'|'founding'|'appointment';
export interface PublicTenure {id:number;realm:RealmId;dynasty:string;regimeId:string;office:'ruler'|'executive';person:string;from:number;until:number|null;basis:TenureBasis;source:string|null}
export interface GovernorTenure {realm:RealmId;territory:string;person:string;from:number;until:number|null;source:'observed'|'appointment'}
export interface RulerHonor {tenure:number;posthumous:string;temple:string|null;grantor:string;day:number}
export interface RulerHistoryState {version:1;nextId:number;tenures:PublicTenure[];local:GovernorTenure[];honors:RulerHonor[];notifications:{tenure:number;acknowledged:boolean;reason?:'death'|'deposed'}[]}
export type HonorCommand={type:'honor';action:'confer';tenure:number;posthumous:string;temple?:string}|{type:'honor';action:'acknowledge';tenure:number};
export function ensureRulerHistory(w:World){if(w.rulerHistory)return w.rulerHistory;const s:RulerHistoryState={version:1,nextId:1,tenures:[],local:[],honors:[],notifications:[]};w.rulerHistory=s;
 for(const r of worldRealms(w)){const g=governmentOf(w,r);if(!g||w.realm?.annexed?.[r])continue;for(const office of ['ruler','executive'] as const)for(const person of office==='ruler'?[g.ruler]:governingExecutives(w,r))if(getPerson(w,person)&&isAlive(w,person))s.tenures.push({id:s.nextId++,realm:r,dynasty:g.dynasty,regimeId:g.regimeId,office,person,from:w.day,until:null,basis:w.day===0?'initial':'migration',source:null});}
 syncLocalHistory(w);return s;
}
/** Observation starts at migration day, never reconstructing dates from a dynasty's founding date. */
export function syncRulerHistory(w:World,basis:TenureBasis='power',source:string|null=null){const s=ensureRulerHistory(w);
 for(const r of worldRealms(w)){const g=governmentOf(w,r);if(!g)continue;for(const office of ['ruler','executive'] as const){const holders=w.realm?.annexed?.[r]?[]:(office==='ruler'?[g.ruler]:governingExecutives(w,r)).filter(p=>getPerson(w,p)&&isAlive(w,p));
 for(const t of s.tenures.filter(t=>t.realm===r&&t.office===office&&t.until===null))if(!holders.includes(t.person)||t.regimeId!==g.regimeId)t.until=w.day;
 for(const person of holders)if(!s.tenures.some(t=>t.realm===r&&t.office===office&&t.until===null&&t.person===person))s.tenures.push({id:s.nextId++,realm:r,dynasty:g.dynasty,regimeId:g.regimeId,office,person,from:w.day,until:null,basis,source});}}
 syncLocalHistory(w);
 for(const q of w.politics?.reassessments??[])if(q.choice==='pending'&&(!isAlive(w,q.person)||detained(w,q.person)||allegianceRealm(w,q.person)!==q.realm||governmentOf(w,q.realm)?.ruler!==q.to)){q.choice='expired';q.reason='人物死亡、被拘、离国或朝廷再次交接，原表态对象失效';}
}
function localHolders(w:World){const rows:Pick<GovernorTenure,'realm'|'territory'|'person'>[]=[];for(const [territory,c] of Object.entries(w.realm?.cities??{}))if(c.governor&&c.owner!=='frontier'&&isAlive(w,c.governor))rows.push({realm:c.owner,territory,person:c.governor});for(const [key,seat] of Object.entries(w.realm?.local?.seats??{})){const [realm,territory]=key.split('|');if(seat.holder&&isAlive(w,seat.holder))rows.push({realm:realm as RealmId,territory,person:seat.holder});}return rows;}
export function syncLocalHistory(w:World){const s=w.rulerHistory;if(!s)return;const holders=localHolders(w);for(const t of s.local)if(t.until===null&&!holders.some(q=>q.realm===t.realm&&q.territory===t.territory&&q.person===t.person))t.until=w.day;for(const q of holders)if(!s.local.some(t=>t.until===null&&t.realm===q.realm&&t.territory===q.territory&&t.person===q.person))s.local.push({...q,from:w.day,until:null,source:'observed'});}
export function announceSuccession(w:World,r:RealmId,previous:string){const s=ensureRulerHistory(w),tenure=s.tenures.filter(t=>t.realm===r&&t.office==='ruler'&&t.person===previous).at(-1);if(tenure&&!s.notifications.some(n=>n.tenure===tenure.id))s.notifications.push({tenure:tenure.id,acknowledged:false,reason:isDeceased(w,previous)?'death':'deposed'});}
export function historyOfRealm(w:World,r:RealmId){return (w.rulerHistory?.tenures??[]).filter(t=>t.realm===r);}
export function historyOfTerritory(w:World,territory:string){return (w.rulerHistory?.local??[]).filter(t=>t.territory===territory);}
/** A restored ruler has several tenures but one deceased identity and one set of death titles. */
export function honorOfPerson(w:World,realm:RealmId,person:string){return w.rulerHistory?.honors.find(h=>w.rulerHistory!.tenures.some(t=>t.id===h.tenure&&t.realm===realm&&t.person===person));}
export function honorRecommendations(w:World,tenure:number){const t=w.rulerHistory?.tenures.find(t=>t.id===tenure);if(!t)return {posthumous:'简',temple:'',reason:'没有本局任期记录',choices:[]};const g=governmentOf(w,t.realm),prefix=t.realm+'|'+t.person+'|';let victories=0;for(const [key,ranges] of Object.entries(w.deeds?.settled??{}))if(key.startsWith(prefix)&&(key.endsWith('|battle')||key.slice(prefix.length).startsWith('siege:')))for(let i=0;i<ranges.length;i+=2)victories+=ranges[i+1]-ranges[i]+1;
 const founder=t.basis==='founding',posthumous=victories>=3?'武':(g?.merit[t.person]??0)>=60?'文':'简',fallen=t.until!==null&&w.realm?.governments?.regimes.some(v=>v.realm===t.realm&&v.predecessor===t.regimeId&&v.dynasty!==t.dynasty);
 const choices=[{posthumous:'简',temple:'',reason:'本局任期 '+Math.max(0,(t.until??w.day)-t.from)+' 日；以留存任期从简议谥'},...(victories>=3?[{posthumous:'武',temple:'',reason:'本局留存 '+victories+' 次战胜／攻城成果'}]:[]),...((g?.merit[t.person]??0)>=60?[{posthumous:'文',temple:'',reason:'实际功绩 '+g!.merit[t.person]}]:[]),...(founder?[{posthumous,temple:'太祖',reason:'本局实际开创新国统'}]:[]),...(fallen?[{posthumous:'哀',temple:'',reason:'任期终止时本局国统实际更替；亡国之君议谥参照'}]:[])].slice(0,4);
 return {posthumous,temple:founder?'太祖':'',reason:founder?'本局实际开创新国统':victories>=3?'本局留存至少三次战胜／攻城成果':(g?.merit[t.person]??0)>=60?'本局实际功绩达到六十':'按已留存任期记录议定；不套用历史结局',choices};
}
export function honorReason(w:World,c:HonorCommand,actor=w.characterId!){const t=w.rulerHistory?.tenures.find(t=>t.id===c.tenure);if(!t||t.office!=='ruler'||t.until===null)return '只能处理已结束的本局君主任期';
 if(c.action==='acknowledge')return !isAlive(w,actor)||allegianceRealm(w,actor)!==t.realm?'须本国在世人物阅继位文书':w.rulerHistory?.notifications.some(n=>n.tenure===c.tenure&&!n.acknowledged)?'':'继位文书已知悉';if(c.action!=='confer')return '未知议谥行动';if(!isDeceased(w,t.person))return '在世逊位者不能议谥或上庙号';
 const g=governmentOf(w,t.realm);if(!g||allegianceRealm(w,actor)!==t.realm||!isAlive(w,actor)||detained(w,actor)||actor!==g.ruler&&actor!==governingAuthority(w,t.realm))return '须当前君主或掌政者为前任议谥';if(honorOfPerson(w,t.realm,t.person))return '该君主已议谥，不可重复册授';if(!/^[\u3400-\u9fff]{1,8}$/u.test(c.posthumous.trim())||c.temple&&!/^[\u3400-\u9fff]{1,3}(?:祖|宗)$/u.test(c.temple.trim()))return '谥号须一至八字，庙号须以祖或宗结尾';if(c.temple&&w.rulerHistory?.honors.some(h=>h.temple===c.temple?.trim()&&w.rulerHistory!.tenures.some(q=>q.id===h.tenure&&q.realm===t.realm&&q.dynasty===t.dynasty)))return '同一国统已有此庙号';return '';
}
export function actHonor(w:World,c:HonorCommand,actor=w.characterId!){const why=honorReason(w,c,actor);if(why)throw new Error(why);const s=ensureRulerHistory(w);if(c.action==='confer'){s.honors.push({tenure:c.tenure,posthumous:c.posthumous.trim(),temple:c.temple?.trim()||null,grantor:actor,day:w.day});const target=s.tenures.find(t=>t.id===c.tenure)!;for(const notice of s.notifications)if(s.tenures.some(t=>t.id===notice.tenure&&t.realm===target.realm&&t.person===target.person))notice.acknowledged=true;}else {const notice=s.notifications.find(n=>n.tenure===c.tenure);if(notice)notice.acknowledged=true;}}
export function validRulerHistory(value:unknown,w:World){if(!value||typeof value!=='object')return false;const s=value as RulerHistoryState;if(s.version!==1||!Number.isSafeInteger(s.nextId)||s.nextId<1||!Array.isArray(s.tenures)||!Array.isArray(s.local)||!Array.isArray(s.honors)||!Array.isArray(s.notifications)||s.tenures.length>1000||s.local.length>10000||s.honors.length>300||s.notifications.length>300)return false;
 const date=(from:number,until:number|null)=>Number.isSafeInteger(from)&&from>=0&&from<=w.day&&(until===null||Number.isSafeInteger(until)&&until>=from&&until<=w.day),ids=new Set<number>(),live=new Set<string>();
 for(const t of s.tenures){if(!t)return false;const regime=w.realm?.governments?.regimes.find(v=>v.id===t.regimeId&&v.realm===t.realm&&v.dynasty===t.dynasty);if(!regime||!getPerson(w,t.person)||!['ruler','executive'].includes(t.office)||!['initial','migration','succession','designation','power','founding','appointment'].includes(t.basis)||!Number.isSafeInteger(t.id)||t.id<1||t.id>=s.nextId||ids.has(t.id)||!date(t.from,t.until)||t.from<regime.from||typeof t.source!=='string'&&t.source!==null)return false;ids.add(t.id);if(t.until===null){const key=[t.realm,t.office,t.person].join('|');if(live.has(key)||w.realm?.annexed?.[t.realm]||!isAlive(w,t.person))return false;live.add(key);const g=governmentOf(w,t.realm);if(!g||g.regimeId!==t.regimeId||(t.office==='ruler'?g.ruler!==t.person:!governingExecutives(w,t.realm).includes(t.person)))return false;}}
 const locals=new Set<string>();for(const t of s.local){if(!t||!w.realm?.governments?.realms[t.realm]||!getPerson(w,t.person)||!siteById[t.territory]&&!territoryNodes[t.territory]||!date(t.from,t.until)||!['observed','appointment'].includes(t.source))return false;if(t.until===null){const key=t.realm+'|'+t.territory;if(locals.has(key)||!localHolders(w).some(q=>q.realm===t.realm&&q.territory===t.territory&&q.person===t.person))return false;locals.add(key);}}
 const honors=new Set<string>(),temples=new Set<string>();for(const h of s.honors){if(!h)return false;const t=s.tenures.find(t=>t.id===h.tenure);if(!t||t.office!=='ruler'||t.until===null||!isDeceased(w,t.person)||!getPerson(w,h.grantor)||honors.has(t.realm+'|'+t.person)||!date(h.day,h.day)||h.day<t.until||h.day<(lifeOf(w,t.person)?.death?.day??t.until)||!/^[\u3400-\u9fff]{1,8}$/u.test(h.posthumous)||h.temple!==null&&!/^[\u3400-\u9fff]{1,3}(?:祖|宗)$/u.test(h.temple))return false;honors.add(t.realm+'|'+t.person);if(h.temple){const key=t.realm+'|'+t.dynasty+'|'+h.temple;if(temples.has(key))return false;temples.add(key);}}
 const notices=new Set<number>();return s.notifications.every(n=>{if(!n)return false;const t=s.tenures.find(t=>t.id===n.tenure);if(!t||t.office!=='ruler'||t.until===null||typeof n.acknowledged!=='boolean'||n.reason!==undefined&&!['death','deposed'].includes(n.reason)||n.reason==='death'&&!isDeceased(w,t.person)||notices.has(n.tenure))return false;notices.add(n.tenure);return true;});
}
