import {economyHost} from './personalEconomyAdapter';
import {calendarDate} from './calendar';
import {civilWar,civilCanAdmin} from './civilWars';
import {realmAtWar} from './wars';
import {payArmy} from './armyOrganization';
import {cityOperatingExpense} from './realm';
import {canonicalTerritory,countyTerritory,localHolder,localSuperior,localSeatSite,localSites,localActive,localAncestors,payLocalOfficials} from './localAdministration';
import {courtSalary,payCourtSalary} from './court';
import {ancestorsOf,territoryNodes} from '../data/territorialHierarchy';
import {siteById} from '../data/scenario';
import {allegianceRealm} from './officeEligibility';
import {cityYield,armyMonthlyPay,realms,type RealmId} from './realm';
import {governmentOf,governingAuthority,governingExecutives} from './government';
import {creditPersonalCoins,relationOpinion} from './relationships';
import {isAlive} from './lifeState';
import {canCommission} from './serviceMandates';
import type {World} from './types';
export interface FiscalEntry {id:number;day:number;realm:RealmId;from:string;to:string;coins:number;reason:string}
export interface GrantRequest {id:number;realm:RealmId;site:string;territory?:string;actor:string;amount:number;purpose:'construction'|'relief'|'military';created:number;changed:number;approver:string;status:'pending'|'approved'|'rejected'|'cancelled';reply:string;evaluation?:{label:string;value:number}[]}
export interface FiscalState {version:1;balances:Record<string,number>;entries:FiscalEntry[];requests:GrantRequest[];nextId:number;nextRequest:number;net:Record<RealmId,number>}
export type FiscalCommand={type:'fiscal';action:'relief';site:string}|{type:'fiscal';action:'request';site:string;territory?:string;amount:number;purpose:GrantRequest['purpose']}|{type:'fiscal';action:'approve'|'reject'|'cancel';id:number}|{type:'fiscal';action:'allocate';site:string;territory?:string;amount:number};
export const grantPurposes={construction:'营建储备',relief:'地方赈济',military:'军需储备'};
export function ensureFiscal(w:World){if(!w.realm)return;return w.realm.fiscal??=( {version:1,balances:{},entries:[],requests:[],nextId:1,nextRequest:1,net:{liang:0,east:0,west:0}} );}
export const centralAccount=(r:RealmId)=>'central:'+r;
export function fiscalPath(w:World,site:string,r=w.realm!.cities[site].controller as RealmId){return ancestorsOf('city:'+site).filter(n=>n.level!=='realm'&&n.level!=='county').reverse().map(n=>r+'|'+n.id).concat(centralAccount(r));}
export function accountName(key:string){if(key==='tax')return '地方税收';if(key.startsWith('custody:'))return '司法担保押金';if(key==='expense')return '公共支出';if(key==='external')return '其他收支';if(key.startsWith('central:'))return '中央国库';if(key.startsWith('task:'))return '差事专款';return territoryNodes[key.split('|')[1]]?.name+'公库';}
export function localBalance(w:World,site:string){return w.realm?.fiscal?.balances[fiscalPath(w,site)[0]]??0;}
export function publicBalance(w:World,key:string){return key.startsWith('central:')?w.realm!.treasuries[key.slice(8) as RealmId].coins:w.realm!.fiscal?.balances[key]??0;}
function setBalance(w:World,key:string,n:number){if(key.startsWith('central:'))w.realm!.treasuries[key.slice(8) as RealmId].coins=n;else ensureFiscal(w)!.balances[key]=n;}
export function fiscalRecord(w:World,r:RealmId,from:string,to:string,coins:number,reason:string){if(!coins)return;const s=ensureFiscal(w)!;for(const realm of realms){if(from===centralAccount(realm))s.net[realm]-=coins;if(to===centralAccount(realm))s.net[realm]+=coins;}s.entries.push({id:s.nextId++,day:w.day,realm:r,from,to,coins,reason});s.entries=s.entries.slice(-1800);}
function transfer(w:World,r:RealmId,from:string,to:string,amount:number,reason:string){if(!Number.isSafeInteger(amount)||amount<0||publicBalance(w,from)<amount)throw new Error('公库余额不足');if(publicBalance(w,to)+amount>1_000_000)throw new Error('目标公库容量不足');setBalance(w,from,publicBalance(w,from)-amount);setBalance(w,to,publicBalance(w,to)+amount);fiscalRecord(w,r,from,to,amount,reason);}
export function grantRoom(w:World,site:string,r=w.realm!.cities[site].controller as RealmId){return Math.min(...fiscalPath(w,site,r).slice(0,-1).map(key=>1_000_000-publicBalance(w,key)));}
export function routeGrant(w:World,site:string,amount:number,reason:string,r=w.realm!.cities[site].controller as RealmId){const path=fiscalPath(w,site,r).reverse();if(!Number.isSafeInteger(amount)||amount<0||publicBalance(w,path[0])<amount)throw new Error('公库余额不足');if(path.slice(1).some(key=>publicBalance(w,key)+amount>1_000_000))throw new Error('拨款路径公库容量不足');for(let i=0;i<path.length-1;i++)transfer(w,r,path[i],path[i+1],amount,reason);}
export function spendLocal(w:World,site:string,amount:number,reason:string,to='expense'){if(!Number.isSafeInteger(amount)||amount<0)throw new Error('无效支出金额');const r=w.realm!.cities[site].controller as RealmId,key=fiscalPath(w,site)[0];if(localBalance(w,site)<amount)throw new Error('本城公库不足，请向上级申请拨款');setBalance(w,key,localBalance(w,site)-amount);fiscalRecord(w,r,key,to,amount,reason);}
export function fundAssignment(w:World,site:string,r:RealmId,amount:number,id:number,reason:string){routeGrant(w,site,amount,reason,r);spendLocal(w,site,amount,reason,'task:'+id);}
export function superiorForCity(w:World,site:string){return localSuperior(w,countyTerritory(site),w.realm!.cities[site].owner as RealmId)?.holder??governingAuthority(w,w.realm!.cities[site].owner as RealmId);}
export function grantFactors(w:World,q:GrantRequest){const city=w.realm!.cities[q.site],g=governmentOf(w,q.realm)!,territory=q.territory??countyTerritory(q.site),balance=publicBalance(w,grantSource(w,q.realm,territory,q.approver)),reserve=publicBalance(w,territoryAccount(w,q.realm,territory));return [{label:'日常拨款',value:35},{label:'上级交情',value:Math.round(relationOpinion(w,q.approver,q.actor)/4)},{label:'历年功绩',value:Math.min(20,Math.floor((g.merit[q.actor]??0)/4))},{label:'地方急需',value:Math.max(reserve<20?15:0,q.purpose==='relief'?Math.max(0,70-city.order):q.purpose==='military'&&realmAtWar(w,q.realm)?20:q.purpose==='construction'?Math.floor((100-city.prosperity)/5):0)},{label:'上级公库余力',value:balance>=q.amount*3?15:balance>=q.amount?5:-20},{label:'申请规模',value:-Math.floor(q.amount/20)}];}
export function territoryAccount(w:World,r:RealmId,t:string){t=canonicalTerritory(t);return ['county','city'].includes(territoryNodes[t]?.level)?r+'|city:'+localSeatSite(w,t,r):r+'|'+t;}
export function territoryFiscalPath(w:World,r:RealmId,t:string){const site=localSeatSite(w,t,r);if(!site)return [];const path=fiscalPath(w,site,r),key=territoryAccount(w,r,t);return path.slice(path.indexOf(key));}
export function grantSource(w:World,r:RealmId,t:string,actor:string){if(governingExecutives(w,r).includes(actor))return centralAccount(r);const n=localAncestors(t).reverse().find(n=>localHolder(w,n.id,r)===actor&&localActive(w,n.id,r));return n?territoryAccount(w,r,n.id):centralAccount(r);}
export function transferTerritoryGrant(w:World,r:RealmId,t:string,source:string,amount:number,reason:string){const path=territoryFiscalPath(w,r,t).reverse(),start=path.indexOf(source);if(start<0||!Number.isSafeInteger(amount)||amount<0||publicBalance(w,source)<amount)throw new Error('上级公库不足');const route=path.slice(start);if(route.length<2||route.slice(1).some(k=>publicBalance(w,k)+amount>1_000_000))throw new Error('拨款路径容量不足');for(let i=0;i<route.length-1;i++)transfer(w,r,route[i],route[i+1],amount,reason);}
export function fiscalReason(w:World,c:FiscalCommand,actor=w.characterId!){if(!w.realm||!actor||!isAlive(w,actor)||w.campaign?.status!=='active')return '当前不能办理公款';const r=allegianceRealm(w,actor) as RealmId;if(!realms.includes(r))return '无所属政权';
 if('site'in c&&!civilCanAdmin(w,actor,c.site))return '该地由内战对方控制';
 if(c.action==='relief'){const city=w.realm.cities[c.site];return !city||!canCommission(w,actor,r,c.site,'relief')?'须实际统辖本国控制的城市':city.order>=100?'本城秩序已满':localBalance(w,c.site)<20?'本城公库不足 20 钱':'';}
 if(c.action==='request'||c.action==='allocate'){const t=canonicalTerritory(c.territory??countyTerritory(c.site));if(!territoryNodes[t]||!localSites(w,t,r).includes(c.site)||!localActive(w,t,r))return '仅限本国控制的本国辖区';if(!Number.isSafeInteger(c.amount)||c.amount<20||c.amount>400)return '拨款须为 20 至 400 钱';if(territoryFiscalPath(w,r,t).slice(0,-1).some(k=>publicBalance(w,k)+c.amount>1_000_000))return '拨款路径公库容量不足';
 if(c.action==='allocate'){if(!governingExecutives(w,r).includes(actor)&&!localAncestors(t).some(n=>localHolder(w,n.id,r)===actor&&localActive(w,n.id,r)))return '须由辖区上级拨款';return publicBalance(w,grantSource(w,r,t,actor))<c.amount?'上级公库不足':'';}
 if(!Object.hasOwn(grantPurposes,c.purpose))return '无效用途';if(localHolder(w,t,r)!==actor)return '须由本辖区主官提出申请';if(governingExecutives(w,r).includes(actor))return '执政者可直接安排拨款';if(!localSuperior(w,t,r,actor))return '没有可请款的上级';if(w.realm.fiscal?.requests.some(q=>canonicalTerritory(q.territory??countyTerritory(q.site))===t&&q.status==='pending'))return '本辖区已有待批拨款';if(w.realm.fiscal?.requests.some(q=>q.actor===actor&&canonicalTerritory(q.territory??countyTerritory(q.site))===t&&q.status!=='pending'&&w.day-q.changed<30))return '本辖区再次申请须间隔 30 日';return '';}
 const q=w.realm.fiscal?.requests.find(q=>q.id===c.id);if(!q||q.status!=='pending')return '申请已结案';if(!civilCanAdmin(w,q.actor,q.site)||!civilCanAdmin(w,actor,q.site))return '内战双方不能沿用原统属拨款';if(c.action==='cancel')return q.actor!==actor?'只能撤回自己的申请':'';if(!['approve','reject'].includes(c.action))return '无效拨款操作';const t=q.territory??countyTerritory(q.site);if(q.approver!==actor||localSuperior(w,t,q.realm,q.actor)?.holder!==actor)return '须由当前上级批示';if(localHolder(w,t,q.realm)!==q.actor||!localActive(w,t,q.realm))return '任职或领土已变化';return c.action==='approve'?(territoryFiscalPath(w,q.realm,t).slice(0,-1).some(k=>publicBalance(w,k)+q.amount>1_000_000)?'拨款路径公库容量不足':publicBalance(w,grantSource(w,q.realm,t,actor))<q.amount?'上级公库不足':''):'';
}
export function actFiscal(w:World,c:FiscalCommand,actor=w.characterId!){const reason=fiscalReason(w,c,actor);if(reason)throw new Error(reason);const s=ensureFiscal(w)!,r=allegianceRealm(w,actor) as RealmId;
 if(c.action==='relief'){spendLocal(w,c.site,20,'平粜赈济');w.realm!.cities[c.site].order=Math.min(100,w.realm!.cities[c.site].order+8);return;}
 if(c.action==='request'){s.requests=s.requests.filter(q=>q.status==='pending').concat(s.requests.filter(q=>q.status!=='pending').slice(-59));s.requests.push({id:s.nextRequest++,realm:r,site:c.site,...(c.territory?{territory:canonicalTerritory(c.territory)}:{}),actor,amount:c.amount,purpose:c.purpose,created:w.day,changed:w.day,approver:localSuperior(w,c.territory??countyTerritory(c.site),r,actor)!.holder,status:'pending',reply:''});return;}
 if(c.action==='allocate'){transferTerritoryGrant(w,r,c.territory??countyTerritory(c.site),grantSource(w,r,c.territory??countyTerritory(c.site),actor),c.amount,'上级拨付地方预算');return;}
 const q=s.requests.find(q=>q.id===c.id)!;q.evaluation=grantFactors(w,q);if(c.action==='approve')transferTerritoryGrant(w,q.realm,q.territory??countyTerritory(q.site),grantSource(w,q.realm,q.territory??countyTerritory(q.site),actor),q.amount,grantPurposes[q.purpose]+'获准');q.status=c.action==='approve'?'approved':c.action==='reject'?'rejected':'cancelled';q.changed=w.day;q.reply=c.action==='approve'?'拨款已入'+accountName(territoryAccount(w,q.realm,q.territory??countyTerritory(q.site))):c.action==='cancel'?'申请已撤回':'上级未准此次拨款';
 w.chronicle.push({day:w.day,person:'player',text:siteById[q.site].name+'：'+q.reply+'。'});w.chronicle=w.chronicle.slice(-100);
}
export function advanceFiscal(w:World){const s=ensureFiscal(w);if(!s)return;if(calendarDate(w.day,w.scriptId).getUTCDate()===6)for(const [site,city] of Object.entries(w.realm!.cities)){const actor=city.governor;if(!actor||actor===w.characterId||city.order>=50||localBalance(w,site)>=20)continue;const approver=localSuperior(w,countyTerritory(site),city.owner as RealmId,actor)?.holder;if(s.requests.filter(q=>q.status==='pending'&&q.approver===approver).length>=2)continue;const cmd:FiscalCommand={type:'fiscal',action:'request',site,amount:Math.max(20,Math.min(100,Math.ceil((50-city.order)*2))),purpose:'relief'};if(!fiscalReason(w,cmd,actor))actFiscal(w,cmd,actor);}
 for(const q of s.requests.filter(q=>q.status==='pending')){const t=q.territory??countyTerritory(q.site);if(localHolder(w,t,q.realm)!==q.actor||!localActive(w,t,q.realm)||!isAlive(w,q.actor)){q.status='cancelled';q.changed=w.day;q.reply='任职、领土或申请人状态变化';continue;}const superior=localSuperior(w,t,q.realm,q.actor)?.holder;if(superior&&superior!==q.approver){q.approver=superior;q.changed=w.day;}if(w.day-q.created>=60){q.status='rejected';q.changed=w.day;q.reply='逾期未批，申请结案';continue;}if(q.approver===w.characterId||w.day-q.changed<3)continue;const source=grantSource(w,q.realm,t,q.approver),shortfall=q.amount-publicBalance(w,source);if(shortfall>0&&requestAccountFunding(w,q.approver,source,shortfall,q.purpose))continue;const approved=grantFactors(w,q).reduce((n,p)=>n+p.value,0)>=50&&!fiscalReason(w,{type:'fiscal',action:'approve',id:q.id},q.approver);actFiscal(w,{type:'fiscal',action:approved?'approve':'reject',id:q.id},q.approver);}}
/** Counties retain 35%; each upper tier retains 10% of incoming current-period remittance. */
export function centralTax(w:World,site:string,coins=cityYield(w,site).coins){const r=w.realm!.cities[site].controller;if(r!=='frontier'&&civilWar(w,r)?.civil?.cities.includes(site))return 0;let n=coins;n-=Math.floor(n*.35);for(const key of fiscalPath(w,site).slice(1,-1))if(key)n-=Math.floor(n*.1);return n;}
export function collectFiscal(w:World,r:RealmId,yields?:ReadonlyMap<string,{coins:number}>){ensureFiscal(w);for(const [site,c] of Object.entries(w.realm!.cities)){if(c.controller!==r)continue;const amount=Math.min((yields?.get(site)??cityYield(w,site)).coins,1_000_000-localBalance(w,site)),path=fiscalPath(w,site,r);setBalance(w,path[0],publicBalance(w,path[0])+amount);fiscalRecord(w,r,'tax',path[0],amount,'征收县域税赋');if(civilWar(w,r)?.civil?.cities.includes(site))continue;let flow=amount-Math.floor(amount*.35);for(let i=0;i<path.length-1;i++){const sent=Math.min(flow,1_000_000-publicBalance(w,path[i+1]));transfer(w,r,path[i],path[i+1],sent,'逐级上缴税赋');flow=sent-Math.floor(sent*.1);}}}
export function distributeFiscal(_w:World,_r:RealmId){/* 留用在征收时完成，不再重复回拨同一笔预算。 */}
export function fiscalSnapshot(w:World){return {net:{...(w.realm?.fiscal?.net??{liang:0,east:0,west:0})},balances:Object.fromEntries(realms.map(r=>[centralAccount(r),w.realm?.treasuries[r].coins??0]))};}
/** Legacy central actions are reconciled to the same ledger, without double-booking transfers. */
export function reconcileFiscal(w:World,before:ReturnType<typeof fiscalSnapshot>,reason:string){if(!w.realm)return;const s=ensureFiscal(w)!;for(const r of realms){const key=centralAccount(r),booked=s.net[r]-before.net[r],delta=w.realm.treasuries[r].coins-before.balances[key]-booked;if(delta)fiscalRecord(w,r,delta>0?'external':key,delta>0?key:'expense',Math.abs(delta),reason);}}

/** Official payroll starts in its own office treasury; the center covers actual gaps. */
export function localSalaryExpense(w:World,r:RealmId){return Object.keys(w.realm?.local?.seats??{}).filter(key=>key.startsWith(r+'|')).reduce((sum,key)=>{const t=key.split('|')[1],level=territoryNodes[t]?.level;return sum+(localHolder(w,t,r)&&localActive(w,t,r)&&!civilWar(w,r)?.civil?.cities.includes(localSeatSite(w,t,r)!)?level==='province'?12:level==='prefecture'?8:0:0);},0);}
/** Forecast the same local-first payments after the next tax collection. */
export function operatingSubsidy(w:World,r:RealmId,yields:ReadonlyMap<string,{coins:number;expense:number}>){
 const balances=new Map(Object.entries(w.realm?.fiscal?.balances??{}));
 const read=(key:string)=>balances.get(key)??0;
 for(const [site,y] of yields){const path=fiscalPath(w,site,r),amount=Math.min(y.coins,1_000_000-read(path[0]));balances.set(path[0],read(path[0])+amount);if(civilWar(w,r)?.civil?.cities.includes(site))continue;let flow=amount-Math.floor(amount*.35);for(let i=0;i<path.length-1;i++){const to=path[i+1],sent=Math.min(flow,1_000_000-(to===centralAccount(r)?w.realm!.treasuries[r].coins:read(to)));balances.set(path[i],read(path[i])-sent);if(to!==centralAccount(r))balances.set(to,read(to)+sent);flow=sent-Math.floor(sent*.1);}}
 let subsidy=0;
 const pay=(key:string,need:number,rebel=false)=>{const own=Math.min(read(key),need);balances.set(key,read(key)-own);if(!rebel)subsidy+=need-own;};
 for(const [site,y] of yields)pay(fiscalPath(w,site,r)[0],y.expense,!!civilWar(w,r)?.civil?.cities.includes(site));
 for(const key of Object.keys(w.realm?.local?.seats??{}).filter(k=>k.startsWith(r+'|'))){const t=key.split('|')[1],level=territoryNodes[t]?.level;if(localHolder(w,t,r)&&localActive(w,t,r))pay(key,level==='province'?12:level==='prefecture'?8:0,!!civilWar(w,r)?.civil?.cities.includes(localSeatSite(w,t,r)!));}
 return subsidy;
}
export function payFiscalOperations(w:World,r:RealmId){
 const t=w.realm!.treasuries[r];
 for(const [site,c] of Object.entries(w.realm!.cities)){if(c.controller!==r)continue;const need=cityOperatingExpense(w,site),own=Math.min(localBalance(w,site),need),rebel=!!civilWar(w,r)?.civil?.cities.includes(site),subsidy=rebel?0:Math.min(t.coins,need-own,grantRoom(w,site,r));if(subsidy)routeGrant(w,site,subsidy,'地方行政缺口补助',r);const paid=own+subsidy;spendLocal(w,site,paid,'地方行政支出');c.administration={day:w.day,need,paid};if(c.integration)c.integration.funded=paid>=need;if(c.governor)creditPersonalCoins(w,c.governor,Math.min(4,Math.max(0,paid-Math.ceil(c.population/900))));}
 payLocalOfficials(w,r,(key,want,reason)=>{const subsidy=civilWar(w,r)?.civil?.cities.includes(localSeatSite(w,key.split('|')[1],r)!)?0:Math.min(t.coins,Math.max(0,want-publicBalance(w,key)),...territoryFiscalPath(w,r,key.split('|')[1]).slice(0,-1).map(k=>1_000_000-publicBalance(w,k)));if(subsidy>0)transferTerritoryGrant(w,r,key.split('|')[1],centralAccount(r),subsidy,'州郡官员俸禄缺口补助');const amount=Math.min(publicBalance(w,key),want);setBalance(w,key,publicBalance(w,key)-amount);fiscalRecord(w,r,key,'expense',amount,reason);return amount;});
 for(const a of w.realm!.armies.filter(a=>a.realm===r))payArmy(w,a,armyMonthlyPay(w,a));
 for(const debt of w.realm!.armyDebts??[]){if(debt.realm!==r)continue;const privateWallet=debt.account.startsWith('person:')?economyHost(w).personal(debt.account.slice(7)):undefined,available=privateWallet?.read()??publicBalance(w,debt.account),paid=Math.min(debt.coins,available);if(privateWallet)privateWallet.write(available-paid);else setBalance(w,debt.account,available-paid);debt.coins-=paid;fiscalRecord(w,r,debt.account,'expense',paid,'补付溃散军伍欠饷');}if(w.realm!.armyDebts)w.realm!.armyDebts=w.realm!.armyDebts.filter(d=>d.coins>0);
 for(const [name,want] of [['中央官员俸禄',courtSalary(w,r)]] as const){const amount=Math.min(t.coins,want);t.coins-=amount;fiscalRecord(w,r,centralAccount(r),'expense',amount,name);if(name==='中央官员俸禄')payCourtSalary(w,r,amount);}
}
export function plannedReinvestment(_w:World,_r:RealmId){return 0;}

/** Merge redundant legacy county transit balances into the existing county-city wallet. */
export function migrateCountyAccounts(w:World){const f=w.realm?.fiscal;if(!f)return;const moves=Object.entries(f.balances).filter(([k,n])=>n>0&&k.split('|')[1]?.startsWith('county:')).map(([key,n])=>({key,n,to:key.replace('|county:','|city:')}));if(moves.some(m=>(f.balances[m.to]??0)+m.n>1_000_000))throw new Error('县城公库合并超出容量，存档未改变');for(const m of moves){f.balances[m.to]=(f.balances[m.to]??0)+m.n;delete f.balances[m.key];fiscalRecord(w,m.key.split('|')[0] as RealmId,m.key,m.to,m.n,'县城公库合并');}}
/** An official asks their own superior for the shortfall; no upper wallet is silently spent. */
export function requestAccountFunding(w:World,actor:string,key:string,shortfall:number,purpose:GrantRequest['purpose']='construction'){
 if(!w.realm||key.startsWith('central:')||shortfall<=0)return false;
 const r=allegianceRealm(w,actor);if(!r||!key.startsWith(r+'|'))return false;
 const t=canonicalTerritory(key.split('|')[1]),site=localSeatSite(w,t,r);if(!site||localHolder(w,t,r)!==actor)return false;
 if(w.realm.fiscal?.requests.some(q=>q.status==='pending'&&q.actor===actor&&canonicalTerritory(q.territory??countyTerritory(q.site))===t))return true;
 const command:FiscalCommand={type:'fiscal',action:'request',territory:t,site,amount:Math.max(20,Math.min(400,Math.ceil(shortfall))),purpose};
 if(fiscalReason(w,command,actor))return false;actFiscal(w,command,actor);return true;
}
