import {describe,expect,it} from 'vitest';
import {act,newCampaignWorld} from './world';
import {advanceRealm,canMarchThrough,cityOperatingExpense,cityYield,fortificationLevel,integrationGain,realmReason,settleWar,siegeRequirement,type Army} from './realm';
import {advanceArmyLogistics,distributeGarrisonFood,armySupplyTarget} from './armyLogistics';
import {roadEncounters} from './battlefield';
import {armyCommander,advanceMobility} from './mobility';
import {ensureArmyOrganization} from './armyOrganization';
import {civilianFood,advancePopulation} from './population';
import {planRoute} from './world';
import {parseWorld,serializeWorld} from './save';
import {validRealm} from './realmSave';
import {validMobility} from './mobilitySave';
import {ensureWars,peaceQuote,warRealmSide,type War} from './wars';
import {mapActivities} from './mapActivities';
import {advanceMilitaryAI} from './militaryAI';
import {actDiplomacy,advanceDiplomacy,canEnter,diplomaticPair} from './diplomacy';
import {assaultQuote,militaryActionReason} from './militaryAftermath';
import {fiscalPath} from './treasury';
import {annexPolity} from './polityLifecycle';

function setup(){const w=newCampaignWorld('xiao-yan',undefined,'sandbox');w.realm!.armies=[];w.realm!.wars=[];w.realm!.war=null;ensureWars(w);return w;}
function army(w:ReturnType<typeof setup>,location:string,realm:'liang'|'east'|'west'='liang'){const a:Army={realm,location,troops:600,morale:80,supply:500,journey:null,siege:0};w.realm!.armies.push(a);ensureArmyOrganization(w);return a;}
function war(w:ReturnType<typeof setup>,defender:'east'|'west',target:string,id:number){const v:War={id,attacker:'liang',defender,target,score:0,started:0};w.realm!.wars!.push(v);w.realm!.war=w.realm!.wars![0];w.realm!.nextWarId=id+1;return v;}

describe('war flow regressions',()=>{
 it('allows Luoyang as an Eastern Wei war objective reached through its own border',()=>{const w=setup();expect(w.realm!.cities.luoyang.owner).toBe('east');expect(realmReason(w,{type:'realm',action:'war',site:'luoyang'})).toBe('');});
 it('routes new marches through Liang County while old direct legs remain readable',()=>{expect(planRoute('xiangyang','luoyang')?.route).toContain('liangxian');expect(planRoute('xiangyang','luoyang')?.route).not.toEqual(['xiangyang','luoyang']);});
 it('makes an enemy fortified city block through movement until it is taken',()=>{const w=setup();war(w,'east','luoyang',1);expect(fortificationLevel(w,'luoyang')).toBe(1);expect(canMarchThrough(w,'liang','luoyang','ye')).toBe(false);expect(canMarchThrough(w,'liang','luoyang','luoyang')).toBe(true);w.realm!.cities.luoyang.fortification={level:0,due:null};expect(canMarchThrough(w,'liang','luoyang','ye')).toBe(true);});
 it('keeps one shared Luoyang siege while another war is active',()=>{const w=setup(),a=army(w,'luoyang'),b=army(w,'luoyang');war(w,'east','luoyang',1);war(w,'west','changan',2);w.realm!.treasuries.east.coins=0;w.realm!.treasuries.west.coins=0;for(let day=1;day<=3;day++){w.day=day;advanceRealm(w);}expect(a.siege).toBe(3);expect(b.siege).toBe(3);expect(w.realm!.cities.luoyang.controller).toBe('east');});
 it('retains a city siege when one army leaves and decays it after the last army withdraws',()=>{const w=setup(),a=army(w,'luoyang'),b=army(w,'luoyang');war(w,'east','luoyang',1);w.day=1;advanceRealm(w);act(w,{type:'realm',action:'march',army:a.id,site:'jiankang'});w.day=2;advanceRealm(w);expect(w.realm!.sieges).toMatchObject([{war:1,site:'luoyang',progress:2}]);expect(b.siege).toBe(2);act(w,{type:'realm',action:'march',army:b.id,site:'jiankang'});w.day=3;advanceRealm(w);expect(w.realm!.sieges).toMatchObject([{war:1,site:'luoyang',progress:1}]);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('projects a real siege as a clickable map activity',()=>{const w=setup();army(w,'luoyang');war(w,'east','luoyang',1);w.day=1;advanceRealm(w);expect(mapActivities(w).find(g=>g.site==='luoyang')?.items[0]).toMatchObject({kind:'military',title:'洛阳围城',target:{page:'city',site:'luoyang',tab:'military'}});});
 it('lets an outnumbered defender gather outside an occupied battlefield',()=>{const w=setup();army(w,'luoyang');army(w,'luoyang');army(w,'luoyang');const defender=army(w,'ye','east');war(w,'east','luoyang',1);for(const c of Object.values(w.realm!.cities))if(c.controller==='east')c.grain=1000;w.day=5;advanceMilitaryAI(w);expect(defender.journey?.route.at(-1)).not.toBe('luoyang');expect(defender.journey?.route.at(-1)).toBeTruthy();});
 it('spends local money and time on fortifications that lengthen sieges',()=>{const w=setup(),site='jiankang',key=fiscalPath(w,site)[0],a=army(w,site),before=w.realm!.fiscal!.balances[key]??0;w.realm!.fiscal!.balances[key]=Math.max(before,500);const old=fortificationLevel(w,site),required=siegeRequirement(w,a);act(w,{type:'realm',action:'fortify',site});expect(w.realm!.fiscal!.balances[key]).toBe(Math.max(before,500)-(old+1)*80);expect(w.realm!.cities[site].fortification?.due).toBe(w.day+(old+1)*30);expect(parseWorld(serializeWorld(w))).toEqual(w);w.day=(old+1)*30;advanceRealm(w);expect(fortificationLevel(w,site)).toBe(old+1);expect(siegeRequirement(w,a)).toBeGreaterThan(required);});
 it('charges a failed assault once per day and preserves the siege',()=>{const w=setup(),a=army(w,'luoyang');war(w,'east','luoyang',1);w.realm!.treasuries.east.coins=0;for(let day=1;day<=5;day++){w.day=day;advanceRealm(w);}const quote=assaultQuote(w,a),before=a.troops;expect(quote.success).toBe(false);act(w,{type:'militaryAction',army:a.id!,site:'luoyang',action:'assault'});expect(a.troops).toBe(before-quote.losses);expect(w.realm!.cities.luoyang.controller).toBe('east');expect(w.realm!.sieges?.[0].progress).toBe(3);expect(militaryActionReason(w,{type:'militaryAction',army:a.id!,site:'luoyang',action:'assault'})).toContain('今日已');expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('captures a city with a stronger assault and records the destruction',()=>{const w=setup(),a=army(w,'luoyang');a.troops=1600;w.realm!.cities.luoyang.fortification={level:1,due:null};war(w,'east','luoyang',1);w.realm!.treasuries.east.coins=0;for(let day=1;day<=5;day++){w.day=day;advanceRealm(w);}expect(assaultQuote(w,a).success).toBe(true);const oldFort=fortificationLevel(w,'luoyang'),order=w.realm!.cities.luoyang.order;act(w,{type:'militaryAction',army:a.id!,site:'luoyang',action:'assault'});expect(w.realm!.cities.luoyang.controller).toBe('liang');expect(w.realm!.cities.luoyang.order).toBe(order-25);expect(fortificationLevel(w,'luoyang')).toBe(oldFort-1);expect(w.realm!.sieges).toHaveLength(0);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('does not take grain from the destination while the army is marching',()=>{const w=setup(),a=army(w,'jiankang');a.supply=0;const route=planRoute('jiankang','jingkou')!;a.journey={route:route.route,durations:route.durations,leg:0,elapsed:0,started:w.day};const city=w.realm!.cities.jingkou;city.grain=civilianFood(w,'jingkou')*2+1000;const before=city.grain;distributeGarrisonFood(w);advanceArmyLogistics(w,a);expect(a.supply).toBe(0);expect(city.grain).toBe(before);expect(a.convoy).toBeUndefined();a.journey=null;a.location='jingkou';distributeGarrisonFood(w);expect(a.supply).toBe(armySupplyTarget(w,a));expect(city.grain).toBe(before-a.supply);});
 it('intercepts an army before it passes an enemy garrison',()=>{const w=setup(),a=army(w,'xiangyang'),b=army(w,'luoyang','east');war(w,'east','luoyang',1);a.journey={route:['xiangyang','luoyang','ye'],durations:[1,10],leg:0,elapsed:0,started:w.day};expect(roadEncounters(w)).toEqual([[a,b]]);});
 it('settles cooperating armies as one battlefield instead of repeated pair fights',()=>{const w=setup(),first=army(w,'luoyang'),second=army(w,'luoyang'),defender=army(w,'luoyang','east');war(w,'east','luoyang',1);w.day=1;advanceRealm(w);const battles=w.militaryAftermath?.battles??[];expect(battles).toHaveLength(1);expect(battles[0].attackers).toEqual([first.id,second.id]);expect(battles[0].defenders).toEqual([defender.id]);expect(first.troops).toBeLessThan(600);expect(second.troops).toBeLessThan(600);expect(defender.troops).toBeLessThan(600);});
 it('lets an accepted ally join the named war and fight on the same side',()=>{const w=setup(),v=war(w,'east','luoyang',1),p=diplomaticPair(w,'liang','west')!;p.opinion=100;p.opinionFactors={base:100,effects:{}};p.treaties.push({kind:'alliance',from:'liang',to:'west',actor:null,since:0,until:720});w.realm!.influence=900;w.realm!.treasuries.liang.coins=10000;expect(canEnter(w,'west','east',undefined,true)).toBe(false);actDiplomacy(w,{type:'diplomacy',action:'join',target:'west',war:1});expect(w.diplomacy!.missions.some(m=>m.action==='join'&&m.war===1)).toBe(true);for(let i=0;i<120&&!v.allies?.west;i++){w.day++;advanceDiplomacy(w);}expect(warRealmSide(v,'west')).toBe('attack');expect(canEnter(w,'west','east',undefined,true)).toBe(true);const ally=army(w,'luoyang','west'),enemy=army(w,'luoyang','east');w.day++;advanceRealm(w);expect(w.militaryAftermath?.battles.at(-1)?.attackers).toContain(ally.id);expect(enemy.troops).toBeLessThan(600);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('keeps fiscal alliance aid distinct from actual war participation',()=>{const w=setup(),v=war(w,'east','luoyang',1),p=diplomaticPair(w,'liang','west')!;p.opinion=100;p.opinionFactors={base:100,effects:{}};p.treaties.push({kind:'alliance',from:'liang',to:'west',actor:null,since:0,until:720});w.realm!.influence=900;w.realm!.treasuries.liang.coins=1000;w.realm!.treasuries.west.coins=1000;w.realm!.treasuries.west.grain=1000;const before={coins:w.realm!.treasuries.liang.coins+w.realm!.treasuries.west.coins,grain:w.realm!.treasuries.liang.grain+w.realm!.treasuries.west.grain,liangGrain:w.realm!.treasuries.liang.grain};actDiplomacy(w,{type:'diplomacy',action:'aid',target:'west'});for(let i=0;i<120&&w.realm!.treasuries.liang.grain===before.grain-1000;i++){w.day++;advanceDiplomacy(w);}expect(warRealmSide(v,'west')).toBeNull();expect(w.realm!.treasuries.liang.coins+w.realm!.treasuries.west.coins).toBeLessThanOrEqual(before.coins);expect(w.realm!.treasuries.liang.grain).toBe(before.liangGrain+120);expect(w.realm!.treasuries.liang.grain+w.realm!.treasuries.west.grain).toBe(before.grain);});
 it('credits allied siege occupation to the war leader and restores allied land in peace',()=>{const w=setup(),v=war(w,'east','luoyang',1);v.allies={west:'attack'};army(w,'luoyang','west').supply=1000;w.realm!.treasuries.east.coins=0;for(const c of Object.values(w.realm!.cities))if(c.owner==='east')c.population=100;for(let day=1;day<=70&&w.realm!.cities.luoyang.controller==='east';day++){w.day=day;advanceRealm(w);}expect(w.realm!.cities.luoyang.controller).toBe('liang');const changan=w.realm!.cities.changan;changan.controller='east';changan.occupiedSince=w.day;expect(validRealm(w)).toBe(true);v.score=100;settleWar(w,v,'demand','liang');expect(w.realm!.cities.luoyang.owner).toBe('liang');expect(changan.controller).toBe('west');expect(w.realm!.truces['east|west']).toBe(w.day+360);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('dispatches a remote commander and activates command only on arrival',()=>{const w=setup(),a=army(w,'jingkou');w.mobility!.residences['xiao-gang']={site:'jiankang',journey:null};act(w,{type:'mobility',action:'command',army:a.id,person:'xiao-gang'});expect(armyCommander(w,a)).toBeUndefined();expect(w.mobility!.pendingCommanders?.[a.id!]?.person).toBe('xiao-gang');expect({mobility:validMobility(w.mobility,w.day),realm:validRealm(w)}).toEqual({mobility:true,realm:true});expect(parseWorld(serializeWorld(w))).toEqual(w);for(let i=0;i<30&&!armyCommander(w,a);i++){w.day++;advanceMobility(w);}expect(armyCommander(w,a)).toBe('xiao-gang');expect(w.mobility!.pendingCommanders?.[a.id!]).toBeUndefined();});
 it('retains progress on the current road when a marching army turns back',()=>{const w=setup(),a=army(w,'jiankang');const target=Object.keys(w.realm!.cities).find(id=>w.realm!.cities[id].controller==='liang'&&(planRoute('jiankang',id)?.durations[0]??0)>1&&id!=='jiankang')!;const route=planRoute('jiankang',target)!;a.journey={route:route.route,durations:route.durations,leg:0,elapsed:1,started:0};w.day=1;act(w,{type:'realm',action:'march',army:a.id,site:'jiankang'});expect(a.journey?.route.slice(0,2)).toEqual(route.route.slice(0,2));expect(a.journey?.elapsed).toBe(1);expect(a.journey?.route.at(-1)).toBe('jiankang');expect(a.location).toBe('jiankang');});
 it('returns discharged soldiers to their regiment home through a conserved transit record',()=>{const w=setup(),a=army(w,'jingkou');a.regiments![0].origin='jiankang';const source=w.realm!.cities.jingkou.population,target=w.realm!.cities.jiankang.population;act(w,{type:'realm',action:'disband',army:a.id});const t=w.realm!.population!.transfers.at(-1)!;expect(t.kind).toBe('demobilized');expect(t.sent).toBe(600);expect(w.realm!.cities.jingkou.population).toBe(source);expect(w.realm!.cities.jiankang.population).toBe(target);expect(parseWorld(serializeWorld(w))).toEqual(w);for(let i=0;i<60&&t.status==='traveling';i++){w.day++;advancePopulation(w);}expect(t.status).toBe('arrived');expect(w.realm!.cities.jiankang.population+ t.lost).toBe(target+600);expect(w.realm!.cities.jingkou.population).toBe(source);});
 it('settles discharged soldiers locally when their home is no longer controlled',()=>{const w=setup(),a=army(w,'jingkou');a.regiments![0].origin='jiankang';w.realm!.cities.jiankang.controller='east';const local=w.realm!.cities.jingkou.population;act(w,{type:'realm',action:'disband',army:a.id});expect(w.realm!.cities.jingkou.population).toBe(local+600);expect(w.realm!.population?.transfers).toHaveLength(0);});
 it('charges an isolated ceded Luoyang without silently treating it as connected',()=>{const w=setup(),v=war(w,'east','luoyang',1),c=w.realm!.cities.luoyang;v.score=100;c.controller='liang';const beforeExpense=cityOperatingExpense(w,'luoyang');settleWar(w,v,'demand','liang');expect(c.owner).toBe('liang');expect(c.integration).toEqual({since:w.day,progress:0,funded:false});expect(cityOperatingExpense(w,'luoyang')).toBeGreaterThan(beforeExpense);expect(cityYield(w,'luoyang').coins).toBeLessThan(1000);expect(integrationGain(w,'luoyang').connected).toBe(false);expect(parseWorld(serializeWorld(w))).toEqual(w);w.realm!.treasuries.liang.coins=100_000;w.day=30;advanceRealm(w);expect(c.integration?.funded).toBe(true);expect(c.integration!.progress).toBe(0);});
 it('requires an occupied corridor claim and settles both counties without inheriting an unfinished fort',()=>{const w=setup(),v=war(w,'east','luoyang',1);v.score=100;w.realm!.cities.luoyang.controller='liang';w.realm!.cities.liangxian.controller='liang';w.realm!.cities.liangxian.fortification={level:1,due:90};expect(peaceQuote(w,v,'liang','demand',['liangxian']).reason).toBe('');expect(peaceQuote(w,v,'liang','demand',['ye']).reason).toContain('已占领');expect(peaceQuote(w,v,'liang','demand',['luoyang']).reason).toContain('附加割地');expect(realmReason(w,{type:'realm',action:'peace',war:1,terms:'demand',claims:['liangxian']})).toBe('');settleWar(w,v,'demand','liang',['liangxian']);expect(w.realm!.cities.luoyang.owner).toBe('liang');expect(w.realm!.cities.liangxian.owner).toBe('liang');expect(w.realm!.cities.liangxian.fortification?.due).toBeNull();expect(integrationGain(w,'luoyang').connected).toBe(true);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('rejects a stale corridor claim before changing ownership',()=>{const w=setup(),v=war(w,'east','luoyang',1);v.score=100;w.realm!.cities.luoyang.controller='liang';w.realm!.cities.liangxian.controller='liang';w.realm!.cities.liangxian.controller='east';expect(()=>settleWar(w,v,'demand','liang',['liangxian'])).toThrow('已占领');expect(w.realm!.cities.luoyang.owner).toBe('east');expect(w.realm!.wars).toContain(v);});
 it('combines a territorial claim with conserved cash and a recorded unpaid balance',()=>{const w=setup(),v=war(w,'east','luoyang',1);v.score=100;w.realm!.cities.luoyang.controller='liang';w.realm!.treasuries.east.coins=200;const liang=w.realm!.treasuries.liang.coins;expect(peaceQuote(w,v,'liang','demand',[],300).reason).toBe('');settleWar(w,v,'demand','liang',[],300);expect(w.realm!.cities.luoyang.owner).toBe('liang');expect(w.realm!.treasuries.east.coins).toBe(0);expect(w.realm!.treasuries.liang.coins).toBe(liang+200);expect(w.realm!.reparations?.at(-1)?.remaining).toBe(100);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('recovers a connected ceded city after funded administration',()=>{const w=setup(),v=war(w,'east','pengcheng',1),c=w.realm!.cities.pengcheng;v.score=100;c.controller='liang';settleWar(w,v,'demand','liang');expect(integrationGain(w,'pengcheng').connected).toBe(true);w.realm!.treasuries.liang.coins=100_000;w.day=30;advanceRealm(w);expect(c.integration?.progress).toBeGreaterThan(0);expect(parseWorld(serializeWorld(w))).toEqual(w);});
 it('cancels unfinished fortification when a polity is annexed',()=>{const w=setup(),c=w.realm!.cities.luoyang;c.fortification={level:1,due:90};for(const site of Object.values(w.realm!.cities))if(site.owner==='east')site.controller='liang';annexPolity(w,'liang','east');expect(c.owner).toBe('liang');expect(c.fortification).toEqual({level:1,due:null});expect(c.integration).toEqual({since:w.day,progress:0,funded:false});expect(w.chronicle.at(-1)?.text).toContain('原城防工程因吞并停建');expect(parseWorld(serializeWorld(w))).toEqual(w);});
});
